// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** icuuc.dll!UCNV_FROM_U_CALLBACK_ESCAPE */
  UCNV_FROM_U_CALLBACK_ESCAPE(context: Win32Pointer, fromUArgs: Win32Pointer, codeUnits: Win32Pointer, length: number, codePoint: number, reason: number, err: Win32Pointer): void;
  /** icuuc.dll!UCNV_FROM_U_CALLBACK_SKIP */
  UCNV_FROM_U_CALLBACK_SKIP(context: Win32Pointer, fromUArgs: Win32Pointer, codeUnits: Win32Pointer, length: number, codePoint: number, reason: number, err: Win32Pointer): void;
  /** icuuc.dll!UCNV_FROM_U_CALLBACK_STOP */
  UCNV_FROM_U_CALLBACK_STOP(context: Win32Pointer, fromUArgs: Win32Pointer, codeUnits: Win32Pointer, length: number, codePoint: number, reason: number, err: Win32Pointer): void;
  /** icuuc.dll!UCNV_FROM_U_CALLBACK_SUBSTITUTE */
  UCNV_FROM_U_CALLBACK_SUBSTITUTE(context: Win32Pointer, fromUArgs: Win32Pointer, codeUnits: Win32Pointer, length: number, codePoint: number, reason: number, err: Win32Pointer): void;
  /** icuuc.dll!UCNV_TO_U_CALLBACK_ESCAPE */
  UCNV_TO_U_CALLBACK_ESCAPE(context: Win32Pointer, toUArgs: Win32Pointer, codeUnits: string | Win32Pointer, length: number, reason: number, err: Win32Pointer): void;
  /** icuuc.dll!UCNV_TO_U_CALLBACK_SKIP */
  UCNV_TO_U_CALLBACK_SKIP(context: Win32Pointer, toUArgs: Win32Pointer, codeUnits: string | Win32Pointer, length: number, reason: number, err: Win32Pointer): void;
  /** icuuc.dll!UCNV_TO_U_CALLBACK_STOP */
  UCNV_TO_U_CALLBACK_STOP(context: Win32Pointer, toUArgs: Win32Pointer, codeUnits: string | Win32Pointer, length: number, reason: number, err: Win32Pointer): void;
  /** icuuc.dll!UCNV_TO_U_CALLBACK_SUBSTITUTE */
  UCNV_TO_U_CALLBACK_SUBSTITUTE(context: Win32Pointer, toUArgs: Win32Pointer, codeUnits: string | Win32Pointer, length: number, reason: number, err: Win32Pointer): void;
  /** icuuc.dll!u_UCharsToChars */
  u_UCharsToChars(us: Win32Pointer, cs: string | Win32Pointer, length: number): void;
  /** icuuc.dll!u_austrcpy */
  u_austrcpy(dst: string | Win32Pointer, src: Win32Pointer): number | null;
  /** icuuc.dll!u_austrncpy */
  u_austrncpy(dst: string | Win32Pointer, src: Win32Pointer, n: number): number | null;
  /** icuuc.dll!u_catclose */
  u_catclose(catd: Win32Pointer): void;
  /** icuuc.dll!u_catgets */
  u_catgets(catd: Win32Pointer, set_num: number, msg_num: number, s: Win32Pointer, len: Win32Pointer, ec: Win32Pointer): number | null;
  /** icuuc.dll!u_catopen */
  u_catopen(name: string | Win32Pointer, locale: string | Win32Pointer, ec: Win32Pointer): number | null;
  /** icuuc.dll!u_charAge */
  u_charAge(c: number, versionArray: Win32Pointer): void;
  /** icuuc.dll!u_charDigitValue */
  u_charDigitValue(c: number): number;
  /** icuuc.dll!u_charDirection */
  u_charDirection(c: number): number;
  /** icuuc.dll!u_charFromName */
  u_charFromName(nameChoice: number, name: string | Win32Pointer, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!u_charMirror */
  u_charMirror(c: number): number;
  /** icuuc.dll!u_charName */
  u_charName(code: number, nameChoice: number, buffer: string | Win32Pointer, bufferLength: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!u_charType */
  u_charType(c: number): number;
  /** icuuc.dll!u_charsToUChars */
  u_charsToUChars(cs: string | Win32Pointer, us: Win32Pointer, length: number): void;
  /** icuuc.dll!u_cleanup */
  u_cleanup(): void;
  /** icuuc.dll!u_countChar32 */
  u_countChar32(s: Win32Pointer, length: number): number;
  /** icuuc.dll!u_digit */
  u_digit(ch: number, radix: number): number;
  /** icuuc.dll!u_enumCharNames */
  u_enumCharNames(start: number, limit: number, fn: Win32Pointer, context: Win32Pointer, nameChoice: number, pErrorCode: Win32Pointer): void;
  /** icuuc.dll!u_enumCharTypes */
  u_enumCharTypes(enumRange: Win32Pointer, context: Win32Pointer): void;
  /** icuuc.dll!u_errorName */
  u_errorName(code: number): number | null;
  /** icuuc.dll!u_foldCase */
  u_foldCase(c: number, options: number): number;
  /** icuuc.dll!u_forDigit */
  u_forDigit(digit: number, radix: number): number;
  /** icuuc.dll!u_getBidiPairedBracket */
  u_getBidiPairedBracket(c: number): number;
  /** icuuc.dll!u_getCombiningClass */
  u_getCombiningClass(c: number): number;
  /** icuuc.dll!u_getDataVersion */
  u_getDataVersion(dataVersionFillin: Win32Pointer, status: Win32Pointer): void;
  /** icuuc.dll!u_getFC_NFKC_Closure */
  u_getFC_NFKC_Closure(c: number, dest: Win32Pointer, destCapacity: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!u_getIntPropertyMaxValue */
  u_getIntPropertyMaxValue(which: number): number;
  /** icuuc.dll!u_getIntPropertyMinValue */
  u_getIntPropertyMinValue(which: number): number;
  /** icuuc.dll!u_getIntPropertyValue */
  u_getIntPropertyValue(c: number, which: number): number;
  /** icuuc.dll!u_getNumericValue */
  u_getNumericValue(c: number): number;
  /** icuuc.dll!u_getPropertyEnum */
  u_getPropertyEnum(alias: string | Win32Pointer): number;
  /** icuuc.dll!u_getPropertyName */
  u_getPropertyName(property: number, nameChoice: number): number | null;
  /** icuuc.dll!u_getPropertyValueEnum */
  u_getPropertyValueEnum(property: number, alias: string | Win32Pointer): number;
  /** icuuc.dll!u_getPropertyValueName */
  u_getPropertyValueName(property: number, value: number, nameChoice: number): number | null;
  /** icuuc.dll!u_getUnicodeVersion */
  u_getUnicodeVersion(versionArray: Win32Pointer): void;
  /** icuuc.dll!u_getVersion */
  u_getVersion(versionArray: Win32Pointer): void;
  /** icuuc.dll!u_hasBinaryProperty */
  u_hasBinaryProperty(c: number, which: number): number;
  /** icuuc.dll!u_init */
  u_init(status: Win32Pointer): void;
  /** icuuc.dll!u_isIDIgnorable */
  u_isIDIgnorable(c: number): number;
  /** icuuc.dll!u_isIDPart */
  u_isIDPart(c: number): number;
  /** icuuc.dll!u_isIDStart */
  u_isIDStart(c: number): number;
  /** icuuc.dll!u_isISOControl */
  u_isISOControl(c: number): number;
  /** icuuc.dll!u_isJavaIDPart */
  u_isJavaIDPart(c: number): number;
  /** icuuc.dll!u_isJavaIDStart */
  u_isJavaIDStart(c: number): number;
  /** icuuc.dll!u_isJavaSpaceChar */
  u_isJavaSpaceChar(c: number): number;
  /** icuuc.dll!u_isMirrored */
  u_isMirrored(c: number): number;
  /** icuuc.dll!u_isUAlphabetic */
  u_isUAlphabetic(c: number): number;
  /** icuuc.dll!u_isULowercase */
  u_isULowercase(c: number): number;
  /** icuuc.dll!u_isUUppercase */
  u_isUUppercase(c: number): number;
  /** icuuc.dll!u_isUWhiteSpace */
  u_isUWhiteSpace(c: number): number;
  /** icuuc.dll!u_isWhitespace */
  u_isWhitespace(c: number): number;
  /** icuuc.dll!u_isalnum */
  u_isalnum(c: number): number;
  /** icuuc.dll!u_isalpha */
  u_isalpha(c: number): number;
  /** icuuc.dll!u_isbase */
  u_isbase(c: number): number;
  /** icuuc.dll!u_isblank */
  u_isblank(c: number): number;
  /** icuuc.dll!u_iscntrl */
  u_iscntrl(c: number): number;
  /** icuuc.dll!u_isdefined */
  u_isdefined(c: number): number;
  /** icuuc.dll!u_isdigit */
  u_isdigit(c: number): number;
  /** icuuc.dll!u_isgraph */
  u_isgraph(c: number): number;
  /** icuuc.dll!u_islower */
  u_islower(c: number): number;
  /** icuuc.dll!u_isprint */
  u_isprint(c: number): number;
  /** icuuc.dll!u_ispunct */
  u_ispunct(c: number): number;
  /** icuuc.dll!u_isspace */
  u_isspace(c: number): number;
  /** icuuc.dll!u_istitle */
  u_istitle(c: number): number;
  /** icuuc.dll!u_isupper */
  u_isupper(c: number): number;
  /** icuuc.dll!u_isxdigit */
  u_isxdigit(c: number): number;
  /** icuuc.dll!u_memcasecmp */
  u_memcasecmp(s1: Win32Pointer, s2: Win32Pointer, length: number, options: number): number;
  /** icuuc.dll!u_memchr */
  u_memchr(s: Win32Pointer, c: number, count: number): number | null;
  /** icuuc.dll!u_memchr32 */
  u_memchr32(s: Win32Pointer, c: number, count: number): number | null;
  /** icuuc.dll!u_memcmp */
  u_memcmp(buf1: Win32Pointer, buf2: Win32Pointer, count: number): number;
  /** icuuc.dll!u_memcmpCodePointOrder */
  u_memcmpCodePointOrder(s1: Win32Pointer, s2: Win32Pointer, count: number): number;
  /** icuuc.dll!u_memcpy */
  u_memcpy(dest: Win32Pointer, src: Win32Pointer, count: number): number | null;
  /** icuuc.dll!u_memmove */
  u_memmove(dest: Win32Pointer, src: Win32Pointer, count: number): number | null;
  /** icuuc.dll!u_memrchr */
  u_memrchr(s: Win32Pointer, c: number, count: number): number | null;
  /** icuuc.dll!u_memrchr32 */
  u_memrchr32(s: Win32Pointer, c: number, count: number): number | null;
  /** icuuc.dll!u_memset */
  u_memset(dest: Win32Pointer, c: number, count: number): number | null;
  /** icuuc.dll!u_setMemoryFunctions */
  u_setMemoryFunctions(context: Win32Pointer, a: Win32Pointer, r: Win32Pointer, f: Win32Pointer, status: Win32Pointer): void;
  /** icuuc.dll!u_shapeArabic */
  u_shapeArabic(source: Win32Pointer, sourceLength: number, dest: Win32Pointer, destSize: number, options: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!u_strCaseCompare */
  u_strCaseCompare(s1: Win32Pointer, length1: number, s2: Win32Pointer, length2: number, options: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!u_strCompare */
  u_strCompare(s1: Win32Pointer, length1: number, s2: Win32Pointer, length2: number, codePointOrder: number): number;
  /** icuuc.dll!u_strCompareIter */
  u_strCompareIter(iter1: Win32Pointer, iter2: Win32Pointer, codePointOrder: number): number;
  /** icuuc.dll!u_strFindFirst */
  u_strFindFirst(s: Win32Pointer, length: number, substring: Win32Pointer, subLength: number): number | null;
  /** icuuc.dll!u_strFindLast */
  u_strFindLast(s: Win32Pointer, length: number, substring: Win32Pointer, subLength: number): number | null;
  /** icuuc.dll!u_strFoldCase */
  u_strFoldCase(dest: Win32Pointer, destCapacity: number, src: Win32Pointer, srcLength: number, options: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!u_strFromJavaModifiedUTF8WithSub */
  u_strFromJavaModifiedUTF8WithSub(dest: Win32Pointer, destCapacity: number, pDestLength: Win32Pointer, src: string | Win32Pointer, srcLength: number, subchar: number, pNumSubstitutions: Win32Pointer, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!u_strFromUTF32 */
  u_strFromUTF32(dest: Win32Pointer, destCapacity: number, pDestLength: Win32Pointer, src: Win32Pointer, srcLength: number, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!u_strFromUTF32WithSub */
  u_strFromUTF32WithSub(dest: Win32Pointer, destCapacity: number, pDestLength: Win32Pointer, src: Win32Pointer, srcLength: number, subchar: number, pNumSubstitutions: Win32Pointer, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!u_strFromUTF8 */
  u_strFromUTF8(dest: Win32Pointer, destCapacity: number, pDestLength: Win32Pointer, src: string | Win32Pointer, srcLength: number, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!u_strFromUTF8Lenient */
  u_strFromUTF8Lenient(dest: Win32Pointer, destCapacity: number, pDestLength: Win32Pointer, src: string | Win32Pointer, srcLength: number, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!u_strFromUTF8WithSub */
  u_strFromUTF8WithSub(dest: Win32Pointer, destCapacity: number, pDestLength: Win32Pointer, src: string | Win32Pointer, srcLength: number, subchar: number, pNumSubstitutions: Win32Pointer, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!u_strFromWCS */
  u_strFromWCS(dest: Win32Pointer, destCapacity: number, pDestLength: Win32Pointer, src: string | Win32Pointer, srcLength: number, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!u_strHasMoreChar32Than */
  u_strHasMoreChar32Than(s: Win32Pointer, length: number, number: number): number;
  /** icuuc.dll!u_strToJavaModifiedUTF8 */
  u_strToJavaModifiedUTF8(dest: string | Win32Pointer, destCapacity: number, pDestLength: Win32Pointer, src: Win32Pointer, srcLength: number, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!u_strToLower */
  u_strToLower(dest: Win32Pointer, destCapacity: number, src: Win32Pointer, srcLength: number, locale: string | Win32Pointer, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!u_strToTitle */
  u_strToTitle(dest: Win32Pointer, destCapacity: number, src: Win32Pointer, srcLength: number, titleIter: Win32Pointer, locale: string | Win32Pointer, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!u_strToUTF32 */
  u_strToUTF32(dest: Win32Pointer, destCapacity: number, pDestLength: Win32Pointer, src: Win32Pointer, srcLength: number, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!u_strToUTF32WithSub */
  u_strToUTF32WithSub(dest: Win32Pointer, destCapacity: number, pDestLength: Win32Pointer, src: Win32Pointer, srcLength: number, subchar: number, pNumSubstitutions: Win32Pointer, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!u_strToUTF8 */
  u_strToUTF8(dest: string | Win32Pointer, destCapacity: number, pDestLength: Win32Pointer, src: Win32Pointer, srcLength: number, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!u_strToUTF8WithSub */
  u_strToUTF8WithSub(dest: string | Win32Pointer, destCapacity: number, pDestLength: Win32Pointer, src: Win32Pointer, srcLength: number, subchar: number, pNumSubstitutions: Win32Pointer, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!u_strToUpper */
  u_strToUpper(dest: Win32Pointer, destCapacity: number, src: Win32Pointer, srcLength: number, locale: string | Win32Pointer, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!u_strToWCS */
  u_strToWCS(dest: string | Win32Pointer, destCapacity: number, pDestLength: Win32Pointer, src: Win32Pointer, srcLength: number, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!u_strcasecmp */
  u_strcasecmp(s1: Win32Pointer, s2: Win32Pointer, options: number): number;
  /** icuuc.dll!u_strcat */
  u_strcat(dst: Win32Pointer, src: Win32Pointer): number | null;
  /** icuuc.dll!u_strchr */
  u_strchr(s: Win32Pointer, c: number): number | null;
  /** icuuc.dll!u_strchr32 */
  u_strchr32(s: Win32Pointer, c: number): number | null;
  /** icuuc.dll!u_strcmp */
  u_strcmp(s1: Win32Pointer, s2: Win32Pointer): number;
  /** icuuc.dll!u_strcmpCodePointOrder */
  u_strcmpCodePointOrder(s1: Win32Pointer, s2: Win32Pointer): number;
  /** icuuc.dll!u_strcpy */
  u_strcpy(dst: Win32Pointer, src: Win32Pointer): number | null;
  /** icuuc.dll!u_strcspn */
  u_strcspn(string: Win32Pointer, matchSet: Win32Pointer): number;
  /** icuuc.dll!u_strlen */
  u_strlen(s: Win32Pointer): number;
  /** icuuc.dll!u_strncasecmp */
  u_strncasecmp(s1: Win32Pointer, s2: Win32Pointer, n: number, options: number): number;
  /** icuuc.dll!u_strncat */
  u_strncat(dst: Win32Pointer, src: Win32Pointer, n: number): number | null;
  /** icuuc.dll!u_strncmp */
  u_strncmp(ucs1: Win32Pointer, ucs2: Win32Pointer, n: number): number;
  /** icuuc.dll!u_strncmpCodePointOrder */
  u_strncmpCodePointOrder(s1: Win32Pointer, s2: Win32Pointer, n: number): number;
  /** icuuc.dll!u_strncpy */
  u_strncpy(dst: Win32Pointer, src: Win32Pointer, n: number): number | null;
  /** icuuc.dll!u_strpbrk */
  u_strpbrk(string: Win32Pointer, matchSet: Win32Pointer): number | null;
  /** icuuc.dll!u_strrchr */
  u_strrchr(s: Win32Pointer, c: number): number | null;
  /** icuuc.dll!u_strrchr32 */
  u_strrchr32(s: Win32Pointer, c: number): number | null;
  /** icuuc.dll!u_strrstr */
  u_strrstr(s: Win32Pointer, substring: Win32Pointer): number | null;
  /** icuuc.dll!u_strspn */
  u_strspn(string: Win32Pointer, matchSet: Win32Pointer): number;
  /** icuuc.dll!u_strstr */
  u_strstr(s: Win32Pointer, substring: Win32Pointer): number | null;
  /** icuuc.dll!u_strtok_r */
  u_strtok_r(src: Win32Pointer, delim: Win32Pointer, saveState: Win32Pointer): number | null;
  /** icuuc.dll!u_tolower */
  u_tolower(c: number): number;
  /** icuuc.dll!u_totitle */
  u_totitle(c: number): number;
  /** icuuc.dll!u_toupper */
  u_toupper(c: number): number;
  /** icuuc.dll!u_uastrcpy */
  u_uastrcpy(dst: Win32Pointer, src: string | Win32Pointer): number | null;
  /** icuuc.dll!u_uastrncpy */
  u_uastrncpy(dst: Win32Pointer, src: string | Win32Pointer, n: number): number | null;
  /** icuuc.dll!u_unescape */
  u_unescape(src: string | Win32Pointer, dest: Win32Pointer, destCapacity: number): number;
  /** icuuc.dll!u_unescapeAt */
  u_unescapeAt(charAt: Win32Callback, offset: Win32Pointer, length: number, context: Win32Pointer): number;
  /** icuuc.dll!u_versionFromString */
  u_versionFromString(versionArray: Win32Pointer, versionString: string | Win32Pointer): void;
  /** icuuc.dll!u_versionFromUString */
  u_versionFromUString(versionArray: Win32Pointer, versionString: Win32Pointer): void;
  /** icuuc.dll!u_versionToString */
  u_versionToString(versionArray: Win32Pointer, versionString: string | Win32Pointer): void;
  /** icuuc.dll!ubidi_close */
  ubidi_close(pBiDi: Win32Pointer): void;
  /** icuuc.dll!ubidi_countParagraphs */
  ubidi_countParagraphs(pBiDi: Win32Pointer): number;
  /** icuuc.dll!ubidi_countRuns */
  ubidi_countRuns(pBiDi: Win32Pointer, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ubidi_getBaseDirection */
  ubidi_getBaseDirection(text: Win32Pointer, length: number): number;
  /** icuuc.dll!ubidi_getClassCallback */
  ubidi_getClassCallback(pBiDi: Win32Pointer, fn: Win32Pointer, context: Win32Pointer): void;
  /** icuuc.dll!ubidi_getCustomizedClass */
  ubidi_getCustomizedClass(pBiDi: Win32Pointer, c: number): number;
  /** icuuc.dll!ubidi_getDirection */
  ubidi_getDirection(pBiDi: Win32Pointer): number;
  /** icuuc.dll!ubidi_getLength */
  ubidi_getLength(pBiDi: Win32Pointer): number;
  /** icuuc.dll!ubidi_getLevelAt */
  ubidi_getLevelAt(pBiDi: Win32Pointer, charIndex: number): number;
  /** icuuc.dll!ubidi_getLevels */
  ubidi_getLevels(pBiDi: Win32Pointer, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!ubidi_getLogicalIndex */
  ubidi_getLogicalIndex(pBiDi: Win32Pointer, visualIndex: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ubidi_getLogicalMap */
  ubidi_getLogicalMap(pBiDi: Win32Pointer, indexMap: Win32Pointer, pErrorCode: Win32Pointer): void;
  /** icuuc.dll!ubidi_getLogicalRun */
  ubidi_getLogicalRun(pBiDi: Win32Pointer, logicalPosition: number, pLogicalLimit: Win32Pointer, pLevel: Win32Pointer): void;
  /** icuuc.dll!ubidi_getParaLevel */
  ubidi_getParaLevel(pBiDi: Win32Pointer): number;
  /** icuuc.dll!ubidi_getParagraph */
  ubidi_getParagraph(pBiDi: Win32Pointer, charIndex: number, pParaStart: Win32Pointer, pParaLimit: Win32Pointer, pParaLevel: Win32Pointer, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ubidi_getParagraphByIndex */
  ubidi_getParagraphByIndex(pBiDi: Win32Pointer, paraIndex: number, pParaStart: Win32Pointer, pParaLimit: Win32Pointer, pParaLevel: Win32Pointer, pErrorCode: Win32Pointer): void;
  /** icuuc.dll!ubidi_getProcessedLength */
  ubidi_getProcessedLength(pBiDi: Win32Pointer): number;
  /** icuuc.dll!ubidi_getReorderingMode */
  ubidi_getReorderingMode(pBiDi: Win32Pointer): number;
  /** icuuc.dll!ubidi_getReorderingOptions */
  ubidi_getReorderingOptions(pBiDi: Win32Pointer): number;
  /** icuuc.dll!ubidi_getResultLength */
  ubidi_getResultLength(pBiDi: Win32Pointer): number;
  /** icuuc.dll!ubidi_getText */
  ubidi_getText(pBiDi: Win32Pointer): number | null;
  /** icuuc.dll!ubidi_getVisualIndex */
  ubidi_getVisualIndex(pBiDi: Win32Pointer, logicalIndex: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ubidi_getVisualMap */
  ubidi_getVisualMap(pBiDi: Win32Pointer, indexMap: Win32Pointer, pErrorCode: Win32Pointer): void;
  /** icuuc.dll!ubidi_getVisualRun */
  ubidi_getVisualRun(pBiDi: Win32Pointer, runIndex: number, pLogicalStart: Win32Pointer, pLength: Win32Pointer): number;
  /** icuuc.dll!ubidi_invertMap */
  ubidi_invertMap(srcMap: Win32Pointer, destMap: Win32Pointer, length: number): void;
  /** icuuc.dll!ubidi_isInverse */
  ubidi_isInverse(pBiDi: Win32Pointer): number;
  /** icuuc.dll!ubidi_isOrderParagraphsLTR */
  ubidi_isOrderParagraphsLTR(pBiDi: Win32Pointer): number;
  /** icuuc.dll!ubidi_open */
  ubidi_open(): number | null;
  /** icuuc.dll!ubidi_openSized */
  ubidi_openSized(maxLength: number, maxRunCount: number, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!ubidi_orderParagraphsLTR */
  ubidi_orderParagraphsLTR(pBiDi: Win32Pointer, orderParagraphsLTR: number): void;
  /** icuuc.dll!ubidi_reorderLogical */
  ubidi_reorderLogical(levels: Win32Pointer, length: number, indexMap: Win32Pointer): void;
  /** icuuc.dll!ubidi_reorderVisual */
  ubidi_reorderVisual(levels: Win32Pointer, length: number, indexMap: Win32Pointer): void;
  /** icuuc.dll!ubidi_setClassCallback */
  ubidi_setClassCallback(pBiDi: Win32Pointer, newFn: Win32Callback, newContext: Win32Pointer, oldFn: Win32Pointer, oldContext: Win32Pointer, pErrorCode: Win32Pointer): void;
  /** icuuc.dll!ubidi_setContext */
  ubidi_setContext(pBiDi: Win32Pointer, prologue: Win32Pointer, proLength: number, epilogue: Win32Pointer, epiLength: number, pErrorCode: Win32Pointer): void;
  /** icuuc.dll!ubidi_setInverse */
  ubidi_setInverse(pBiDi: Win32Pointer, isInverse: number): void;
  /** icuuc.dll!ubidi_setLine */
  ubidi_setLine(pParaBiDi: Win32Pointer, start: number, limit: number, pLineBiDi: Win32Pointer, pErrorCode: Win32Pointer): void;
  /** icuuc.dll!ubidi_setPara */
  ubidi_setPara(pBiDi: Win32Pointer, text: Win32Pointer, length: number, paraLevel: number, embeddingLevels: Win32Pointer, pErrorCode: Win32Pointer): void;
  /** icuuc.dll!ubidi_setReorderingMode */
  ubidi_setReorderingMode(pBiDi: Win32Pointer, reorderingMode: number): void;
  /** icuuc.dll!ubidi_setReorderingOptions */
  ubidi_setReorderingOptions(pBiDi: Win32Pointer, reorderingOptions: number): void;
  /** icuuc.dll!ubidi_writeReordered */
  ubidi_writeReordered(pBiDi: Win32Pointer, dest: Win32Pointer, destSize: number, options: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ubidi_writeReverse */
  ubidi_writeReverse(src: Win32Pointer, srcLength: number, dest: Win32Pointer, destSize: number, options: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ubiditransform_close */
  ubiditransform_close(pBidiTransform: Win32Pointer): void;
  /** icuuc.dll!ubiditransform_open */
  ubiditransform_open(pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!ubiditransform_transform */
  ubiditransform_transform(pBiDiTransform: Win32Pointer, src: Win32Pointer, srcLength: number, dest: Win32Pointer, destSize: number, inParaLevel: number, inOrder: number, outParaLevel: number, outOrder: number, doMirroring: number, shapingOptions: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ublock_getCode */
  ublock_getCode(c: number): number;
  /** icuuc.dll!ubrk_close */
  ubrk_close(bi: Win32Pointer): void;
  /** icuuc.dll!ubrk_countAvailable */
  ubrk_countAvailable(): number;
  /** icuuc.dll!ubrk_current */
  ubrk_current(bi: Win32Pointer): number;
  /** icuuc.dll!ubrk_first */
  ubrk_first(bi: Win32Pointer): number;
  /** icuuc.dll!ubrk_following */
  ubrk_following(bi: Win32Pointer, offset: number): number;
  /** icuuc.dll!ubrk_getAvailable */
  ubrk_getAvailable(index: number): number | null;
  /** icuuc.dll!ubrk_getBinaryRules */
  ubrk_getBinaryRules(bi: Win32Pointer, binaryRules: Win32Pointer, rulesCapacity: number, status: Win32Pointer): number;
  /** icuuc.dll!ubrk_getLocaleByType */
  ubrk_getLocaleByType(bi: Win32Pointer, type: number, status: Win32Pointer): number | null;
  /** icuuc.dll!ubrk_getRuleStatus */
  ubrk_getRuleStatus(bi: Win32Pointer): number;
  /** icuuc.dll!ubrk_getRuleStatusVec */
  ubrk_getRuleStatusVec(bi: Win32Pointer, fillInVec: Win32Pointer, capacity: number, status: Win32Pointer): number;
  /** icuuc.dll!ubrk_isBoundary */
  ubrk_isBoundary(bi: Win32Pointer, offset: number): number;
  /** icuuc.dll!ubrk_last */
  ubrk_last(bi: Win32Pointer): number;
  /** icuuc.dll!ubrk_next */
  ubrk_next(bi: Win32Pointer): number;
  /** icuuc.dll!ubrk_open */
  ubrk_open(type: number, locale: string | Win32Pointer, text: Win32Pointer, textLength: number, status: Win32Pointer): number | null;
  /** icuuc.dll!ubrk_openBinaryRules */
  ubrk_openBinaryRules(binaryRules: Win32Pointer, rulesLength: number, text: Win32Pointer, textLength: number, status: Win32Pointer): number | null;
  /** icuuc.dll!ubrk_openRules */
  ubrk_openRules(rules: Win32Pointer, rulesLength: number, text: Win32Pointer, textLength: number, parseErr: Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!ubrk_preceding */
  ubrk_preceding(bi: Win32Pointer, offset: number): number;
  /** icuuc.dll!ubrk_previous */
  ubrk_previous(bi: Win32Pointer): number;
  /** icuuc.dll!ubrk_refreshUText */
  ubrk_refreshUText(bi: Win32Pointer, text: Win32Pointer, status: Win32Pointer): void;
  /** icuuc.dll!ubrk_safeClone */
  ubrk_safeClone(bi: Win32Pointer, stackBuffer: Win32Pointer, pBufferSize: Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!ubrk_setText */
  ubrk_setText(bi: Win32Pointer, text: Win32Pointer, textLength: number, status: Win32Pointer): void;
  /** icuuc.dll!ubrk_setUText */
  ubrk_setUText(bi: Win32Pointer, text: Win32Pointer, status: Win32Pointer): void;
  /** icuuc.dll!ucasemap_close */
  ucasemap_close(csm: Win32Pointer): void;
  /** icuuc.dll!ucasemap_getBreakIterator */
  ucasemap_getBreakIterator(csm: Win32Pointer): number | null;
  /** icuuc.dll!ucasemap_getLocale */
  ucasemap_getLocale(csm: Win32Pointer): number | null;
  /** icuuc.dll!ucasemap_getOptions */
  ucasemap_getOptions(csm: Win32Pointer): number;
  /** icuuc.dll!ucasemap_open */
  ucasemap_open(locale: string | Win32Pointer, options: number, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!ucasemap_setBreakIterator */
  ucasemap_setBreakIterator(csm: Win32Pointer, iterToAdopt: Win32Pointer, pErrorCode: Win32Pointer): void;
  /** icuuc.dll!ucasemap_setLocale */
  ucasemap_setLocale(csm: Win32Pointer, locale: string | Win32Pointer, pErrorCode: Win32Pointer): void;
  /** icuuc.dll!ucasemap_setOptions */
  ucasemap_setOptions(csm: Win32Pointer, options: number, pErrorCode: Win32Pointer): void;
  /** icuuc.dll!ucasemap_toTitle */
  ucasemap_toTitle(csm: Win32Pointer, dest: Win32Pointer, destCapacity: number, src: Win32Pointer, srcLength: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ucasemap_utf8FoldCase */
  ucasemap_utf8FoldCase(csm: Win32Pointer, dest: string | Win32Pointer, destCapacity: number, src: string | Win32Pointer, srcLength: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ucasemap_utf8ToLower */
  ucasemap_utf8ToLower(csm: Win32Pointer, dest: string | Win32Pointer, destCapacity: number, src: string | Win32Pointer, srcLength: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ucasemap_utf8ToTitle */
  ucasemap_utf8ToTitle(csm: Win32Pointer, dest: string | Win32Pointer, destCapacity: number, src: string | Win32Pointer, srcLength: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ucasemap_utf8ToUpper */
  ucasemap_utf8ToUpper(csm: Win32Pointer, dest: string | Win32Pointer, destCapacity: number, src: string | Win32Pointer, srcLength: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ucnv_cbFromUWriteBytes */
  ucnv_cbFromUWriteBytes(args: Win32Pointer, source: string | Win32Pointer, length: number, offsetIndex: number, err: Win32Pointer): void;
  /** icuuc.dll!ucnv_cbFromUWriteSub */
  ucnv_cbFromUWriteSub(args: Win32Pointer, offsetIndex: number, err: Win32Pointer): void;
  /** icuuc.dll!ucnv_cbFromUWriteUChars */
  ucnv_cbFromUWriteUChars(args: Win32Pointer, source: Win32Pointer, sourceLimit: Win32Pointer, offsetIndex: number, err: Win32Pointer): void;
  /** icuuc.dll!ucnv_cbToUWriteSub */
  ucnv_cbToUWriteSub(args: Win32Pointer, offsetIndex: number, err: Win32Pointer): void;
  /** icuuc.dll!ucnv_cbToUWriteUChars */
  ucnv_cbToUWriteUChars(args: Win32Pointer, source: Win32Pointer, length: number, offsetIndex: number, err: Win32Pointer): void;
  /** icuuc.dll!ucnv_close */
  ucnv_close(converter: Win32Pointer): void;
  /** icuuc.dll!ucnv_compareNames */
  ucnv_compareNames(name1: string | Win32Pointer, name2: string | Win32Pointer): number;
  /** icuuc.dll!ucnv_convert */
  ucnv_convert(toConverterName: string | Win32Pointer, fromConverterName: string | Win32Pointer, target: string | Win32Pointer, targetCapacity: number, source: string | Win32Pointer, sourceLength: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ucnv_convertEx */
  ucnv_convertEx(targetCnv: Win32Pointer, sourceCnv: Win32Pointer, target: Win32Pointer, targetLimit: string | Win32Pointer, source: Win32Pointer, sourceLimit: string | Win32Pointer, pivotStart: Win32Pointer, pivotSource: Win32Pointer, pivotTarget: Win32Pointer, pivotLimit: Win32Pointer, reset: number, flush: number, pErrorCode: Win32Pointer): void;
  /** icuuc.dll!ucnv_countAliases */
  ucnv_countAliases(alias: string | Win32Pointer, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ucnv_countAvailable */
  ucnv_countAvailable(): number;
  /** icuuc.dll!ucnv_countStandards */
  ucnv_countStandards(): number;
  /** icuuc.dll!ucnv_detectUnicodeSignature */
  ucnv_detectUnicodeSignature(source: string | Win32Pointer, sourceLength: number, signatureLength: Win32Pointer, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!ucnv_fixFileSeparator */
  ucnv_fixFileSeparator(cnv: Win32Pointer, source: Win32Pointer, sourceLen: number): void;
  /** icuuc.dll!ucnv_flushCache */
  ucnv_flushCache(): number;
  /** icuuc.dll!ucnv_fromAlgorithmic */
  ucnv_fromAlgorithmic(cnv: Win32Pointer, algorithmicType: number, target: string | Win32Pointer, targetCapacity: number, source: string | Win32Pointer, sourceLength: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ucnv_fromUChars */
  ucnv_fromUChars(cnv: Win32Pointer, dest: string | Win32Pointer, destCapacity: number, src: Win32Pointer, srcLength: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ucnv_fromUCountPending */
  ucnv_fromUCountPending(cnv: Win32Pointer, status: Win32Pointer): number;
  /** icuuc.dll!ucnv_fromUnicode */
  ucnv_fromUnicode(converter: Win32Pointer, target: Win32Pointer, targetLimit: string | Win32Pointer, source: Win32Pointer, sourceLimit: Win32Pointer, offsets: Win32Pointer, flush: number, err: Win32Pointer): void;
  /** icuuc.dll!ucnv_getAlias */
  ucnv_getAlias(alias: string | Win32Pointer, n: number, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!ucnv_getAliases */
  ucnv_getAliases(alias: string | Win32Pointer, aliases: Win32Pointer, pErrorCode: Win32Pointer): void;
  /** icuuc.dll!ucnv_getAvailableName */
  ucnv_getAvailableName(n: number): number | null;
  /** icuuc.dll!ucnv_getCCSID */
  ucnv_getCCSID(converter: Win32Pointer, err: Win32Pointer): number;
  /** icuuc.dll!ucnv_getCanonicalName */
  ucnv_getCanonicalName(alias: string | Win32Pointer, standard: string | Win32Pointer, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!ucnv_getDefaultName */
  ucnv_getDefaultName(): number | null;
  /** icuuc.dll!ucnv_getDisplayName */
  ucnv_getDisplayName(converter: Win32Pointer, displayLocale: string | Win32Pointer, displayName: Win32Pointer, displayNameCapacity: number, err: Win32Pointer): number;
  /** icuuc.dll!ucnv_getFromUCallBack */
  ucnv_getFromUCallBack(converter: Win32Pointer, action: Win32Pointer, context: Win32Pointer): void;
  /** icuuc.dll!ucnv_getInvalidChars */
  ucnv_getInvalidChars(converter: Win32Pointer, errBytes: string | Win32Pointer, len: Win32Pointer, err: Win32Pointer): void;
  /** icuuc.dll!ucnv_getInvalidUChars */
  ucnv_getInvalidUChars(converter: Win32Pointer, errUChars: Win32Pointer, len: Win32Pointer, err: Win32Pointer): void;
  /** icuuc.dll!ucnv_getMaxCharSize */
  ucnv_getMaxCharSize(converter: Win32Pointer): number;
  /** icuuc.dll!ucnv_getMinCharSize */
  ucnv_getMinCharSize(converter: Win32Pointer): number;
  /** icuuc.dll!ucnv_getName */
  ucnv_getName(converter: Win32Pointer, err: Win32Pointer): number | null;
  /** icuuc.dll!ucnv_getNextUChar */
  ucnv_getNextUChar(converter: Win32Pointer, source: Win32Pointer, sourceLimit: string | Win32Pointer, err: Win32Pointer): number;
  /** icuuc.dll!ucnv_getPlatform */
  ucnv_getPlatform(converter: Win32Pointer, err: Win32Pointer): number;
  /** icuuc.dll!ucnv_getStandard */
  ucnv_getStandard(n: number, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!ucnv_getStandardName */
  ucnv_getStandardName(name: string | Win32Pointer, standard: string | Win32Pointer, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!ucnv_getStarters */
  ucnv_getStarters(converter: Win32Pointer, starters: Win32Pointer, err: Win32Pointer): void;
  /** icuuc.dll!ucnv_getSubstChars */
  ucnv_getSubstChars(converter: Win32Pointer, subChars: string | Win32Pointer, len: Win32Pointer, err: Win32Pointer): void;
  /** icuuc.dll!ucnv_getToUCallBack */
  ucnv_getToUCallBack(converter: Win32Pointer, action: Win32Pointer, context: Win32Pointer): void;
  /** icuuc.dll!ucnv_getType */
  ucnv_getType(converter: Win32Pointer): number;
  /** icuuc.dll!ucnv_getUnicodeSet */
  ucnv_getUnicodeSet(cnv: Win32Pointer, setFillIn: Win32Pointer, whichSet: number, pErrorCode: Win32Pointer): void;
  /** icuuc.dll!ucnv_isAmbiguous */
  ucnv_isAmbiguous(cnv: Win32Pointer): number;
  /** icuuc.dll!ucnv_isFixedWidth */
  ucnv_isFixedWidth(cnv: Win32Pointer, status: Win32Pointer): number;
  /** icuuc.dll!ucnv_open */
  ucnv_open(converterName: string | Win32Pointer, err: Win32Pointer): number | null;
  /** icuuc.dll!ucnv_openAllNames */
  ucnv_openAllNames(pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!ucnv_openCCSID */
  ucnv_openCCSID(codepage: number, platform: number, err: Win32Pointer): number | null;
  /** icuuc.dll!ucnv_openPackage */
  ucnv_openPackage(packageName: string | Win32Pointer, converterName: string | Win32Pointer, err: Win32Pointer): number | null;
  /** icuuc.dll!ucnv_openStandardNames */
  ucnv_openStandardNames(convName: string | Win32Pointer, standard: string | Win32Pointer, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!ucnv_openU */
  ucnv_openU(name: Win32Pointer, err: Win32Pointer): number | null;
  /** icuuc.dll!ucnv_reset */
  ucnv_reset(converter: Win32Pointer): void;
  /** icuuc.dll!ucnv_resetFromUnicode */
  ucnv_resetFromUnicode(converter: Win32Pointer): void;
  /** icuuc.dll!ucnv_resetToUnicode */
  ucnv_resetToUnicode(converter: Win32Pointer): void;
  /** icuuc.dll!ucnv_safeClone */
  ucnv_safeClone(cnv: Win32Pointer, stackBuffer: Win32Pointer, pBufferSize: Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!ucnv_setDefaultName */
  ucnv_setDefaultName(name: string | Win32Pointer): void;
  /** icuuc.dll!ucnv_setFallback */
  ucnv_setFallback(cnv: Win32Pointer, usesFallback: number): void;
  /** icuuc.dll!ucnv_setFromUCallBack */
  ucnv_setFromUCallBack(converter: Win32Pointer, newAction: Win32Callback, newContext: Win32Pointer, oldAction: Win32Pointer, oldContext: Win32Pointer, err: Win32Pointer): void;
  /** icuuc.dll!ucnv_setSubstChars */
  ucnv_setSubstChars(converter: Win32Pointer, subChars: string | Win32Pointer, len: number, err: Win32Pointer): void;
  /** icuuc.dll!ucnv_setSubstString */
  ucnv_setSubstString(cnv: Win32Pointer, s: Win32Pointer, length: number, err: Win32Pointer): void;
  /** icuuc.dll!ucnv_setToUCallBack */
  ucnv_setToUCallBack(converter: Win32Pointer, newAction: Win32Callback, newContext: Win32Pointer, oldAction: Win32Pointer, oldContext: Win32Pointer, err: Win32Pointer): void;
  /** icuuc.dll!ucnv_toAlgorithmic */
  ucnv_toAlgorithmic(algorithmicType: number, cnv: Win32Pointer, target: string | Win32Pointer, targetCapacity: number, source: string | Win32Pointer, sourceLength: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ucnv_toUChars */
  ucnv_toUChars(cnv: Win32Pointer, dest: Win32Pointer, destCapacity: number, src: string | Win32Pointer, srcLength: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ucnv_toUCountPending */
  ucnv_toUCountPending(cnv: Win32Pointer, status: Win32Pointer): number;
  /** icuuc.dll!ucnv_toUnicode */
  ucnv_toUnicode(converter: Win32Pointer, target: Win32Pointer, targetLimit: Win32Pointer, source: Win32Pointer, sourceLimit: string | Win32Pointer, offsets: Win32Pointer, flush: number, err: Win32Pointer): void;
  /** icuuc.dll!ucnv_usesFallback */
  ucnv_usesFallback(cnv: Win32Pointer): number;
  /** icuuc.dll!ucnvsel_close */
  ucnvsel_close(sel: Win32Pointer): void;
  /** icuuc.dll!ucnvsel_open */
  ucnvsel_open(converterList: Win32Pointer, converterListSize: number, excludedCodePoints: Win32Pointer, whichSet: number, status: Win32Pointer): number | null;
  /** icuuc.dll!ucnvsel_openFromSerialized */
  ucnvsel_openFromSerialized(buffer: Win32Pointer, length: number, status: Win32Pointer): number | null;
  /** icuuc.dll!ucnvsel_selectForString */
  ucnvsel_selectForString(sel: Win32Pointer, s: Win32Pointer, length: number, status: Win32Pointer): number | null;
  /** icuuc.dll!ucnvsel_selectForUTF8 */
  ucnvsel_selectForUTF8(sel: Win32Pointer, s: string | Win32Pointer, length: number, status: Win32Pointer): number | null;
  /** icuuc.dll!ucnvsel_serialize */
  ucnvsel_serialize(sel: Win32Pointer, buffer: Win32Pointer, bufferCapacity: number, status: Win32Pointer): number;
  /** icuuc.dll!ucurr_countCurrencies */
  ucurr_countCurrencies(locale: string | Win32Pointer, date: number, ec: Win32Pointer): number;
  /** icuuc.dll!ucurr_forLocale */
  ucurr_forLocale(locale: string | Win32Pointer, buff: Win32Pointer, buffCapacity: number, ec: Win32Pointer): number;
  /** icuuc.dll!ucurr_forLocaleAndDate */
  ucurr_forLocaleAndDate(locale: string | Win32Pointer, date: number, index: number, buff: Win32Pointer, buffCapacity: number, ec: Win32Pointer): number;
  /** icuuc.dll!ucurr_getDefaultFractionDigits */
  ucurr_getDefaultFractionDigits(currency: Win32Pointer, ec: Win32Pointer): number;
  /** icuuc.dll!ucurr_getDefaultFractionDigitsForUsage */
  ucurr_getDefaultFractionDigitsForUsage(currency: Win32Pointer, usage: number, ec: Win32Pointer): number;
  /** icuuc.dll!ucurr_getKeywordValuesForLocale */
  ucurr_getKeywordValuesForLocale(key: string | Win32Pointer, locale: string | Win32Pointer, commonlyUsed: number, status: Win32Pointer): number | null;
  /** icuuc.dll!ucurr_getName */
  ucurr_getName(currency: Win32Pointer, locale: string | Win32Pointer, nameStyle: number, isChoiceFormat: Win32Pointer, len: Win32Pointer, ec: Win32Pointer): number | null;
  /** icuuc.dll!ucurr_getNumericCode */
  ucurr_getNumericCode(currency: Win32Pointer): number;
  /** icuuc.dll!ucurr_getPluralName */
  ucurr_getPluralName(currency: Win32Pointer, locale: string | Win32Pointer, isChoiceFormat: Win32Pointer, pluralCount: string | Win32Pointer, len: Win32Pointer, ec: Win32Pointer): number | null;
  /** icuuc.dll!ucurr_getRoundingIncrement */
  ucurr_getRoundingIncrement(currency: Win32Pointer, ec: Win32Pointer): number;
  /** icuuc.dll!ucurr_getRoundingIncrementForUsage */
  ucurr_getRoundingIncrementForUsage(currency: Win32Pointer, usage: number, ec: Win32Pointer): number;
  /** icuuc.dll!ucurr_isAvailable */
  ucurr_isAvailable(isoCode: Win32Pointer, from: number, to: number, errorCode: Win32Pointer): number;
  /** icuuc.dll!ucurr_openISOCurrencies */
  ucurr_openISOCurrencies(currType: number, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!ucurr_register */
  ucurr_register(isoCode: Win32Pointer, locale: string | Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!ucurr_unregister */
  ucurr_unregister(key: Win32Pointer, status: Win32Pointer): number;
  /** icuuc.dll!uenum_close */
  uenum_close(en: Win32Pointer): void;
  /** icuuc.dll!uenum_count */
  uenum_count(en: Win32Pointer, status: Win32Pointer): number;
  /** icuuc.dll!uenum_next */
  uenum_next(en: Win32Pointer, resultLength: Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!uenum_openCharStringsEnumeration */
  uenum_openCharStringsEnumeration(strings: Win32Pointer, count: number, ec: Win32Pointer): number | null;
  /** icuuc.dll!uenum_openUCharStringsEnumeration */
  uenum_openUCharStringsEnumeration(strings: Win32Pointer, count: number, ec: Win32Pointer): number | null;
  /** icuuc.dll!uenum_reset */
  uenum_reset(en: Win32Pointer, status: Win32Pointer): void;
  /** icuuc.dll!uenum_unext */
  uenum_unext(en: Win32Pointer, resultLength: Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!uidna_close */
  uidna_close(idna: Win32Pointer): void;
  /** icuuc.dll!uidna_labelToASCII */
  uidna_labelToASCII(idna: Win32Pointer, label: Win32Pointer, length: number, dest: Win32Pointer, capacity: number, pInfo: Win32Pointer, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uidna_labelToASCII_UTF8 */
  uidna_labelToASCII_UTF8(idna: Win32Pointer, label: string | Win32Pointer, length: number, dest: string | Win32Pointer, capacity: number, pInfo: Win32Pointer, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uidna_labelToUnicode */
  uidna_labelToUnicode(idna: Win32Pointer, label: Win32Pointer, length: number, dest: Win32Pointer, capacity: number, pInfo: Win32Pointer, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uidna_labelToUnicodeUTF8 */
  uidna_labelToUnicodeUTF8(idna: Win32Pointer, label: string | Win32Pointer, length: number, dest: string | Win32Pointer, capacity: number, pInfo: Win32Pointer, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uidna_nameToASCII */
  uidna_nameToASCII(idna: Win32Pointer, name: Win32Pointer, length: number, dest: Win32Pointer, capacity: number, pInfo: Win32Pointer, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uidna_nameToASCII_UTF8 */
  uidna_nameToASCII_UTF8(idna: Win32Pointer, name: string | Win32Pointer, length: number, dest: string | Win32Pointer, capacity: number, pInfo: Win32Pointer, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uidna_nameToUnicode */
  uidna_nameToUnicode(idna: Win32Pointer, name: Win32Pointer, length: number, dest: Win32Pointer, capacity: number, pInfo: Win32Pointer, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uidna_nameToUnicodeUTF8 */
  uidna_nameToUnicodeUTF8(idna: Win32Pointer, name: string | Win32Pointer, length: number, dest: string | Win32Pointer, capacity: number, pInfo: Win32Pointer, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uidna_openUTS46 */
  uidna_openUTS46(options: number, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!uiter_current32 */
  uiter_current32(iter: Win32Pointer): number;
  /** icuuc.dll!uiter_getState */
  uiter_getState(iter: Win32Pointer): number;
  /** icuuc.dll!uiter_next32 */
  uiter_next32(iter: Win32Pointer): number;
  /** icuuc.dll!uiter_previous32 */
  uiter_previous32(iter: Win32Pointer): number;
  /** icuuc.dll!uiter_setState */
  uiter_setState(iter: Win32Pointer, state: number, pErrorCode: Win32Pointer): void;
  /** icuuc.dll!uiter_setString */
  uiter_setString(iter: Win32Pointer, s: Win32Pointer, length: number): void;
  /** icuuc.dll!uiter_setUTF16BE */
  uiter_setUTF16BE(iter: Win32Pointer, s: string | Win32Pointer, length: number): void;
  /** icuuc.dll!uiter_setUTF8 */
  uiter_setUTF8(iter: Win32Pointer, s: string | Win32Pointer, length: number): void;
  /** icuuc.dll!uldn_close */
  uldn_close(ldn: Win32Pointer): void;
  /** icuuc.dll!uldn_getContext */
  uldn_getContext(ldn: Win32Pointer, type: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uldn_getDialectHandling */
  uldn_getDialectHandling(ldn: Win32Pointer): number;
  /** icuuc.dll!uldn_getLocale */
  uldn_getLocale(ldn: Win32Pointer): number | null;
  /** icuuc.dll!uldn_keyDisplayName */
  uldn_keyDisplayName(ldn: Win32Pointer, key: string | Win32Pointer, result: Win32Pointer, maxResultSize: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uldn_keyValueDisplayName */
  uldn_keyValueDisplayName(ldn: Win32Pointer, key: string | Win32Pointer, value: string | Win32Pointer, result: Win32Pointer, maxResultSize: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uldn_languageDisplayName */
  uldn_languageDisplayName(ldn: Win32Pointer, lang: string | Win32Pointer, result: Win32Pointer, maxResultSize: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uldn_localeDisplayName */
  uldn_localeDisplayName(ldn: Win32Pointer, locale: string | Win32Pointer, result: Win32Pointer, maxResultSize: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uldn_open */
  uldn_open(locale: string | Win32Pointer, dialectHandling: number, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!uldn_openForContext */
  uldn_openForContext(locale: string | Win32Pointer, contexts: Win32Pointer, length: number, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!uldn_regionDisplayName */
  uldn_regionDisplayName(ldn: Win32Pointer, region: string | Win32Pointer, result: Win32Pointer, maxResultSize: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uldn_scriptCodeDisplayName */
  uldn_scriptCodeDisplayName(ldn: Win32Pointer, scriptCode: number, result: Win32Pointer, maxResultSize: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uldn_scriptDisplayName */
  uldn_scriptDisplayName(ldn: Win32Pointer, script: string | Win32Pointer, result: Win32Pointer, maxResultSize: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uldn_variantDisplayName */
  uldn_variantDisplayName(ldn: Win32Pointer, variant: string | Win32Pointer, result: Win32Pointer, maxResultSize: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ulistfmt_close */
  ulistfmt_close(listfmt: Win32Pointer): void;
  /** icuuc.dll!ulistfmt_format */
  ulistfmt_format(listfmt: Win32Pointer, strings: Win32Pointer, stringLengths: Win32Pointer, stringCount: number, result: Win32Pointer, resultCapacity: number, status: Win32Pointer): number;
  /** icuuc.dll!ulistfmt_open */
  ulistfmt_open(locale: string | Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!uloc_acceptLanguage */
  uloc_acceptLanguage(result: string | Win32Pointer, resultAvailable: number, outResult: Win32Pointer, acceptList: Win32Pointer, acceptListCount: number, availableLocales: Win32Pointer, status: Win32Pointer): number;
  /** icuuc.dll!uloc_acceptLanguageFromHTTP */
  uloc_acceptLanguageFromHTTP(result: string | Win32Pointer, resultAvailable: number, outResult: Win32Pointer, httpAcceptLanguage: string | Win32Pointer, availableLocales: Win32Pointer, status: Win32Pointer): number;
  /** icuuc.dll!uloc_addLikelySubtags */
  uloc_addLikelySubtags(localeID: string | Win32Pointer, maximizedLocaleID: string | Win32Pointer, maximizedLocaleIDCapacity: number, err: Win32Pointer): number;
  /** icuuc.dll!uloc_canonicalize */
  uloc_canonicalize(localeID: string | Win32Pointer, name: string | Win32Pointer, nameCapacity: number, err: Win32Pointer): number;
  /** icuuc.dll!uloc_countAvailable */
  uloc_countAvailable(): number;
  /** icuuc.dll!uloc_forLanguageTag */
  uloc_forLanguageTag(langtag: string | Win32Pointer, localeID: string | Win32Pointer, localeIDCapacity: number, parsedLength: Win32Pointer, err: Win32Pointer): number;
  /** icuuc.dll!uloc_getAvailable */
  uloc_getAvailable(n: number): number | null;
  /** icuuc.dll!uloc_getBaseName */
  uloc_getBaseName(localeID: string | Win32Pointer, name: string | Win32Pointer, nameCapacity: number, err: Win32Pointer): number;
  /** icuuc.dll!uloc_getCharacterOrientation */
  uloc_getCharacterOrientation(localeId: string | Win32Pointer, status: Win32Pointer): number;
  /** icuuc.dll!uloc_getCountry */
  uloc_getCountry(localeID: string | Win32Pointer, country: string | Win32Pointer, countryCapacity: number, err: Win32Pointer): number;
  /** icuuc.dll!uloc_getDefault */
  uloc_getDefault(): number | null;
  /** icuuc.dll!uloc_getDisplayCountry */
  uloc_getDisplayCountry(locale: string | Win32Pointer, displayLocale: string | Win32Pointer, country: Win32Pointer, countryCapacity: number, status: Win32Pointer): number;
  /** icuuc.dll!uloc_getDisplayKeyword */
  uloc_getDisplayKeyword(keyword: string | Win32Pointer, displayLocale: string | Win32Pointer, dest: Win32Pointer, destCapacity: number, status: Win32Pointer): number;
  /** icuuc.dll!uloc_getDisplayKeywordValue */
  uloc_getDisplayKeywordValue(locale: string | Win32Pointer, keyword: string | Win32Pointer, displayLocale: string | Win32Pointer, dest: Win32Pointer, destCapacity: number, status: Win32Pointer): number;
  /** icuuc.dll!uloc_getDisplayLanguage */
  uloc_getDisplayLanguage(locale: string | Win32Pointer, displayLocale: string | Win32Pointer, language: Win32Pointer, languageCapacity: number, status: Win32Pointer): number;
  /** icuuc.dll!uloc_getDisplayName */
  uloc_getDisplayName(localeID: string | Win32Pointer, inLocaleID: string | Win32Pointer, result: Win32Pointer, maxResultSize: number, err: Win32Pointer): number;
  /** icuuc.dll!uloc_getDisplayScript */
  uloc_getDisplayScript(locale: string | Win32Pointer, displayLocale: string | Win32Pointer, script: Win32Pointer, scriptCapacity: number, status: Win32Pointer): number;
  /** icuuc.dll!uloc_getDisplayVariant */
  uloc_getDisplayVariant(locale: string | Win32Pointer, displayLocale: string | Win32Pointer, variant: Win32Pointer, variantCapacity: number, status: Win32Pointer): number;
  /** icuuc.dll!uloc_getISO3Country */
  uloc_getISO3Country(localeID: string | Win32Pointer): number | null;
  /** icuuc.dll!uloc_getISO3Language */
  uloc_getISO3Language(localeID: string | Win32Pointer): number | null;
  /** icuuc.dll!uloc_getISOCountries */
  uloc_getISOCountries(): number | null;
  /** icuuc.dll!uloc_getISOLanguages */
  uloc_getISOLanguages(): number | null;
  /** icuuc.dll!uloc_getKeywordValue */
  uloc_getKeywordValue(localeID: string | Win32Pointer, keywordName: string | Win32Pointer, buffer: string | Win32Pointer, bufferCapacity: number, status: Win32Pointer): number;
  /** icuuc.dll!uloc_getLCID */
  uloc_getLCID(localeID: string | Win32Pointer): number;
  /** icuuc.dll!uloc_getLanguage */
  uloc_getLanguage(localeID: string | Win32Pointer, language: string | Win32Pointer, languageCapacity: number, err: Win32Pointer): number;
  /** icuuc.dll!uloc_getLineOrientation */
  uloc_getLineOrientation(localeId: string | Win32Pointer, status: Win32Pointer): number;
  /** icuuc.dll!uloc_getLocaleForLCID */
  uloc_getLocaleForLCID(hostID: number, locale: string | Win32Pointer, localeCapacity: number, status: Win32Pointer): number;
  /** icuuc.dll!uloc_getName */
  uloc_getName(localeID: string | Win32Pointer, name: string | Win32Pointer, nameCapacity: number, err: Win32Pointer): number;
  /** icuuc.dll!uloc_getParent */
  uloc_getParent(localeID: string | Win32Pointer, parent: string | Win32Pointer, parentCapacity: number, err: Win32Pointer): number;
  /** icuuc.dll!uloc_getScript */
  uloc_getScript(localeID: string | Win32Pointer, script: string | Win32Pointer, scriptCapacity: number, err: Win32Pointer): number;
  /** icuuc.dll!uloc_getVariant */
  uloc_getVariant(localeID: string | Win32Pointer, variant: string | Win32Pointer, variantCapacity: number, err: Win32Pointer): number;
  /** icuuc.dll!uloc_isRightToLeft */
  uloc_isRightToLeft(locale: string | Win32Pointer): number;
  /** icuuc.dll!uloc_minimizeSubtags */
  uloc_minimizeSubtags(localeID: string | Win32Pointer, minimizedLocaleID: string | Win32Pointer, minimizedLocaleIDCapacity: number, err: Win32Pointer): number;
  /** icuuc.dll!uloc_openKeywords */
  uloc_openKeywords(localeID: string | Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!uloc_setDefault */
  uloc_setDefault(localeID: string | Win32Pointer, status: Win32Pointer): void;
  /** icuuc.dll!uloc_setKeywordValue */
  uloc_setKeywordValue(keywordName: string | Win32Pointer, keywordValue: string | Win32Pointer, buffer: string | Win32Pointer, bufferCapacity: number, status: Win32Pointer): number;
  /** icuuc.dll!uloc_toLanguageTag */
  uloc_toLanguageTag(localeID: string | Win32Pointer, langtag: string | Win32Pointer, langtagCapacity: number, strict: number, err: Win32Pointer): number;
  /** icuuc.dll!uloc_toLegacyKey */
  uloc_toLegacyKey(keyword: string | Win32Pointer): number | null;
  /** icuuc.dll!uloc_toLegacyType */
  uloc_toLegacyType(keyword: string | Win32Pointer, value: string | Win32Pointer): number | null;
  /** icuuc.dll!uloc_toUnicodeLocaleKey */
  uloc_toUnicodeLocaleKey(keyword: string | Win32Pointer): number | null;
  /** icuuc.dll!uloc_toUnicodeLocaleType */
  uloc_toUnicodeLocaleType(keyword: string | Win32Pointer, value: string | Win32Pointer): number | null;
  /** icuuc.dll!unorm2_append */
  unorm2_append(norm2: Win32Pointer, first: Win32Pointer, firstLength: number, firstCapacity: number, second: Win32Pointer, secondLength: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!unorm2_close */
  unorm2_close(norm2: Win32Pointer): void;
  /** icuuc.dll!unorm2_composePair */
  unorm2_composePair(norm2: Win32Pointer, a: number, b: number): number;
  /** icuuc.dll!unorm2_getCombiningClass */
  unorm2_getCombiningClass(norm2: Win32Pointer, c: number): number;
  /** icuuc.dll!unorm2_getDecomposition */
  unorm2_getDecomposition(norm2: Win32Pointer, c: number, decomposition: Win32Pointer, capacity: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!unorm2_getInstance */
  unorm2_getInstance(packageName: string | Win32Pointer, name: string | Win32Pointer, mode: number, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!unorm2_getNFCInstance */
  unorm2_getNFCInstance(pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!unorm2_getNFDInstance */
  unorm2_getNFDInstance(pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!unorm2_getNFKCCasefoldInstance */
  unorm2_getNFKCCasefoldInstance(pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!unorm2_getNFKCInstance */
  unorm2_getNFKCInstance(pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!unorm2_getNFKDInstance */
  unorm2_getNFKDInstance(pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!unorm2_getRawDecomposition */
  unorm2_getRawDecomposition(norm2: Win32Pointer, c: number, decomposition: Win32Pointer, capacity: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!unorm2_hasBoundaryAfter */
  unorm2_hasBoundaryAfter(norm2: Win32Pointer, c: number): number;
  /** icuuc.dll!unorm2_hasBoundaryBefore */
  unorm2_hasBoundaryBefore(norm2: Win32Pointer, c: number): number;
  /** icuuc.dll!unorm2_isInert */
  unorm2_isInert(norm2: Win32Pointer, c: number): number;
  /** icuuc.dll!unorm2_isNormalized */
  unorm2_isNormalized(norm2: Win32Pointer, s: Win32Pointer, length: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!unorm2_normalize */
  unorm2_normalize(norm2: Win32Pointer, src: Win32Pointer, length: number, dest: Win32Pointer, capacity: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!unorm2_normalizeSecondAndAppend */
  unorm2_normalizeSecondAndAppend(norm2: Win32Pointer, first: Win32Pointer, firstLength: number, firstCapacity: number, second: Win32Pointer, secondLength: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!unorm2_openFiltered */
  unorm2_openFiltered(norm2: Win32Pointer, filterSet: Win32Pointer, pErrorCode: Win32Pointer): number | null;
  /** icuuc.dll!unorm2_quickCheck */
  unorm2_quickCheck(norm2: Win32Pointer, s: Win32Pointer, length: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!unorm2_spanQuickCheckYes */
  unorm2_spanQuickCheckYes(norm2: Win32Pointer, s: Win32Pointer, length: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!unorm_compare */
  unorm_compare(s1: Win32Pointer, length1: number, s2: Win32Pointer, length2: number, options: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!ures_close */
  ures_close(resourceBundle: Win32Pointer): void;
  /** icuuc.dll!ures_getBinary */
  ures_getBinary(resourceBundle: Win32Pointer, len: Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!ures_getByIndex */
  ures_getByIndex(resourceBundle: Win32Pointer, indexR: number, fillIn: Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!ures_getByKey */
  ures_getByKey(resourceBundle: Win32Pointer, key: string | Win32Pointer, fillIn: Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!ures_getInt */
  ures_getInt(resourceBundle: Win32Pointer, status: Win32Pointer): number;
  /** icuuc.dll!ures_getIntVector */
  ures_getIntVector(resourceBundle: Win32Pointer, len: Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!ures_getKey */
  ures_getKey(resourceBundle: Win32Pointer): number | null;
  /** icuuc.dll!ures_getLocaleByType */
  ures_getLocaleByType(resourceBundle: Win32Pointer, type: number, status: Win32Pointer): number | null;
  /** icuuc.dll!ures_getNextResource */
  ures_getNextResource(resourceBundle: Win32Pointer, fillIn: Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!ures_getNextString */
  ures_getNextString(resourceBundle: Win32Pointer, len: Win32Pointer, key: Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!ures_getSize */
  ures_getSize(resourceBundle: Win32Pointer): number;
  /** icuuc.dll!ures_getString */
  ures_getString(resourceBundle: Win32Pointer, len: Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!ures_getStringByIndex */
  ures_getStringByIndex(resourceBundle: Win32Pointer, indexS: number, len: Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!ures_getStringByKey */
  ures_getStringByKey(resB: Win32Pointer, key: string | Win32Pointer, len: Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!ures_getType */
  ures_getType(resourceBundle: Win32Pointer): number;
  /** icuuc.dll!ures_getUInt */
  ures_getUInt(resourceBundle: Win32Pointer, status: Win32Pointer): number;
  /** icuuc.dll!ures_getUTF8String */
  ures_getUTF8String(resB: Win32Pointer, dest: string | Win32Pointer, length: Win32Pointer, forceCopy: number, status: Win32Pointer): number | null;
  /** icuuc.dll!ures_getUTF8StringByIndex */
  ures_getUTF8StringByIndex(resB: Win32Pointer, stringIndex: number, dest: string | Win32Pointer, pLength: Win32Pointer, forceCopy: number, status: Win32Pointer): number | null;
  /** icuuc.dll!ures_getUTF8StringByKey */
  ures_getUTF8StringByKey(resB: Win32Pointer, key: string | Win32Pointer, dest: string | Win32Pointer, pLength: Win32Pointer, forceCopy: number, status: Win32Pointer): number | null;
  /** icuuc.dll!ures_getVersion */
  ures_getVersion(resB: Win32Pointer, versionInfo: Win32Pointer): void;
  /** icuuc.dll!ures_hasNext */
  ures_hasNext(resourceBundle: Win32Pointer): number;
  /** icuuc.dll!ures_open */
  ures_open(packageName: string | Win32Pointer, locale: string | Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!ures_openAvailableLocales */
  ures_openAvailableLocales(packageName: string | Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!ures_openDirect */
  ures_openDirect(packageName: string | Win32Pointer, locale: string | Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!ures_openU */
  ures_openU(packageName: Win32Pointer, locale: string | Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!ures_resetIterator */
  ures_resetIterator(resourceBundle: Win32Pointer): void;
  /** icuuc.dll!uscript_breaksBetweenLetters */
  uscript_breaksBetweenLetters(script: number): number;
  /** icuuc.dll!uscript_getCode */
  uscript_getCode(nameOrAbbrOrLocale: string | Win32Pointer, fillIn: Win32Pointer, capacity: number, err: Win32Pointer): number;
  /** icuuc.dll!uscript_getName */
  uscript_getName(scriptCode: number): number | null;
  /** icuuc.dll!uscript_getSampleString */
  uscript_getSampleString(script: number, dest: Win32Pointer, capacity: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uscript_getScript */
  uscript_getScript(codepoint: number, err: Win32Pointer): number;
  /** icuuc.dll!uscript_getScriptExtensions */
  uscript_getScriptExtensions(c: number, scripts: Win32Pointer, capacity: number, errorCode: Win32Pointer): number;
  /** icuuc.dll!uscript_getShortName */
  uscript_getShortName(scriptCode: number): number | null;
  /** icuuc.dll!uscript_getUsage */
  uscript_getUsage(script: number): number;
  /** icuuc.dll!uscript_hasScript */
  uscript_hasScript(c: number, sc: number): number;
  /** icuuc.dll!uscript_isCased */
  uscript_isCased(script: number): number;
  /** icuuc.dll!uscript_isRightToLeft */
  uscript_isRightToLeft(script: number): number;
  /** icuuc.dll!uset_add */
  uset_add(set: Win32Pointer, c: number): void;
  /** icuuc.dll!uset_addAll */
  uset_addAll(set: Win32Pointer, additionalSet: Win32Pointer): void;
  /** icuuc.dll!uset_addAllCodePoints */
  uset_addAllCodePoints(set: Win32Pointer, str: Win32Pointer, strLen: number): void;
  /** icuuc.dll!uset_addRange */
  uset_addRange(set: Win32Pointer, start: number, end: number): void;
  /** icuuc.dll!uset_addString */
  uset_addString(set: Win32Pointer, str: Win32Pointer, strLen: number): void;
  /** icuuc.dll!uset_applyIntPropertyValue */
  uset_applyIntPropertyValue(set: Win32Pointer, prop: number, value: number, ec: Win32Pointer): void;
  /** icuuc.dll!uset_applyPattern */
  uset_applyPattern(set: Win32Pointer, pattern: Win32Pointer, patternLength: number, options: number, status: Win32Pointer): number;
  /** icuuc.dll!uset_applyPropertyAlias */
  uset_applyPropertyAlias(set: Win32Pointer, prop: Win32Pointer, propLength: number, value: Win32Pointer, valueLength: number, ec: Win32Pointer): void;
  /** icuuc.dll!uset_charAt */
  uset_charAt(set: Win32Pointer, charIndex: number): number;
  /** icuuc.dll!uset_clear */
  uset_clear(set: Win32Pointer): void;
  /** icuuc.dll!uset_clone */
  uset_clone(set: Win32Pointer): number | null;
  /** icuuc.dll!uset_cloneAsThawed */
  uset_cloneAsThawed(set: Win32Pointer): number | null;
  /** icuuc.dll!uset_close */
  uset_close(set: Win32Pointer): void;
  /** icuuc.dll!uset_closeOver */
  uset_closeOver(set: Win32Pointer, attributes: number): void;
  /** icuuc.dll!uset_compact */
  uset_compact(set: Win32Pointer): void;
  /** icuuc.dll!uset_complement */
  uset_complement(set: Win32Pointer): void;
  /** icuuc.dll!uset_complementAll */
  uset_complementAll(set: Win32Pointer, complement: Win32Pointer): void;
  /** icuuc.dll!uset_contains */
  uset_contains(set: Win32Pointer, c: number): number;
  /** icuuc.dll!uset_containsAll */
  uset_containsAll(set1: Win32Pointer, set2: Win32Pointer): number;
  /** icuuc.dll!uset_containsAllCodePoints */
  uset_containsAllCodePoints(set: Win32Pointer, str: Win32Pointer, strLen: number): number;
  /** icuuc.dll!uset_containsNone */
  uset_containsNone(set1: Win32Pointer, set2: Win32Pointer): number;
  /** icuuc.dll!uset_containsRange */
  uset_containsRange(set: Win32Pointer, start: number, end: number): number;
  /** icuuc.dll!uset_containsSome */
  uset_containsSome(set1: Win32Pointer, set2: Win32Pointer): number;
  /** icuuc.dll!uset_containsString */
  uset_containsString(set: Win32Pointer, str: Win32Pointer, strLen: number): number;
  /** icuuc.dll!uset_equals */
  uset_equals(set1: Win32Pointer, set2: Win32Pointer): number;
  /** icuuc.dll!uset_freeze */
  uset_freeze(set: Win32Pointer): void;
  /** icuuc.dll!uset_getItem */
  uset_getItem(set: Win32Pointer, itemIndex: number, start: Win32Pointer, end: Win32Pointer, str: Win32Pointer, strCapacity: number, ec: Win32Pointer): number;
  /** icuuc.dll!uset_getItemCount */
  uset_getItemCount(set: Win32Pointer): number;
  /** icuuc.dll!uset_getSerializedRange */
  uset_getSerializedRange(set: Win32Pointer, rangeIndex: number, pStart: Win32Pointer, pEnd: Win32Pointer): number;
  /** icuuc.dll!uset_getSerializedRangeCount */
  uset_getSerializedRangeCount(set: Win32Pointer): number;
  /** icuuc.dll!uset_getSerializedSet */
  uset_getSerializedSet(fillSet: Win32Pointer, src: Win32Pointer, srcLength: number): number;
  /** icuuc.dll!uset_indexOf */
  uset_indexOf(set: Win32Pointer, c: number): number;
  /** icuuc.dll!uset_isEmpty */
  uset_isEmpty(set: Win32Pointer): number;
  /** icuuc.dll!uset_isFrozen */
  uset_isFrozen(set: Win32Pointer): number;
  /** icuuc.dll!uset_open */
  uset_open(start: number, end: number): number | null;
  /** icuuc.dll!uset_openEmpty */
  uset_openEmpty(): number | null;
  /** icuuc.dll!uset_openPattern */
  uset_openPattern(pattern: Win32Pointer, patternLength: number, ec: Win32Pointer): number | null;
  /** icuuc.dll!uset_openPatternOptions */
  uset_openPatternOptions(pattern: Win32Pointer, patternLength: number, options: number, ec: Win32Pointer): number | null;
  /** icuuc.dll!uset_remove */
  uset_remove(set: Win32Pointer, c: number): void;
  /** icuuc.dll!uset_removeAll */
  uset_removeAll(set: Win32Pointer, removeSet: Win32Pointer): void;
  /** icuuc.dll!uset_removeAllStrings */
  uset_removeAllStrings(set: Win32Pointer): void;
  /** icuuc.dll!uset_removeRange */
  uset_removeRange(set: Win32Pointer, start: number, end: number): void;
  /** icuuc.dll!uset_removeString */
  uset_removeString(set: Win32Pointer, str: Win32Pointer, strLen: number): void;
  /** icuuc.dll!uset_resemblesPattern */
  uset_resemblesPattern(pattern: Win32Pointer, patternLength: number, pos: number): number;
  /** icuuc.dll!uset_retain */
  uset_retain(set: Win32Pointer, start: number, end: number): void;
  /** icuuc.dll!uset_retainAll */
  uset_retainAll(set: Win32Pointer, retain: Win32Pointer): void;
  /** icuuc.dll!uset_serialize */
  uset_serialize(set: Win32Pointer, dest: Win32Pointer, destCapacity: number, pErrorCode: Win32Pointer): number;
  /** icuuc.dll!uset_serializedContains */
  uset_serializedContains(set: Win32Pointer, c: number): number;
  /** icuuc.dll!uset_set */
  uset_set(set: Win32Pointer, start: number, end: number): void;
  /** icuuc.dll!uset_setSerializedToOne */
  uset_setSerializedToOne(fillSet: Win32Pointer, c: number): void;
  /** icuuc.dll!uset_size */
  uset_size(set: Win32Pointer): number;
  /** icuuc.dll!uset_span */
  uset_span(set: Win32Pointer, s: Win32Pointer, length: number, spanCondition: number): number;
  /** icuuc.dll!uset_spanBack */
  uset_spanBack(set: Win32Pointer, s: Win32Pointer, length: number, spanCondition: number): number;
  /** icuuc.dll!uset_spanBackUTF8 */
  uset_spanBackUTF8(set: Win32Pointer, s: string | Win32Pointer, length: number, spanCondition: number): number;
  /** icuuc.dll!uset_spanUTF8 */
  uset_spanUTF8(set: Win32Pointer, s: string | Win32Pointer, length: number, spanCondition: number): number;
  /** icuuc.dll!uset_toPattern */
  uset_toPattern(set: Win32Pointer, result: Win32Pointer, resultCapacity: number, escapeUnprintable: number, ec: Win32Pointer): number;
  /** icuuc.dll!usprep_close */
  usprep_close(profile: Win32Pointer): void;
  /** icuuc.dll!usprep_open */
  usprep_open(path: string | Win32Pointer, fileName: string | Win32Pointer, status: Win32Pointer): number | null;
  /** icuuc.dll!usprep_openByType */
  usprep_openByType(type: number, status: Win32Pointer): number | null;
  /** icuuc.dll!usprep_prepare */
  usprep_prepare(prep: Win32Pointer, src: Win32Pointer, srcLength: number, dest: Win32Pointer, destCapacity: number, options: number, parseError: Win32Pointer, status: Win32Pointer): number;
  /** icuuc.dll!utext_char32At */
  utext_char32At(ut: Win32Pointer, nativeIndex: number | bigint): number;
  /** icuuc.dll!utext_clone */
  utext_clone(dest: Win32Pointer, src: Win32Pointer, deep: number, readOnly: number, status: Win32Pointer): number | null;
  /** icuuc.dll!utext_close */
  utext_close(ut: Win32Pointer): number | null;
  /** icuuc.dll!utext_copy */
  utext_copy(ut: Win32Pointer, nativeStart: number | bigint, nativeLimit: number | bigint, destIndex: number | bigint, move: number, status: Win32Pointer): void;
  /** icuuc.dll!utext_current32 */
  utext_current32(ut: Win32Pointer): number;
  /** icuuc.dll!utext_equals */
  utext_equals(a: Win32Pointer, b: Win32Pointer): number;
  /** icuuc.dll!utext_extract */
  utext_extract(ut: Win32Pointer, nativeStart: number | bigint, nativeLimit: number | bigint, dest: Win32Pointer, destCapacity: number, status: Win32Pointer): number;
  /** icuuc.dll!utext_freeze */
  utext_freeze(ut: Win32Pointer): void;
  /** icuuc.dll!utext_getNativeIndex */
  utext_getNativeIndex(ut: Win32Pointer): bigint;
  /** icuuc.dll!utext_getPreviousNativeIndex */
  utext_getPreviousNativeIndex(ut: Win32Pointer): bigint;
  /** icuuc.dll!utext_hasMetaData */
  utext_hasMetaData(ut: Win32Pointer): number;
  /** icuuc.dll!utext_isLengthExpensive */
  utext_isLengthExpensive(ut: Win32Pointer): number;
  /** icuuc.dll!utext_isWritable */
  utext_isWritable(ut: Win32Pointer): number;
  /** icuuc.dll!utext_moveIndex32 */
  utext_moveIndex32(ut: Win32Pointer, delta: number): number;
  /** icuuc.dll!utext_nativeLength */
  utext_nativeLength(ut: Win32Pointer): bigint;
  /** icuuc.dll!utext_next32 */
  utext_next32(ut: Win32Pointer): number;
  /** icuuc.dll!utext_next32From */
  utext_next32From(ut: Win32Pointer, nativeIndex: number | bigint): number;
  /** icuuc.dll!utext_openUChars */
  utext_openUChars(ut: Win32Pointer, s: Win32Pointer, length: number | bigint, status: Win32Pointer): number | null;
  /** icuuc.dll!utext_openUTF8 */
  utext_openUTF8(ut: Win32Pointer, s: string | Win32Pointer, length: number | bigint, status: Win32Pointer): number | null;
  /** icuuc.dll!utext_previous32 */
  utext_previous32(ut: Win32Pointer): number;
  /** icuuc.dll!utext_previous32From */
  utext_previous32From(ut: Win32Pointer, nativeIndex: number | bigint): number;
  /** icuuc.dll!utext_replace */
  utext_replace(ut: Win32Pointer, nativeStart: number | bigint, nativeLimit: number | bigint, replacementText: Win32Pointer, replacementLength: number, status: Win32Pointer): number;
  /** icuuc.dll!utext_setNativeIndex */
  utext_setNativeIndex(ut: Win32Pointer, nativeIndex: number | bigint): void;
  /** icuuc.dll!utext_setup */
  utext_setup(ut: Win32Pointer, extraSpace: number, status: Win32Pointer): number | null;
  /** icuuc.dll!utf8_appendCharSafeBody */
  utf8_appendCharSafeBody(s: Win32Pointer, i: number, length: number, c: number, pIsError: Win32Pointer): number;
  /** icuuc.dll!utf8_back1SafeBody */
  utf8_back1SafeBody(s: Win32Pointer, start: number, i: number): number;
  /** icuuc.dll!utf8_nextCharSafeBody */
  utf8_nextCharSafeBody(s: Win32Pointer, pi: Win32Pointer, length: number, c: number, strict: number): number;
  /** icuuc.dll!utf8_prevCharSafeBody */
  utf8_prevCharSafeBody(s: Win32Pointer, start: number, pi: Win32Pointer, c: number, strict: number): number;
  /** icuuc.dll!utrace_format */
  utrace_format(outBuf: string | Win32Pointer, capacity: number, indent: number, fmt: string | Win32Pointer): number;
  /** icuuc.dll!utrace_functionName */
  utrace_functionName(fnNumber: number): number | null;
  /** icuuc.dll!utrace_getFunctions */
  utrace_getFunctions(context: Win32Pointer, e: Win32Pointer, x: Win32Pointer, d: Win32Pointer): void;
  /** icuuc.dll!utrace_getLevel */
  utrace_getLevel(): number;
  /** icuuc.dll!utrace_setFunctions */
  utrace_setFunctions(context: Win32Pointer, e: Win32Callback, x: Win32Callback, d: Win32Callback): void;
  /** icuuc.dll!utrace_setLevel */
  utrace_setLevel(traceLevel: number): void;
  /** icuuc.dll!utrace_vformat */
  utrace_vformat(outBuf: string | Win32Pointer, capacity: number, indent: number, fmt: string | Win32Pointer, args: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
