// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** mdmlocalmanagement.dll!ApplyLocalManagementSyncML */
  ApplyLocalManagementSyncML(syncMLRequest: string | Win32Pointer, syncMLResult: Win32Pointer): number;
  /** mdmlocalmanagement.dll!RegisterDeviceWithLocalManagement */
  RegisterDeviceWithLocalManagement(alreadyRegistered: Win32Pointer): number;
  /** mdmlocalmanagement.dll!UnregisterDeviceWithLocalManagement */
  UnregisterDeviceWithLocalManagement(): number;
}

declare const family: Win32Family & Functions;
export = family;
