// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** opengl32.dll!glAccum */
  glAccum(op: number, value: number): void;
  /** opengl32.dll!glAlphaFunc */
  glAlphaFunc(func: number, ref: number): void;
  /** opengl32.dll!glAreTexturesResident */
  glAreTexturesResident(n: number, textures: Win32Pointer, residences: Win32Pointer): number;
  /** opengl32.dll!glArrayElement */
  glArrayElement(i: number): void;
  /** opengl32.dll!glBegin */
  glBegin(mode: number): void;
  /** opengl32.dll!glBindTexture */
  glBindTexture(target: number, texture: number): void;
  /** opengl32.dll!glBitmap */
  glBitmap(width: number, height: number, xorig: number, yorig: number, xmove: number, ymove: number, bitmap: Win32Pointer): void;
  /** opengl32.dll!glBlendFunc */
  glBlendFunc(sfactor: number, dfactor: number): void;
  /** opengl32.dll!glCallList */
  glCallList(list: number): void;
  /** opengl32.dll!glCallLists */
  glCallLists(n: number, type: number, lists: Win32Pointer): void;
  /** opengl32.dll!glClear */
  glClear(mask: number): void;
  /** opengl32.dll!glClearAccum */
  glClearAccum(red: number, green: number, blue: number, alpha: number): void;
  /** opengl32.dll!glClearColor */
  glClearColor(red: number, green: number, blue: number, alpha: number): void;
  /** opengl32.dll!glClearDepth */
  glClearDepth(depth: number): void;
  /** opengl32.dll!glClearIndex */
  glClearIndex(c: number): void;
  /** opengl32.dll!glClearStencil */
  glClearStencil(s: number): void;
  /** opengl32.dll!glClipPlane */
  glClipPlane(plane: number, equation: Win32Pointer): void;
  /** opengl32.dll!glColor3b */
  glColor3b(red: number, green: number, blue: number): void;
  /** opengl32.dll!glColor3bv */
  glColor3bv(v: Win32Pointer): void;
  /** opengl32.dll!glColor3d */
  glColor3d(red: number, green: number, blue: number): void;
  /** opengl32.dll!glColor3dv */
  glColor3dv(v: Win32Pointer): void;
  /** opengl32.dll!glColor3f */
  glColor3f(red: number, green: number, blue: number): void;
  /** opengl32.dll!glColor3fv */
  glColor3fv(v: Win32Pointer): void;
  /** opengl32.dll!glColor3i */
  glColor3i(red: number, green: number, blue: number): void;
  /** opengl32.dll!glColor3iv */
  glColor3iv(v: Win32Pointer): void;
  /** opengl32.dll!glColor3s */
  glColor3s(red: number, green: number, blue: number): void;
  /** opengl32.dll!glColor3sv */
  glColor3sv(v: Win32Pointer): void;
  /** opengl32.dll!glColor3ub */
  glColor3ub(red: number, green: number, blue: number): void;
  /** opengl32.dll!glColor3ubv */
  glColor3ubv(v: Win32Pointer): void;
  /** opengl32.dll!glColor3ui */
  glColor3ui(red: number, green: number, blue: number): void;
  /** opengl32.dll!glColor3uiv */
  glColor3uiv(v: Win32Pointer): void;
  /** opengl32.dll!glColor3us */
  glColor3us(red: number, green: number, blue: number): void;
  /** opengl32.dll!glColor3usv */
  glColor3usv(v: Win32Pointer): void;
  /** opengl32.dll!glColor4b */
  glColor4b(red: number, green: number, blue: number, alpha: number): void;
  /** opengl32.dll!glColor4bv */
  glColor4bv(v: Win32Pointer): void;
  /** opengl32.dll!glColor4d */
  glColor4d(red: number, green: number, blue: number, alpha: number): void;
  /** opengl32.dll!glColor4dv */
  glColor4dv(v: Win32Pointer): void;
  /** opengl32.dll!glColor4f */
  glColor4f(red: number, green: number, blue: number, alpha: number): void;
  /** opengl32.dll!glColor4fv */
  glColor4fv(v: Win32Pointer): void;
  /** opengl32.dll!glColor4i */
  glColor4i(red: number, green: number, blue: number, alpha: number): void;
  /** opengl32.dll!glColor4iv */
  glColor4iv(v: Win32Pointer): void;
  /** opengl32.dll!glColor4s */
  glColor4s(red: number, green: number, blue: number, alpha: number): void;
  /** opengl32.dll!glColor4sv */
  glColor4sv(v: Win32Pointer): void;
  /** opengl32.dll!glColor4ub */
  glColor4ub(red: number, green: number, blue: number, alpha: number): void;
  /** opengl32.dll!glColor4ubv */
  glColor4ubv(v: Win32Pointer): void;
  /** opengl32.dll!glColor4ui */
  glColor4ui(red: number, green: number, blue: number, alpha: number): void;
  /** opengl32.dll!glColor4uiv */
  glColor4uiv(v: Win32Pointer): void;
  /** opengl32.dll!glColor4us */
  glColor4us(red: number, green: number, blue: number, alpha: number): void;
  /** opengl32.dll!glColor4usv */
  glColor4usv(v: Win32Pointer): void;
  /** opengl32.dll!glColorMask */
  glColorMask(red: number, green: number, blue: number, alpha: number): void;
  /** opengl32.dll!glColorMaterial */
  glColorMaterial(face: number, mode: number): void;
  /** opengl32.dll!glColorPointer */
  glColorPointer(size: number, type: number, stride: number, pointer: Win32Pointer): void;
  /** opengl32.dll!glCopyPixels */
  glCopyPixels(x: number, y: number, width: number, height: number, type: number): void;
  /** opengl32.dll!glCopyTexImage1D */
  glCopyTexImage1D(target: number, level: number, internalFormat: number, x: number, y: number, width: number, border: number): void;
  /** opengl32.dll!glCopyTexImage2D */
  glCopyTexImage2D(target: number, level: number, internalFormat: number, x: number, y: number, width: number, height: number, border: number): void;
  /** opengl32.dll!glCopyTexSubImage1D */
  glCopyTexSubImage1D(target: number, level: number, xoffset: number, x: number, y: number, width: number): void;
  /** opengl32.dll!glCopyTexSubImage2D */
  glCopyTexSubImage2D(target: number, level: number, xoffset: number, yoffset: number, x: number, y: number, width: number, height: number): void;
  /** opengl32.dll!glCullFace */
  glCullFace(mode: number): void;
  /** opengl32.dll!glDeleteLists */
  glDeleteLists(list: number, range: number): void;
  /** opengl32.dll!glDeleteTextures */
  glDeleteTextures(n: number, textures: Win32Pointer): void;
  /** opengl32.dll!glDepthFunc */
  glDepthFunc(func: number): void;
  /** opengl32.dll!glDepthMask */
  glDepthMask(flag: number): void;
  /** opengl32.dll!glDepthRange */
  glDepthRange(zNear: number, zFar: number): void;
  /** opengl32.dll!glDisable */
  glDisable(cap: number): void;
  /** opengl32.dll!glDisableClientState */
  glDisableClientState(array: number): void;
  /** opengl32.dll!glDrawArrays */
  glDrawArrays(mode: number, first: number, count: number): void;
  /** opengl32.dll!glDrawBuffer */
  glDrawBuffer(mode: number): void;
  /** opengl32.dll!glDrawElements */
  glDrawElements(mode: number, count: number, type: number, indices: Win32Pointer): void;
  /** opengl32.dll!glDrawPixels */
  glDrawPixels(width: number, height: number, format: number, type: number, pixels: Win32Pointer): void;
  /** opengl32.dll!glEdgeFlag */
  glEdgeFlag(flag: number): void;
  /** opengl32.dll!glEdgeFlagPointer */
  glEdgeFlagPointer(stride: number, pointer: Win32Pointer): void;
  /** opengl32.dll!glEdgeFlagv */
  glEdgeFlagv(flag: Win32Pointer): void;
  /** opengl32.dll!glEnable */
  glEnable(cap: number): void;
  /** opengl32.dll!glEnableClientState */
  glEnableClientState(array: number): void;
  /** opengl32.dll!glEnd */
  glEnd(): void;
  /** opengl32.dll!glEndList */
  glEndList(): void;
  /** opengl32.dll!glEvalCoord1d */
  glEvalCoord1d(u: number): void;
  /** opengl32.dll!glEvalCoord1dv */
  glEvalCoord1dv(u: Win32Pointer): void;
  /** opengl32.dll!glEvalCoord1f */
  glEvalCoord1f(u: number): void;
  /** opengl32.dll!glEvalCoord1fv */
  glEvalCoord1fv(u: Win32Pointer): void;
  /** opengl32.dll!glEvalCoord2d */
  glEvalCoord2d(u: number, v: number): void;
  /** opengl32.dll!glEvalCoord2dv */
  glEvalCoord2dv(u: Win32Pointer): void;
  /** opengl32.dll!glEvalCoord2f */
  glEvalCoord2f(u: number, v: number): void;
  /** opengl32.dll!glEvalCoord2fv */
  glEvalCoord2fv(u: Win32Pointer): void;
  /** opengl32.dll!glEvalMesh1 */
  glEvalMesh1(mode: number, i1: number, i2: number): void;
  /** opengl32.dll!glEvalMesh2 */
  glEvalMesh2(mode: number, i1: number, i2: number, j1: number, j2: number): void;
  /** opengl32.dll!glEvalPoint1 */
  glEvalPoint1(i: number): void;
  /** opengl32.dll!glEvalPoint2 */
  glEvalPoint2(i: number, j: number): void;
  /** opengl32.dll!glFeedbackBuffer */
  glFeedbackBuffer(size: number, type: number, buffer: Win32Pointer): void;
  /** opengl32.dll!glFinish */
  glFinish(): void;
  /** opengl32.dll!glFlush */
  glFlush(): void;
  /** opengl32.dll!glFogf */
  glFogf(pname: number, param1: number): void;
  /** opengl32.dll!glFogfv */
  glFogfv(pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glFogi */
  glFogi(pname: number, param1: number): void;
  /** opengl32.dll!glFogiv */
  glFogiv(pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glFrontFace */
  glFrontFace(mode: number): void;
  /** opengl32.dll!glFrustum */
  glFrustum(left: number, right: number, bottom: number, top: number, zNear: number, zFar: number): void;
  /** opengl32.dll!glGenLists */
  glGenLists(range: number): number;
  /** opengl32.dll!glGenTextures */
  glGenTextures(n: number, textures: Win32Pointer): void;
  /** opengl32.dll!glGetBooleanv */
  glGetBooleanv(pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glGetClipPlane */
  glGetClipPlane(plane: number, equation: Win32Pointer): void;
  /** opengl32.dll!glGetDoublev */
  glGetDoublev(pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glGetError */
  glGetError(): number;
  /** opengl32.dll!glGetFloatv */
  glGetFloatv(pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glGetIntegerv */
  glGetIntegerv(pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glGetLightfv */
  glGetLightfv(light: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glGetLightiv */
  glGetLightiv(light: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glGetMapdv */
  glGetMapdv(target: number, query: number, v: Win32Pointer): void;
  /** opengl32.dll!glGetMapfv */
  glGetMapfv(target: number, query: number, v: Win32Pointer): void;
  /** opengl32.dll!glGetMapiv */
  glGetMapiv(target: number, query: number, v: Win32Pointer): void;
  /** opengl32.dll!glGetMaterialfv */
  glGetMaterialfv(face: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glGetMaterialiv */
  glGetMaterialiv(face: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glGetPixelMapfv */
  glGetPixelMapfv(map: number, values: Win32Pointer): void;
  /** opengl32.dll!glGetPixelMapuiv */
  glGetPixelMapuiv(map: number, values: Win32Pointer): void;
  /** opengl32.dll!glGetPixelMapusv */
  glGetPixelMapusv(map: number, values: Win32Pointer): void;
  /** opengl32.dll!glGetPointerv */
  glGetPointerv(pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glGetPolygonStipple */
  glGetPolygonStipple(mask: Win32Pointer): void;
  /** opengl32.dll!glGetString */
  glGetString(name: number): number | null;
  /** opengl32.dll!glGetTexEnvfv */
  glGetTexEnvfv(target: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glGetTexEnviv */
  glGetTexEnviv(target: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glGetTexGendv */
  glGetTexGendv(coord: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glGetTexGenfv */
  glGetTexGenfv(coord: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glGetTexGeniv */
  glGetTexGeniv(coord: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glGetTexImage */
  glGetTexImage(target: number, level: number, format: number, type: number, pixels: Win32Pointer): void;
  /** opengl32.dll!glGetTexLevelParameterfv */
  glGetTexLevelParameterfv(target: number, level: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glGetTexLevelParameteriv */
  glGetTexLevelParameteriv(target: number, level: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glGetTexParameterfv */
  glGetTexParameterfv(target: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glGetTexParameteriv */
  glGetTexParameteriv(target: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glHint */
  glHint(target: number, mode: number): void;
  /** opengl32.dll!glIndexMask */
  glIndexMask(mask: number): void;
  /** opengl32.dll!glIndexPointer */
  glIndexPointer(type: number, stride: number, pointer: Win32Pointer): void;
  /** opengl32.dll!glIndexd */
  glIndexd(c: number): void;
  /** opengl32.dll!glIndexdv */
  glIndexdv(c: Win32Pointer): void;
  /** opengl32.dll!glIndexf */
  glIndexf(c: number): void;
  /** opengl32.dll!glIndexfv */
  glIndexfv(c: Win32Pointer): void;
  /** opengl32.dll!glIndexi */
  glIndexi(c: number): void;
  /** opengl32.dll!glIndexiv */
  glIndexiv(c: Win32Pointer): void;
  /** opengl32.dll!glIndexs */
  glIndexs(c: number): void;
  /** opengl32.dll!glIndexsv */
  glIndexsv(c: Win32Pointer): void;
  /** opengl32.dll!glIndexub */
  glIndexub(c: number): void;
  /** opengl32.dll!glIndexubv */
  glIndexubv(c: Win32Pointer): void;
  /** opengl32.dll!glInitNames */
  glInitNames(): void;
  /** opengl32.dll!glInterleavedArrays */
  glInterleavedArrays(format: number, stride: number, pointer: Win32Pointer): void;
  /** opengl32.dll!glIsEnabled */
  glIsEnabled(cap: number): number;
  /** opengl32.dll!glIsList */
  glIsList(list: number): number;
  /** opengl32.dll!glIsTexture */
  glIsTexture(texture: number): number;
  /** opengl32.dll!glLightModelf */
  glLightModelf(pname: number, param1: number): void;
  /** opengl32.dll!glLightModelfv */
  glLightModelfv(pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glLightModeli */
  glLightModeli(pname: number, param1: number): void;
  /** opengl32.dll!glLightModeliv */
  glLightModeliv(pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glLightf */
  glLightf(light: number, pname: number, param2: number): void;
  /** opengl32.dll!glLightfv */
  glLightfv(light: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glLighti */
  glLighti(light: number, pname: number, param2: number): void;
  /** opengl32.dll!glLightiv */
  glLightiv(light: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glLineStipple */
  glLineStipple(factor: number, pattern: number): void;
  /** opengl32.dll!glLineWidth */
  glLineWidth(width: number): void;
  /** opengl32.dll!glListBase */
  glListBase(base: number): void;
  /** opengl32.dll!glLoadIdentity */
  glLoadIdentity(): void;
  /** opengl32.dll!glLoadMatrixd */
  glLoadMatrixd(m: Win32Pointer): void;
  /** opengl32.dll!glLoadMatrixf */
  glLoadMatrixf(m: Win32Pointer): void;
  /** opengl32.dll!glLoadName */
  glLoadName(name: number): void;
  /** opengl32.dll!glLogicOp */
  glLogicOp(opcode: number): void;
  /** opengl32.dll!glMap1d */
  glMap1d(target: number, u1: number, u2: number, stride: number, order: number, points: Win32Pointer): void;
  /** opengl32.dll!glMap1f */
  glMap1f(target: number, u1: number, u2: number, stride: number, order: number, points: Win32Pointer): void;
  /** opengl32.dll!glMap2d */
  glMap2d(target: number, u1: number, u2: number, ustride: number, uorder: number, v1: number, v2: number, vstride: number, vorder: number, points: Win32Pointer): void;
  /** opengl32.dll!glMap2f */
  glMap2f(target: number, u1: number, u2: number, ustride: number, uorder: number, v1: number, v2: number, vstride: number, vorder: number, points: Win32Pointer): void;
  /** opengl32.dll!glMapGrid1d */
  glMapGrid1d(un: number, u1: number, u2: number): void;
  /** opengl32.dll!glMapGrid1f */
  glMapGrid1f(un: number, u1: number, u2: number): void;
  /** opengl32.dll!glMapGrid2d */
  glMapGrid2d(un: number, u1: number, u2: number, vn: number, v1: number, v2: number): void;
  /** opengl32.dll!glMapGrid2f */
  glMapGrid2f(un: number, u1: number, u2: number, vn: number, v1: number, v2: number): void;
  /** opengl32.dll!glMaterialf */
  glMaterialf(face: number, pname: number, param2: number): void;
  /** opengl32.dll!glMaterialfv */
  glMaterialfv(face: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glMateriali */
  glMateriali(face: number, pname: number, param2: number): void;
  /** opengl32.dll!glMaterialiv */
  glMaterialiv(face: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glMatrixMode */
  glMatrixMode(mode: number): void;
  /** opengl32.dll!glMultMatrixd */
  glMultMatrixd(m: Win32Pointer): void;
  /** opengl32.dll!glMultMatrixf */
  glMultMatrixf(m: Win32Pointer): void;
  /** opengl32.dll!glNewList */
  glNewList(list: number, mode: number): void;
  /** opengl32.dll!glNormal3b */
  glNormal3b(nx: number, ny: number, nz: number): void;
  /** opengl32.dll!glNormal3bv */
  glNormal3bv(v: Win32Pointer): void;
  /** opengl32.dll!glNormal3d */
  glNormal3d(nx: number, ny: number, nz: number): void;
  /** opengl32.dll!glNormal3dv */
  glNormal3dv(v: Win32Pointer): void;
  /** opengl32.dll!glNormal3f */
  glNormal3f(nx: number, ny: number, nz: number): void;
  /** opengl32.dll!glNormal3fv */
  glNormal3fv(v: Win32Pointer): void;
  /** opengl32.dll!glNormal3i */
  glNormal3i(nx: number, ny: number, nz: number): void;
  /** opengl32.dll!glNormal3iv */
  glNormal3iv(v: Win32Pointer): void;
  /** opengl32.dll!glNormal3s */
  glNormal3s(nx: number, ny: number, nz: number): void;
  /** opengl32.dll!glNormal3sv */
  glNormal3sv(v: Win32Pointer): void;
  /** opengl32.dll!glNormalPointer */
  glNormalPointer(type: number, stride: number, pointer: Win32Pointer): void;
  /** opengl32.dll!glOrtho */
  glOrtho(left: number, right: number, bottom: number, top: number, zNear: number, zFar: number): void;
  /** opengl32.dll!glPassThrough */
  glPassThrough(token: number): void;
  /** opengl32.dll!glPixelMapfv */
  glPixelMapfv(map: number, mapsize: number, values: Win32Pointer): void;
  /** opengl32.dll!glPixelMapuiv */
  glPixelMapuiv(map: number, mapsize: number, values: Win32Pointer): void;
  /** opengl32.dll!glPixelMapusv */
  glPixelMapusv(map: number, mapsize: number, values: Win32Pointer): void;
  /** opengl32.dll!glPixelStoref */
  glPixelStoref(pname: number, param1: number): void;
  /** opengl32.dll!glPixelStorei */
  glPixelStorei(pname: number, param1: number): void;
  /** opengl32.dll!glPixelTransferf */
  glPixelTransferf(pname: number, param1: number): void;
  /** opengl32.dll!glPixelTransferi */
  glPixelTransferi(pname: number, param1: number): void;
  /** opengl32.dll!glPixelZoom */
  glPixelZoom(xfactor: number, yfactor: number): void;
  /** opengl32.dll!glPointSize */
  glPointSize(size: number): void;
  /** opengl32.dll!glPolygonMode */
  glPolygonMode(face: number, mode: number): void;
  /** opengl32.dll!glPolygonOffset */
  glPolygonOffset(factor: number, units: number): void;
  /** opengl32.dll!glPolygonStipple */
  glPolygonStipple(mask: Win32Pointer): void;
  /** opengl32.dll!glPopAttrib */
  glPopAttrib(): void;
  /** opengl32.dll!glPopClientAttrib */
  glPopClientAttrib(): void;
  /** opengl32.dll!glPopMatrix */
  glPopMatrix(): void;
  /** opengl32.dll!glPopName */
  glPopName(): void;
  /** opengl32.dll!glPrioritizeTextures */
  glPrioritizeTextures(n: number, textures: Win32Pointer, priorities: Win32Pointer): void;
  /** opengl32.dll!glPushAttrib */
  glPushAttrib(mask: number): void;
  /** opengl32.dll!glPushClientAttrib */
  glPushClientAttrib(mask: number): void;
  /** opengl32.dll!glPushMatrix */
  glPushMatrix(): void;
  /** opengl32.dll!glPushName */
  glPushName(name: number): void;
  /** opengl32.dll!glRasterPos2d */
  glRasterPos2d(x: number, y: number): void;
  /** opengl32.dll!glRasterPos2dv */
  glRasterPos2dv(v: Win32Pointer): void;
  /** opengl32.dll!glRasterPos2f */
  glRasterPos2f(x: number, y: number): void;
  /** opengl32.dll!glRasterPos2fv */
  glRasterPos2fv(v: Win32Pointer): void;
  /** opengl32.dll!glRasterPos2i */
  glRasterPos2i(x: number, y: number): void;
  /** opengl32.dll!glRasterPos2iv */
  glRasterPos2iv(v: Win32Pointer): void;
  /** opengl32.dll!glRasterPos2s */
  glRasterPos2s(x: number, y: number): void;
  /** opengl32.dll!glRasterPos2sv */
  glRasterPos2sv(v: Win32Pointer): void;
  /** opengl32.dll!glRasterPos3d */
  glRasterPos3d(x: number, y: number, z: number): void;
  /** opengl32.dll!glRasterPos3dv */
  glRasterPos3dv(v: Win32Pointer): void;
  /** opengl32.dll!glRasterPos3f */
  glRasterPos3f(x: number, y: number, z: number): void;
  /** opengl32.dll!glRasterPos3fv */
  glRasterPos3fv(v: Win32Pointer): void;
  /** opengl32.dll!glRasterPos3i */
  glRasterPos3i(x: number, y: number, z: number): void;
  /** opengl32.dll!glRasterPos3iv */
  glRasterPos3iv(v: Win32Pointer): void;
  /** opengl32.dll!glRasterPos3s */
  glRasterPos3s(x: number, y: number, z: number): void;
  /** opengl32.dll!glRasterPos3sv */
  glRasterPos3sv(v: Win32Pointer): void;
  /** opengl32.dll!glRasterPos4d */
  glRasterPos4d(x: number, y: number, z: number, w: number): void;
  /** opengl32.dll!glRasterPos4dv */
  glRasterPos4dv(v: Win32Pointer): void;
  /** opengl32.dll!glRasterPos4f */
  glRasterPos4f(x: number, y: number, z: number, w: number): void;
  /** opengl32.dll!glRasterPos4fv */
  glRasterPos4fv(v: Win32Pointer): void;
  /** opengl32.dll!glRasterPos4i */
  glRasterPos4i(x: number, y: number, z: number, w: number): void;
  /** opengl32.dll!glRasterPos4iv */
  glRasterPos4iv(v: Win32Pointer): void;
  /** opengl32.dll!glRasterPos4s */
  glRasterPos4s(x: number, y: number, z: number, w: number): void;
  /** opengl32.dll!glRasterPos4sv */
  glRasterPos4sv(v: Win32Pointer): void;
  /** opengl32.dll!glReadBuffer */
  glReadBuffer(mode: number): void;
  /** opengl32.dll!glReadPixels */
  glReadPixels(x: number, y: number, width: number, height: number, format: number, type: number, pixels: Win32Pointer): void;
  /** opengl32.dll!glRectd */
  glRectd(x1: number, y1: number, x2: number, y2: number): void;
  /** opengl32.dll!glRectdv */
  glRectdv(v1: Win32Pointer, v2: Win32Pointer): void;
  /** opengl32.dll!glRectf */
  glRectf(x1: number, y1: number, x2: number, y2: number): void;
  /** opengl32.dll!glRectfv */
  glRectfv(v1: Win32Pointer, v2: Win32Pointer): void;
  /** opengl32.dll!glRecti */
  glRecti(x1: number, y1: number, x2: number, y2: number): void;
  /** opengl32.dll!glRectiv */
  glRectiv(v1: Win32Pointer, v2: Win32Pointer): void;
  /** opengl32.dll!glRects */
  glRects(x1: number, y1: number, x2: number, y2: number): void;
  /** opengl32.dll!glRectsv */
  glRectsv(v1: Win32Pointer, v2: Win32Pointer): void;
  /** opengl32.dll!glRenderMode */
  glRenderMode(mode: number): number;
  /** opengl32.dll!glRotated */
  glRotated(angle: number, x: number, y: number, z: number): void;
  /** opengl32.dll!glRotatef */
  glRotatef(angle: number, x: number, y: number, z: number): void;
  /** opengl32.dll!glScaled */
  glScaled(x: number, y: number, z: number): void;
  /** opengl32.dll!glScalef */
  glScalef(x: number, y: number, z: number): void;
  /** opengl32.dll!glScissor */
  glScissor(x: number, y: number, width: number, height: number): void;
  /** opengl32.dll!glSelectBuffer */
  glSelectBuffer(size: number, buffer: Win32Pointer): void;
  /** opengl32.dll!glShadeModel */
  glShadeModel(mode: number): void;
  /** opengl32.dll!glStencilFunc */
  glStencilFunc(func: number, ref: number, mask: number): void;
  /** opengl32.dll!glStencilMask */
  glStencilMask(mask: number): void;
  /** opengl32.dll!glStencilOp */
  glStencilOp(fail: number, zfail: number, zpass: number): void;
  /** opengl32.dll!glTexCoord1d */
  glTexCoord1d(s: number): void;
  /** opengl32.dll!glTexCoord1dv */
  glTexCoord1dv(v: Win32Pointer): void;
  /** opengl32.dll!glTexCoord1f */
  glTexCoord1f(s: number): void;
  /** opengl32.dll!glTexCoord1fv */
  glTexCoord1fv(v: Win32Pointer): void;
  /** opengl32.dll!glTexCoord1i */
  glTexCoord1i(s: number): void;
  /** opengl32.dll!glTexCoord1iv */
  glTexCoord1iv(v: Win32Pointer): void;
  /** opengl32.dll!glTexCoord1s */
  glTexCoord1s(s: number): void;
  /** opengl32.dll!glTexCoord1sv */
  glTexCoord1sv(v: Win32Pointer): void;
  /** opengl32.dll!glTexCoord2d */
  glTexCoord2d(s: number, t: number): void;
  /** opengl32.dll!glTexCoord2dv */
  glTexCoord2dv(v: Win32Pointer): void;
  /** opengl32.dll!glTexCoord2f */
  glTexCoord2f(s: number, t: number): void;
  /** opengl32.dll!glTexCoord2fv */
  glTexCoord2fv(v: Win32Pointer): void;
  /** opengl32.dll!glTexCoord2i */
  glTexCoord2i(s: number, t: number): void;
  /** opengl32.dll!glTexCoord2iv */
  glTexCoord2iv(v: Win32Pointer): void;
  /** opengl32.dll!glTexCoord2s */
  glTexCoord2s(s: number, t: number): void;
  /** opengl32.dll!glTexCoord2sv */
  glTexCoord2sv(v: Win32Pointer): void;
  /** opengl32.dll!glTexCoord3d */
  glTexCoord3d(s: number, t: number, r: number): void;
  /** opengl32.dll!glTexCoord3dv */
  glTexCoord3dv(v: Win32Pointer): void;
  /** opengl32.dll!glTexCoord3f */
  glTexCoord3f(s: number, t: number, r: number): void;
  /** opengl32.dll!glTexCoord3fv */
  glTexCoord3fv(v: Win32Pointer): void;
  /** opengl32.dll!glTexCoord3i */
  glTexCoord3i(s: number, t: number, r: number): void;
  /** opengl32.dll!glTexCoord3iv */
  glTexCoord3iv(v: Win32Pointer): void;
  /** opengl32.dll!glTexCoord3s */
  glTexCoord3s(s: number, t: number, r: number): void;
  /** opengl32.dll!glTexCoord3sv */
  glTexCoord3sv(v: Win32Pointer): void;
  /** opengl32.dll!glTexCoord4d */
  glTexCoord4d(s: number, t: number, r: number, q: number): void;
  /** opengl32.dll!glTexCoord4dv */
  glTexCoord4dv(v: Win32Pointer): void;
  /** opengl32.dll!glTexCoord4f */
  glTexCoord4f(s: number, t: number, r: number, q: number): void;
  /** opengl32.dll!glTexCoord4fv */
  glTexCoord4fv(v: Win32Pointer): void;
  /** opengl32.dll!glTexCoord4i */
  glTexCoord4i(s: number, t: number, r: number, q: number): void;
  /** opengl32.dll!glTexCoord4iv */
  glTexCoord4iv(v: Win32Pointer): void;
  /** opengl32.dll!glTexCoord4s */
  glTexCoord4s(s: number, t: number, r: number, q: number): void;
  /** opengl32.dll!glTexCoord4sv */
  glTexCoord4sv(v: Win32Pointer): void;
  /** opengl32.dll!glTexCoordPointer */
  glTexCoordPointer(size: number, type: number, stride: number, pointer: Win32Pointer): void;
  /** opengl32.dll!glTexEnvf */
  glTexEnvf(target: number, pname: number, param2: number): void;
  /** opengl32.dll!glTexEnvfv */
  glTexEnvfv(target: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glTexEnvi */
  glTexEnvi(target: number, pname: number, param2: number): void;
  /** opengl32.dll!glTexEnviv */
  glTexEnviv(target: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glTexGend */
  glTexGend(coord: number, pname: number, param2: number): void;
  /** opengl32.dll!glTexGendv */
  glTexGendv(coord: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glTexGenf */
  glTexGenf(coord: number, pname: number, param2: number): void;
  /** opengl32.dll!glTexGenfv */
  glTexGenfv(coord: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glTexGeni */
  glTexGeni(coord: number, pname: number, param2: number): void;
  /** opengl32.dll!glTexGeniv */
  glTexGeniv(coord: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glTexImage1D */
  glTexImage1D(target: number, level: number, internalformat: number, width: number, border: number, format: number, type: number, pixels: Win32Pointer): void;
  /** opengl32.dll!glTexImage2D */
  glTexImage2D(target: number, level: number, internalformat: number, width: number, height: number, border: number, format: number, type: number, pixels: Win32Pointer): void;
  /** opengl32.dll!glTexParameterf */
  glTexParameterf(target: number, pname: number, param2: number): void;
  /** opengl32.dll!glTexParameterfv */
  glTexParameterfv(target: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glTexParameteri */
  glTexParameteri(target: number, pname: number, param2: number): void;
  /** opengl32.dll!glTexParameteriv */
  glTexParameteriv(target: number, pname: number, params: Win32Pointer): void;
  /** opengl32.dll!glTexSubImage1D */
  glTexSubImage1D(target: number, level: number, xoffset: number, width: number, format: number, type: number, pixels: Win32Pointer): void;
  /** opengl32.dll!glTexSubImage2D */
  glTexSubImage2D(target: number, level: number, xoffset: number, yoffset: number, width: number, height: number, format: number, type: number, pixels: Win32Pointer): void;
  /** opengl32.dll!glTranslated */
  glTranslated(x: number, y: number, z: number): void;
  /** opengl32.dll!glTranslatef */
  glTranslatef(x: number, y: number, z: number): void;
  /** opengl32.dll!glVertex2d */
  glVertex2d(x: number, y: number): void;
  /** opengl32.dll!glVertex2dv */
  glVertex2dv(v: Win32Pointer): void;
  /** opengl32.dll!glVertex2f */
  glVertex2f(x: number, y: number): void;
  /** opengl32.dll!glVertex2fv */
  glVertex2fv(v: Win32Pointer): void;
  /** opengl32.dll!glVertex2i */
  glVertex2i(x: number, y: number): void;
  /** opengl32.dll!glVertex2iv */
  glVertex2iv(v: Win32Pointer): void;
  /** opengl32.dll!glVertex2s */
  glVertex2s(x: number, y: number): void;
  /** opengl32.dll!glVertex2sv */
  glVertex2sv(v: Win32Pointer): void;
  /** opengl32.dll!glVertex3d */
  glVertex3d(x: number, y: number, z: number): void;
  /** opengl32.dll!glVertex3dv */
  glVertex3dv(v: Win32Pointer): void;
  /** opengl32.dll!glVertex3f */
  glVertex3f(x: number, y: number, z: number): void;
  /** opengl32.dll!glVertex3fv */
  glVertex3fv(v: Win32Pointer): void;
  /** opengl32.dll!glVertex3i */
  glVertex3i(x: number, y: number, z: number): void;
  /** opengl32.dll!glVertex3iv */
  glVertex3iv(v: Win32Pointer): void;
  /** opengl32.dll!glVertex3s */
  glVertex3s(x: number, y: number, z: number): void;
  /** opengl32.dll!glVertex3sv */
  glVertex3sv(v: Win32Pointer): void;
  /** opengl32.dll!glVertex4d */
  glVertex4d(x: number, y: number, z: number, w: number): void;
  /** opengl32.dll!glVertex4dv */
  glVertex4dv(v: Win32Pointer): void;
  /** opengl32.dll!glVertex4f */
  glVertex4f(x: number, y: number, z: number, w: number): void;
  /** opengl32.dll!glVertex4fv */
  glVertex4fv(v: Win32Pointer): void;
  /** opengl32.dll!glVertex4i */
  glVertex4i(x: number, y: number, z: number, w: number): void;
  /** opengl32.dll!glVertex4iv */
  glVertex4iv(v: Win32Pointer): void;
  /** opengl32.dll!glVertex4s */
  glVertex4s(x: number, y: number, z: number, w: number): void;
  /** opengl32.dll!glVertex4sv */
  glVertex4sv(v: Win32Pointer): void;
  /** opengl32.dll!glVertexPointer */
  glVertexPointer(size: number, type: number, stride: number, pointer: Win32Pointer): void;
  /** opengl32.dll!glViewport */
  glViewport(x: number, y: number, width: number, height: number): void;
  /** opengl32.dll!wglCopyContext */
  wglCopyContext(param0: Win32Pointer, param1: Win32Pointer, param2: number): number;
  /** opengl32.dll!wglCreateContext */
  wglCreateContext(param0: Win32Pointer): number | null;
  /** opengl32.dll!wglCreateLayerContext */
  wglCreateLayerContext(param0: Win32Pointer, param1: number): number | null;
  /** opengl32.dll!wglDeleteContext */
  wglDeleteContext(param0: Win32Pointer): number;
  /** opengl32.dll!wglDescribeLayerPlane */
  wglDescribeLayerPlane(param0: Win32Pointer, param1: number, param2: number, param3: number, param4: Win32Pointer): number;
  /** opengl32.dll!wglGetCurrentContext */
  wglGetCurrentContext(): number | null;
  /** opengl32.dll!wglGetCurrentDC */
  wglGetCurrentDC(): number | null;
  /** opengl32.dll!wglGetLayerPaletteEntries */
  wglGetLayerPaletteEntries(param0: Win32Pointer, param1: number, param2: number, param3: number, param4: Win32Pointer): number;
  /** opengl32.dll!wglGetProcAddress */
  wglGetProcAddress(param0: string | Win32Pointer): number | null;
  /** opengl32.dll!wglMakeCurrent */
  wglMakeCurrent(param0: Win32Pointer, param1: Win32Pointer): number;
  /** opengl32.dll!wglRealizeLayerPalette */
  wglRealizeLayerPalette(param0: Win32Pointer, param1: number, param2: number): number;
  /** opengl32.dll!wglSetLayerPaletteEntries */
  wglSetLayerPaletteEntries(param0: Win32Pointer, param1: number, param2: number, param3: number, param4: Win32Pointer): number;
  /** opengl32.dll!wglShareLists */
  wglShareLists(param0: Win32Pointer, param1: Win32Pointer): number;
  /** opengl32.dll!wglSwapLayerBuffers */
  wglSwapLayerBuffers(param0: Win32Pointer, param1: number): number;
  /** opengl32.dll!wglSwapMultipleBuffers */
  wglSwapMultipleBuffers(param0: number, param1: Win32Pointer): number;
  /** opengl32.dll!wglUseFontBitmapsA */
  wglUseFontBitmapsA(param0: Win32Pointer, param1: number, param2: number, param3: number): number;
  /** opengl32.dll!wglUseFontBitmapsW */
  wglUseFontBitmapsW(param0: Win32Pointer, param1: number, param2: number, param3: number): number;
  /** opengl32.dll!wglUseFontBitmapsW */
  wglUseFontBitmaps(param0: Win32Pointer, param1: number, param2: number, param3: number): number;
  /** opengl32.dll!wglUseFontOutlinesA */
  wglUseFontOutlinesA(param0: Win32Pointer, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: Win32Pointer): number;
  /** opengl32.dll!wglUseFontOutlinesW */
  wglUseFontOutlinesW(param0: Win32Pointer, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: Win32Pointer): number;
  /** opengl32.dll!wglUseFontOutlinesW */
  wglUseFontOutlines(param0: Win32Pointer, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number, param7: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
