// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** spoolss.dll!AddPrintDeviceObject */
  AddPrintDeviceObject(hPrinter: Win32StructInit, phDeviceObject: Win32Pointer): number;
  /** spoolss.dll!AppendPrinterNotifyInfoData */
  AppendPrinterNotifyInfoData(pInfoDest: Win32Pointer, pDataSrc: Win32Pointer, fdwFlags: number): number;
  /** spoolss.dll!CallRouterFindFirstPrinterChangeNotification */
  CallRouterFindFirstPrinterChangeNotification(hPrinterRPC: Win32Pointer, fdwFilterFlags: number, fdwOptions: number, hNotify: Win32Pointer, pPrinterNotifyOptions: Win32Pointer): number;
  /** spoolss.dll!GetJobAttributes */
  GetJobAttributes(pPrinterName: string | Win32Pointer, pDevmode: Win32Pointer, pAttributeInfo: Win32Pointer): number;
  /** spoolss.dll!GetJobAttributesEx */
  GetJobAttributesEx(pPrinterName: string | Win32Pointer, pDevmode: Win32Pointer, dwLevel: number, pAttributeInfo: Win32Pointer, nSize: number, dwFlags: number): number;
  /** spoolss.dll!ImpersonatePrinterClient */
  ImpersonatePrinterClient(hToken: Win32Pointer): number;
  /** spoolss.dll!PartialReplyPrinterChangeNotification */
  PartialReplyPrinterChangeNotification(hPrinter: Win32StructInit, pDataSrc: Win32Pointer): number;
  /** spoolss.dll!ProvidorFindClosePrinterChangeNotification */
  ProvidorFindClosePrinterChangeNotification(hPrinter: Win32StructInit): number;
  /** spoolss.dll!ProvidorFindFirstPrinterChangeNotification */
  ProvidorFindFirstPrinterChangeNotification(hPrinter: Win32StructInit, fdwFlags: number, fdwOptions: number, hNotify: Win32Pointer, pPrinterNotifyOptions: Win32Pointer, pvReserved1: Win32Pointer): number;
  /** spoolss.dll!RemovePrintDeviceObject */
  RemovePrintDeviceObject(hDeviceObject: Win32Pointer): number;
  /** spoolss.dll!ReplyPrinterChangeNotification */
  ReplyPrinterChangeNotification(hPrinter: Win32StructInit, fdwChangeFlags: number, pdwResult: Win32Pointer, pPrinterNotifyInfo: Win32Pointer): number;
  /** spoolss.dll!ReplyPrinterChangeNotificationEx */
  ReplyPrinterChangeNotificationEx(hNotify: Win32Pointer, dwColor: number, fdwFlags: number, pdwResult: Win32Pointer, pPrinterNotifyInfo: Win32Pointer): number;
  /** spoolss.dll!RevertToPrinterSelf */
  RevertToPrinterSelf(): number | null;
  /** spoolss.dll!RouterAllocBidiMem */
  RouterAllocBidiMem(NumBytes: number | bigint): number | null;
  /** spoolss.dll!RouterAllocBidiResponseContainer */
  RouterAllocBidiResponseContainer(Count: number): number | null;
  /** spoolss.dll!RouterAllocPrinterNotifyInfo */
  RouterAllocPrinterNotifyInfo(cPrinterNotifyInfoData: number): number | null;
  /** spoolss.dll!RouterCreatePrintAsyncNotificationChannel */
  RouterCreatePrintAsyncNotificationChannel(pName: string | Win32Pointer, pNotificationType: Win32Pointer, eNotifyFilter: number, eConversationStyle: number, pCallback: Win32Pointer, ppIAsynchNotification: Win32Pointer): number;
  /** spoolss.dll!RouterFreeBidiMem */
  RouterFreeBidiMem(pMemPointer: Win32Pointer): void;
  /** spoolss.dll!RouterFreePrinterNotifyInfo */
  RouterFreePrinterNotifyInfo(pInfo: Win32Pointer): number;
  /** spoolss.dll!RouterGetPrintClassObject */
  RouterGetPrintClassObject(pPrinter: string | Win32Pointer, riid: Win32Pointer, ppv: Win32Pointer): number;
  /** spoolss.dll!RouterUnregisterForPrintAsyncNotifications */
  RouterUnregisterForPrintAsyncNotifications(hNotify: Win32Pointer): number;
  /** spoolss.dll!SplIsSessionZero */
  SplIsSessionZero(hPrinter: Win32StructInit, JobId: number, pIsSessionZero: Win32Pointer): number;
  /** spoolss.dll!SplPromptUIInUsersSession */
  SplPromptUIInUsersSession(hPrinter: Win32StructInit, JobId: number, pUIParams: Win32Pointer, pResponse: Win32Pointer): number;
  /** spoolss.dll!SpoolerFindClosePrinterChangeNotification */
  SpoolerFindClosePrinterChangeNotification(hPrinter: Win32StructInit): number;
  /** spoolss.dll!SpoolerFindFirstPrinterChangeNotification */
  SpoolerFindFirstPrinterChangeNotification(hPrinter: Win32StructInit, fdwFilterFlags: number, fdwOptions: number, pPrinterNotifyOptions: Win32Pointer, pvReserved: Win32Pointer, pNotificationConfig: Win32Pointer, phNotify: Win32Pointer, phEvent: Win32Pointer): number;
  /** spoolss.dll!SpoolerFindNextPrinterChangeNotification */
  SpoolerFindNextPrinterChangeNotification(hPrinter: Win32StructInit, pfdwChange: Win32Pointer, pPrinterNotifyOptions: Win32Pointer, ppPrinterNotifyInfo: Win32Pointer): number;
  /** spoolss.dll!SpoolerFreePrinterNotifyInfo */
  SpoolerFreePrinterNotifyInfo(pInfo: Win32Pointer): void;
  /** spoolss.dll!SpoolerRefreshPrinterChangeNotification */
  SpoolerRefreshPrinterChangeNotification(hPrinter: Win32StructInit, dwColor: number, pOptions: Win32Pointer, ppInfo: Win32Pointer): number;
  /** spoolss.dll!UpdatePrintDeviceObject */
  UpdatePrintDeviceObject(hPrinter: Win32StructInit, hDeviceObject: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
