// Équivalents des paquets MSYS2 installés dans C:/msys64 (clé : nom sans préfixe mingw-w64-<env>-), relus par
// msys2-mirror.ts. Aports Alpine résolus sur APKINDEX v3.24 main/community (binaire -> origine) puis revérifiés
// dans C:/aports (origin/3.24-stable) à chaque `verify`.
export type Equivalent =
  | { kind: "aport"; repo: "main" | "community"; name: string }
  | { kind: "aphrody-aport"; name: string }
  | { kind: "aphrody-mingw"; name: string }
  | { kind: "bun-builtin"; name: string }
  | { kind: "bun"; file: string; pattern?: string }
  | { kind: "windows"; path: string }
  | { kind: "built"; path: string }
  | { kind: "na"; reason: string }
  | { kind: "planned"; plan: string };

export interface PackageMapping {
  use: string;
  alpine: Equivalent[];
  windows?: Equivalent[];
  bun?: Equivalent[];
}

const ALPINE: Record<string, string> = {
  "base": "main/alpine-base",
  "bash": "main/bash",
  "bash-completion": "main/bash-completion",
  "brotli": "main/brotli",
  "bsdtar": "main/libarchive",
  "bzip2": "main/bzip2",
  "ca-certificates": "main/ca-certificates",
  "coreutils": "main/coreutils",
  "curl": "main/curl",
  "dash": "main/dash",
  "db": "main/db",
  "file": "main/file",
  "filesystem": "main/alpine-baselayout",
  "findutils": "main/findutils",
  "gawk": "main/gawk",
  "gcc-libs": "main/gcc",
  "gdbm": "main/gdbm",
  "getent": "main/musl",
  "gettext": "main/gettext",
  "gmp": "main/gmp",
  "gnupg": "main/gnupg",
  "grep": "main/grep",
  "gzip": "main/gzip",
  "inetutils": "community/inetutils-telnet",
  "info": "main/texinfo",
  "less": "main/less",
  "libargp": "main/argp-standalone",
  "libasprintf": "main/gettext",
  "libassuan": "main/libassuan",
  "libbz2": "main/bzip2",
  "libcurl": "main/curl",
  "libdb": "main/db",
  "libexpat": "main/expat",
  "libffi": "main/libffi",
  "libgcrypt": "main/libgcrypt",
  "libgdbm": "main/gdbm",
  "libgettextpo": "main/gettext",
  "libgnutls": "main/gnutls",
  "libgpg-error": "main/libgpg-error",
  "libhogweed": "main/nettle",
  "libiconv": "community/gnu-libiconv",
  "libidn2": "main/libidn2",
  "libintl": "main/gettext",
  "libksba": "main/libksba",
  "liblz4": "main/lz4",
  "liblzma": "main/xz",
  "libnettle": "main/nettle",
  "libnghttp2": "main/nghttp2",
  "libnghttp3": "main/nghttp3",
  "libngtcp2": "main/ngtcp2",
  "libnpth": "main/npth",
  "libopenssl": "main/openssl",
  "libp11-kit": "main/p11-kit",
  "libpcre": "main/pcre",
  "libpcre2_8": "main/pcre2",
  "libpsl": "main/libpsl",
  "libreadline": "main/readline",
  "libsqlite": "main/sqlite",
  "libssh2": "main/libssh2",
  "libtasn1": "main/libtasn1",
  "libunistring": "main/libunistring",
  "libutil-linux": "main/util-linux",
  "libxcrypt": "main/musl",
  "libzstd": "main/zstd",
  "adwaita-icon-theme": "community/adwaita-icon-theme",
  "adwaita-icon-theme-legacy": "community/adwaita-icon-theme",
  "binutils": "main/binutils",
  "breeze-icons": "community/breeze-icons",
  "cairo": "main/cairo",
  "cc-libs": "main/gcc",
  "crt": "community/mingw-w64-crt",
  "dbus": "main/dbus",
  "double-conversion": "community/double-conversion",
  "egl-headers": "main/mesa",
  "expat": "main/expat",
  "fontconfig": "main/fontconfig",
  "freetype": "main/freetype",
  "fribidi": "main/fribidi",
  "gcc": "main/gcc",
  "gdk-pixbuf2": "community/gdk-pixbuf",
  "gettext-runtime": "main/gettext",
  "giflib": "main/giflib",
  "gles-headers": "main/mesa",
  "glib2": "main/glib",
  "gnutls": "main/gnutls",
  "graphene": "main/graphene",
  "graphite2": "main/graphite2",
  "gst-plugins-bad-libs": "community/gst-plugins-bad",
  "gst-plugins-base": "main/gst-plugins-base",
  "gstreamer": "main/gstreamer",
  "gtk-update-icon-cache": "community/gtk+3.0",
  "gtk4": "community/gtk4.0",
  "harfbuzz": "main/harfbuzz",
  "headers": "community/mingw-w64-headers",
  "hicolor-icon-theme": "main/hicolor-icon-theme",
  "icu": "main/icu",
  "isl": "main/isl26",
  "iso-codes": "main/iso-codes",
  "json-glib": "community/json-glib",
  "karchive": "community/karchive",
  "kcodecs": "community/kcodecs",
  "kcolorscheme": "community/kcolorscheme",
  "kconfig": "community/kconfig",
  "kconfigwidgets": "community/kconfigwidgets",
  "kcoreaddons": "community/kcoreaddons",
  "kguiaddons": "community/kguiaddons",
  "ki18n": "community/ki18n",
  "kiconthemes": "community/kiconthemes",
  "kirigami": "community/kirigami",
  "kwidgetsaddons": "community/kwidgetsaddons",
  "lerc": "community/lerc",
  "libatomic": "main/gcc",
  "libb2": "community/libb2",
  "libdatrie": "community/libdatrie",
  "libdeflate": "community/libdeflate",
  "libepoxy": "main/libepoxy",
  "libgcc": "main/gcc",
  "libgomp": "main/gcc",
  "libjpeg-turbo": "main/libjpeg-turbo",
  "libnice": "community/libnice",
  "libogg": "main/libogg",
  "libpng": "main/libpng",
  "libquadmath": "main/gcc",
  "librsvg": "community/librsvg",
  "libstdc++": "main/gcc",
  "libsystre": "main/musl",
  "libtre": "main/musl",
  "libthai": "community/libthai",
  "libtheora": "main/libtheora",
  "libtiff": "main/tiff",
  "libva": "main/libva",
  "libvorbis": "main/libvorbis",
  "libwebp": "main/libwebp",
  "libwinpthread": "community/mingw-w64-winpthreads",
  "libxml2": "main/libxml2",
  "lzo2": "main/lzo",
  "md4c": "community/md4c",
  "mpc": "community/mpc",
  "mpdecimal": "main/mpdecimal",
  "mpfr": "main/mpfr4",
  "ncurses": "main/ncurses",
  "nettle": "main/nettle",
  "openssl": "main/openssl",
  "opus": "main/opus",
  "orc": "main/orc",
  "p11-kit": "main/p11-kit",
  "pango": "main/pango",
  "pcre2": "main/pcre2",
  "pixman": "main/pixman",
  "pkgconf": "main/pkgconf",
  "python": "main/python3",
  "python-packaging": "main/py3-packaging",
  "qqc2-desktop-style": "community/qqc2-desktop-style",
  "qt6-base": "community/qt6-qtbase",
  "qt6-declarative": "community/qt6-qtdeclarative",
  "qt6-svg": "community/qt6-qtsvg",
  "shared-mime-info": "main/shared-mime-info",
  "sonnet": "community/sonnet",
  "sqlite3": "main/sqlite",
  "tcl": "main/tcl",
  "tk": "main/tk",
  "tzdata": "main/tzdata",
  "vulkan-headers": "main/vulkan-headers",
  "vulkan-loader": "main/vulkan-loader",
  "wineditline": "main/libedit",
  "winpthreads": "community/mingw-w64-winpthreads",
  "xz": "main/xz",
  "zlib": "main/zlib",
  "zstd": "main/zstd",
  "mintty": "community/cosmic-term",
  "msys2-keyring": "main/alpine-keys",
  "msys2-runtime": "main/musl",
  "nano": "main/nano",
  "pacman": "main/apk-tools",
  "pacman-contrib": "community/pacman",
  "pacman-mirrors": "main/apk-tools",
  "perl": "main/perl",
  "pinentry": "main/pinentry",
  "sed": "main/sed",
  "tar": "main/tar",
  "time": "community/time",
  "tzcode": "main/tzdata",
  "util-linux": "main/util-linux",
  "wget": "main/wget",
  "which": "main/which",
};

// Absents d'Alpine 3.24 : recettes du fork (C:/aports/aphrody/<nom>).
const APHRODY: Record<string, string> = {
  "directx-headers": "directx-headers",
  "directxmath": "directxmath",
  "jbigkit": "jbigkit",
  "libtre": "tre",
  "libsystre": "tre",
};

// Sans objet sous Linux (la fonction n'existe que pour la couche POSIX de Windows ou le format PE).
const NA_LINUX: Record<string, string> = {
  "rebase": "adresses de base des DLL Cygwin/MSYS (fork() émulé) ; les ELF sont PIC",
  "msys2-launcher": "lanceurs .exe des environnements MSYS2 ; Linux : shell de connexion (bunsh -l, /etc/shells)",
  "windows-default-manifest": "manifeste PE par défaut ; sans équivalent ELF",
};

const MINGW_TOOLCHAIN: Equivalent[] = [
  { kind: "built", path: "C:/tools/llvm-mingw/bin/x86_64-w64-mingw32-clang.exe" },
  { kind: "aport", repo: "community", name: "mingw-w64-gcc" },
];

const W = (path: string): Equivalent => ({ kind: "windows", path });
const B = (file: string, pattern?: string): Equivalent => ({ kind: "bun", file, pattern });
const BI = (...names: string[]): Equivalent[] => names.map(name => ({ kind: "bun-builtin", name }));

const WINDOWS: Record<string, Equivalent[]> = {
  "bash": [W("%LOCALAPPDATA%/Microsoft/WindowsApps/pwsh.exe")],
  "dash": [W("%LOCALAPPDATA%/Microsoft/WindowsApps/pwsh.exe")],
  "curl": [W("C:/Windows/System32/curl.exe")],
  "libcurl": [W("C:/Windows/System32/curl.exe")],
  "bsdtar": [W("C:/Windows/System32/tar.exe")],
  "tar": [W("C:/Windows/System32/tar.exe")],
  "findutils": [W("%USERPROFILE%/.cargo/bin/fd.exe")],
  "grep": [W("%USERPROFILE%/.cargo/bin/rg.exe"), W("C:/Windows/System32/findstr.exe")],
  "sed": [W("%USERPROFILE%/.cargo/bin/sd.exe")],
  "gawk": [W("%USERPROFILE%/.cargo/bin/nu.exe")],
  "which": [W("C:/Windows/System32/where.exe")],
  "ca-certificates": [W("C:/Windows/System32/certutil.exe")],
  "mintty": [W("%LOCALAPPDATA%/Microsoft/WindowsApps/wt.exe")],
  "nano": [W("%LOCALAPPDATA%/Microsoft/WinGet/Links/hx.exe")],
  "python": [W("%USERPROFILE%/.cargo/bin/uv.exe")],
  "icu": [W("C:/Windows/System32/icu.dll")],
  "vulkan-loader": [W("C:/Windows/System32/vulkan-1.dll")],
  "pacman": [B("src/install/system/winget/mod.rs")],
  "msys2-runtime": [{ kind: "na", reason: "binaires Windows natifs (llvm-mingw, MSVC) : pas de couche POSIX" }],
  "rebase": [{ kind: "na", reason: "seulement pour les DLL msys-2.0" }],
  "crt": MINGW_TOOLCHAIN,
  "headers": MINGW_TOOLCHAIN,
  "gcc": MINGW_TOOLCHAIN,
  "binutils": MINGW_TOOLCHAIN,
  "winpthreads": MINGW_TOOLCHAIN,
  "libwinpthread": MINGW_TOOLCHAIN,
  "libgcc": MINGW_TOOLCHAIN,
  "libstdc++": MINGW_TOOLCHAIN,
  "cc-libs": MINGW_TOOLCHAIN,
  "libatomic": MINGW_TOOLCHAIN,
  "libquadmath": MINGW_TOOLCHAIN,
  "libgomp": MINGW_TOOLCHAIN,
  "isl": MINGW_TOOLCHAIN,
  "mpc": MINGW_TOOLCHAIN,
  "mpfr": MINGW_TOOLCHAIN,
  "gmp": MINGW_TOOLCHAIN,
  "windows-default-manifest": MINGW_TOOLCHAIN,
};

const BUN: Record<string, Equivalent[]> = {
  "bash": [B("src/runtime/cli/bunsh.rs")],
  "dash": [B("src/runtime/cli/bunsh.rs")],
  "base": [B("src/runtime/cli/bunsh.rs")],
  "filesystem": [B("src/runtime/cli/bunsh.rs")],
  "msys2-launcher": [B("src/runtime/cli/bunsh.rs", "login shell")],
  "coreutils": BI(
    "cat",
    "cp",
    "echo",
    "ls",
    "mkdir",
    "mv",
    "pwd",
    "rm",
    "seq",
    "touch",
    "true",
    "false",
    "yes",
    "basename",
    "dirname",
  ),
  "which": BI("which"),
  "findutils": [B("src/runtime/api/glob.rs")],
  "curl": [B("src/runtime/webcore/fetch.rs")],
  "libcurl": [B("src/runtime/webcore/fetch.rs")],
  "wget": [B("src/runtime/webcore/fetch.rs")],
  "bsdtar": [B("src/runtime/api/Archive.rs"), B("vendor/libarchive")],
  "tar": [B("src/runtime/api/Archive.rs")],
  "gzip": [B("src/js/node/zlib.ts")],
  "zlib": [B("vendor/zlib")],
  "brotli": [B("vendor/brotli")],
  "zstd": [B("vendor/zstd")],
  "libzstd": [B("vendor/zstd")],
  "libdeflate": [B("vendor/libdeflate")],
  "libjpeg-turbo": [B("vendor/libjpeg-turbo")],
  "libpng": [B("src/runtime/image/codec_png.rs")],
  "libwebp": [B("vendor/libwebp")],
  "openssl": [B("vendor/boringssl")],
  "libopenssl": [B("vendor/boringssl")],
  "gnutls": [B("vendor/boringssl")],
  "libgnutls": [B("vendor/boringssl")],
  "nettle": [B("src/runtime/crypto/EVP.rs")],
  "libnettle": [B("src/runtime/crypto/EVP.rs")],
  "libhogweed": [B("src/runtime/crypto/EVP.rs")],
  "libgcrypt": [B("src/runtime/crypto/EVP.rs")],
  "libxcrypt": [B("src/runtime/crypto/PasswordObject.rs")],
  "ca-certificates": [B("src/runtime/socket/bundled_root_certs.rs")],
  "sqlite3": [B("src/js/bun/sqlite.ts")],
  "libsqlite": [B("src/js/bun/sqlite.ts")],
  "libffi": [B("src/js/bun/ffi.ts"), B("vendor/tinycc")],
  "libnghttp2": [B("src/js/node/http2.ts"), B("vendor/lshpack")],
  "libnghttp3": [B("vendor/lsqpack")],
  "libngtcp2": [B("vendor/lsquic")],
  "libiconv": [B("src/runtime/webcore/TextDecoder.rs")],
  "libunistring": [B("src/runtime/webcore/encoding.rs")],
  "libidn2": [B("src/js/node/url.ts", "domainToASCII")],
  "libreadline": [B("src/runtime/cli/repl.rs")],
  "wineditline": [B("src/runtime/cli/repl.rs")],
  "ncurses": [B("src/runtime/api/Terminal.classes.ts")],
  "pacman": [B("src/install/system/mod.rs")],
  "pacman-mirrors": [B("src/install/system/mod.rs")],
  "md4c": [B("src/runtime/api/MarkdownObject.rs")],
  "msys2-runtime": [B("src/sys/lib.rs")],
};

const USE: Record<string, string> = {
  "msys2-runtime": "couche POSIX (msys-2.0.dll, fork de Cygwin) liée par 495 PE de usr/bin",
  "base": "méta-paquet de l'installation MSYS2 minimale",
  "filesystem": "arborescence /etc /usr, profils (/etc/profile, profile.d), fstab, nsswitch",
  "rebase": "rebaseall des DLL msys après mise à jour (autorebase.bat)",
  "pacman": "gestionnaire de paquets (pacman -S/-Syu), utilisé par les agents UI pour GTK4/Qt6 ucrt64",
  "mintty": "terminal des lanceurs MSYS2",
  "gtk4": "GTK 4 (fixture test/js/bun/ffi/gtk-window.fixture.ts, agent UI)",
  "qt6-base": "Qt 6 (fixtures qt-window/kde-window, agent UI)",
  "kirigami": "KDE Kirigami (fixture kde-window, agent UI)",
};

function build(): Record<string, PackageMapping> {
  const out: Record<string, PackageMapping> = {};
  const keys = new Set([...Object.keys(ALPINE), ...Object.keys(APHRODY), ...Object.keys(NA_LINUX)]);
  for (const base of keys) {
    const alpine: Equivalent[] = [];
    if (APHRODY[base]) alpine.push({ kind: "aphrody-aport", name: APHRODY[base] });
    if (ALPINE[base]) {
      const [repo, name] = ALPINE[base].split("/") as ["main" | "community", string];
      alpine.push({ kind: "aport", repo, name });
    }
    if (NA_LINUX[base]) alpine.push({ kind: "na", reason: NA_LINUX[base] });
    out[base] = { use: USE[base] ?? "", alpine, windows: WINDOWS[base], bun: BUN[base] };
  }
  return out;
}

export const MAP: Record<string, PackageMapping> = build();

// Paquets mingw-w64 sans recette Windows dédiée ci-dessus : recette croisée du fork aports (agent MS,
// C:/aports/aphrody/mingw-w64/**).
export function windowsDefault(base: string): Equivalent[] {
  return WINDOWS[base] ?? [{ kind: "aphrody-mingw", name: base }];
}
