// Publishes the fork's Rust SDK crates to crates.io under the `aphrody-bun-*`
// names. Upstream's crate names (`bun-native-plugin`, `bun-macro`) belong to
// other owners, so the rename happens here, on a staged copy, and never in the
// upstream manifests: the upstream sync keeps merging them without conflicts.
// The staged packages keep their upstream library names (`bun_native_plugin`,
// `bun_macro`) because the `#[bun]` and `define_bun_plugin!` expansions refer
// to `bun_native_plugin::` by path.
//
//   bun scripts/aphrody/publish-crates.ts                  stage + cargo package --list + publish --dry-run
//   bun scripts/aphrody/publish-crates.ts --publish        publish every version not yet on crates.io
//   options: --out <dir> (staging dir), --toolchain <name> (default stable), --skip-tests,
//            --only sdk,packages/bun-n2b,packages/bun-oxc (default: all)

import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "../..");
const REPOSITORY = "https://github.com/aphrody-labs/bun";
const USER_AGENT = "aphrody-labs/bun publish-crates (https://github.com/aphrody-labs/bun)";

type Crate = {
  dir: string;
  upstream: string;
  name: string;
  lib: string;
  // Files and directories copied from `dir`, besides the manifest.
  include: string[];
  description: string;
  keywords: string[];
  categories: string[];
  // Set to publish a fork-only release when the upstream version is already taken.
  version?: string;
};

// Dependency order: a crate comes after the crates it depends on.
export const CRATES: Crate[] = [
  {
    dir: "packages/bun-native-plugin-rs/bun-macro",
    upstream: "bun-macro",
    name: "aphrody-bun-macro",
    lib: "bun_macro",
    include: ["src", "README.md"],
    description:
      "Proc macros for writing Bun native bundler plugins in Rust (Aphrody fork of oven-sh/bun's bun-macro).",
    keywords: ["bun", "plugin", "bundler", "napi", "macro"],
    categories: ["development-tools::procedural-macro-helpers"],
  },
  {
    dir: "packages/bun-native-plugin-rs",
    upstream: "bun-native-plugin",
    name: "aphrody-bun-native-plugin",
    lib: "bun_native_plugin",
    include: ["src", "headers", "wrapper.h", "README.md"],
    description:
      "Rust SDK for writing native bundler plugins for Bun (Aphrody fork of oven-sh/bun's bun-native-plugin).",
    keywords: ["bun", "plugin", "bundler", "napi", "ffi"],
    categories: ["development-tools::build-utils", "api-bindings"],
  },
];

// Fork-only crates, published under their own names straight from the package's
// own Cargo workspace (no staging: nothing upstream to keep mergeable). Listed in
// dependency order.
export const WORKSPACES: { dir: string; crates: string[] }[] = [
  {
    dir: "packages/bun-n2b",
    crates: ["aphrody-n2b-types", "aphrody-n2b-registry", "aphrody-n2b-core", "aphrody-n2b"],
  },
  { dir: "packages/bun-oxc", crates: ["aphrody-oxc-bridge"] },
];

const renamed = new Map(CRATES.map(c => [c.upstream, c]));

type Toml = Record<string, any>;

function value(v: unknown): string {
  if (typeof v === "string") return JSON.stringify(v);
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) return `[${v.map(value).join(", ")}]`;
  if (v && typeof v === "object")
    return `{ ${Object.entries(v)
      .map(([k, x]) => `${key(k)} = ${value(x)}`)
      .join(", ")} }`;
  throw new Error(`unsupported TOML value: ${v}`);
}

function key(k: string) {
  return /^[A-Za-z0-9_-]+$/.test(k) ? k : JSON.stringify(k);
}

function table(name: string, t: Toml): string {
  return [`[${name}]`, ...Object.entries(t).map(([k, v]) => `${key(k)} = ${value(v)}`), ""].join("\n");
}

function versionOf(c: Crate): string {
  return c.version ?? (Bun.TOML.parse(readFileSync(join(ROOT, c.dir, "Cargo.toml"), "utf8")) as Toml).package.version;
}

function manifest(c: Crate): string {
  const src = Bun.TOML.parse(readFileSync(join(ROOT, c.dir, "Cargo.toml"), "utf8")) as Toml;
  const pkg: Toml = {
    name: c.name,
    version: versionOf(c),
    edition: src.package.edition,
    ...(src.package["rust-version"] ? { "rust-version": src.package["rust-version"] } : {}),
    description: c.description,
    license: src.package.license,
    repository: REPOSITORY,
    homepage: `${REPOSITORY}/tree/main/${c.dir}`,
    readme: "README.md",
    keywords: c.keywords,
    categories: c.categories,
  };
  const out = [
    "# Generated by scripts/aphrody/publish-crates.ts from " + c.dir + "/Cargo.toml.",
    "",
    table("package", pkg),
  ];
  out.push(table("lib", { ...src.lib, name: c.lib }));
  for (const section of ["dependencies", "build-dependencies", "dev-dependencies"]) {
    if (!src[section]) continue;
    const deps: Toml = {};
    for (const [dep, spec] of Object.entries<any>(src[section])) {
      const target = renamed.get(dep);
      if (!target) {
        if (typeof spec === "object" && spec.path) throw new Error(`${c.dir}: path dependency ${dep} is not staged`);
        deps[dep] = spec;
        continue;
      }
      // Keep the dependency key so `use bun_macro::...` still resolves.
      deps[dep] = { package: target.name, version: `=${versionOf(target)}`, path: `../${target.name}` };
    }
    out.push(table(section, deps));
  }
  for (const k of Object.keys(src))
    if (!["package", "lib", "dependencies", "build-dependencies", "dev-dependencies"].includes(k))
      throw new Error(`${c.dir}/Cargo.toml: section [${k}] is not handled by publish-crates.ts`);
  return out.join("\n");
}

function readme(c: Crate, text: string): string {
  let body = text;
  for (const other of CRATES)
    body = body.replace(new RegExp(`cargo add ${other.upstream}\\b`, "g"), `cargo add ${other.name}`);
  const note =
    `> Published from the [Aphrody fork of Bun](${REPOSITORY}) as \`${c.name}\`. ` +
    `The library name is still \`${c.lib}\`, so code written for upstream's \`${c.upstream}\` compiles unchanged.\n\n`;
  return note + body;
}

export function stage(out: string) {
  rmSync(out, { recursive: true, force: true });
  mkdirSync(out, { recursive: true });
  for (const c of CRATES) {
    const dest = join(out, c.name);
    mkdirSync(dest, { recursive: true });
    for (const entry of c.include) {
      const from = join(ROOT, c.dir, entry);
      if (!existsSync(from)) throw new Error(`missing ${from}`);
      cpSync(from, join(dest, entry), { recursive: true });
    }
    writeFileSync(join(dest, "Cargo.toml"), manifest(c));
    writeFileSync(join(dest, "README.md"), readme(c, readFileSync(join(ROOT, c.dir, "README.md"), "utf8")));
  }
  // Own workspace root: cargo must not attach the staged crates to the repository's workspace.
  writeFileSync(join(out, "Cargo.toml"), table("workspace", { resolver: "2", members: CRATES.map(c => c.name) }));
}

async function published(name: string, version: string): Promise<boolean> {
  const res = await fetch(`https://crates.io/api/v1/crates/${name}/${version}`, {
    headers: { "User-Agent": USER_AGENT },
  });
  if (res.status === 404) return false;
  if (!res.ok) throw new Error(`crates.io ${name}@${version}: HTTP ${res.status}`);
  return true;
}

function cargo(cwd: string, toolchain: string, args: string[]) {
  console.log(`$ cargo +${toolchain} ${args.join(" ")}`);
  const r = Bun.spawnSync(["cargo", `+${toolchain}`, ...args], {
    cwd,
    stdio: ["inherit", "inherit", "inherit"],
    env: { ...process.env, RUSTUP_TOOLCHAIN: toolchain },
  });
  if (r.exitCode !== 0) throw new Error(`cargo ${args.join(" ")} failed (exit ${r.exitCode})`);
}

async function main() {
  const argv = process.argv.slice(2);
  const opt = (name: string) => {
    const i = argv.indexOf(name);
    return i >= 0 ? argv[i + 1] : undefined;
  };
  const publish = argv.includes("--publish");
  const toolchain = opt("--toolchain") ?? "stable";
  const out = resolve(opt("--out") ?? join(tmpdir(), "aphrody-crates"));
  const skipTests = argv.includes("--skip-tests");
  // --only sdk | packages/bun-n2b | packages/bun-oxc (comma-separated); default everything.
  const only = opt("--only")?.split(",");
  const selected = (key: string) => !only || only.includes(key);

  if (selected("sdk")) {
    stage(out);
    console.log(`staged ${CRATES.map(c => `${c.name}@${versionOf(c)}`).join(", ")} in ${out}`);
    const pending: { name: string; version: string }[] = [];
    for (const c of CRATES) {
      if (await published(c.name, versionOf(c))) console.log(`skip ${c.name}@${versionOf(c)}: already on crates.io`);
      else pending.push({ name: c.name, version: versionOf(c) });
    }
    for (const c of CRATES) cargo(out, toolchain, ["package", "--list", "--allow-dirty", "-p", c.name]);
    cargo(out, toolchain, ["check", "--workspace", "--all-targets"]);
    if (!skipTests) cargo(out, toolchain, ["test", "--workspace", "--lib"]);
    publishPending(out, toolchain, pending, publish);
  }

  for (const ws of WORKSPACES) {
    if (!selected(ws.dir)) continue;
    const dir = join(ROOT, ws.dir);
    const versions = workspaceVersions(dir, toolchain);
    const pending: { name: string; version: string }[] = [];
    for (const name of ws.crates) {
      const version = versions.get(name);
      if (!version) throw new Error(`${ws.dir}: no crate ${name} in the workspace`);
      if (await published(name, version)) console.log(`skip ${name}@${version}: already on crates.io`);
      else pending.push({ name, version });
    }
    for (const name of ws.crates) cargo(dir, toolchain, ["package", "--list", "--allow-dirty", "-p", name]);
    const sel = ws.crates.flatMap(name => ["-p", name]);
    cargo(dir, toolchain, ["check", "--all-targets", ...sel]);
    if (!skipTests) cargo(dir, toolchain, ["test", ...sel]);
    publishPending(dir, toolchain, pending, publish);
  }
}

function workspaceVersions(dir: string, toolchain: string): Map<string, string> {
  const r = Bun.spawnSync(["cargo", `+${toolchain}`, "metadata", "--no-deps", "--format-version", "1"], {
    cwd: dir,
    stdout: "pipe",
    stderr: "inherit",
  });
  if (r.exitCode !== 0) throw new Error(`cargo metadata failed in ${dir}`);
  const meta = JSON.parse(r.stdout.toString()) as { packages: { name: string; version: string }[] };
  return new Map(meta.packages.map(p => [p.name, p.version]));
}

function publishPending(
  cwd: string,
  toolchain: string,
  pending: { name: string; version: string }[],
  publish: boolean,
) {
  if (pending.length === 0) {
    console.log(`nothing to publish in ${cwd}`);
    return;
  }
  const sel = pending.flatMap(c => ["-p", c.name]);
  cargo(cwd, toolchain, ["publish", "--allow-dirty", "--dry-run", ...sel]);
  if (!publish) return;
  cargo(cwd, toolchain, ["publish", "--allow-dirty", ...sel]);
  for (const c of pending) console.log(`published https://crates.io/crates/${c.name}/${c.version}`);
}

if (import.meta.main) await main();
