// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** elscore.dll!MappingDoAction */
  MappingDoAction(pBag: Win32Pointer, dwRangeIndex: number, pszActionId: string | Win32Pointer): number;
  /** elscore.dll!MappingFreePropertyBag */
  MappingFreePropertyBag(pBag: Win32Pointer): number;
  /** elscore.dll!MappingFreeServices */
  MappingFreeServices(pServiceInfo: Win32Pointer): number;
  /** elscore.dll!MappingGetServices */
  MappingGetServices(pOptions: Win32Pointer, prgServices: Win32Pointer, pdwServicesCount: Win32Pointer): number;
  /** elscore.dll!MappingRecognizeText */
  MappingRecognizeText(pServiceInfo: Win32Pointer, pszText: string | Win32Pointer, dwLength: number, dwIndex: number, pOptions: Win32Pointer, pbag: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
