// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** wer.dll!WerAddExcludedApplication */
  WerAddExcludedApplication(pwzExeName: string | Win32Pointer, bAllUsers: number): number;
  /** wer.dll!WerFreeString */
  WerFreeString(pwszStr: string | Win32Pointer): void;
  /** wer.dll!WerRemoveExcludedApplication */
  WerRemoveExcludedApplication(pwzExeName: string | Win32Pointer, bAllUsers: number): number;
  /** wer.dll!WerReportAddDump */
  WerReportAddDump(hReportHandle: Win32Pointer, hProcess: Win32Pointer, hThread: Win32Pointer, dumpType: number, pExceptionParam: Win32Pointer, pDumpCustomOptions: Win32Pointer, dwFlags: number): number;
  /** wer.dll!WerReportAddFile */
  WerReportAddFile(hReportHandle: Win32Pointer, pwzPath: string | Win32Pointer, repFileType: number, dwFileFlags: number): number;
  /** wer.dll!WerReportCloseHandle */
  WerReportCloseHandle(hReportHandle: Win32Pointer): number;
  /** wer.dll!WerReportCreate */
  WerReportCreate(pwzEventType: string | Win32Pointer, repType: number, pReportInformation: Win32Pointer, phReportHandle: Win32Pointer): number;
  /** wer.dll!WerReportSetParameter */
  WerReportSetParameter(hReportHandle: Win32Pointer, dwparamID: number, pwzName: string | Win32Pointer, pwzValue: string | Win32Pointer): number;
  /** wer.dll!WerReportSetUIOption */
  WerReportSetUIOption(hReportHandle: Win32Pointer, repUITypeID: number, pwzValue: string | Win32Pointer): number;
  /** wer.dll!WerReportSubmit */
  WerReportSubmit(hReportHandle: Win32Pointer, consent: number, dwFlags: number, pSubmitResult: Win32Pointer): number;
  /** wer.dll!WerStoreClose */
  WerStoreClose(hReportStore: Win32Pointer): void;
  /** wer.dll!WerStoreGetFirstReportKey */
  WerStoreGetFirstReportKey(hReportStore: Win32Pointer, ppszReportKey: Win32Pointer): number;
  /** wer.dll!WerStoreGetNextReportKey */
  WerStoreGetNextReportKey(hReportStore: Win32Pointer, ppszReportKey: Win32Pointer): number;
  /** wer.dll!WerStoreGetReportCount */
  WerStoreGetReportCount(hReportStore: Win32Pointer, pdwReportCount: Win32Pointer): number;
  /** wer.dll!WerStoreGetSizeOnDisk */
  WerStoreGetSizeOnDisk(hReportStore: Win32Pointer, pqwSizeInBytes: Win32Pointer): number;
  /** wer.dll!WerStoreOpen */
  WerStoreOpen(repStoreType: number, phReportStore: Win32Pointer): number;
  /** wer.dll!WerStorePurge */
  WerStorePurge(): number;
  /** wer.dll!WerStoreQueryReportMetadataV1 */
  WerStoreQueryReportMetadataV1(hReportStore: Win32Pointer, pszReportKey: string | Win32Pointer, pReportMetadata: Win32Pointer): number;
  /** wer.dll!WerStoreQueryReportMetadataV2 */
  WerStoreQueryReportMetadataV2(hReportStore: Win32Pointer, pszReportKey: string | Win32Pointer, pReportMetadata: Win32Pointer): number;
  /** wer.dll!WerStoreQueryReportMetadataV3 */
  WerStoreQueryReportMetadataV3(hReportStore: Win32Pointer, pszReportKey: string | Win32Pointer, pReportMetadata: Win32Pointer): number;
  /** wer.dll!WerStoreUploadReport */
  WerStoreUploadReport(hReportStore: Win32Pointer, pszReportKey: string | Win32Pointer, dwFlags: number, pSubmitResult: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
