// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** wsclient.dll!AcquireDeveloperLicense */
  AcquireDeveloperLicense(hwndParent: Win32Pointer, pExpiration: Win32Pointer): number;
  /** wsclient.dll!CheckDeveloperLicense */
  CheckDeveloperLicense(pExpiration: Win32Pointer): number;
  /** wsclient.dll!RemoveDeveloperLicense */
  RemoveDeveloperLicense(hwndParent: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
