// Copies the JS layer of oxc-parser (wrapper, visitors, raw-transfer deserializers) and the
// .d.ts of oxc-parser / oxc-transform / oxc-minify from an oxc checkout into vendor/, with a
// bindings.js that reads the native functions from this package's addon.
//
//   bun packages/bun-oxc/scripts/sync-oxc-js.ts [path/to/oxc]   (default: $OXC_DIR or ../oxc)

import { existsSync, mkdirSync, rmSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const PACKAGE = resolve(import.meta.dir, "..");
const OXC = resolve(process.argv[2] ?? process.env.OXC_DIR ?? join(PACKAGE, "../../../oxc"));
const VENDOR = join(PACKAGE, "vendor");
const parserSrc = join(OXC, "napi/parser/src-js");

if (!existsSync(parserSrc)) {
  console.error(`oxc checkout not found: ${parserSrc}`);
  process.exit(1);
}

const SKIP = [/^bindings\.js$/, /^browser\.js$/, /wasi/, /wasm/, /^webcontainer/, /\.cjs$/, /\.d\.cts$/];

async function copy(from: string, to: string) {
  mkdirSync(dirname(to), { recursive: true });
  await Bun.write(to, Bun.file(from));
}

rmSync(VENDOR, { recursive: true, force: true });

let count = 0;
for await (const rel of new Bun.Glob("**/*.{js,d.ts}").scan({ cwd: parserSrc })) {
  const normalized = rel.split("\\").join("/");
  if (SKIP.some(pattern => pattern.test(normalized))) continue;
  await copy(join(parserSrc, rel), join(VENDOR, "oxc-parser", normalized));
  count++;
}

const BINDINGS = `// Generated by scripts/sync-oxc-js.ts: oxc-parser's native functions come from the
// @aphrody/bun-plugin-oxc addon, which links the official oxc_parser_napi crate.
import { native } from "../../src/native.ts";

const binding = native();

export const {
  Severity,
  ParseResult,
  ExportExportNameKind,
  ExportImportNameKind,
  ExportLocalNameKind,
  ImportNameKind,
  parse,
  parseSync,
  rawTransferSupported,
  getBufferOffset,
  parseRaw,
  parseRawSync,
} = binding;
export const __napiBindingTarget = "native";
`;
await Bun.write(join(VENDOR, "oxc-parser", "bindings.js"), BINDINGS);

for (const name of ["transform", "minify"]) {
  await copy(join(OXC, "napi", name, "index.d.ts"), join(VENDOR, `oxc-${name}`, "index.d.ts"));
  count++;
}

const version = (await Bun.file(join(OXC, "napi/parser/package.json")).json()).version as string;
await Bun.write(
  join(VENDOR, "README.md"),
  `Synced from oxc ${version} (napi/parser/src-js, napi/transform/index.d.ts, ` +
    `napi/minify/index.d.ts) by \`scripts/sync-oxc-js.ts\`. Do not edit by hand. MIT, (c) oxc contributors.\n`,
);
console.log(`vendor/: ${count} files from oxc ${version}`);
