// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** api-ms-win-shcore-scaling-l1-1-1.dll!GetDpiForMonitor */
  GetDpiForMonitor(hmonitor: Win32Pointer, dpiType: number, dpiX: Win32Pointer, dpiY: Win32Pointer): number;
  /** api-ms-win-shcore-scaling-l1-1-1.dll!GetProcessDpiAwareness */
  GetProcessDpiAwareness(hprocess: Win32Pointer, value: Win32Pointer): number;
  /** api-ms-win-shcore-scaling-l1-1-1.dll!GetScaleFactorForMonitor */
  GetScaleFactorForMonitor(hMon: Win32Pointer, pScale: Win32Pointer): number;
  /** api-ms-win-shcore-scaling-l1-1-1.dll!RegisterScaleChangeEvent */
  RegisterScaleChangeEvent(hEvent: Win32Pointer, pdwCookie: Win32Pointer): number;
  /** api-ms-win-shcore-scaling-l1-1-1.dll!SetProcessDpiAwareness */
  SetProcessDpiAwareness(value: number): number;
  /** api-ms-win-shcore-scaling-l1-1-1.dll!UnregisterScaleChangeEvent */
  UnregisterScaleChangeEvent(dwCookie: number | bigint): number;
}

declare const family: Win32Family & Functions;
export = family;
