// Copyright 2026 aphrody-code
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Génère `llms.txt` (index) et `llms-full.txt` (concat) selon la spec
//! https://llmstxt.org/.

use std::{fs, io::Write, path::Path};

use anyhow::{Context, Result};

use super::parse::{Page, Site};

/// llms.txt : format officiel
///
///   # <Site title>
///
///   > <description>
///
///   ## Section
///   - [Title](url): short description
pub fn write_index(site: &Site, out: &Path) -> Result<()> {
    let mut f = fs::File::create(out).with_context(|| format!("créer {}", out.display()))?;
    writeln!(f, "# {}", site.site_title)?;
    writeln!(f)?;
    writeln!(f, "> {}", site.site_description)?;
    writeln!(f)?;
    writeln!(f, "Source: {} — generated by llmstxt-rs", site.root_url)?;
    writeln!(f)?;

    for (section, pages) in site.sections() {
        writeln!(f, "## {section}")?;
        writeln!(f)?;
        for p in pages {
            let desc = if p.description.is_empty() {
                "".to_string()
            } else {
                format!(": {}", p.description)
            };
            writeln!(f, "- [{}]({}){}", p.title, p.url, desc)?;
        }
        writeln!(f)?;
    }
    Ok(())
}

/// llms-full.txt : concat de toutes les pages, séparées par `---` + URL.
/// Préfère utiliser le single-file produit par siteone si présent ; sinon
/// reconstruit depuis les Page individuelles.
pub fn write_full(site: &Site, siteone_single: &Path, out: &Path) -> Result<()> {
    if siteone_single.exists() {
        fs::copy(siteone_single, out).with_context(|| "copie siteone single-file")?;
        return Ok(());
    }
    let mut f = fs::File::create(out).with_context(|| format!("créer {}", out.display()))?;
    writeln!(f, "# {}", site.site_title)?;
    writeln!(f)?;
    writeln!(f, "> {}", site.site_description)?;
    writeln!(f)?;
    writeln!(f, "Source: {}", site.root_url)?;
    writeln!(f)?;
    for p in &site.pages {
        writeln!(f, "\n---\n")?;
        writeln!(f, "# {}", p.title)?;
        writeln!(f, "URL: {}", p.url)?;
        writeln!(f)?;
        write_page_body(&mut f, p)?;
    }
    Ok(())
}

fn write_page_body(f: &mut fs::File, page: &Page) -> std::io::Result<()> {
    // Strip le premier H1 pour éviter double-title (on l'a déjà émis).
    let mut first_h1_consumed = false;
    for line in page.content.lines() {
        if !first_h1_consumed && line.trim_start().starts_with("# ") {
            first_h1_consumed = true;
            continue;
        }
        writeln!(f, "{line}")?;
    }
    Ok(())
}

/// Écrit `sitemap.xml` (spec sitemaps.org 0.9) + `sitemap.txt` (1 URL/ligne).
/// Utilisé quand l'utilisateur passe `--export-sitemap` et que siteone n'a
/// pas écrit lui-même (ex : `--skip-crawl`).
pub fn write_sitemap(site: &Site, xml_out: &Path, txt_out: &Path) -> Result<()> {
    // sitemap.xml
    let mut xml =
        fs::File::create(xml_out).with_context(|| format!("créer {}", xml_out.display()))?;
    writeln!(xml, r#"<?xml version="1.0" encoding="UTF-8"?>"#)?;
    writeln!(xml, r#"<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">"#)?;
    for p in &site.pages {
        writeln!(xml, "  <url><loc>{}</loc></url>", escape_xml(&p.url))?;
    }
    writeln!(xml, "</urlset>")?;

    // sitemap.txt
    let mut txt =
        fs::File::create(txt_out).with_context(|| format!("créer {}", txt_out.display()))?;
    for p in &site.pages {
        writeln!(txt, "{}", p.url)?;
    }
    Ok(())
}

fn escape_xml(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}
