// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** cscapi.dll!OfflineFilesEnable */
  OfflineFilesEnable(bEnable: number, pbRebootRequired: Win32Pointer): number;
  /** cscapi.dll!OfflineFilesQueryStatus */
  OfflineFilesQueryStatus(pbActive: Win32Pointer, pbEnabled: Win32Pointer): number;
  /** cscapi.dll!OfflineFilesQueryStatusEx */
  OfflineFilesQueryStatusEx(pbActive: Win32Pointer, pbEnabled: Win32Pointer, pbAvailable: Win32Pointer): number;
  /** cscapi.dll!OfflineFilesStart */
  OfflineFilesStart(): number;
}

declare const family: Win32Family & Functions;
export = family;
