// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** drttransport.dll!DrtCreateIpv6UdpTransport */
  DrtCreateIpv6UdpTransport(scope: number, dwScopeId: number, dwLocalityThreshold: number, pwPort: Win32Pointer, phTransport: Win32Pointer): number;
  /** drttransport.dll!DrtDeleteIpv6UdpTransport */
  DrtDeleteIpv6UdpTransport(hTransport: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
