// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** sas.dll!SendSAS */
  SendSAS(AsUser: number): void;
}

declare const family: Win32Family & Functions;
export = family;
