// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** msports.dll!ComDBClaimNextFreePort */
  ComDBClaimNextFreePort(HComDB: Win32Pointer, ComNumber: Win32Pointer): number;
  /** msports.dll!ComDBClaimPort */
  ComDBClaimPort(HComDB: Win32Pointer, ComNumber: number, ForceClaim: number, Forced: Win32Pointer): number;
  /** msports.dll!ComDBClose */
  ComDBClose(HComDB: Win32Pointer): number;
  /** msports.dll!ComDBGetCurrentPortUsage */
  ComDBGetCurrentPortUsage(HComDB: Win32Pointer, Buffer: Win32Pointer, BufferSize: number, ReportType: number, MaxPortsReported: Win32Pointer): number;
  /** msports.dll!ComDBOpen */
  ComDBOpen(PHComDB: Win32Pointer): number;
  /** msports.dll!ComDBReleasePort */
  ComDBReleasePort(HComDB: Win32Pointer, ComNumber: number): number;
  /** msports.dll!ComDBResizeDatabase */
  ComDBResizeDatabase(HComDB: Win32Pointer, NewSize: number): number;
}

declare const family: Win32Family & Functions;
export = family;
