// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** ksuser.dll!KsCreateAllocator */
  KsCreateAllocator(ConnectionHandle: Win32Pointer, AllocatorFraming: Win32Pointer, AllocatorHandle: Win32Pointer): number;
  /** ksuser.dll!KsCreateAllocator2 */
  KsCreateAllocator2(ConnectionHandle: Win32Pointer, AllocatorFraming: Win32Pointer, AllocatorHandle: Win32Pointer): number;
  /** ksuser.dll!KsCreateClock */
  KsCreateClock(ConnectionHandle: Win32Pointer, ClockCreate: Win32Pointer, ClockHandle: Win32Pointer): number;
  /** ksuser.dll!KsCreateClock2 */
  KsCreateClock2(ConnectionHandle: Win32Pointer, ClockCreate: Win32Pointer, ClockHandle: Win32Pointer): number;
  /** ksuser.dll!KsCreatePin */
  KsCreatePin(FilterHandle: Win32Pointer, Connect: Win32Pointer, DesiredAccess: number, ConnectionHandle: Win32Pointer): number;
  /** ksuser.dll!KsCreatePin2 */
  KsCreatePin2(FilterHandle: Win32Pointer, Connect: Win32Pointer, DesiredAccess: number, ConnectionHandle: Win32Pointer): number;
  /** ksuser.dll!KsCreateTopologyNode */
  KsCreateTopologyNode(ParentHandle: Win32Pointer, NodeCreate: Win32Pointer, DesiredAccess: number, NodeHandle: Win32Pointer): number;
  /** ksuser.dll!KsCreateTopologyNode2 */
  KsCreateTopologyNode2(ParentHandle: Win32Pointer, NodeCreate: Win32Pointer, DesiredAccess: number, NodeHandle: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
