// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** avifil32.dll!AVIBuildFilterA */
  AVIBuildFilterA(lpszFilter: string | Win32Pointer, cbFilter: number, fSaving: number): number;
  /** avifil32.dll!AVIBuildFilterW */
  AVIBuildFilterW(lpszFilter: string | Win32Pointer, cbFilter: number, fSaving: number): number;
  /** avifil32.dll!AVIBuildFilterW */
  AVIBuildFilter(lpszFilter: string | Win32Pointer, cbFilter: number, fSaving: number): number;
  /** avifil32.dll!AVIClearClipboard */
  AVIClearClipboard(): number;
  /** avifil32.dll!AVIFileAddRef */
  AVIFileAddRef(pfile: Win32Pointer): number;
  /** avifil32.dll!AVIFileCreateStreamA */
  AVIFileCreateStreamA(pfile: Win32Pointer, ppavi: Win32Pointer, psi: Win32Pointer): number;
  /** avifil32.dll!AVIFileCreateStreamW */
  AVIFileCreateStreamW(pfile: Win32Pointer, ppavi: Win32Pointer, psi: Win32Pointer): number;
  /** avifil32.dll!AVIFileCreateStreamW */
  AVIFileCreateStream(pfile: Win32Pointer, ppavi: Win32Pointer, psi: Win32Pointer): number;
  /** avifil32.dll!AVIFileEndRecord */
  AVIFileEndRecord(pfile: Win32Pointer): number;
  /** avifil32.dll!AVIFileExit */
  AVIFileExit(): void;
  /** avifil32.dll!AVIFileGetStream */
  AVIFileGetStream(pfile: Win32Pointer, ppavi: Win32Pointer, fccType: number, lParam: number): number;
  /** avifil32.dll!AVIFileInfoA */
  AVIFileInfoA(pfile: Win32Pointer, pfi: Win32Pointer, lSize: number): number;
  /** avifil32.dll!AVIFileInfoW */
  AVIFileInfoW(pfile: Win32Pointer, pfi: Win32Pointer, lSize: number): number;
  /** avifil32.dll!AVIFileInfoW */
  AVIFileInfo(pfile: Win32Pointer, pfi: Win32Pointer, lSize: number): number;
  /** avifil32.dll!AVIFileInit */
  AVIFileInit(): void;
  /** avifil32.dll!AVIFileOpenA */
  AVIFileOpenA(ppfile: Win32Pointer, szFile: string | Win32Pointer, uMode: number, lpHandler: Win32Pointer): number;
  /** avifil32.dll!AVIFileOpenW */
  AVIFileOpenW(ppfile: Win32Pointer, szFile: string | Win32Pointer, uMode: number, lpHandler: Win32Pointer): number;
  /** avifil32.dll!AVIFileOpenW */
  AVIFileOpen(ppfile: Win32Pointer, szFile: string | Win32Pointer, uMode: number, lpHandler: Win32Pointer): number;
  /** avifil32.dll!AVIFileReadData */
  AVIFileReadData(pfile: Win32Pointer, ckid: number, lpData: Win32Pointer, lpcbData: Win32Pointer): number;
  /** avifil32.dll!AVIFileRelease */
  AVIFileRelease(pfile: Win32Pointer): number;
  /** avifil32.dll!AVIFileWriteData */
  AVIFileWriteData(pfile: Win32Pointer, ckid: number, lpData: Win32Pointer, cbData: number): number;
  /** avifil32.dll!AVIGetFromClipboard */
  AVIGetFromClipboard(lppf: Win32Pointer): number;
  /** avifil32.dll!AVIMakeCompressedStream */
  AVIMakeCompressedStream(ppsCompressed: Win32Pointer, ppsSource: Win32Pointer, lpOptions: Win32Pointer, pclsidHandler: Win32Pointer): number;
  /** avifil32.dll!AVIMakeFileFromStreams */
  AVIMakeFileFromStreams(ppfile: Win32Pointer, nStreams: number, papStreams: Win32Pointer): number;
  /** avifil32.dll!AVIMakeStreamFromClipboard */
  AVIMakeStreamFromClipboard(cfFormat: number, hGlobal: Win32Pointer, ppstream: Win32Pointer): number;
  /** avifil32.dll!AVIPutFileOnClipboard */
  AVIPutFileOnClipboard(pf: Win32Pointer): number;
  /** avifil32.dll!AVISaveA */
  AVISaveA(szFile: string | Win32Pointer, pclsidHandler: Win32Pointer, lpfnCallback: Win32Callback, nStreams: number, pfile: Win32Pointer, lpOptions: Win32Pointer): number;
  /** avifil32.dll!AVISaveOptions */
  AVISaveOptions(hwnd: Win32Pointer, uiFlags: number, nStreams: number, ppavi: Win32Pointer, plpOptions: Win32Pointer): number | bigint;
  /** avifil32.dll!AVISaveOptionsFree */
  AVISaveOptionsFree(nStreams: number, plpOptions: Win32Pointer): number;
  /** avifil32.dll!AVISaveVA */
  AVISaveVA(szFile: string | Win32Pointer, pclsidHandler: Win32Pointer, lpfnCallback: Win32Callback, nStreams: number, ppavi: Win32Pointer, plpOptions: Win32Pointer): number;
  /** avifil32.dll!AVISaveVW */
  AVISaveVW(szFile: string | Win32Pointer, pclsidHandler: Win32Pointer, lpfnCallback: Win32Callback, nStreams: number, ppavi: Win32Pointer, plpOptions: Win32Pointer): number;
  /** avifil32.dll!AVISaveVW */
  AVISaveV(szFile: string | Win32Pointer, pclsidHandler: Win32Pointer, lpfnCallback: Win32Callback, nStreams: number, ppavi: Win32Pointer, plpOptions: Win32Pointer): number;
  /** avifil32.dll!AVISaveW */
  AVISaveW(szFile: string | Win32Pointer, pclsidHandler: Win32Pointer, lpfnCallback: Win32Callback, nStreams: number, pfile: Win32Pointer, lpOptions: Win32Pointer): number;
  /** avifil32.dll!AVISaveW */
  AVISave(szFile: string | Win32Pointer, pclsidHandler: Win32Pointer, lpfnCallback: Win32Callback, nStreams: number, pfile: Win32Pointer, lpOptions: Win32Pointer): number;
  /** avifil32.dll!AVIStreamAddRef */
  AVIStreamAddRef(pavi: Win32Pointer): number;
  /** avifil32.dll!AVIStreamBeginStreaming */
  AVIStreamBeginStreaming(pavi: Win32Pointer, lStart: number, lEnd: number, lRate: number): number;
  /** avifil32.dll!AVIStreamCreate */
  AVIStreamCreate(ppavi: Win32Pointer, lParam1: number, lParam2: number, pclsidHandler: Win32Pointer): number;
  /** avifil32.dll!AVIStreamEndStreaming */
  AVIStreamEndStreaming(pavi: Win32Pointer): number;
  /** avifil32.dll!AVIStreamFindSample */
  AVIStreamFindSample(pavi: Win32Pointer, lPos: number, lFlags: number): number;
  /** avifil32.dll!AVIStreamGetFrame */
  AVIStreamGetFrame(pg: Win32Pointer, lPos: number): number | null;
  /** avifil32.dll!AVIStreamGetFrameClose */
  AVIStreamGetFrameClose(pg: Win32Pointer): number;
  /** avifil32.dll!AVIStreamGetFrameOpen */
  AVIStreamGetFrameOpen(pavi: Win32Pointer, lpbiWanted: Win32Pointer): number | null;
  /** avifil32.dll!AVIStreamInfoA */
  AVIStreamInfoA(pavi: Win32Pointer, psi: Win32Pointer, lSize: number): number;
  /** avifil32.dll!AVIStreamInfoW */
  AVIStreamInfoW(pavi: Win32Pointer, psi: Win32Pointer, lSize: number): number;
  /** avifil32.dll!AVIStreamInfoW */
  AVIStreamInfo(pavi: Win32Pointer, psi: Win32Pointer, lSize: number): number;
  /** avifil32.dll!AVIStreamLength */
  AVIStreamLength(pavi: Win32Pointer): number;
  /** avifil32.dll!AVIStreamOpenFromFileA */
  AVIStreamOpenFromFileA(ppavi: Win32Pointer, szFile: string | Win32Pointer, fccType: number, lParam: number, mode: number, pclsidHandler: Win32Pointer): number;
  /** avifil32.dll!AVIStreamOpenFromFileW */
  AVIStreamOpenFromFileW(ppavi: Win32Pointer, szFile: string | Win32Pointer, fccType: number, lParam: number, mode: number, pclsidHandler: Win32Pointer): number;
  /** avifil32.dll!AVIStreamOpenFromFileW */
  AVIStreamOpenFromFile(ppavi: Win32Pointer, szFile: string | Win32Pointer, fccType: number, lParam: number, mode: number, pclsidHandler: Win32Pointer): number;
  /** avifil32.dll!AVIStreamRead */
  AVIStreamRead(pavi: Win32Pointer, lStart: number, lSamples: number, lpBuffer: Win32Pointer, cbBuffer: number, plBytes: Win32Pointer, plSamples: Win32Pointer): number;
  /** avifil32.dll!AVIStreamReadData */
  AVIStreamReadData(pavi: Win32Pointer, fcc: number, lp: Win32Pointer, lpcb: Win32Pointer): number;
  /** avifil32.dll!AVIStreamReadFormat */
  AVIStreamReadFormat(pavi: Win32Pointer, lPos: number, lpFormat: Win32Pointer, lpcbFormat: Win32Pointer): number;
  /** avifil32.dll!AVIStreamRelease */
  AVIStreamRelease(pavi: Win32Pointer): number;
  /** avifil32.dll!AVIStreamSampleToTime */
  AVIStreamSampleToTime(pavi: Win32Pointer, lSample: number): number;
  /** avifil32.dll!AVIStreamSetFormat */
  AVIStreamSetFormat(pavi: Win32Pointer, lPos: number, lpFormat: Win32Pointer, cbFormat: number): number;
  /** avifil32.dll!AVIStreamStart */
  AVIStreamStart(pavi: Win32Pointer): number;
  /** avifil32.dll!AVIStreamTimeToSample */
  AVIStreamTimeToSample(pavi: Win32Pointer, lTime: number): number;
  /** avifil32.dll!AVIStreamWrite */
  AVIStreamWrite(pavi: Win32Pointer, lStart: number, lSamples: number, lpBuffer: Win32Pointer, cbBuffer: number, dwFlags: number, plSampWritten: Win32Pointer, plBytesWritten: Win32Pointer): number;
  /** avifil32.dll!AVIStreamWriteData */
  AVIStreamWriteData(pavi: Win32Pointer, fcc: number, lp: Win32Pointer, cb: number): number;
  /** avifil32.dll!CreateEditableStream */
  CreateEditableStream(ppsEditable: Win32Pointer, psSource: Win32Pointer): number;
  /** avifil32.dll!EditStreamClone */
  EditStreamClone(pavi: Win32Pointer, ppResult: Win32Pointer): number;
  /** avifil32.dll!EditStreamCopy */
  EditStreamCopy(pavi: Win32Pointer, plStart: Win32Pointer, plLength: Win32Pointer, ppResult: Win32Pointer): number;
  /** avifil32.dll!EditStreamCut */
  EditStreamCut(pavi: Win32Pointer, plStart: Win32Pointer, plLength: Win32Pointer, ppResult: Win32Pointer): number;
  /** avifil32.dll!EditStreamPaste */
  EditStreamPaste(pavi: Win32Pointer, plPos: Win32Pointer, plLength: Win32Pointer, pstream: Win32Pointer, lStart: number, lEnd: number): number;
  /** avifil32.dll!EditStreamSetInfoA */
  EditStreamSetInfoA(pavi: Win32Pointer, lpInfo: Win32Pointer, cbInfo: number): number;
  /** avifil32.dll!EditStreamSetInfoW */
  EditStreamSetInfoW(pavi: Win32Pointer, lpInfo: Win32Pointer, cbInfo: number): number;
  /** avifil32.dll!EditStreamSetInfoW */
  EditStreamSetInfo(pavi: Win32Pointer, lpInfo: Win32Pointer, cbInfo: number): number;
  /** avifil32.dll!EditStreamSetNameA */
  EditStreamSetNameA(pavi: Win32Pointer, lpszName: string | Win32Pointer): number;
  /** avifil32.dll!EditStreamSetNameW */
  EditStreamSetNameW(pavi: Win32Pointer, lpszName: string | Win32Pointer): number;
  /** avifil32.dll!EditStreamSetNameW */
  EditStreamSetName(pavi: Win32Pointer, lpszName: string | Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
