// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** wldp.dll!WldpCanExecuteBuffer */
  WldpCanExecuteBuffer(host: Win32Pointer, options: number, buffer: Win32Pointer, bufferSize: number, auditInfo: string | Win32Pointer, result: Win32Pointer): number;
  /** wldp.dll!WldpCanExecuteFile */
  WldpCanExecuteFile(host: Win32Pointer, options: number, fileHandle: Win32Pointer, auditInfo: string | Win32Pointer, result: Win32Pointer): number;
  /** wldp.dll!WldpCanExecuteFileFromDetachedSignature */
  WldpCanExecuteFileFromDetachedSignature(host: Win32Pointer, options: number, contentFileHandle: Win32Pointer, signatureFileHandle: Win32Pointer, auditInfo: string | Win32Pointer, result: Win32Pointer): number;
  /** wldp.dll!WldpCanExecuteStream */
  WldpCanExecuteStream(host: Win32Pointer, options: number, stream: Win32Pointer, auditInfo: string | Win32Pointer, result: Win32Pointer): number;
  /** wldp.dll!WldpGetApplicationSettingBoolean */
  WldpGetApplicationSettingBoolean(id: string | Win32Pointer, setting: string | Win32Pointer, result: Win32Pointer): number;
  /** wldp.dll!WldpGetApplicationSettingStringList */
  WldpGetApplicationSettingStringList(id: string | Win32Pointer, setting: string | Win32Pointer, dataCount: number | bigint, requiredCount: Win32Pointer, result: string | Win32Pointer): number;
  /** wldp.dll!WldpGetApplicationSettingStringSet */
  WldpGetApplicationSettingStringSet(id: string | Win32Pointer, setting: string | Win32Pointer, dataCount: number | bigint, requiredCount: Win32Pointer, result: string | Win32Pointer): number;
  /** wldp.dll!WldpGetLockdownPolicy */
  WldpGetLockdownPolicy(hostInformation: Win32Pointer, lockdownState: Win32Pointer, lockdownFlags: number): number;
  /** wldp.dll!WldpIsAppApprovedByPolicy */
  WldpIsAppApprovedByPolicy(PackageFamilyName: string | Win32Pointer, PackageVersion: number | bigint): number;
  /** wldp.dll!WldpIsClassInApprovedList */
  WldpIsClassInApprovedList(classID: Win32Pointer, hostInformation: Win32Pointer, isApproved: Win32Pointer, optionalFlags: number): number;
  /** wldp.dll!WldpIsDynamicCodePolicyEnabled */
  WldpIsDynamicCodePolicyEnabled(isEnabled: Win32Pointer): number;
  /** wldp.dll!WldpIsProductionConfiguration */
  WldpIsProductionConfiguration(IsProductionConfiguration: Win32Pointer): number;
  /** wldp.dll!WldpIsWcosProductionConfiguration */
  WldpIsWcosProductionConfiguration(IsProductionConfiguration: Win32Pointer): number;
  /** wldp.dll!WldpQueryDeviceSecurityInformation */
  WldpQueryDeviceSecurityInformation(information: Win32Pointer, informationLength: number, returnLength: Win32Pointer): number;
  /** wldp.dll!WldpQueryDynamicCodeTrust */
  WldpQueryDynamicCodeTrust(fileHandle: Win32Pointer, baseImage: Win32Pointer, imageSize: number): number;
  /** wldp.dll!WldpQueryPolicySettingEnabled */
  WldpQueryPolicySettingEnabled(Setting: number, Enabled: Win32Pointer): number;
  /** wldp.dll!WldpQueryPolicySettingEnabled2 */
  WldpQueryPolicySettingEnabled2(SettingString: string | Win32Pointer, Enabled: Win32Pointer): number;
  /** wldp.dll!WldpQuerySecurityPolicy */
  WldpQuerySecurityPolicy(providerName: Win32Pointer, keyName: Win32Pointer, valueName: Win32Pointer, valueType: Win32Pointer, valueAddress: Win32Pointer, valueSize: Win32Pointer): number;
  /** wldp.dll!WldpQueryWindowsLockdownMode */
  WldpQueryWindowsLockdownMode(lockdownMode: Win32Pointer): number;
  /** wldp.dll!WldpQueryWindowsLockdownRestriction */
  WldpQueryWindowsLockdownRestriction(LockdownRestriction: Win32Pointer): number;
  /** wldp.dll!WldpResetProductionConfiguration */
  WldpResetProductionConfiguration(): number;
  /** wldp.dll!WldpResetWcosProductionConfiguration */
  WldpResetWcosProductionConfiguration(): number;
  /** wldp.dll!WldpSetDynamicCodeTrust */
  WldpSetDynamicCodeTrust(fileHandle: Win32Pointer): number;
  /** wldp.dll!WldpSetWindowsLockdownRestriction */
  WldpSetWindowsLockdownRestriction(LockdownRestriction: number): number;
}

declare const family: Win32Family & Functions;
export = family;
