// Generates the bun:windows WinRT families from the local Windows SDK metadata:
//   bun scripts/aphrody/winrt/gen.ts [--sdk 10.0.26100.0] [--all] Windows.System.Profile Windows.Storage ...
//   bun scripts/aphrody/winrt/gen.ts --winmd <framework>/Microsoft.UI.Xaml.winmd --version 1.8 Microsoft.UI.Xaml ...
// Each namespace becomes packages/bun-windows-winrt-<namespace>, loaded by windows.family("winrt-<namespace>").
// Only data derived from Windows.winmd is written; SDK headers are never copied.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import winmd from "../../../src/js/internal/winmd.ts";

const args = process.argv.slice(2);
const sdkIndex = args.indexOf("--sdk");
const sdk = sdkIndex >= 0 ? args.splice(sdkIndex, 2)[1] : "10.0.26100.0";
const all = args.includes("--all");
const winmdIndex = args.indexOf("--winmd");
const winmdArg = winmdIndex >= 0 ? args.splice(winmdIndex, 2)[1] : undefined;
const versionIndex = args.indexOf("--version");
const versionArg = versionIndex >= 0 ? args.splice(versionIndex, 2)[1] : undefined;
const kits = process.env.WindowsSdkDir ?? "C:/Program Files (x86)/Windows Kits/10";
const winmdPath = winmdArg ?? join(kits, "UnionMetadata", sdk, "Windows.winmd");
const source = winmdArg ? require("node:path").basename(winmdArg) : `UnionMetadata\\${sdk}\\Windows.winmd`;
const packageVersion = versionArg ?? sdk;
const repo = join(import.meta.dir, "..", "..", "..");

export function familyName(ns: string) {
  return `winrt-${ns.toLowerCase().replaceAll(".", "-")}`;
}

export function loadModel(path = winmdPath) {
  return winmd.winrtModel(new Uint8Array(readFileSync(path)));
}

if (import.meta.main) {
  const model = loadModel();
  const wanted = all ? [...model.keys()] : args.filter(a => !a.startsWith("--"));
  for (const ns of wanted) {
    const data = model.get(ns);
    if (!data) throw new Error(`namespace ${ns} not found in ${winmdPath}`);
    const family = familyName(ns);
    const dir = join(repo, "packages", `bun-windows-${family}`);
    const pkg = {
      name: `@aphrody/bun-windows-${family}`,
      version: packageVersion,
      description: winmdArg
        ? `bun:windows WinRT family for ${ns}, generated from ${source}`
        : `bun:windows WinRT family for ${ns}, generated from Windows SDK ${sdk} metadata`,
      license: "MIT",
      main: "index.js",
    };
    const index = `// Generated by scripts/aphrody/winrt/gen.ts from ${source}. Do not edit.
module.exports = require("bun:winrt").defineNamespace(${JSON.stringify({ namespace: ns, ...data })});
`;
    await Bun.write(join(dir, "package.json"), JSON.stringify(pkg, null, 2) + "\n");
    await Bun.write(join(dir, "index.js"), index);
    const counts = [
      Object.keys(data.interfaces).length,
      Object.keys(data.classes).length,
      Object.keys(data.enums).length,
    ];
    console.log(
      `${ns} -> packages/bun-windows-${family} (${counts[0]} interfaces, ${counts[1]} classes, ${counts[2]} enums)`,
    );
  }
}
