// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** api-ms-win-service-core-l1-1-4.dll!GetServiceDirectory */
  GetServiceDirectory(hServiceStatus: Win32Pointer, eDirectoryType: number, lpPathBuffer: string | Win32Pointer, cchPathBufferLength: number, lpcchRequiredBufferLength: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
