// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** davclnt.dll!DavCancelConnectionsToServer */
  DavCancelConnectionsToServer(lpName: string | Win32Pointer, fForce: number): number;
  /** davclnt.dll!DavGetTheLockOwnerOfTheFile */
  DavGetTheLockOwnerOfTheFile(FileName: string | Win32Pointer, LockOwnerName: string | Win32Pointer, LockOwnerNameLengthInBytes: Win32Pointer): number;
  /** davclnt.dll!DavInvalidateCache */
  DavInvalidateCache(URLName: string | Win32Pointer): number;
  /** davclnt.dll!DavRegisterAuthCallback */
  DavRegisterAuthCallback(CallBack: Win32Callback, Version: number): number;
  /** davclnt.dll!DavUnregisterAuthCallback */
  DavUnregisterAuthCallback(hCallback: number): void;
  /** davclnt.dll!NPAddConnection */
  NPAddConnection(lpNetResource: Win32Pointer, lpPassword: string | Win32Pointer, lpUserName: string | Win32Pointer): number;
  /** davclnt.dll!NPAddConnection3 */
  NPAddConnection3(hwndOwner: Win32Pointer, lpNetResource: Win32Pointer, lpPassword: string | Win32Pointer, lpUserName: string | Win32Pointer, dwFlags: number): number;
  /** davclnt.dll!NPCancelConnection */
  NPCancelConnection(lpName: string | Win32Pointer, fForce: number): number;
  /** davclnt.dll!NPCloseEnum */
  NPCloseEnum(hEnum: Win32Pointer): number;
  /** davclnt.dll!NPEnumResource */
  NPEnumResource(hEnum: Win32Pointer, lpcCount: Win32Pointer, lpBuffer: Win32Pointer, lpBufferSize: Win32Pointer): number;
  /** davclnt.dll!NPFormatNetworkName */
  NPFormatNetworkName(lpRemoteName: string | Win32Pointer, lpFormattedName: string | Win32Pointer, lpnLength: Win32Pointer, dwFlags: number, dwAveCharPerLine: number): number;
  /** davclnt.dll!NPGetCaps */
  NPGetCaps(ndex: number): number;
  /** davclnt.dll!NPGetConnection */
  NPGetConnection(lpLocalName: string | Win32Pointer, lpRemoteName: string | Win32Pointer, lpnBufferLen: Win32Pointer): number;
  /** davclnt.dll!NPGetResourceInformation */
  NPGetResourceInformation(lpNetResource: Win32Pointer, lpBuffer: Win32Pointer, lpBufferSize: Win32Pointer, lplpSystem: Win32Pointer): number;
  /** davclnt.dll!NPGetResourceParent */
  NPGetResourceParent(lpNetResource: Win32Pointer, lpBuffer: Win32Pointer, lpBufferSize: Win32Pointer): number;
  /** davclnt.dll!NPGetUniversalName */
  NPGetUniversalName(lpLocalPath: string | Win32Pointer, dwInfoLevel: number, lpBuffer: Win32Pointer, lpBufferSize: Win32Pointer): number;
  /** davclnt.dll!NPGetUser */
  NPGetUser(lpName: string | Win32Pointer, lpUserName: string | Win32Pointer, lpnBufferLen: Win32Pointer): number;
  /** davclnt.dll!NPOpenEnum */
  NPOpenEnum(dwScope: number, dwType: number, dwUsage: number, lpNetResource: Win32Pointer, lphEnum: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
