// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** tokenbinding.dll!TokenBindingDeleteAllBindings */
  TokenBindingDeleteAllBindings(): number;
  /** tokenbinding.dll!TokenBindingDeleteBinding */
  TokenBindingDeleteBinding(targetURL: string | Win32Pointer): number;
  /** tokenbinding.dll!TokenBindingGenerateBinding */
  TokenBindingGenerateBinding(keyType: number, targetURL: string | Win32Pointer, bindingType: number, tlsEKM: Win32Pointer, tlsEKMSize: number, extensionFormat: number, extensionData: Win32Pointer, tokenBinding: Win32Pointer, tokenBindingSize: Win32Pointer, resultData: Win32Pointer): number;
  /** tokenbinding.dll!TokenBindingGenerateID */
  TokenBindingGenerateID(keyType: number, publicKey: Win32Pointer, publicKeySize: number, resultData: Win32Pointer): number;
  /** tokenbinding.dll!TokenBindingGenerateIDForUri */
  TokenBindingGenerateIDForUri(keyType: number, targetUri: string | Win32Pointer, resultData: Win32Pointer): number;
  /** tokenbinding.dll!TokenBindingGenerateMessage */
  TokenBindingGenerateMessage(tokenBindings: Win32Pointer, tokenBindingsSize: Win32Pointer, tokenBindingsCount: number, tokenBindingMessage: Win32Pointer, tokenBindingMessageSize: Win32Pointer): number;
  /** tokenbinding.dll!TokenBindingGetHighestSupportedVersion */
  TokenBindingGetHighestSupportedVersion(majorVersion: Win32Pointer, minorVersion: Win32Pointer): number;
  /** tokenbinding.dll!TokenBindingGetKeyTypesClient */
  TokenBindingGetKeyTypesClient(keyTypes: Win32Pointer): number;
  /** tokenbinding.dll!TokenBindingGetKeyTypesServer */
  TokenBindingGetKeyTypesServer(keyTypes: Win32Pointer): number;
  /** tokenbinding.dll!TokenBindingVerifyMessage */
  TokenBindingVerifyMessage(tokenBindingMessage: Win32Pointer, tokenBindingMessageSize: number, keyType: number, tlsEKM: Win32Pointer, tlsEKMSize: number, resultList: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
