// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** xaudio2_8.dll!CreateAudioReverb */
  CreateAudioReverb(ppApo: Win32Pointer): number;
  /** xaudio2_8.dll!CreateAudioVolumeMeter */
  CreateAudioVolumeMeter(ppApo: Win32Pointer): number;
  /** xaudio2_8.dll!CreateFX */
  CreateFX(clsid: Win32Pointer, pEffect: Win32Pointer, pInitDat: Win32Pointer, InitDataByteSize: number): number;
  /** xaudio2_8.dll!XAudio2CreateWithVersionInfo */
  XAudio2CreateWithVersionInfo(ppXAudio2: Win32Pointer, Flags: number, XAudio2Processor: number, ntddiVersion: number): number;
}

declare const family: Win32Family & Functions;
export = family;
