// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** xpsprint.dll!StartXpsPrintJob */
  StartXpsPrintJob(printerName: string | Win32Pointer, jobName: string | Win32Pointer, outputFileName: string | Win32Pointer, progressEvent: Win32Pointer, completionEvent: Win32Pointer, printablePagesOn: Win32Pointer, printablePagesOnCount: number, xpsPrintJob: Win32Pointer, documentStream: Win32Pointer, printTicketStream: Win32Pointer): number;
  /** xpsprint.dll!StartXpsPrintJob1 */
  StartXpsPrintJob1(printerName: string | Win32Pointer, jobName: string | Win32Pointer, outputFileName: string | Win32Pointer, progressEvent: Win32Pointer, completionEvent: Win32Pointer, xpsPrintJob: Win32Pointer, printContentReceiver: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
