// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** wdsmc.dll!WdsTransportServerAllocateBuffer */
  WdsTransportServerAllocateBuffer(hProvider: Win32Pointer, ulBufferSize: number): number | null;
  /** wdsmc.dll!WdsTransportServerCompleteRead */
  WdsTransportServerCompleteRead(hProvider: Win32Pointer, ulBytesRead: number, pvUserData: Win32Pointer, hReadResult: number): number;
  /** wdsmc.dll!WdsTransportServerFreeBuffer */
  WdsTransportServerFreeBuffer(hProvider: Win32Pointer, pvBuffer: Win32Pointer): number;
  /** wdsmc.dll!WdsTransportServerRegisterCallback */
  WdsTransportServerRegisterCallback(hProvider: Win32Pointer, CallbackId: number, pfnCallback: Win32Pointer): number;
  /** wdsmc.dll!WdsTransportServerTrace */
  WdsTransportServerTrace(hProvider: Win32Pointer, Severity: number, pwszFormat: string | Win32Pointer): number;
  /** wdsmc.dll!WdsTransportServerTraceV */
  WdsTransportServerTraceV(hProvider: Win32Pointer, Severity: number, pwszFormat: string | Win32Pointer, Params: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
