// SPDX-License-Identifier: Apache-2.0
// `m3 compile` and `m3 docker` for App Router projects.
//
// compile: build (and prerender), then a generated entry imports the two server layers and embeds every other build
// file (`with { type: "file" }`), and `Bun.build({ compile })` links it with the Bun runtime into one executable.
// docker: build into `<context>/dist`, bundle a small `server.js` that serves it, and write a Dockerfile on the
// Aphrody Alpine runtime image (Bun on musl), so the image runs `bun server.js` without node_modules.
import { existsSync, readFileSync, rmSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { basename, dirname, join, relative, resolve } from "node:path";
import type { AppManifest } from "./build";
import type { AppProject } from "./cli";
import { buildAppProject } from "./cli";

/** Base image of `m3 docker` (scripts/aphrody/alpine/runtime.Dockerfile of the Bun fork). */
export const DOCKER_BASE_IMAGE = "ghcr.io/aphrody-labs/alpine:3.24-runtime";

const HOST = join(import.meta.dir, "host.ts");
const toPosix = (path: string) => path.replaceAll("\\", "/");
const js = (value: unknown) => JSON.stringify(value);

/** Build files the executable embeds: everything but the server layers (bundled as code) and the manifest. */
export async function embeddedFiles(outDir: string): Promise<[string, string][]> {
  const files: [string, string][] = [];
  for await (const file of new Bun.Glob("**/*").scan({ cwd: outDir, onlyFiles: true })) {
    const path = toPosix(file);
    if (path === "manifest.json" || path.startsWith("server/")) continue;
    files.push([path, join(outDir, file)]);
  }
  return files.toSorted(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
}

export interface ExecutableEntryParams {
  /** Absolute path of `host.ts`. */
  host: string;
  outDir: string;
  manifest: Pick<AppManifest, "rscEntry" | "ssrEntry">;
  files: ReadonlyArray<readonly [string, string]>;
  port: number;
}

/** Source of the entry `m3 compile` links. Pure, so tests read it. */
export function renderExecutableEntry(params: ExecutableEntryParams): string {
  const path = (file: string) => js(toPosix(file));
  return [
    "// Generated by m3 compile. Do not edit.",
    `import { serveEmbeddedApp } from ${path(params.host)};`,
    `import manifest from ${path(join(params.outDir, "manifest.json"))};`,
    ...params.files.map(([, file], i) => `import file${i} from ${path(file)} with { type: "file" };`),
    "",
    "serveEmbeddedApp({",
    "  manifest,",
    `  rsc: () => import(${path(join(params.outDir, params.manifest.rscEntry))}),`,
    `  ssr: () => import(${path(join(params.outDir, params.manifest.ssrEntry))}),`,
    "  files: {",
    ...params.files.map(([key], i) => `    ${js(key)}: file${i},`),
    "  },",
    `  port: Number(process.env.PORT ?? ${params.port}),`,
    "  hostname: process.env.HOSTNAME,",
    "}).then(",
    "  server => console.log(`m3: ${server.url}`),",
    "  (error: unknown) => {",
    "    console.error(error);",
    "    process.exit(1);",
    "  },",
    ");",
    "",
  ].join("\n");
}

/** The package name of the project without its scope, or the directory name. */
export function projectName(root: string): string {
  const manifest = join(root, "package.json");
  const name = existsSync(manifest)
    ? (JSON.parse(readFileSync(manifest, "utf8")) as { name?: string }).name
    : undefined;
  return (name ?? basename(root)).replace(/^@[^/]+\//, "");
}

export interface CompileAppRouterOptions {
  project: AppProject;
  outDir?: string;
  outfile?: string;
  /** `Bun.build` compile target (`bun-linux-x64-musl`, ...); default: the host. */
  target?: string;
  /** Build first (default true); false compiles the existing build. */
  build?: boolean;
  prerender?: boolean;
  /** Where the generated entry is written (default `<root>/.m3`). */
  cacheDir?: string;
}

export interface CompileAppRouterReport {
  outfile: string;
  bytes: number;
  files: number;
  target: string;
  entryFile: string;
  ms: number;
}

/** Compile an App Router project into one executable. */
export async function compileAppRouter(options: CompileAppRouterOptions): Promise<CompileAppRouterReport> {
  const started = performance.now();
  const { project } = options;
  const outDir = options.outDir ?? project.outDir;
  if (options.build !== false) await buildAppProject(project, { outDir, prerender: options.prerender });
  if (!existsSync(join(outDir, "manifest.json"))) throw new Error(`m3 compile: no build in ${outDir} (run m3 build)`);
  const manifest = (await Bun.file(join(outDir, "manifest.json")).json()) as AppManifest;
  const files = await embeddedFiles(outDir);
  const entryFile = join(options.cacheDir ?? join(project.root, ".m3"), "compile-entry.ts");
  await mkdir(dirname(entryFile), { recursive: true });
  await Bun.write(
    entryFile,
    renderExecutableEntry({ host: HOST, outDir, manifest, files, port: project.port ?? 3000 }),
  );

  const windows = options.target ? options.target.includes("windows") : process.platform === "win32";
  const name = projectName(project.root);
  const outfile = resolve(options.outfile ?? join(project.root, "bin", name + (windows ? ".exe" : "")));
  await mkdir(dirname(outfile), { recursive: true });
  const result = await Bun.build({
    entrypoints: [entryFile],
    compile: {
      outfile,
      ...(options.target ? { target: options.target as Bun.Build.CompileTarget } : {}),
      autoloadDotenv: false,
      autoloadBunfig: false,
    },
    minify: true,
    sourcemap: "none",
    define: { "process.env.NODE_ENV": js("production") },
    throw: false,
  });
  if (!result.success) throw new Error(`m3 compile: failed\n${result.logs.map(String).join("\n")}`);
  if (!existsSync(outfile)) throw new Error(`m3 compile: Bun.build reported success but wrote no ${outfile}`);
  return {
    outfile,
    bytes: Bun.file(outfile).size,
    files: files.length,
    target: options.target ?? `host (${process.platform}-${process.arch})`,
    entryFile,
    ms: Math.round(performance.now() - started),
  };
}

/** Source of `server.js` in the Docker context: serves `./dist` next to it. Pure, so tests read it. */
export function renderDockerServer(host: string, port: number): string {
  return [
    "// Generated by m3 docker. Do not edit.",
    `import { join } from "node:path";`,
    `import { serveApp } from ${js(toPosix(host))};`,
    "",
    "const server = await serveApp({",
    `  outDir: join(import.meta.dir, "dist"),`,
    `  port: Number(process.env.PORT ?? ${port}),`,
    `  hostname: process.env.HOSTNAME ?? "0.0.0.0",`,
    "});",
    "console.log(`m3: ${server.url}`);",
    "",
  ].join("\n");
}

/** The Dockerfile of `m3 docker`. Pure, so tests read it. */
export function renderDockerfile(options: { base: string; port: number }): string {
  return [
    "# Generated by m3 docker. Do not edit.",
    "# The base is the Aphrody Alpine runtime (Alpine 3.24, the Bun fork on musl, user agent uid 1000).",
    `ARG BASE=${options.base}`,
    "FROM ${BASE}",
    "WORKDIR /app",
    "COPY --chown=agent:agent server.js ./",
    "COPY --chown=agent:agent dist ./dist",
    `ENV NODE_ENV=production PORT=${options.port} HOSTNAME=0.0.0.0`,
    `EXPOSE ${options.port}`,
    `CMD ["bun", "server.js"]`,
    "",
  ].join("\n");
}

export interface DockerAppRouterOptions {
  project: AppProject;
  /** Docker build context (default `<root>/.m3/docker`). */
  contextDir?: string;
  base?: string;
  prerender?: boolean;
}

export interface DockerAppRouterReport {
  contextDir: string;
  /** Files written at the top of the context. */
  files: string[];
  ms: number;
}

/** Write the Docker build context of an App Router project. */
export async function dockerAppRouter(options: DockerAppRouterOptions): Promise<DockerAppRouterReport> {
  const started = performance.now();
  const { project } = options;
  const contextDir = resolve(options.contextDir ?? join(project.root, ".m3", "docker"));
  const port = project.port ?? 3000;
  rmSync(contextDir, { recursive: true, force: true });
  const outDir = join(contextDir, "dist");
  await buildAppProject(project, { outDir, prerender: options.prerender });

  const entryFile = join(contextDir, "server-entry.ts");
  await Bun.write(entryFile, renderDockerServer(HOST, port));
  const result = await Bun.build({
    entrypoints: [entryFile],
    outdir: contextDir,
    target: "bun",
    format: "esm",
    naming: "server.js",
    minify: true,
    define: { "process.env.NODE_ENV": js("production") },
    throw: false,
  });
  rmSync(entryFile, { force: true });
  if (!result.success) throw new Error(`m3 docker: server bundle failed\n${result.logs.map(String).join("\n")}`);
  await Bun.write(join(contextDir, "Dockerfile"), renderDockerfile({ base: options.base ?? DOCKER_BASE_IMAGE, port }));
  return {
    contextDir,
    files: ["Dockerfile", "server.js", toPosix(relative(contextDir, outDir))],
    ms: Math.round(performance.now() - started),
  };
}
