// SPDX-License-Identifier: Apache-2.0
// Request handler and Bun.serve host of a built app: client assets under /_m3/, `public/` files,
// prerendered pages, then the rsc layer (middleware, routes, actions) and HTML through the ssr layer.
// The build comes from a directory (`loadApp`) or from files embedded in an executable (`m3 compile`).
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import type { AppManifest } from "./build";
import type { HandleOptions, HandleResult } from "./runtime/rsc";
import { aliases, loaders, modules } from "./runtime/registry";
import { ACTION_HEADER, ASSET_PREFIX, RSC_CONTENT_TYPE, RSC_HEADER } from "./runtime/shared";

interface RscModule {
  handle(request: Request, options?: HandleOptions): Promise<HandleResult>;
  setStylesheets(urls: string[]): void;
  prerenderPaths(): Promise<string[]>;
}

interface SsrModule {
  renderHtml(
    rsc: ReadableStream<Uint8Array>,
    options: {
      bootstrap: string;
      bootstrapScriptContent?: string;
      formState?: unknown;
      nonce?: string;
      onError?: (error: unknown) => void;
    },
  ): Promise<ReadableStream<Uint8Array>>;
  setClientBundles(bundles: Record<string, string[]>): void;
}

export interface AppHandler {
  manifest: AppManifest;
  /** The build directory, or `embedded` for an executable. */
  outDir: string;
  fetch(request: Request): Promise<Response>;
  /** Render one request without the HTTP layer details (used by prerendering). */
  render(
    request: Request,
    options?: HandleOptions,
  ): Promise<{ response: Response; dynamic: boolean; rsc?: Uint8Array }>;
  /** URL paths that can be prerendered. */
  prerenderPaths(): Promise<string[]>;
}

export interface LoadAppOptions {
  /** Inline script run before the browser runtime (development flags). */
  bootstrapScript?: string;
  /** Custom HTMLRewriter transforms for the streamed HTML document. */
  rewriter?: (rewriter: HTMLRewriter) => HTMLRewriter;
}

/** Where the files and server layers of a build come from. */
export interface AppSource {
  manifest: AppManifest;
  /** The build directory, or `embedded`. */
  location: string;
  /** The build file at `path` (posix, relative to the build directory, without `.` or `..` segments). */
  file(path: string): Promise<Blob | undefined>;
  rsc(): Promise<unknown>;
  ssr(): Promise<unknown>;
}

/** A build directory written by `buildApp`. */
export async function directorySource(outDir: string): Promise<AppSource> {
  const manifest = (await Bun.file(join(outDir, "manifest.json")).json()) as AppManifest;
  return {
    manifest,
    location: outDir,
    async file(path) {
      const file = Bun.file(join(outDir, path));
      return (await file.exists()) ? file : undefined;
    },
    rsc: () => import(pathToFileURL(join(outDir, manifest.rscEntry)).href),
    ssr: () => import(pathToFileURL(join(outDir, manifest.ssrEntry)).href),
  };
}

export interface EmbeddedBuild {
  manifest: AppManifest;
  /** Build file path (relative to the build directory) to the path of the embedded file. */
  files: Record<string, string>;
  /** Imports of the server layers, run after the module registry is reset (a static import would register first). */
  rsc(): Promise<unknown>;
  ssr(): Promise<unknown>;
}

/** A build linked into an executable: the entry generated by `m3 compile` imports the server layers. */
export function embeddedSource(build: EmbeddedBuild): AppSource {
  return {
    manifest: build.manifest,
    location: "embedded",
    async file(path) {
      const embedded = Object.hasOwn(build.files, path) ? build.files[path] : undefined;
      return embedded === undefined ? undefined : Bun.file(embedded);
    },
    rsc: build.rsc,
    ssr: build.ssr,
  };
}

const g = globalThis as typeof globalThis & { __m3_client_bundles?: (id: string) => string[] };

/** `path` when it is a plain relative posix path, else `undefined` (traversal, backslashes, empty segments). */
export function relativeFile(path: string): string | undefined {
  if (path.includes("\\") || path.includes("\0")) return undefined;
  const parts = path.split("/");
  return parts.every(part => part !== "" && part !== "." && part !== "..") ? path : undefined;
}

const decodePath = (pathname: string) => {
  try {
    return decodeURIComponent(pathname);
  } catch {
    return undefined;
  }
};

/** Load a build from `outDir` (the result of `buildApp`). */
export async function loadApp(outDir: string, options: LoadAppOptions = {}): Promise<AppHandler> {
  return loadAppSource(await directorySource(outDir), options);
}

/** Load a build from a source (a directory or an executable). */
export async function loadAppSource(source: AppSource, options: LoadAppOptions = {}): Promise<AppHandler> {
  const { manifest } = source;
  // A new build replaces the previous one in this process (development rebuilds).
  modules.clear();
  loaders.clear();
  aliases.clear();
  g.__m3_client_bundles = id => manifest.clientModules[id] ?? [];
  const ssr = (await source.ssr()) as SsrModule & { registerSsr?: () => void };
  ssr.registerSsr?.();
  ssr.setClientBundles(manifest.clientModules);
  const rsc = (await source.rsc()) as RscModule & { registerRsc?: () => void };
  rsc.registerRsc?.();
  rsc.setStylesheets(manifest.css.map(file => ASSET_PREFIX + file));
  const bootstrap = ASSET_PREFIX + manifest.bootstrap;
  const prerendered = new Map<string, { html: string; rsc: string }>();
  const prerenderIndex = manifest.middleware ? undefined : await source.file("prerender/index.json");
  if (prerenderIndex)
    for (const [path, files] of Object.entries(
      (await prerenderIndex.json()) as Record<string, { html: string; rsc: string }>,
    ))
      prerendered.set(path, files);

  const html = async (result: Extract<HandleResult, { kind: "rsc" }>, method: string): Promise<Response> => {
    const [watch, forHtml] = result.stream.tee();
    const finished = watch.pipeTo(new WritableStream()).catch(() => {});
    await Promise.race([result.store.shell.promise, finished]);
    const headers = new Headers(result.headers);
    if (result.store.redirect) {
      void forHtml.cancel();
      headers.set("location", result.store.redirect.url);
      return new Response(null, { status: result.store.redirect.status, headers });
    }
    headers.set("content-type", "text/html; charset=utf-8");
    let body: ReadableStream<Uint8Array>;
    try {
      body = await ssr.renderHtml(forHtml, {
        bootstrap,
        bootstrapScriptContent: options.bootstrapScript,
        formState: result.formState,
      });
    } catch (error) {
      // The shell failed (an error outside every Suspense boundary).
      console.error(error);
      const message = options.bootstrapScript && error instanceof Error ? (error.stack ?? error.message) : "";
      return new Response(
        `<!DOCTYPE html><title>500</title><h1>Internal Server Error</h1><pre>${Bun.escapeHTML(message)}</pre>`,
        {
          status: 500,
          headers,
        },
      );
    }
    const response = new Response(method === "HEAD" ? null : body, { status: result.store.status ?? 200, headers });
    if (options.rewriter && method !== "HEAD") {
      return options.rewriter(new HTMLRewriter()).transform(response);
    }
    return response;
  };

  const render: AppHandler["render"] = async (request, handleOptions) => {
    const result = await rsc.handle(request, handleOptions);
    if (result.kind === "response") return { response: result.response, dynamic: true };
    const [forRsc, forHtml] = result.stream.tee();
    const rscBytes = new Uint8Array(await new Response(forRsc).arrayBuffer());
    const response = await html({ ...result, stream: forHtml }, request.method);
    return { response, dynamic: result.store.dynamic, rsc: rscBytes };
  };

  const fetch = async (request: Request): Promise<Response> => {
    const url = new URL(request.url);
    const pathname = decodePath(url.pathname);
    if (pathname === undefined) return new Response("Bad Request", { status: 400 });

    if (pathname.startsWith(ASSET_PREFIX)) {
      const path = relativeFile(pathname.slice(ASSET_PREFIX.length));
      const file = path && (await source.file(`client/${path}`));
      if (file) return new Response(file, { headers: { "cache-control": "public, max-age=31536000, immutable" } });
      return new Response("Not Found", { status: 404 });
    }
    const readsFile = request.method === "GET" || request.method === "HEAD";
    const staticPath = readsFile && Object.hasOwn(manifest.static, pathname) ? manifest.static[pathname] : undefined;
    const staticFile = staticPath && (await source.file(staticPath));
    if (staticFile) return new Response(staticFile);

    const isRsc = request.headers.get(RSC_HEADER) === "1" || request.headers.has(ACTION_HEADER);
    const page = readsFile ? prerendered.get(pathname) : undefined;
    const pageFile = page && (await source.file(`prerender/${isRsc ? page.rsc : page.html}`));
    if (pageFile) {
      return new Response(request.method === "HEAD" ? null : pageFile, {
        headers: { "content-type": isRsc ? RSC_CONTENT_TYPE : "text/html; charset=utf-8", vary: RSC_HEADER },
      });
    }

    const result = await rsc.handle(request);
    if (result.kind === "response") {
      if (request.method === "HEAD") return new Response(null, result.response);
      return result.response;
    }
    if (isRsc) {
      const headers = new Headers(result.headers);
      headers.set("content-type", RSC_CONTENT_TYPE);
      headers.set("vary", RSC_HEADER);
      return new Response(result.stream, { status: result.store.status ?? 200, headers });
    }
    return html(result, request.method);
  };

  return { manifest, outDir: source.location, fetch, render, prerenderPaths: () => rsc.prerenderPaths() };
}

export interface ServeAppOptions extends LoadAppOptions {
  outDir: string;
  port?: number;
  hostname?: string;
}

/** Serve a build with Bun.serve. */
export async function serveApp(options: ServeAppOptions): Promise<Bun.Server<undefined>> {
  return serveHandler(await loadApp(options.outDir, options), options);
}

export interface ServeEmbeddedAppOptions extends LoadAppOptions, EmbeddedBuild {
  port?: number;
  hostname?: string;
}

/** Serve a build embedded in an executable (the entry generated by `m3 compile`). */
export async function serveEmbeddedApp(options: ServeEmbeddedAppOptions): Promise<Bun.Server<undefined>> {
  return serveHandler(await loadAppSource(embeddedSource(options), options), options);
}

function serveHandler(app: AppHandler, options: { port?: number; hostname?: string }): Bun.Server<undefined> {
  return Bun.serve({
    port: options.port ?? Number(process.env.PORT ?? 3000),
    hostname: options.hostname ?? process.env.HOSTNAME,
    fetch: request => app.fetch(request),
    error(error) {
      console.error(error);
      return new Response("Internal Server Error", { status: 500 });
    },
  });
}
