// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** iphlpapi.dll!AddIPAddress */
  AddIPAddress(Address: number, IpMask: number, IfIndex: number, NTEContext: Win32Pointer, NTEInstance: Win32Pointer): number;
  /** iphlpapi.dll!CancelIPChangeNotify */
  CancelIPChangeNotify(notifyOverlapped: Win32Pointer): number;
  /** iphlpapi.dll!CancelIfTimestampConfigChange */
  CancelIfTimestampConfigChange(NotificationHandle: Win32Pointer): void;
  /** iphlpapi.dll!CancelMibChangeNotify2 */
  CancelMibChangeNotify2(NotificationHandle: Win32Pointer): number;
  /** iphlpapi.dll!CaptureInterfaceHardwareCrossTimestamp */
  CaptureInterfaceHardwareCrossTimestamp(InterfaceLuid: Win32Pointer, CrossTimestamp: Win32Pointer): number;
  /** iphlpapi.dll!ConvertCompartmentGuidToId */
  ConvertCompartmentGuidToId(CompartmentGuid: Win32Pointer, CompartmentId: Win32Pointer): number;
  /** iphlpapi.dll!ConvertCompartmentIdToGuid */
  ConvertCompartmentIdToGuid(CompartmentId: number, CompartmentGuid: Win32Pointer): number;
  /** iphlpapi.dll!ConvertInterfaceAliasToLuid */
  ConvertInterfaceAliasToLuid(InterfaceAlias: string | Win32Pointer, InterfaceLuid: Win32Pointer): number;
  /** iphlpapi.dll!ConvertInterfaceGuidToLuid */
  ConvertInterfaceGuidToLuid(InterfaceGuid: Win32Pointer, InterfaceLuid: Win32Pointer): number;
  /** iphlpapi.dll!ConvertInterfaceIndexToLuid */
  ConvertInterfaceIndexToLuid(InterfaceIndex: number, InterfaceLuid: Win32Pointer): number;
  /** iphlpapi.dll!ConvertInterfaceLuidToAlias */
  ConvertInterfaceLuidToAlias(InterfaceLuid: Win32Pointer, InterfaceAlias: string | Win32Pointer, Length: number | bigint): number;
  /** iphlpapi.dll!ConvertInterfaceLuidToGuid */
  ConvertInterfaceLuidToGuid(InterfaceLuid: Win32Pointer, InterfaceGuid: Win32Pointer): number;
  /** iphlpapi.dll!ConvertInterfaceLuidToIndex */
  ConvertInterfaceLuidToIndex(InterfaceLuid: Win32Pointer, InterfaceIndex: Win32Pointer): number;
  /** iphlpapi.dll!ConvertInterfaceLuidToNameA */
  ConvertInterfaceLuidToNameA(InterfaceLuid: Win32Pointer, InterfaceName: string | Win32Pointer, Length: number | bigint): number;
  /** iphlpapi.dll!ConvertInterfaceLuidToNameW */
  ConvertInterfaceLuidToNameW(InterfaceLuid: Win32Pointer, InterfaceName: string | Win32Pointer, Length: number | bigint): number;
  /** iphlpapi.dll!ConvertInterfaceLuidToNameW */
  ConvertInterfaceLuidToName(InterfaceLuid: Win32Pointer, InterfaceName: string | Win32Pointer, Length: number | bigint): number;
  /** iphlpapi.dll!ConvertInterfaceNameToLuidA */
  ConvertInterfaceNameToLuidA(InterfaceName: string | Win32Pointer, InterfaceLuid: Win32Pointer): number;
  /** iphlpapi.dll!ConvertInterfaceNameToLuidW */
  ConvertInterfaceNameToLuidW(InterfaceName: string | Win32Pointer, InterfaceLuid: Win32Pointer): number;
  /** iphlpapi.dll!ConvertInterfaceNameToLuidW */
  ConvertInterfaceNameToLuid(InterfaceName: string | Win32Pointer, InterfaceLuid: Win32Pointer): number;
  /** iphlpapi.dll!ConvertIpv4MaskToLength */
  ConvertIpv4MaskToLength(Mask: number, MaskLength: Win32Pointer): number;
  /** iphlpapi.dll!ConvertLengthToIpv4Mask */
  ConvertLengthToIpv4Mask(MaskLength: number, Mask: Win32Pointer): number;
  /** iphlpapi.dll!CreateAnycastIpAddressEntry */
  CreateAnycastIpAddressEntry(Row: Win32Pointer): number;
  /** iphlpapi.dll!CreateFlVirtualInterface */
  CreateFlVirtualInterface(Row: Win32Pointer): number;
  /** iphlpapi.dll!CreateIpForwardEntry */
  CreateIpForwardEntry(pRoute: Win32Pointer): number;
  /** iphlpapi.dll!CreateIpForwardEntry2 */
  CreateIpForwardEntry2(Row: Win32Pointer): number;
  /** iphlpapi.dll!CreateIpNetEntry */
  CreateIpNetEntry(pArpEntry: Win32Pointer): number;
  /** iphlpapi.dll!CreateIpNetEntry2 */
  CreateIpNetEntry2(Row: Win32Pointer): number;
  /** iphlpapi.dll!CreatePersistentTcpPortReservation */
  CreatePersistentTcpPortReservation(StartPort: number, NumberOfPorts: number, Token: Win32Pointer): number;
  /** iphlpapi.dll!CreatePersistentUdpPortReservation */
  CreatePersistentUdpPortReservation(StartPort: number, NumberOfPorts: number, Token: Win32Pointer): number;
  /** iphlpapi.dll!CreateProxyArpEntry */
  CreateProxyArpEntry(dwAddress: number, dwMask: number, dwIfIndex: number): number;
  /** iphlpapi.dll!CreateSortedAddressPairs */
  CreateSortedAddressPairs(SourceAddressList: Win32Pointer, SourceAddressCount: number, DestinationAddressList: Win32Pointer, DestinationAddressCount: number, AddressSortOptions: number, SortedAddressPairList: Win32Pointer, SortedAddressPairCount: Win32Pointer): number;
  /** iphlpapi.dll!CreateUnicastIpAddressEntry */
  CreateUnicastIpAddressEntry(Row: Win32Pointer): number;
  /** iphlpapi.dll!DeleteAnycastIpAddressEntry */
  DeleteAnycastIpAddressEntry(Row: Win32Pointer): number;
  /** iphlpapi.dll!DeleteFlVirtualInterface */
  DeleteFlVirtualInterface(Row: Win32Pointer): number;
  /** iphlpapi.dll!DeleteIPAddress */
  DeleteIPAddress(NTEContext: number): number;
  /** iphlpapi.dll!DeleteIpForwardEntry */
  DeleteIpForwardEntry(pRoute: Win32Pointer): number;
  /** iphlpapi.dll!DeleteIpForwardEntry2 */
  DeleteIpForwardEntry2(Row: Win32Pointer): number;
  /** iphlpapi.dll!DeleteIpNetEntry */
  DeleteIpNetEntry(pArpEntry: Win32Pointer): number;
  /** iphlpapi.dll!DeleteIpNetEntry2 */
  DeleteIpNetEntry2(Row: Win32Pointer): number;
  /** iphlpapi.dll!DeletePersistentTcpPortReservation */
  DeletePersistentTcpPortReservation(StartPort: number, NumberOfPorts: number): number;
  /** iphlpapi.dll!DeletePersistentUdpPortReservation */
  DeletePersistentUdpPortReservation(StartPort: number, NumberOfPorts: number): number;
  /** iphlpapi.dll!DeleteProxyArpEntry */
  DeleteProxyArpEntry(dwAddress: number, dwMask: number, dwIfIndex: number): number;
  /** iphlpapi.dll!DeleteUnicastIpAddressEntry */
  DeleteUnicastIpAddressEntry(Row: Win32Pointer): number;
  /** iphlpapi.dll!DisableMediaSense */
  DisableMediaSense(pHandle: Win32Pointer, pOverLapped: Win32Pointer): number;
  /** iphlpapi.dll!EnableRouter */
  EnableRouter(pHandle: Win32Pointer, pOverlapped: Win32Pointer): number;
  /** iphlpapi.dll!FlushIpNetTable */
  FlushIpNetTable(dwIfIndex: number): number;
  /** iphlpapi.dll!FlushIpNetTable2 */
  FlushIpNetTable2(Family: number, InterfaceIndex: number): number;
  /** iphlpapi.dll!FlushIpPathTable */
  FlushIpPathTable(Family: number): number;
  /** iphlpapi.dll!FreeDnsSettings */
  FreeDnsSettings(Settings: Win32Pointer): void;
  /** iphlpapi.dll!FreeInterfaceDnsSettings */
  FreeInterfaceDnsSettings(Settings: Win32Pointer): void;
  /** iphlpapi.dll!FreeMibTable */
  FreeMibTable(Memory: Win32Pointer): void;
  /** iphlpapi.dll!GetAdapterIndex */
  GetAdapterIndex(AdapterName: string | Win32Pointer, IfIndex: Win32Pointer): number;
  /** iphlpapi.dll!GetAdapterOrderMap */
  GetAdapterOrderMap(): number | null;
  /** iphlpapi.dll!GetAdaptersAddresses */
  GetAdaptersAddresses(Family: number, Flags: number, Reserved: Win32Pointer, AdapterAddresses: Win32Pointer, SizePointer: Win32Pointer): number;
  /** iphlpapi.dll!GetAdaptersInfo */
  GetAdaptersInfo(AdapterInfo: Win32Pointer, SizePointer: Win32Pointer): number;
  /** iphlpapi.dll!GetAnycastIpAddressEntry */
  GetAnycastIpAddressEntry(Row: Win32Pointer): number;
  /** iphlpapi.dll!GetAnycastIpAddressTable */
  GetAnycastIpAddressTable(Family: number, Table: Win32Pointer): number;
  /** iphlpapi.dll!GetBestInterface */
  GetBestInterface(dwDestAddr: number, pdwBestIfIndex: Win32Pointer): number;
  /** iphlpapi.dll!GetBestInterfaceEx */
  GetBestInterfaceEx(pDestAddr: Win32Pointer, pdwBestIfIndex: Win32Pointer): number;
  /** iphlpapi.dll!GetBestRoute */
  GetBestRoute(dwDestAddr: number, dwSourceAddr: number, pBestRoute: Win32Pointer): number;
  /** iphlpapi.dll!GetBestRoute2 */
  GetBestRoute2(InterfaceLuid: Win32Pointer, InterfaceIndex: number, SourceAddress: Win32Pointer, DestinationAddress: Win32Pointer, AddressSortOptions: number, BestRoute: Win32Pointer, BestSourceAddress: Win32Pointer): number;
  /** iphlpapi.dll!GetCurrentThreadCompartmentId */
  GetCurrentThreadCompartmentId(): number;
  /** iphlpapi.dll!GetCurrentThreadCompartmentScope */
  GetCurrentThreadCompartmentScope(CompartmentScope: Win32Pointer, CompartmentId: Win32Pointer): void;
  /** iphlpapi.dll!GetDefaultCompartmentId */
  GetDefaultCompartmentId(): number;
  /** iphlpapi.dll!GetDnsSettings */
  GetDnsSettings(Settings: Win32Pointer): number;
  /** iphlpapi.dll!GetExtendedTcpTable */
  GetExtendedTcpTable(pTcpTable: Win32Pointer, pdwSize: Win32Pointer, bOrder: number, ulAf: number, TableClass: number, Reserved: number): number;
  /** iphlpapi.dll!GetExtendedUdpTable */
  GetExtendedUdpTable(pUdpTable: Win32Pointer, pdwSize: Win32Pointer, bOrder: number, ulAf: number, TableClass: number, Reserved: number): number;
  /** iphlpapi.dll!GetFlVirtualInterface */
  GetFlVirtualInterface(Row: Win32Pointer): number;
  /** iphlpapi.dll!GetFlVirtualInterfaceTable */
  GetFlVirtualInterfaceTable(Family: number, Table: Win32Pointer): number;
  /** iphlpapi.dll!GetFriendlyIfIndex */
  GetFriendlyIfIndex(IfIndex: number): number;
  /** iphlpapi.dll!GetIcmpStatistics */
  GetIcmpStatistics(Statistics: Win32Pointer): number;
  /** iphlpapi.dll!GetIcmpStatisticsEx */
  GetIcmpStatisticsEx(Statistics: Win32Pointer, Family: number): number;
  /** iphlpapi.dll!GetIfEntry */
  GetIfEntry(pIfRow: Win32Pointer): number;
  /** iphlpapi.dll!GetIfEntry2 */
  GetIfEntry2(Row: Win32Pointer): number;
  /** iphlpapi.dll!GetIfEntry2Ex */
  GetIfEntry2Ex(Level: number, Row: Win32Pointer): number;
  /** iphlpapi.dll!GetIfStackTable */
  GetIfStackTable(Table: Win32Pointer): number;
  /** iphlpapi.dll!GetIfTable */
  GetIfTable(pIfTable: Win32Pointer, pdwSize: Win32Pointer, bOrder: number): number;
  /** iphlpapi.dll!GetIfTable2 */
  GetIfTable2(Table: Win32Pointer): number;
  /** iphlpapi.dll!GetIfTable2Ex */
  GetIfTable2Ex(Level: number, Table: Win32Pointer): number;
  /** iphlpapi.dll!GetInterfaceActiveTimestampCapabilities */
  GetInterfaceActiveTimestampCapabilities(InterfaceLuid: Win32Pointer, TimestampCapabilites: Win32Pointer): number;
  /** iphlpapi.dll!GetInterfaceCurrentTimestampCapabilities */
  GetInterfaceCurrentTimestampCapabilities(InterfaceLuid: Win32Pointer, TimestampCapabilites: Win32Pointer): number;
  /** iphlpapi.dll!GetInterfaceDnsSettings */
  GetInterfaceDnsSettings(Interface: Win32StructInit, Settings: Win32Pointer): number;
  /** iphlpapi.dll!GetInterfaceHardwareTimestampCapabilities */
  GetInterfaceHardwareTimestampCapabilities(InterfaceLuid: Win32Pointer, TimestampCapabilites: Win32Pointer): number;
  /** iphlpapi.dll!GetInterfaceInfo */
  GetInterfaceInfo(pIfTable: Win32Pointer, dwOutBufLen: Win32Pointer): number;
  /** iphlpapi.dll!GetInterfaceSupportedTimestampCapabilities */
  GetInterfaceSupportedTimestampCapabilities(InterfaceLuid: Win32Pointer, TimestampCapabilites: Win32Pointer): number;
  /** iphlpapi.dll!GetInvertedIfStackTable */
  GetInvertedIfStackTable(Table: Win32Pointer): number;
  /** iphlpapi.dll!GetIpAddrTable */
  GetIpAddrTable(pIpAddrTable: Win32Pointer, pdwSize: Win32Pointer, bOrder: number): number;
  /** iphlpapi.dll!GetIpErrorString */
  GetIpErrorString(ErrorCode: number, Buffer: string | Win32Pointer, Size: Win32Pointer): number;
  /** iphlpapi.dll!GetIpForwardEntry2 */
  GetIpForwardEntry2(Row: Win32Pointer): number;
  /** iphlpapi.dll!GetIpForwardTable */
  GetIpForwardTable(pIpForwardTable: Win32Pointer, pdwSize: Win32Pointer, bOrder: number): number;
  /** iphlpapi.dll!GetIpForwardTable2 */
  GetIpForwardTable2(Family: number, Table: Win32Pointer): number;
  /** iphlpapi.dll!GetIpInterfaceEntry */
  GetIpInterfaceEntry(Row: Win32Pointer): number;
  /** iphlpapi.dll!GetIpInterfaceTable */
  GetIpInterfaceTable(Family: number, Table: Win32Pointer): number;
  /** iphlpapi.dll!GetIpNetEntry2 */
  GetIpNetEntry2(Row: Win32Pointer): number;
  /** iphlpapi.dll!GetIpNetTable */
  GetIpNetTable(IpNetTable: Win32Pointer, SizePointer: Win32Pointer, Order: number): number;
  /** iphlpapi.dll!GetIpNetTable2 */
  GetIpNetTable2(Family: number, Table: Win32Pointer): number;
  /** iphlpapi.dll!GetIpNetworkConnectionBandwidthEstimates */
  GetIpNetworkConnectionBandwidthEstimates(InterfaceIndex: number, AddressFamily: number, BandwidthEstimates: Win32Pointer): number;
  /** iphlpapi.dll!GetIpPathEntry */
  GetIpPathEntry(Row: Win32Pointer): number;
  /** iphlpapi.dll!GetIpPathTable */
  GetIpPathTable(Family: number, Table: Win32Pointer): number;
  /** iphlpapi.dll!GetIpStatistics */
  GetIpStatistics(Statistics: Win32Pointer): number;
  /** iphlpapi.dll!GetIpStatisticsEx */
  GetIpStatisticsEx(Statistics: Win32Pointer, Family: number): number;
  /** iphlpapi.dll!GetJobCompartmentId */
  GetJobCompartmentId(JobHandle: Win32Pointer): number;
  /** iphlpapi.dll!GetMulticastIpAddressEntry */
  GetMulticastIpAddressEntry(Row: Win32Pointer): number;
  /** iphlpapi.dll!GetMulticastIpAddressTable */
  GetMulticastIpAddressTable(Family: number, Table: Win32Pointer): number;
  /** iphlpapi.dll!GetNetworkConnectivityHint */
  GetNetworkConnectivityHint(ConnectivityHint: Win32Pointer): number;
  /** iphlpapi.dll!GetNetworkConnectivityHintForInterface */
  GetNetworkConnectivityHintForInterface(InterfaceIndex: number, ConnectivityHint: Win32Pointer): number;
  /** iphlpapi.dll!GetNetworkInformation */
  GetNetworkInformation(NetworkGuid: Win32Pointer, CompartmentId: Win32Pointer, SiteId: Win32Pointer, NetworkName: string | Win32Pointer, Length: number): number;
  /** iphlpapi.dll!GetNetworkParams */
  GetNetworkParams(pFixedInfo: Win32Pointer, pOutBufLen: Win32Pointer): number;
  /** iphlpapi.dll!GetNumberOfInterfaces */
  GetNumberOfInterfaces(pdwNumIf: Win32Pointer): number;
  /** iphlpapi.dll!GetOwnerModuleFromPidAndInfo */
  GetOwnerModuleFromPidAndInfo(ulPid: number, pInfo: Win32Pointer, Class: number, pBuffer: Win32Pointer, pdwSize: Win32Pointer): number;
  /** iphlpapi.dll!GetOwnerModuleFromTcp6Entry */
  GetOwnerModuleFromTcp6Entry(pTcpEntry: Win32Pointer, Class: number, pBuffer: Win32Pointer, pdwSize: Win32Pointer): number;
  /** iphlpapi.dll!GetOwnerModuleFromTcpEntry */
  GetOwnerModuleFromTcpEntry(pTcpEntry: Win32Pointer, Class: number, pBuffer: Win32Pointer, pdwSize: Win32Pointer): number;
  /** iphlpapi.dll!GetOwnerModuleFromUdp6Entry */
  GetOwnerModuleFromUdp6Entry(pUdpEntry: Win32Pointer, Class: number, pBuffer: Win32Pointer, pdwSize: Win32Pointer): number;
  /** iphlpapi.dll!GetOwnerModuleFromUdpEntry */
  GetOwnerModuleFromUdpEntry(pUdpEntry: Win32Pointer, Class: number, pBuffer: Win32Pointer, pdwSize: Win32Pointer): number;
  /** iphlpapi.dll!GetPerAdapterInfo */
  GetPerAdapterInfo(IfIndex: number, pPerAdapterInfo: Win32Pointer, pOutBufLen: Win32Pointer): number;
  /** iphlpapi.dll!GetPerTcp6ConnectionEStats */
  GetPerTcp6ConnectionEStats(Row: Win32Pointer, EstatsType: number, Rw: Win32Pointer, RwVersion: number, RwSize: number, Ros: Win32Pointer, RosVersion: number, RosSize: number, Rod: Win32Pointer, RodVersion: number, RodSize: number): number;
  /** iphlpapi.dll!GetPerTcpConnectionEStats */
  GetPerTcpConnectionEStats(Row: Win32Pointer, EstatsType: number, Rw: Win32Pointer, RwVersion: number, RwSize: number, Ros: Win32Pointer, RosVersion: number, RosSize: number, Rod: Win32Pointer, RodVersion: number, RodSize: number): number;
  /** iphlpapi.dll!GetRTTAndHopCount */
  GetRTTAndHopCount(DestIpAddress: number, HopCount: Win32Pointer, MaxHops: number, RTT: Win32Pointer): number;
  /** iphlpapi.dll!GetSessionCompartmentId */
  GetSessionCompartmentId(SessionId: number): number;
  /** iphlpapi.dll!GetTcp6Table */
  GetTcp6Table(TcpTable: Win32Pointer, SizePointer: Win32Pointer, Order: number): number;
  /** iphlpapi.dll!GetTcp6Table2 */
  GetTcp6Table2(TcpTable: Win32Pointer, SizePointer: Win32Pointer, Order: number): number;
  /** iphlpapi.dll!GetTcpStatistics */
  GetTcpStatistics(Statistics: Win32Pointer): number;
  /** iphlpapi.dll!GetTcpStatisticsEx */
  GetTcpStatisticsEx(Statistics: Win32Pointer, Family: number): number;
  /** iphlpapi.dll!GetTcpStatisticsEx2 */
  GetTcpStatisticsEx2(Statistics: Win32Pointer, Family: number): number;
  /** iphlpapi.dll!GetTcpTable */
  GetTcpTable(TcpTable: Win32Pointer, SizePointer: Win32Pointer, Order: number): number;
  /** iphlpapi.dll!GetTcpTable2 */
  GetTcpTable2(TcpTable: Win32Pointer, SizePointer: Win32Pointer, Order: number): number;
  /** iphlpapi.dll!GetTeredoPort */
  GetTeredoPort(Port: Win32Pointer): number;
  /** iphlpapi.dll!GetUdp6Table */
  GetUdp6Table(Udp6Table: Win32Pointer, SizePointer: Win32Pointer, Order: number): number;
  /** iphlpapi.dll!GetUdpStatistics */
  GetUdpStatistics(Stats: Win32Pointer): number;
  /** iphlpapi.dll!GetUdpStatisticsEx */
  GetUdpStatisticsEx(Statistics: Win32Pointer, Family: number): number;
  /** iphlpapi.dll!GetUdpStatisticsEx2 */
  GetUdpStatisticsEx2(Statistics: Win32Pointer, Family: number): number;
  /** iphlpapi.dll!GetUdpTable */
  GetUdpTable(UdpTable: Win32Pointer, SizePointer: Win32Pointer, Order: number): number;
  /** iphlpapi.dll!GetUniDirectionalAdapterInfo */
  GetUniDirectionalAdapterInfo(pIPIfInfo: Win32Pointer, dwOutBufLen: Win32Pointer): number;
  /** iphlpapi.dll!GetUnicastIpAddressEntry */
  GetUnicastIpAddressEntry(Row: Win32Pointer): number;
  /** iphlpapi.dll!GetUnicastIpAddressTable */
  GetUnicastIpAddressTable(Family: number, Table: Win32Pointer): number;
  /** iphlpapi.dll!Icmp6CreateFile */
  Icmp6CreateFile(): number | null;
  /** iphlpapi.dll!Icmp6ParseReplies */
  Icmp6ParseReplies(ReplyBuffer: Win32Pointer, ReplySize: number): number;
  /** iphlpapi.dll!Icmp6SendEcho2 */
  Icmp6SendEcho2(IcmpHandle: Win32Pointer, Event: Win32Pointer, ApcRoutine: Win32Callback, ApcContext: Win32Pointer, SourceAddress: Win32Pointer, DestinationAddress: Win32Pointer, RequestData: Win32Pointer, RequestSize: number, RequestOptions: Win32Pointer, ReplyBuffer: Win32Pointer, ReplySize: number, Timeout: number): number;
  /** iphlpapi.dll!IcmpCloseHandle */
  IcmpCloseHandle(IcmpHandle: Win32Pointer): number;
  /** iphlpapi.dll!IcmpCreateFile */
  IcmpCreateFile(): number | null;
  /** iphlpapi.dll!IcmpParseReplies */
  IcmpParseReplies(ReplyBuffer: Win32Pointer, ReplySize: number): number;
  /** iphlpapi.dll!IcmpSendEcho */
  IcmpSendEcho(IcmpHandle: Win32Pointer, DestinationAddress: number, RequestData: Win32Pointer, RequestSize: number, RequestOptions: Win32Pointer, ReplyBuffer: Win32Pointer, ReplySize: number, Timeout: number): number;
  /** iphlpapi.dll!IcmpSendEcho2 */
  IcmpSendEcho2(IcmpHandle: Win32Pointer, Event: Win32Pointer, ApcRoutine: Win32Callback, ApcContext: Win32Pointer, DestinationAddress: number, RequestData: Win32Pointer, RequestSize: number, RequestOptions: Win32Pointer, ReplyBuffer: Win32Pointer, ReplySize: number, Timeout: number): number;
  /** iphlpapi.dll!IcmpSendEcho2Ex */
  IcmpSendEcho2Ex(IcmpHandle: Win32Pointer, Event: Win32Pointer, ApcRoutine: Win32Callback, ApcContext: Win32Pointer, SourceAddress: number, DestinationAddress: number, RequestData: Win32Pointer, RequestSize: number, RequestOptions: Win32Pointer, ReplyBuffer: Win32Pointer, ReplySize: number, Timeout: number): number;
  /** iphlpapi.dll!InitializeFlVirtualInterfaceEntry */
  InitializeFlVirtualInterfaceEntry(Row: Win32Pointer): void;
  /** iphlpapi.dll!InitializeIpForwardEntry */
  InitializeIpForwardEntry(Row: Win32Pointer): void;
  /** iphlpapi.dll!InitializeIpInterfaceEntry */
  InitializeIpInterfaceEntry(Row: Win32Pointer): void;
  /** iphlpapi.dll!InitializeUnicastIpAddressEntry */
  InitializeUnicastIpAddressEntry(Row: Win32Pointer): void;
  /** iphlpapi.dll!IpReleaseAddress */
  IpReleaseAddress(AdapterInfo: Win32Pointer): number;
  /** iphlpapi.dll!IpRenewAddress */
  IpRenewAddress(AdapterInfo: Win32Pointer): number;
  /** iphlpapi.dll!LookupPersistentTcpPortReservation */
  LookupPersistentTcpPortReservation(StartPort: number, NumberOfPorts: number, Token: Win32Pointer): number;
  /** iphlpapi.dll!LookupPersistentUdpPortReservation */
  LookupPersistentUdpPortReservation(StartPort: number, NumberOfPorts: number, Token: Win32Pointer): number;
  /** iphlpapi.dll!NhpAllocateAndGetInterfaceInfoFromStack */
  NhpAllocateAndGetInterfaceInfoFromStack(ppTable: Win32Pointer, pdwCount: Win32Pointer, bOrder: number, hHeap: Win32Pointer, dwFlags: number): number;
  /** iphlpapi.dll!NotifyAddrChange */
  NotifyAddrChange(Handle: Win32Pointer, overlapped: Win32Pointer): number;
  /** iphlpapi.dll!NotifyIfTimestampConfigChange */
  NotifyIfTimestampConfigChange(CallerContext: Win32Pointer, Callback: Win32Callback, NotificationHandle: Win32Pointer): number;
  /** iphlpapi.dll!NotifyIpInterfaceChange */
  NotifyIpInterfaceChange(Family: number, Callback: Win32Callback, CallerContext: Win32Pointer, InitialNotification: number, NotificationHandle: Win32Pointer): number;
  /** iphlpapi.dll!NotifyNetworkConnectivityHintChange */
  NotifyNetworkConnectivityHintChange(Callback: Win32Callback, CallerContext: Win32Pointer, InitialNotification: number, NotificationHandle: Win32Pointer): number;
  /** iphlpapi.dll!NotifyRouteChange */
  NotifyRouteChange(Handle: Win32Pointer, overlapped: Win32Pointer): number;
  /** iphlpapi.dll!NotifyRouteChange2 */
  NotifyRouteChange2(AddressFamily: number, Callback: Win32Callback, CallerContext: Win32Pointer, InitialNotification: number, NotificationHandle: Win32Pointer): number;
  /** iphlpapi.dll!NotifyStableUnicastIpAddressTable */
  NotifyStableUnicastIpAddressTable(Family: number, Table: Win32Pointer, CallerCallback: Win32Callback, CallerContext: Win32Pointer, NotificationHandle: Win32Pointer): number;
  /** iphlpapi.dll!NotifyTeredoPortChange */
  NotifyTeredoPortChange(Callback: Win32Callback, CallerContext: Win32Pointer, InitialNotification: number, NotificationHandle: Win32Pointer): number;
  /** iphlpapi.dll!NotifyUnicastIpAddressChange */
  NotifyUnicastIpAddressChange(Family: number, Callback: Win32Callback, CallerContext: Win32Pointer, InitialNotification: number, NotificationHandle: Win32Pointer): number;
  /** iphlpapi.dll!ParseNetworkString */
  ParseNetworkString(NetworkString: string | Win32Pointer, Types: number, AddressInfo: Win32Pointer, PortNumber: Win32Pointer, PrefixLength: Win32Pointer): number;
  /** iphlpapi.dll!PfAddFiltersToInterface */
  PfAddFiltersToInterface(ih: Win32Pointer, cInFilters: number, pfiltIn: Win32Pointer, cOutFilters: number, pfiltOut: Win32Pointer, pfHandle: Win32Pointer): number;
  /** iphlpapi.dll!PfAddGlobalFilterToInterface */
  PfAddGlobalFilterToInterface(pInterface: Win32Pointer, gfFilter: number): number;
  /** iphlpapi.dll!PfBindInterfaceToIPAddress */
  PfBindInterfaceToIPAddress(pInterface: Win32Pointer, pfatType: number, IPAddress: Win32Pointer): number;
  /** iphlpapi.dll!PfBindInterfaceToIndex */
  PfBindInterfaceToIndex(pInterface: Win32Pointer, dwIndex: number, pfatLinkType: number, LinkIPAddress: Win32Pointer): number;
  /** iphlpapi.dll!PfCreateInterface */
  PfCreateInterface(dwName: number, inAction: number, outAction: number, bUseLog: number, bMustBeUnique: number, ppInterface: Win32Pointer): number;
  /** iphlpapi.dll!PfDeleteInterface */
  PfDeleteInterface(pInterface: Win32Pointer): number;
  /** iphlpapi.dll!PfDeleteLog */
  PfDeleteLog(): number;
  /** iphlpapi.dll!PfGetInterfaceStatistics */
  PfGetInterfaceStatistics(pInterface: Win32Pointer, ppfStats: Win32Pointer, pdwBufferSize: Win32Pointer, fResetCounters: number): number;
  /** iphlpapi.dll!PfMakeLog */
  PfMakeLog(hEvent: Win32Pointer): number;
  /** iphlpapi.dll!PfRebindFilters */
  PfRebindFilters(pInterface: Win32Pointer, pLateBindInfo: Win32Pointer): number;
  /** iphlpapi.dll!PfRemoveFilterHandles */
  PfRemoveFilterHandles(pInterface: Win32Pointer, cFilters: number, pvHandles: Win32Pointer): number;
  /** iphlpapi.dll!PfRemoveFiltersFromInterface */
  PfRemoveFiltersFromInterface(ih: Win32Pointer, cInFilters: number, pfiltIn: Win32Pointer, cOutFilters: number, pfiltOut: Win32Pointer): number;
  /** iphlpapi.dll!PfRemoveGlobalFilterFromInterface */
  PfRemoveGlobalFilterFromInterface(pInterface: Win32Pointer, gfFilter: number): number;
  /** iphlpapi.dll!PfSetLogBuffer */
  PfSetLogBuffer(pbBuffer: Win32Pointer, dwSize: number, dwThreshold: number, dwEntries: number, pdwLoggedEntries: Win32Pointer, pdwLostEntries: Win32Pointer, pdwSizeUsed: Win32Pointer): number;
  /** iphlpapi.dll!PfTestPacket */
  PfTestPacket(pInInterface: Win32Pointer, pOutInterface: Win32Pointer, cBytes: number, pbPacket: Win32Pointer, ppAction: Win32Pointer): number;
  /** iphlpapi.dll!PfUnBindInterface */
  PfUnBindInterface(pInterface: Win32Pointer): number;
  /** iphlpapi.dll!RegisterInterfaceTimestampConfigChange */
  RegisterInterfaceTimestampConfigChange(Callback: Win32Callback, CallerContext: Win32Pointer, NotificationHandle: Win32Pointer): number;
  /** iphlpapi.dll!ResolveIpNetEntry2 */
  ResolveIpNetEntry2(Row: Win32Pointer, SourceAddress: Win32Pointer): number;
  /** iphlpapi.dll!ResolveNeighbor */
  ResolveNeighbor(NetworkAddress: Win32Pointer, PhysicalAddress: Win32Pointer, PhysicalAddressLength: Win32Pointer): number;
  /** iphlpapi.dll!RestoreMediaSense */
  RestoreMediaSense(pOverlapped: Win32Pointer, lpdwEnableCount: Win32Pointer): number;
  /** iphlpapi.dll!SendARP */
  SendARP(DestIP: number, SrcIP: number, pMacAddr: Win32Pointer, PhyAddrLen: Win32Pointer): number;
  /** iphlpapi.dll!SetCurrentThreadCompartmentId */
  SetCurrentThreadCompartmentId(CompartmentId: number): number;
  /** iphlpapi.dll!SetCurrentThreadCompartmentScope */
  SetCurrentThreadCompartmentScope(CompartmentScope: number): number;
  /** iphlpapi.dll!SetDnsSettings */
  SetDnsSettings(Settings: Win32Pointer): number;
  /** iphlpapi.dll!SetFlVirtualInterface */
  SetFlVirtualInterface(Row: Win32Pointer): number;
  /** iphlpapi.dll!SetIfEntry */
  SetIfEntry(pIfRow: Win32Pointer): number;
  /** iphlpapi.dll!SetInterfaceDnsSettings */
  SetInterfaceDnsSettings(Interface: Win32StructInit, Settings: Win32Pointer): number;
  /** iphlpapi.dll!SetIpForwardEntry */
  SetIpForwardEntry(pRoute: Win32Pointer): number;
  /** iphlpapi.dll!SetIpForwardEntry2 */
  SetIpForwardEntry2(Route: Win32Pointer): number;
  /** iphlpapi.dll!SetIpInterfaceEntry */
  SetIpInterfaceEntry(Row: Win32Pointer): number;
  /** iphlpapi.dll!SetIpNetEntry */
  SetIpNetEntry(pArpEntry: Win32Pointer): number;
  /** iphlpapi.dll!SetIpNetEntry2 */
  SetIpNetEntry2(Row: Win32Pointer): number;
  /** iphlpapi.dll!SetIpStatistics */
  SetIpStatistics(pIpStats: Win32Pointer): number;
  /** iphlpapi.dll!SetIpStatisticsEx */
  SetIpStatisticsEx(Statistics: Win32Pointer, Family: number): number;
  /** iphlpapi.dll!SetIpTTL */
  SetIpTTL(nTTL: number): number;
  /** iphlpapi.dll!SetJobCompartmentId */
  SetJobCompartmentId(JobHandle: Win32Pointer, CompartmentId: number): number;
  /** iphlpapi.dll!SetNetworkInformation */
  SetNetworkInformation(NetworkGuid: Win32Pointer, CompartmentId: number, NetworkName: string | Win32Pointer): number;
  /** iphlpapi.dll!SetPerTcp6ConnectionEStats */
  SetPerTcp6ConnectionEStats(Row: Win32Pointer, EstatsType: number, Rw: Win32Pointer, RwVersion: number, RwSize: number, Offset: number): number;
  /** iphlpapi.dll!SetPerTcpConnectionEStats */
  SetPerTcpConnectionEStats(Row: Win32Pointer, EstatsType: number, Rw: Win32Pointer, RwVersion: number, RwSize: number, Offset: number): number;
  /** iphlpapi.dll!SetSessionCompartmentId */
  SetSessionCompartmentId(SessionId: number, CompartmentId: number): number;
  /** iphlpapi.dll!SetTcpEntry */
  SetTcpEntry(pTcpRow: Win32Pointer): number;
  /** iphlpapi.dll!SetUnicastIpAddressEntry */
  SetUnicastIpAddressEntry(Row: Win32Pointer): number;
  /** iphlpapi.dll!UnenableRouter */
  UnenableRouter(pOverlapped: Win32Pointer, lpdwEnableCount: Win32Pointer): number;
  /** iphlpapi.dll!UnregisterInterfaceTimestampConfigChange */
  UnregisterInterfaceTimestampConfigChange(NotificationHandle: Win32Pointer): void;
  /** iphlpapi.dll!if_indextoname */
  if_indextoname(InterfaceIndex: number, InterfaceName: string | Win32Pointer): number | null;
  /** iphlpapi.dll!if_nametoindex */
  if_nametoindex(InterfaceName: string | Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
