// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** ntdsapi.dll!DsAddSidHistoryA */
  DsAddSidHistoryA(hDS: Win32Pointer, Flags: number, SrcDomain: string | Win32Pointer, SrcPrincipal: string | Win32Pointer, SrcDomainController: string | Win32Pointer, SrcDomainCreds: Win32Pointer, DstDomain: string | Win32Pointer, DstPrincipal: string | Win32Pointer): number;
  /** ntdsapi.dll!DsAddSidHistoryW */
  DsAddSidHistoryW(hDS: Win32Pointer, Flags: number, SrcDomain: string | Win32Pointer, SrcPrincipal: string | Win32Pointer, SrcDomainController: string | Win32Pointer, SrcDomainCreds: Win32Pointer, DstDomain: string | Win32Pointer, DstPrincipal: string | Win32Pointer): number;
  /** ntdsapi.dll!DsAddSidHistoryW */
  DsAddSidHistory(hDS: Win32Pointer, Flags: number, SrcDomain: string | Win32Pointer, SrcPrincipal: string | Win32Pointer, SrcDomainController: string | Win32Pointer, SrcDomainCreds: Win32Pointer, DstDomain: string | Win32Pointer, DstPrincipal: string | Win32Pointer): number;
  /** ntdsapi.dll!DsBindA */
  DsBindA(DomainControllerName: string | Win32Pointer, DnsDomainName: string | Win32Pointer, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindByInstanceA */
  DsBindByInstanceA(ServerName: string | Win32Pointer, Annotation: string | Win32Pointer, InstanceGuid: Win32Pointer, DnsDomainName: string | Win32Pointer, AuthIdentity: Win32Pointer, ServicePrincipalName: string | Win32Pointer, BindFlags: number, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindByInstanceW */
  DsBindByInstanceW(ServerName: string | Win32Pointer, Annotation: string | Win32Pointer, InstanceGuid: Win32Pointer, DnsDomainName: string | Win32Pointer, AuthIdentity: Win32Pointer, ServicePrincipalName: string | Win32Pointer, BindFlags: number, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindByInstanceW */
  DsBindByInstance(ServerName: string | Win32Pointer, Annotation: string | Win32Pointer, InstanceGuid: Win32Pointer, DnsDomainName: string | Win32Pointer, AuthIdentity: Win32Pointer, ServicePrincipalName: string | Win32Pointer, BindFlags: number, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindToISTGA */
  DsBindToISTGA(SiteName: string | Win32Pointer, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindToISTGW */
  DsBindToISTGW(SiteName: string | Win32Pointer, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindToISTGW */
  DsBindToISTG(SiteName: string | Win32Pointer, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindW */
  DsBindW(DomainControllerName: string | Win32Pointer, DnsDomainName: string | Win32Pointer, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindW */
  DsBind(DomainControllerName: string | Win32Pointer, DnsDomainName: string | Win32Pointer, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindWithCredA */
  DsBindWithCredA(DomainControllerName: string | Win32Pointer, DnsDomainName: string | Win32Pointer, AuthIdentity: Win32Pointer, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindWithCredW */
  DsBindWithCredW(DomainControllerName: string | Win32Pointer, DnsDomainName: string | Win32Pointer, AuthIdentity: Win32Pointer, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindWithCredW */
  DsBindWithCred(DomainControllerName: string | Win32Pointer, DnsDomainName: string | Win32Pointer, AuthIdentity: Win32Pointer, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindWithSpnA */
  DsBindWithSpnA(DomainControllerName: string | Win32Pointer, DnsDomainName: string | Win32Pointer, AuthIdentity: Win32Pointer, ServicePrincipalName: string | Win32Pointer, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindWithSpnExA */
  DsBindWithSpnExA(DomainControllerName: string | Win32Pointer, DnsDomainName: string | Win32Pointer, AuthIdentity: Win32Pointer, ServicePrincipalName: string | Win32Pointer, BindFlags: number, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindWithSpnExW */
  DsBindWithSpnExW(DomainControllerName: string | Win32Pointer, DnsDomainName: string | Win32Pointer, AuthIdentity: Win32Pointer, ServicePrincipalName: string | Win32Pointer, BindFlags: number, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindWithSpnExW */
  DsBindWithSpnEx(DomainControllerName: string | Win32Pointer, DnsDomainName: string | Win32Pointer, AuthIdentity: Win32Pointer, ServicePrincipalName: string | Win32Pointer, BindFlags: number, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindWithSpnW */
  DsBindWithSpnW(DomainControllerName: string | Win32Pointer, DnsDomainName: string | Win32Pointer, AuthIdentity: Win32Pointer, ServicePrincipalName: string | Win32Pointer, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindWithSpnW */
  DsBindWithSpn(DomainControllerName: string | Win32Pointer, DnsDomainName: string | Win32Pointer, AuthIdentity: Win32Pointer, ServicePrincipalName: string | Win32Pointer, phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsBindingSetTimeout */
  DsBindingSetTimeout(hDS: Win32Pointer, cTimeoutSecs: number): number;
  /** ntdsapi.dll!DsClientMakeSpnForTargetServerA */
  DsClientMakeSpnForTargetServerA(ServiceClass: string | Win32Pointer, ServiceName: string | Win32Pointer, pcSpnLength: Win32Pointer, pszSpn: string | Win32Pointer): number;
  /** ntdsapi.dll!DsClientMakeSpnForTargetServerW */
  DsClientMakeSpnForTargetServerW(ServiceClass: string | Win32Pointer, ServiceName: string | Win32Pointer, pcSpnLength: Win32Pointer, pszSpn: string | Win32Pointer): number;
  /** ntdsapi.dll!DsClientMakeSpnForTargetServerW */
  DsClientMakeSpnForTargetServer(ServiceClass: string | Win32Pointer, ServiceName: string | Win32Pointer, pcSpnLength: Win32Pointer, pszSpn: string | Win32Pointer): number;
  /** ntdsapi.dll!DsCrackNamesA */
  DsCrackNamesA(hDS: Win32Pointer, flags: number, formatOffered: number, formatDesired: number, cNames: number, rpNames: Win32Pointer, ppResult: Win32Pointer): number;
  /** ntdsapi.dll!DsCrackNamesW */
  DsCrackNamesW(hDS: Win32Pointer, flags: number, formatOffered: number, formatDesired: number, cNames: number, rpNames: Win32Pointer, ppResult: Win32Pointer): number;
  /** ntdsapi.dll!DsCrackNamesW */
  DsCrackNames(hDS: Win32Pointer, flags: number, formatOffered: number, formatDesired: number, cNames: number, rpNames: Win32Pointer, ppResult: Win32Pointer): number;
  /** ntdsapi.dll!DsFreeDomainControllerInfoA */
  DsFreeDomainControllerInfoA(InfoLevel: number, cInfo: number, pInfo: Win32Pointer): void;
  /** ntdsapi.dll!DsFreeDomainControllerInfoW */
  DsFreeDomainControllerInfoW(InfoLevel: number, cInfo: number, pInfo: Win32Pointer): void;
  /** ntdsapi.dll!DsFreeDomainControllerInfoW */
  DsFreeDomainControllerInfo(InfoLevel: number, cInfo: number, pInfo: Win32Pointer): void;
  /** ntdsapi.dll!DsFreeNameResultA */
  DsFreeNameResultA(pResult: Win32Pointer): void;
  /** ntdsapi.dll!DsFreeNameResultW */
  DsFreeNameResultW(pResult: Win32Pointer): void;
  /** ntdsapi.dll!DsFreeNameResultW */
  DsFreeNameResult(pResult: Win32Pointer): void;
  /** ntdsapi.dll!DsFreePasswordCredentials */
  DsFreePasswordCredentials(AuthIdentity: Win32Pointer): void;
  /** ntdsapi.dll!DsFreeSchemaGuidMapA */
  DsFreeSchemaGuidMapA(pGuidMap: Win32Pointer): void;
  /** ntdsapi.dll!DsFreeSchemaGuidMapW */
  DsFreeSchemaGuidMapW(pGuidMap: Win32Pointer): void;
  /** ntdsapi.dll!DsFreeSchemaGuidMapW */
  DsFreeSchemaGuidMap(pGuidMap: Win32Pointer): void;
  /** ntdsapi.dll!DsFreeSpnArrayA */
  DsFreeSpnArrayA(cSpn: number, rpszSpn: Win32Pointer): void;
  /** ntdsapi.dll!DsFreeSpnArrayW */
  DsFreeSpnArrayW(cSpn: number, rpszSpn: Win32Pointer): void;
  /** ntdsapi.dll!DsFreeSpnArrayW */
  DsFreeSpnArray(cSpn: number, rpszSpn: Win32Pointer): void;
  /** ntdsapi.dll!DsGetDomainControllerInfoA */
  DsGetDomainControllerInfoA(hDs: Win32Pointer, DomainName: string | Win32Pointer, InfoLevel: number, pcOut: Win32Pointer, ppInfo: Win32Pointer): number;
  /** ntdsapi.dll!DsGetDomainControllerInfoW */
  DsGetDomainControllerInfoW(hDs: Win32Pointer, DomainName: string | Win32Pointer, InfoLevel: number, pcOut: Win32Pointer, ppInfo: Win32Pointer): number;
  /** ntdsapi.dll!DsGetDomainControllerInfoW */
  DsGetDomainControllerInfo(hDs: Win32Pointer, DomainName: string | Win32Pointer, InfoLevel: number, pcOut: Win32Pointer, ppInfo: Win32Pointer): number;
  /** ntdsapi.dll!DsGetSpnA */
  DsGetSpnA(ServiceType: number, ServiceClass: string | Win32Pointer, ServiceName: string | Win32Pointer, InstancePort: number, cInstanceNames: number, pInstanceNames: Win32Pointer, pInstancePorts: Win32Pointer, pcSpn: Win32Pointer, prpszSpn: Win32Pointer): number;
  /** ntdsapi.dll!DsGetSpnW */
  DsGetSpnW(ServiceType: number, ServiceClass: string | Win32Pointer, ServiceName: string | Win32Pointer, InstancePort: number, cInstanceNames: number, pInstanceNames: Win32Pointer, pInstancePorts: Win32Pointer, pcSpn: Win32Pointer, prpszSpn: Win32Pointer): number;
  /** ntdsapi.dll!DsGetSpnW */
  DsGetSpn(ServiceType: number, ServiceClass: string | Win32Pointer, ServiceName: string | Win32Pointer, InstancePort: number, cInstanceNames: number, pInstanceNames: Win32Pointer, pInstancePorts: Win32Pointer, pcSpn: Win32Pointer, prpszSpn: Win32Pointer): number;
  /** ntdsapi.dll!DsInheritSecurityIdentityA */
  DsInheritSecurityIdentityA(hDS: Win32Pointer, Flags: number, SrcPrincipal: string | Win32Pointer, DstPrincipal: string | Win32Pointer): number;
  /** ntdsapi.dll!DsInheritSecurityIdentityW */
  DsInheritSecurityIdentityW(hDS: Win32Pointer, Flags: number, SrcPrincipal: string | Win32Pointer, DstPrincipal: string | Win32Pointer): number;
  /** ntdsapi.dll!DsInheritSecurityIdentityW */
  DsInheritSecurityIdentity(hDS: Win32Pointer, Flags: number, SrcPrincipal: string | Win32Pointer, DstPrincipal: string | Win32Pointer): number;
  /** ntdsapi.dll!DsListDomainsInSiteA */
  DsListDomainsInSiteA(hDs: Win32Pointer, site: string | Win32Pointer, ppDomains: Win32Pointer): number;
  /** ntdsapi.dll!DsListDomainsInSiteW */
  DsListDomainsInSiteW(hDs: Win32Pointer, site: string | Win32Pointer, ppDomains: Win32Pointer): number;
  /** ntdsapi.dll!DsListDomainsInSiteW */
  DsListDomainsInSite(hDs: Win32Pointer, site: string | Win32Pointer, ppDomains: Win32Pointer): number;
  /** ntdsapi.dll!DsListInfoForServerA */
  DsListInfoForServerA(hDs: Win32Pointer, server: string | Win32Pointer, ppInfo: Win32Pointer): number;
  /** ntdsapi.dll!DsListInfoForServerW */
  DsListInfoForServerW(hDs: Win32Pointer, server: string | Win32Pointer, ppInfo: Win32Pointer): number;
  /** ntdsapi.dll!DsListInfoForServerW */
  DsListInfoForServer(hDs: Win32Pointer, server: string | Win32Pointer, ppInfo: Win32Pointer): number;
  /** ntdsapi.dll!DsListRolesA */
  DsListRolesA(hDs: Win32Pointer, ppRoles: Win32Pointer): number;
  /** ntdsapi.dll!DsListRolesW */
  DsListRolesW(hDs: Win32Pointer, ppRoles: Win32Pointer): number;
  /** ntdsapi.dll!DsListRolesW */
  DsListRoles(hDs: Win32Pointer, ppRoles: Win32Pointer): number;
  /** ntdsapi.dll!DsListServersForDomainInSiteA */
  DsListServersForDomainInSiteA(hDs: Win32Pointer, domain: string | Win32Pointer, site: string | Win32Pointer, ppServers: Win32Pointer): number;
  /** ntdsapi.dll!DsListServersForDomainInSiteW */
  DsListServersForDomainInSiteW(hDs: Win32Pointer, domain: string | Win32Pointer, site: string | Win32Pointer, ppServers: Win32Pointer): number;
  /** ntdsapi.dll!DsListServersForDomainInSiteW */
  DsListServersForDomainInSite(hDs: Win32Pointer, domain: string | Win32Pointer, site: string | Win32Pointer, ppServers: Win32Pointer): number;
  /** ntdsapi.dll!DsListServersInSiteA */
  DsListServersInSiteA(hDs: Win32Pointer, site: string | Win32Pointer, ppServers: Win32Pointer): number;
  /** ntdsapi.dll!DsListServersInSiteW */
  DsListServersInSiteW(hDs: Win32Pointer, site: string | Win32Pointer, ppServers: Win32Pointer): number;
  /** ntdsapi.dll!DsListServersInSiteW */
  DsListServersInSite(hDs: Win32Pointer, site: string | Win32Pointer, ppServers: Win32Pointer): number;
  /** ntdsapi.dll!DsListSitesA */
  DsListSitesA(hDs: Win32Pointer, ppSites: Win32Pointer): number;
  /** ntdsapi.dll!DsListSitesW */
  DsListSitesW(hDs: Win32Pointer, ppSites: Win32Pointer): number;
  /** ntdsapi.dll!DsListSitesW */
  DsListSites(hDs: Win32Pointer, ppSites: Win32Pointer): number;
  /** ntdsapi.dll!DsMakePasswordCredentialsA */
  DsMakePasswordCredentialsA(User: string | Win32Pointer, Domain: string | Win32Pointer, Password: string | Win32Pointer, pAuthIdentity: Win32Pointer): number;
  /** ntdsapi.dll!DsMakePasswordCredentialsW */
  DsMakePasswordCredentialsW(User: string | Win32Pointer, Domain: string | Win32Pointer, Password: string | Win32Pointer, pAuthIdentity: Win32Pointer): number;
  /** ntdsapi.dll!DsMakePasswordCredentialsW */
  DsMakePasswordCredentials(User: string | Win32Pointer, Domain: string | Win32Pointer, Password: string | Win32Pointer, pAuthIdentity: Win32Pointer): number;
  /** ntdsapi.dll!DsMapSchemaGuidsA */
  DsMapSchemaGuidsA(hDs: Win32Pointer, cGuids: number, rGuids: Win32Pointer, ppGuidMap: Win32Pointer): number;
  /** ntdsapi.dll!DsMapSchemaGuidsW */
  DsMapSchemaGuidsW(hDs: Win32Pointer, cGuids: number, rGuids: Win32Pointer, ppGuidMap: Win32Pointer): number;
  /** ntdsapi.dll!DsMapSchemaGuidsW */
  DsMapSchemaGuids(hDs: Win32Pointer, cGuids: number, rGuids: Win32Pointer, ppGuidMap: Win32Pointer): number;
  /** ntdsapi.dll!DsQuerySitesByCostA */
  DsQuerySitesByCostA(hDS: Win32Pointer, pszFromSite: string | Win32Pointer, rgszToSites: Win32Pointer, cToSites: number, dwFlags: number, prgSiteInfo: Win32Pointer): number;
  /** ntdsapi.dll!DsQuerySitesByCostW */
  DsQuerySitesByCostW(hDS: Win32Pointer, pwszFromSite: string | Win32Pointer, rgwszToSites: Win32Pointer, cToSites: number, dwFlags: number, prgSiteInfo: Win32Pointer): number;
  /** ntdsapi.dll!DsQuerySitesByCostW */
  DsQuerySitesByCost(hDS: Win32Pointer, pwszFromSite: string | Win32Pointer, rgwszToSites: Win32Pointer, cToSites: number, dwFlags: number, prgSiteInfo: Win32Pointer): number;
  /** ntdsapi.dll!DsQuerySitesFree */
  DsQuerySitesFree(rgSiteInfo: Win32Pointer): void;
  /** ntdsapi.dll!DsRemoveDsDomainA */
  DsRemoveDsDomainA(hDs: Win32Pointer, DomainDN: string | Win32Pointer): number;
  /** ntdsapi.dll!DsRemoveDsDomainW */
  DsRemoveDsDomainW(hDs: Win32Pointer, DomainDN: string | Win32Pointer): number;
  /** ntdsapi.dll!DsRemoveDsDomainW */
  DsRemoveDsDomain(hDs: Win32Pointer, DomainDN: string | Win32Pointer): number;
  /** ntdsapi.dll!DsRemoveDsServerA */
  DsRemoveDsServerA(hDs: Win32Pointer, ServerDN: string | Win32Pointer, DomainDN: string | Win32Pointer, fLastDcInDomain: Win32Pointer, fCommit: number): number;
  /** ntdsapi.dll!DsRemoveDsServerW */
  DsRemoveDsServerW(hDs: Win32Pointer, ServerDN: string | Win32Pointer, DomainDN: string | Win32Pointer, fLastDcInDomain: Win32Pointer, fCommit: number): number;
  /** ntdsapi.dll!DsRemoveDsServerW */
  DsRemoveDsServer(hDs: Win32Pointer, ServerDN: string | Win32Pointer, DomainDN: string | Win32Pointer, fLastDcInDomain: Win32Pointer, fCommit: number): number;
  /** ntdsapi.dll!DsReplicaAddA */
  DsReplicaAddA(hDS: Win32Pointer, NameContext: string | Win32Pointer, SourceDsaDn: string | Win32Pointer, TransportDn: string | Win32Pointer, SourceDsaAddress: string | Win32Pointer, pSchedule: Win32Pointer, Options: number): number;
  /** ntdsapi.dll!DsReplicaAddW */
  DsReplicaAddW(hDS: Win32Pointer, NameContext: string | Win32Pointer, SourceDsaDn: string | Win32Pointer, TransportDn: string | Win32Pointer, SourceDsaAddress: string | Win32Pointer, pSchedule: Win32Pointer, Options: number): number;
  /** ntdsapi.dll!DsReplicaAddW */
  DsReplicaAdd(hDS: Win32Pointer, NameContext: string | Win32Pointer, SourceDsaDn: string | Win32Pointer, TransportDn: string | Win32Pointer, SourceDsaAddress: string | Win32Pointer, pSchedule: Win32Pointer, Options: number): number;
  /** ntdsapi.dll!DsReplicaConsistencyCheck */
  DsReplicaConsistencyCheck(hDS: Win32Pointer, TaskID: number, dwFlags: number): number;
  /** ntdsapi.dll!DsReplicaDelA */
  DsReplicaDelA(hDS: Win32Pointer, NameContext: string | Win32Pointer, DsaSrc: string | Win32Pointer, Options: number): number;
  /** ntdsapi.dll!DsReplicaDelW */
  DsReplicaDelW(hDS: Win32Pointer, NameContext: string | Win32Pointer, DsaSrc: string | Win32Pointer, Options: number): number;
  /** ntdsapi.dll!DsReplicaDelW */
  DsReplicaDel(hDS: Win32Pointer, NameContext: string | Win32Pointer, DsaSrc: string | Win32Pointer, Options: number): number;
  /** ntdsapi.dll!DsReplicaFreeInfo */
  DsReplicaFreeInfo(InfoType: number, pInfo: Win32Pointer): void;
  /** ntdsapi.dll!DsReplicaGetInfo2W */
  DsReplicaGetInfo2W(hDS: Win32Pointer, InfoType: number, pszObject: string | Win32Pointer, puuidForSourceDsaObjGuid: Win32Pointer, pszAttributeName: string | Win32Pointer, pszValue: string | Win32Pointer, dwFlags: number, dwEnumerationContext: number, ppInfo: Win32Pointer): number;
  /** ntdsapi.dll!DsReplicaGetInfoW */
  DsReplicaGetInfoW(hDS: Win32Pointer, InfoType: number, pszObject: string | Win32Pointer, puuidForSourceDsaObjGuid: Win32Pointer, ppInfo: Win32Pointer): number;
  /** ntdsapi.dll!DsReplicaModifyA */
  DsReplicaModifyA(hDS: Win32Pointer, NameContext: string | Win32Pointer, pUuidSourceDsa: Win32Pointer, TransportDn: string | Win32Pointer, SourceDsaAddress: string | Win32Pointer, pSchedule: Win32Pointer, ReplicaFlags: number, ModifyFields: number, Options: number): number;
  /** ntdsapi.dll!DsReplicaModifyW */
  DsReplicaModifyW(hDS: Win32Pointer, NameContext: string | Win32Pointer, pUuidSourceDsa: Win32Pointer, TransportDn: string | Win32Pointer, SourceDsaAddress: string | Win32Pointer, pSchedule: Win32Pointer, ReplicaFlags: number, ModifyFields: number, Options: number): number;
  /** ntdsapi.dll!DsReplicaModifyW */
  DsReplicaModify(hDS: Win32Pointer, NameContext: string | Win32Pointer, pUuidSourceDsa: Win32Pointer, TransportDn: string | Win32Pointer, SourceDsaAddress: string | Win32Pointer, pSchedule: Win32Pointer, ReplicaFlags: number, ModifyFields: number, Options: number): number;
  /** ntdsapi.dll!DsReplicaSyncA */
  DsReplicaSyncA(hDS: Win32Pointer, NameContext: string | Win32Pointer, pUuidDsaSrc: Win32Pointer, Options: number): number;
  /** ntdsapi.dll!DsReplicaSyncAllA */
  DsReplicaSyncAllA(hDS: Win32Pointer, pszNameContext: string | Win32Pointer, ulFlags: number, pFnCallBack: number | bigint, pCallbackData: Win32Pointer, pErrors: Win32Pointer): number;
  /** ntdsapi.dll!DsReplicaSyncAllW */
  DsReplicaSyncAllW(hDS: Win32Pointer, pszNameContext: string | Win32Pointer, ulFlags: number, pFnCallBack: number | bigint, pCallbackData: Win32Pointer, pErrors: Win32Pointer): number;
  /** ntdsapi.dll!DsReplicaSyncAllW */
  DsReplicaSyncAll(hDS: Win32Pointer, pszNameContext: string | Win32Pointer, ulFlags: number, pFnCallBack: number | bigint, pCallbackData: Win32Pointer, pErrors: Win32Pointer): number;
  /** ntdsapi.dll!DsReplicaSyncW */
  DsReplicaSyncW(hDS: Win32Pointer, NameContext: string | Win32Pointer, pUuidDsaSrc: Win32Pointer, Options: number): number;
  /** ntdsapi.dll!DsReplicaSyncW */
  DsReplicaSync(hDS: Win32Pointer, NameContext: string | Win32Pointer, pUuidDsaSrc: Win32Pointer, Options: number): number;
  /** ntdsapi.dll!DsReplicaUpdateRefsA */
  DsReplicaUpdateRefsA(hDS: Win32Pointer, NameContext: string | Win32Pointer, DsaDest: string | Win32Pointer, pUuidDsaDest: Win32Pointer, Options: number): number;
  /** ntdsapi.dll!DsReplicaUpdateRefsW */
  DsReplicaUpdateRefsW(hDS: Win32Pointer, NameContext: string | Win32Pointer, DsaDest: string | Win32Pointer, pUuidDsaDest: Win32Pointer, Options: number): number;
  /** ntdsapi.dll!DsReplicaUpdateRefsW */
  DsReplicaUpdateRefs(hDS: Win32Pointer, NameContext: string | Win32Pointer, DsaDest: string | Win32Pointer, pUuidDsaDest: Win32Pointer, Options: number): number;
  /** ntdsapi.dll!DsReplicaVerifyObjectsA */
  DsReplicaVerifyObjectsA(hDS: Win32Pointer, NameContext: string | Win32Pointer, pUuidDsaSrc: Win32Pointer, ulOptions: number): number;
  /** ntdsapi.dll!DsReplicaVerifyObjectsW */
  DsReplicaVerifyObjectsW(hDS: Win32Pointer, NameContext: string | Win32Pointer, pUuidDsaSrc: Win32Pointer, ulOptions: number): number;
  /** ntdsapi.dll!DsReplicaVerifyObjectsW */
  DsReplicaVerifyObjects(hDS: Win32Pointer, NameContext: string | Win32Pointer, pUuidDsaSrc: Win32Pointer, ulOptions: number): number;
  /** ntdsapi.dll!DsServerRegisterSpnA */
  DsServerRegisterSpnA(Operation: number, ServiceClass: string | Win32Pointer, UserObjectDN: string | Win32Pointer): number;
  /** ntdsapi.dll!DsServerRegisterSpnW */
  DsServerRegisterSpnW(Operation: number, ServiceClass: string | Win32Pointer, UserObjectDN: string | Win32Pointer): number;
  /** ntdsapi.dll!DsServerRegisterSpnW */
  DsServerRegisterSpn(Operation: number, ServiceClass: string | Win32Pointer, UserObjectDN: string | Win32Pointer): number;
  /** ntdsapi.dll!DsUnBindA */
  DsUnBindA(phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsUnBindW */
  DsUnBindW(phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsUnBindW */
  DsUnBind(phDS: Win32Pointer): number;
  /** ntdsapi.dll!DsWriteAccountSpnA */
  DsWriteAccountSpnA(hDS: Win32Pointer, Operation: number, pszAccount: string | Win32Pointer, cSpn: number, rpszSpn: Win32Pointer): number;
  /** ntdsapi.dll!DsWriteAccountSpnW */
  DsWriteAccountSpnW(hDS: Win32Pointer, Operation: number, pszAccount: string | Win32Pointer, cSpn: number, rpszSpn: Win32Pointer): number;
  /** ntdsapi.dll!DsWriteAccountSpnW */
  DsWriteAccountSpn(hDS: Win32Pointer, Operation: number, pszAccount: string | Win32Pointer, cSpn: number, rpszSpn: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
