// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** oleaut32.dll!BSTR_UserFree */
  BSTR_UserFree(param0: Win32Pointer, param1: Win32Pointer): void;
  /** oleaut32.dll!BSTR_UserFree64 */
  BSTR_UserFree64(param0: Win32Pointer, param1: Win32Pointer): void;
  /** oleaut32.dll!BSTR_UserMarshal */
  BSTR_UserMarshal(param0: Win32Pointer, param1: Win32Pointer, param2: Win32Pointer): number | null;
  /** oleaut32.dll!BSTR_UserMarshal64 */
  BSTR_UserMarshal64(param0: Win32Pointer, param1: Win32Pointer, param2: Win32Pointer): number | null;
  /** oleaut32.dll!BSTR_UserSize */
  BSTR_UserSize(param0: Win32Pointer, param1: number, param2: Win32Pointer): number;
  /** oleaut32.dll!BSTR_UserSize64 */
  BSTR_UserSize64(param0: Win32Pointer, param1: number, param2: Win32Pointer): number;
  /** oleaut32.dll!BSTR_UserUnmarshal */
  BSTR_UserUnmarshal(param0: Win32Pointer, param1: Win32Pointer, param2: Win32Pointer): number | null;
  /** oleaut32.dll!BSTR_UserUnmarshal64 */
  BSTR_UserUnmarshal64(param0: Win32Pointer, param1: Win32Pointer, param2: Win32Pointer): number | null;
  /** oleaut32.dll!BstrFromVector */
  BstrFromVector(psa: Win32Pointer, pbstr: Win32Pointer): number;
  /** oleaut32.dll!ClearCustData */
  ClearCustData(pCustData: Win32Pointer): void;
  /** oleaut32.dll!CreateDispTypeInfo */
  CreateDispTypeInfo(pidata: Win32Pointer, lcid: number, pptinfo: Win32Pointer): number;
  /** oleaut32.dll!CreateErrorInfo */
  CreateErrorInfo(pperrinfo: Win32Pointer): number;
  /** oleaut32.dll!CreateStdDispatch */
  CreateStdDispatch(punkOuter: Win32Pointer, pvThis: Win32Pointer, ptinfo: Win32Pointer, ppunkStdDisp: Win32Pointer): number;
  /** oleaut32.dll!CreateTypeLib */
  CreateTypeLib(syskind: number, szFile: string | Win32Pointer, ppctlib: Win32Pointer): number;
  /** oleaut32.dll!CreateTypeLib2 */
  CreateTypeLib2(syskind: number, szFile: string | Win32Pointer, ppctlib: Win32Pointer): number;
  /** oleaut32.dll!DispCallFunc */
  DispCallFunc(pvInstance: Win32Pointer, oVft: number | bigint, cc: number, vtReturn: number, cActuals: number, prgvt: Win32Pointer, prgpvarg: Win32Pointer, pvargResult: Win32Pointer): number;
  /** oleaut32.dll!DispGetIDsOfNames */
  DispGetIDsOfNames(ptinfo: Win32Pointer, rgszNames: Win32Pointer, cNames: number, rgdispid: Win32Pointer): number;
  /** oleaut32.dll!DispGetParam */
  DispGetParam(pdispparams: Win32Pointer, position: number, vtTarg: number, pvarResult: Win32Pointer, puArgErr: Win32Pointer): number;
  /** oleaut32.dll!DispInvoke */
  DispInvoke(_this: Win32Pointer, ptinfo: Win32Pointer, dispidMember: number, wFlags: number, pparams: Win32Pointer, pvarResult: Win32Pointer, pexcepinfo: Win32Pointer, puArgErr: Win32Pointer): number;
  /** oleaut32.dll!DosDateTimeToVariantTime */
  DosDateTimeToVariantTime(wDosDate: number, wDosTime: number, pvtime: Win32Pointer): number;
  /** oleaut32.dll!GetActiveObject */
  GetActiveObject(rclsid: Win32Pointer, pvReserved: Win32Pointer, ppunk: Win32Pointer): number;
  /** oleaut32.dll!GetAltMonthNames */
  GetAltMonthNames(lcid: number, prgp: Win32Pointer): number;
  /** oleaut32.dll!GetErrorInfo */
  GetErrorInfo(dwReserved: number, pperrinfo: Win32Pointer): number;
  /** oleaut32.dll!GetRecordInfoFromGuids */
  GetRecordInfoFromGuids(rGuidTypeLib: Win32Pointer, uVerMajor: number, uVerMinor: number, lcid: number, rGuidTypeInfo: Win32Pointer, ppRecInfo: Win32Pointer): number;
  /** oleaut32.dll!GetRecordInfoFromTypeInfo */
  GetRecordInfoFromTypeInfo(pTypeInfo: Win32Pointer, ppRecInfo: Win32Pointer): number;
  /** oleaut32.dll!LHashValOfNameSys */
  LHashValOfNameSys(syskind: number, lcid: number, szName: string | Win32Pointer): number;
  /** oleaut32.dll!LHashValOfNameSysA */
  LHashValOfNameSysA(syskind: number, lcid: number, szName: string | Win32Pointer): number;
  /** oleaut32.dll!LPSAFEARRAY_UserFree */
  LPSAFEARRAY_UserFree(param0: Win32Pointer, param1: Win32Pointer): void;
  /** oleaut32.dll!LPSAFEARRAY_UserFree64 */
  LPSAFEARRAY_UserFree64(param0: Win32Pointer, param1: Win32Pointer): void;
  /** oleaut32.dll!LPSAFEARRAY_UserMarshal */
  LPSAFEARRAY_UserMarshal(param0: Win32Pointer, param1: Win32Pointer, param2: Win32Pointer): number | null;
  /** oleaut32.dll!LPSAFEARRAY_UserMarshal64 */
  LPSAFEARRAY_UserMarshal64(param0: Win32Pointer, param1: Win32Pointer, param2: Win32Pointer): number | null;
  /** oleaut32.dll!LPSAFEARRAY_UserSize */
  LPSAFEARRAY_UserSize(param0: Win32Pointer, param1: number, param2: Win32Pointer): number;
  /** oleaut32.dll!LPSAFEARRAY_UserSize64 */
  LPSAFEARRAY_UserSize64(param0: Win32Pointer, param1: number, param2: Win32Pointer): number;
  /** oleaut32.dll!LPSAFEARRAY_UserUnmarshal */
  LPSAFEARRAY_UserUnmarshal(param0: Win32Pointer, param1: Win32Pointer, param2: Win32Pointer): number | null;
  /** oleaut32.dll!LPSAFEARRAY_UserUnmarshal64 */
  LPSAFEARRAY_UserUnmarshal64(param0: Win32Pointer, param1: Win32Pointer, param2: Win32Pointer): number | null;
  /** oleaut32.dll!LoadRegTypeLib */
  LoadRegTypeLib(rguid: Win32Pointer, wVerMajor: number, wVerMinor: number, lcid: number, pptlib: Win32Pointer): number;
  /** oleaut32.dll!LoadTypeLib */
  LoadTypeLib(szFile: string | Win32Pointer, pptlib: Win32Pointer): number;
  /** oleaut32.dll!LoadTypeLibEx */
  LoadTypeLibEx(szFile: string | Win32Pointer, regkind: number, pptlib: Win32Pointer): number;
  /** oleaut32.dll!OaBuildVersion */
  OaBuildVersion(): number;
  /** oleaut32.dll!OaEnablePerUserTLibRegistration */
  OaEnablePerUserTLibRegistration(): void;
  /** oleaut32.dll!OleCreateFontIndirect */
  OleCreateFontIndirect(lpFontDesc: Win32Pointer, riid: Win32Pointer, lplpvObj: Win32Pointer): number;
  /** oleaut32.dll!OleCreatePictureIndirect */
  OleCreatePictureIndirect(lpPictDesc: Win32Pointer, riid: Win32Pointer, fOwn: number, lplpvObj: Win32Pointer): number;
  /** oleaut32.dll!OleCreatePropertyFrame */
  OleCreatePropertyFrame(hwndOwner: Win32Pointer, x: number, y: number, lpszCaption: string | Win32Pointer, cObjects: number, ppUnk: Win32Pointer, cPages: number, pPageClsID: Win32Pointer, lcid: number, dwReserved: number, pvReserved: Win32Pointer): number;
  /** oleaut32.dll!OleCreatePropertyFrameIndirect */
  OleCreatePropertyFrameIndirect(lpParams: Win32Pointer): number;
  /** oleaut32.dll!OleIconToCursor */
  OleIconToCursor(hinstExe: Win32Pointer, hIcon: Win32Pointer): number | null;
  /** oleaut32.dll!OleLoadPicture */
  OleLoadPicture(lpstream: Win32Pointer, lSize: number, fRunmode: number, riid: Win32Pointer, lplpvObj: Win32Pointer): number;
  /** oleaut32.dll!OleLoadPictureEx */
  OleLoadPictureEx(lpstream: Win32Pointer, lSize: number, fRunmode: number, riid: Win32Pointer, xSizeDesired: number, ySizeDesired: number, dwFlags: number, lplpvObj: Win32Pointer): number;
  /** oleaut32.dll!OleLoadPictureFile */
  OleLoadPictureFile(varFileName: Win32StructInit, lplpdispPicture: Win32Pointer): number;
  /** oleaut32.dll!OleLoadPictureFileEx */
  OleLoadPictureFileEx(varFileName: Win32StructInit, xSizeDesired: number, ySizeDesired: number, dwFlags: number, lplpdispPicture: Win32Pointer): number;
  /** oleaut32.dll!OleLoadPicturePath */
  OleLoadPicturePath(szURLorPath: string | Win32Pointer, punkCaller: Win32Pointer, dwReserved: number, clrReserved: number, riid: Win32Pointer, ppvRet: Win32Pointer): number;
  /** oleaut32.dll!OleSavePictureFile */
  OleSavePictureFile(lpdispPicture: Win32Pointer, bstrFileName: string | Win32Pointer): number;
  /** oleaut32.dll!OleTranslateColor */
  OleTranslateColor(clr: number, hpal: Win32Pointer, lpcolorref: Win32Pointer): number;
  /** oleaut32.dll!QueryPathOfRegTypeLib */
  QueryPathOfRegTypeLib(guid: Win32Pointer, wMaj: number, wMin: number, lcid: number, lpbstrPathName: Win32Pointer): number;
  /** oleaut32.dll!RegisterActiveObject */
  RegisterActiveObject(punk: Win32Pointer, rclsid: Win32Pointer, dwFlags: number, pdwRegister: Win32Pointer): number;
  /** oleaut32.dll!RegisterTypeLib */
  RegisterTypeLib(ptlib: Win32Pointer, szFullPath: string | Win32Pointer, szHelpDir: string | Win32Pointer): number;
  /** oleaut32.dll!RegisterTypeLibForUser */
  RegisterTypeLibForUser(ptlib: Win32Pointer, szFullPath: string | Win32Pointer, szHelpDir: string | Win32Pointer): number;
  /** oleaut32.dll!RevokeActiveObject */
  RevokeActiveObject(dwRegister: number, pvReserved: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayAccessData */
  SafeArrayAccessData(psa: Win32Pointer, ppvData: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayAddRef */
  SafeArrayAddRef(psa: Win32Pointer, ppDataToRelease: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayAllocData */
  SafeArrayAllocData(psa: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayAllocDescriptor */
  SafeArrayAllocDescriptor(cDims: number, ppsaOut: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayAllocDescriptorEx */
  SafeArrayAllocDescriptorEx(vt: number, cDims: number, ppsaOut: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayCopy */
  SafeArrayCopy(psa: Win32Pointer, ppsaOut: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayCopyData */
  SafeArrayCopyData(psaSource: Win32Pointer, psaTarget: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayCreate */
  SafeArrayCreate(vt: number, cDims: number, rgsabound: Win32Pointer): number | null;
  /** oleaut32.dll!SafeArrayCreateEx */
  SafeArrayCreateEx(vt: number, cDims: number, rgsabound: Win32Pointer, pvExtra: Win32Pointer): number | null;
  /** oleaut32.dll!SafeArrayCreateVector */
  SafeArrayCreateVector(vt: number, lLbound: number, cElements: number): number | null;
  /** oleaut32.dll!SafeArrayCreateVectorEx */
  SafeArrayCreateVectorEx(vt: number, lLbound: number, cElements: number, pvExtra: Win32Pointer): number | null;
  /** oleaut32.dll!SafeArrayDestroy */
  SafeArrayDestroy(psa: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayDestroyData */
  SafeArrayDestroyData(psa: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayDestroyDescriptor */
  SafeArrayDestroyDescriptor(psa: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayGetDim */
  SafeArrayGetDim(psa: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayGetElement */
  SafeArrayGetElement(psa: Win32Pointer, rgIndices: Win32Pointer, pv: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayGetElemsize */
  SafeArrayGetElemsize(psa: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayGetIID */
  SafeArrayGetIID(psa: Win32Pointer, pguid: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayGetLBound */
  SafeArrayGetLBound(psa: Win32Pointer, nDim: number, plLbound: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayGetRecordInfo */
  SafeArrayGetRecordInfo(psa: Win32Pointer, prinfo: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayGetUBound */
  SafeArrayGetUBound(psa: Win32Pointer, nDim: number, plUbound: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayGetVartype */
  SafeArrayGetVartype(psa: Win32Pointer, pvt: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayLock */
  SafeArrayLock(psa: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayPtrOfIndex */
  SafeArrayPtrOfIndex(psa: Win32Pointer, rgIndices: Win32Pointer, ppvData: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayPutElement */
  SafeArrayPutElement(psa: Win32Pointer, rgIndices: Win32Pointer, pv: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayRedim */
  SafeArrayRedim(psa: Win32Pointer, psaboundNew: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayReleaseData */
  SafeArrayReleaseData(pData: Win32Pointer): void;
  /** oleaut32.dll!SafeArrayReleaseDescriptor */
  SafeArrayReleaseDescriptor(psa: Win32Pointer): void;
  /** oleaut32.dll!SafeArraySetIID */
  SafeArraySetIID(psa: Win32Pointer, guid: Win32Pointer): number;
  /** oleaut32.dll!SafeArraySetRecordInfo */
  SafeArraySetRecordInfo(psa: Win32Pointer, prinfo: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayUnaccessData */
  SafeArrayUnaccessData(psa: Win32Pointer): number;
  /** oleaut32.dll!SafeArrayUnlock */
  SafeArrayUnlock(psa: Win32Pointer): number;
  /** oleaut32.dll!SetErrorInfo */
  SetErrorInfo(dwReserved: number, perrinfo: Win32Pointer): number;
  /** oleaut32.dll!SysAddRefString */
  SysAddRefString(bstrString: string | Win32Pointer): number;
  /** oleaut32.dll!SysAllocString */
  SysAllocString(psz: string | Win32Pointer): number | null;
  /** oleaut32.dll!SysAllocStringByteLen */
  SysAllocStringByteLen(psz: string | Win32Pointer, len: number): number | null;
  /** oleaut32.dll!SysAllocStringLen */
  SysAllocStringLen(strIn: string | Win32Pointer, ui: number): number | null;
  /** oleaut32.dll!SysFreeString */
  SysFreeString(bstrString: string | Win32Pointer): void;
  /** oleaut32.dll!SysReAllocString */
  SysReAllocString(pbstr: Win32Pointer, psz: string | Win32Pointer): number;
  /** oleaut32.dll!SysReAllocStringLen */
  SysReAllocStringLen(pbstr: Win32Pointer, psz: string | Win32Pointer, len: number): number;
  /** oleaut32.dll!SysReleaseString */
  SysReleaseString(bstrString: string | Win32Pointer): void;
  /** oleaut32.dll!SysStringByteLen */
  SysStringByteLen(bstr: string | Win32Pointer): number;
  /** oleaut32.dll!SysStringLen */
  SysStringLen(pbstr: string | Win32Pointer): number;
  /** oleaut32.dll!SystemTimeToVariantTime */
  SystemTimeToVariantTime(lpSystemTime: Win32Pointer, pvtime: Win32Pointer): number;
  /** oleaut32.dll!UnRegisterTypeLib */
  UnRegisterTypeLib(libID: Win32Pointer, wVerMajor: number, wVerMinor: number, lcid: number, syskind: number): number;
  /** oleaut32.dll!UnRegisterTypeLibForUser */
  UnRegisterTypeLibForUser(libID: Win32Pointer, wMajorVerNum: number, wMinorVerNum: number, lcid: number, syskind: number): number;
  /** oleaut32.dll!VARIANT_UserFree */
  VARIANT_UserFree(param0: Win32Pointer, param1: Win32Pointer): void;
  /** oleaut32.dll!VARIANT_UserFree64 */
  VARIANT_UserFree64(param0: Win32Pointer, param1: Win32Pointer): void;
  /** oleaut32.dll!VARIANT_UserMarshal */
  VARIANT_UserMarshal(param0: Win32Pointer, param1: Win32Pointer, param2: Win32Pointer): number | null;
  /** oleaut32.dll!VARIANT_UserMarshal64 */
  VARIANT_UserMarshal64(param0: Win32Pointer, param1: Win32Pointer, param2: Win32Pointer): number | null;
  /** oleaut32.dll!VARIANT_UserSize */
  VARIANT_UserSize(param0: Win32Pointer, param1: number, param2: Win32Pointer): number;
  /** oleaut32.dll!VARIANT_UserSize64 */
  VARIANT_UserSize64(param0: Win32Pointer, param1: number, param2: Win32Pointer): number;
  /** oleaut32.dll!VARIANT_UserUnmarshal */
  VARIANT_UserUnmarshal(param0: Win32Pointer, param1: Win32Pointer, param2: Win32Pointer): number | null;
  /** oleaut32.dll!VARIANT_UserUnmarshal64 */
  VARIANT_UserUnmarshal64(param0: Win32Pointer, param1: Win32Pointer, param2: Win32Pointer): number | null;
  /** oleaut32.dll!VarAbs */
  VarAbs(pvarIn: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarAdd */
  VarAdd(pvarLeft: Win32Pointer, pvarRight: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarAnd */
  VarAnd(pvarLeft: Win32Pointer, pvarRight: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarBoolFromCy */
  VarBoolFromCy(cyIn: Win32StructInit, pboolOut: Win32Pointer): number;
  /** oleaut32.dll!VarBoolFromDate */
  VarBoolFromDate(dateIn: number, pboolOut: Win32Pointer): number;
  /** oleaut32.dll!VarBoolFromDec */
  VarBoolFromDec(pdecIn: Win32Pointer, pboolOut: Win32Pointer): number;
  /** oleaut32.dll!VarBoolFromDisp */
  VarBoolFromDisp(pdispIn: Win32Pointer, lcid: number, pboolOut: Win32Pointer): number;
  /** oleaut32.dll!VarBoolFromI1 */
  VarBoolFromI1(cIn: number, pboolOut: Win32Pointer): number;
  /** oleaut32.dll!VarBoolFromI2 */
  VarBoolFromI2(sIn: number, pboolOut: Win32Pointer): number;
  /** oleaut32.dll!VarBoolFromI4 */
  VarBoolFromI4(lIn: number, pboolOut: Win32Pointer): number;
  /** oleaut32.dll!VarBoolFromI8 */
  VarBoolFromI8(i64In: number | bigint, pboolOut: Win32Pointer): number;
  /** oleaut32.dll!VarBoolFromR4 */
  VarBoolFromR4(fltIn: number, pboolOut: Win32Pointer): number;
  /** oleaut32.dll!VarBoolFromR8 */
  VarBoolFromR8(dblIn: number, pboolOut: Win32Pointer): number;
  /** oleaut32.dll!VarBoolFromStr */
  VarBoolFromStr(strIn: string | Win32Pointer, lcid: number, dwFlags: number, pboolOut: Win32Pointer): number;
  /** oleaut32.dll!VarBoolFromUI1 */
  VarBoolFromUI1(bIn: number, pboolOut: Win32Pointer): number;
  /** oleaut32.dll!VarBoolFromUI2 */
  VarBoolFromUI2(uiIn: number, pboolOut: Win32Pointer): number;
  /** oleaut32.dll!VarBoolFromUI4 */
  VarBoolFromUI4(ulIn: number, pboolOut: Win32Pointer): number;
  /** oleaut32.dll!VarBoolFromUI8 */
  VarBoolFromUI8(i64In: number | bigint, pboolOut: Win32Pointer): number;
  /** oleaut32.dll!VarBstrCat */
  VarBstrCat(bstrLeft: string | Win32Pointer, bstrRight: string | Win32Pointer, pbstrResult: Win32Pointer): number;
  /** oleaut32.dll!VarBstrCmp */
  VarBstrCmp(bstrLeft: string | Win32Pointer, bstrRight: string | Win32Pointer, lcid: number, dwFlags: number): number;
  /** oleaut32.dll!VarBstrFromBool */
  VarBstrFromBool(boolIn: number, lcid: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarBstrFromCy */
  VarBstrFromCy(cyIn: Win32StructInit, lcid: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarBstrFromDate */
  VarBstrFromDate(dateIn: number, lcid: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarBstrFromDec */
  VarBstrFromDec(pdecIn: Win32Pointer, lcid: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarBstrFromDisp */
  VarBstrFromDisp(pdispIn: Win32Pointer, lcid: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarBstrFromI1 */
  VarBstrFromI1(cIn: number, lcid: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarBstrFromI2 */
  VarBstrFromI2(iVal: number, lcid: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarBstrFromI4 */
  VarBstrFromI4(lIn: number, lcid: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarBstrFromI8 */
  VarBstrFromI8(i64In: number | bigint, lcid: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarBstrFromR4 */
  VarBstrFromR4(fltIn: number, lcid: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarBstrFromR8 */
  VarBstrFromR8(dblIn: number, lcid: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarBstrFromUI1 */
  VarBstrFromUI1(bVal: number, lcid: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarBstrFromUI2 */
  VarBstrFromUI2(uiIn: number, lcid: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarBstrFromUI4 */
  VarBstrFromUI4(ulIn: number, lcid: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarBstrFromUI8 */
  VarBstrFromUI8(ui64In: number | bigint, lcid: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarCat */
  VarCat(pvarLeft: Win32Pointer, pvarRight: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarCmp */
  VarCmp(pvarLeft: Win32Pointer, pvarRight: Win32Pointer, lcid: number, dwFlags: number): number;
  /** oleaut32.dll!VarCyAbs */
  VarCyAbs(cyIn: Win32StructInit, pcyResult: Win32Pointer): number;
  /** oleaut32.dll!VarCyAdd */
  VarCyAdd(cyLeft: Win32StructInit, cyRight: Win32StructInit, pcyResult: Win32Pointer): number;
  /** oleaut32.dll!VarCyCmp */
  VarCyCmp(cyLeft: Win32StructInit, cyRight: Win32StructInit): number;
  /** oleaut32.dll!VarCyCmpR8 */
  VarCyCmpR8(cyLeft: Win32StructInit, dblRight: number): number;
  /** oleaut32.dll!VarCyFix */
  VarCyFix(cyIn: Win32StructInit, pcyResult: Win32Pointer): number;
  /** oleaut32.dll!VarCyFromBool */
  VarCyFromBool(boolIn: number, pcyOut: Win32Pointer): number;
  /** oleaut32.dll!VarCyFromDate */
  VarCyFromDate(dateIn: number, pcyOut: Win32Pointer): number;
  /** oleaut32.dll!VarCyFromDec */
  VarCyFromDec(pdecIn: Win32Pointer, pcyOut: Win32Pointer): number;
  /** oleaut32.dll!VarCyFromDisp */
  VarCyFromDisp(pdispIn: Win32Pointer, lcid: number, pcyOut: Win32Pointer): number;
  /** oleaut32.dll!VarCyFromI1 */
  VarCyFromI1(cIn: number, pcyOut: Win32Pointer): number;
  /** oleaut32.dll!VarCyFromI2 */
  VarCyFromI2(sIn: number, pcyOut: Win32Pointer): number;
  /** oleaut32.dll!VarCyFromI4 */
  VarCyFromI4(lIn: number, pcyOut: Win32Pointer): number;
  /** oleaut32.dll!VarCyFromI8 */
  VarCyFromI8(i64In: number | bigint, pcyOut: Win32Pointer): number;
  /** oleaut32.dll!VarCyFromR4 */
  VarCyFromR4(fltIn: number, pcyOut: Win32Pointer): number;
  /** oleaut32.dll!VarCyFromR8 */
  VarCyFromR8(dblIn: number, pcyOut: Win32Pointer): number;
  /** oleaut32.dll!VarCyFromStr */
  VarCyFromStr(strIn: string | Win32Pointer, lcid: number, dwFlags: number, pcyOut: Win32Pointer): number;
  /** oleaut32.dll!VarCyFromUI1 */
  VarCyFromUI1(bIn: number, pcyOut: Win32Pointer): number;
  /** oleaut32.dll!VarCyFromUI2 */
  VarCyFromUI2(uiIn: number, pcyOut: Win32Pointer): number;
  /** oleaut32.dll!VarCyFromUI4 */
  VarCyFromUI4(ulIn: number, pcyOut: Win32Pointer): number;
  /** oleaut32.dll!VarCyFromUI8 */
  VarCyFromUI8(ui64In: number | bigint, pcyOut: Win32Pointer): number;
  /** oleaut32.dll!VarCyInt */
  VarCyInt(cyIn: Win32StructInit, pcyResult: Win32Pointer): number;
  /** oleaut32.dll!VarCyMul */
  VarCyMul(cyLeft: Win32StructInit, cyRight: Win32StructInit, pcyResult: Win32Pointer): number;
  /** oleaut32.dll!VarCyMulI4 */
  VarCyMulI4(cyLeft: Win32StructInit, lRight: number, pcyResult: Win32Pointer): number;
  /** oleaut32.dll!VarCyMulI8 */
  VarCyMulI8(cyLeft: Win32StructInit, lRight: number | bigint, pcyResult: Win32Pointer): number;
  /** oleaut32.dll!VarCyNeg */
  VarCyNeg(cyIn: Win32StructInit, pcyResult: Win32Pointer): number;
  /** oleaut32.dll!VarCyRound */
  VarCyRound(cyIn: Win32StructInit, cDecimals: number, pcyResult: Win32Pointer): number;
  /** oleaut32.dll!VarCySub */
  VarCySub(cyLeft: Win32StructInit, cyRight: Win32StructInit, pcyResult: Win32Pointer): number;
  /** oleaut32.dll!VarDateFromBool */
  VarDateFromBool(boolIn: number, pdateOut: Win32Pointer): number;
  /** oleaut32.dll!VarDateFromCy */
  VarDateFromCy(cyIn: Win32StructInit, pdateOut: Win32Pointer): number;
  /** oleaut32.dll!VarDateFromDec */
  VarDateFromDec(pdecIn: Win32Pointer, pdateOut: Win32Pointer): number;
  /** oleaut32.dll!VarDateFromDisp */
  VarDateFromDisp(pdispIn: Win32Pointer, lcid: number, pdateOut: Win32Pointer): number;
  /** oleaut32.dll!VarDateFromI1 */
  VarDateFromI1(cIn: number, pdateOut: Win32Pointer): number;
  /** oleaut32.dll!VarDateFromI2 */
  VarDateFromI2(sIn: number, pdateOut: Win32Pointer): number;
  /** oleaut32.dll!VarDateFromI4 */
  VarDateFromI4(lIn: number, pdateOut: Win32Pointer): number;
  /** oleaut32.dll!VarDateFromI8 */
  VarDateFromI8(i64In: number | bigint, pdateOut: Win32Pointer): number;
  /** oleaut32.dll!VarDateFromR4 */
  VarDateFromR4(fltIn: number, pdateOut: Win32Pointer): number;
  /** oleaut32.dll!VarDateFromR8 */
  VarDateFromR8(dblIn: number, pdateOut: Win32Pointer): number;
  /** oleaut32.dll!VarDateFromStr */
  VarDateFromStr(strIn: string | Win32Pointer, lcid: number, dwFlags: number, pdateOut: Win32Pointer): number;
  /** oleaut32.dll!VarDateFromUI1 */
  VarDateFromUI1(bIn: number, pdateOut: Win32Pointer): number;
  /** oleaut32.dll!VarDateFromUI2 */
  VarDateFromUI2(uiIn: number, pdateOut: Win32Pointer): number;
  /** oleaut32.dll!VarDateFromUI4 */
  VarDateFromUI4(ulIn: number, pdateOut: Win32Pointer): number;
  /** oleaut32.dll!VarDateFromUI8 */
  VarDateFromUI8(ui64In: number | bigint, pdateOut: Win32Pointer): number;
  /** oleaut32.dll!VarDateFromUdate */
  VarDateFromUdate(pudateIn: Win32Pointer, dwFlags: number, pdateOut: Win32Pointer): number;
  /** oleaut32.dll!VarDateFromUdateEx */
  VarDateFromUdateEx(pudateIn: Win32Pointer, lcid: number, dwFlags: number, pdateOut: Win32Pointer): number;
  /** oleaut32.dll!VarDecAbs */
  VarDecAbs(pdecIn: Win32Pointer, pdecResult: Win32Pointer): number;
  /** oleaut32.dll!VarDecAdd */
  VarDecAdd(pdecLeft: Win32Pointer, pdecRight: Win32Pointer, pdecResult: Win32Pointer): number;
  /** oleaut32.dll!VarDecCmp */
  VarDecCmp(pdecLeft: Win32Pointer, pdecRight: Win32Pointer): number;
  /** oleaut32.dll!VarDecCmpR8 */
  VarDecCmpR8(pdecLeft: Win32Pointer, dblRight: number): number;
  /** oleaut32.dll!VarDecDiv */
  VarDecDiv(pdecLeft: Win32Pointer, pdecRight: Win32Pointer, pdecResult: Win32Pointer): number;
  /** oleaut32.dll!VarDecFix */
  VarDecFix(pdecIn: Win32Pointer, pdecResult: Win32Pointer): number;
  /** oleaut32.dll!VarDecFromBool */
  VarDecFromBool(boolIn: number, pdecOut: Win32Pointer): number;
  /** oleaut32.dll!VarDecFromCy */
  VarDecFromCy(cyIn: Win32StructInit, pdecOut: Win32Pointer): number;
  /** oleaut32.dll!VarDecFromDate */
  VarDecFromDate(dateIn: number, pdecOut: Win32Pointer): number;
  /** oleaut32.dll!VarDecFromDisp */
  VarDecFromDisp(pdispIn: Win32Pointer, lcid: number, pdecOut: Win32Pointer): number;
  /** oleaut32.dll!VarDecFromI1 */
  VarDecFromI1(cIn: number, pdecOut: Win32Pointer): number;
  /** oleaut32.dll!VarDecFromI2 */
  VarDecFromI2(uiIn: number, pdecOut: Win32Pointer): number;
  /** oleaut32.dll!VarDecFromI4 */
  VarDecFromI4(lIn: number, pdecOut: Win32Pointer): number;
  /** oleaut32.dll!VarDecFromI8 */
  VarDecFromI8(i64In: number | bigint, pdecOut: Win32Pointer): number;
  /** oleaut32.dll!VarDecFromR4 */
  VarDecFromR4(fltIn: number, pdecOut: Win32Pointer): number;
  /** oleaut32.dll!VarDecFromR8 */
  VarDecFromR8(dblIn: number, pdecOut: Win32Pointer): number;
  /** oleaut32.dll!VarDecFromStr */
  VarDecFromStr(strIn: string | Win32Pointer, lcid: number, dwFlags: number, pdecOut: Win32Pointer): number;
  /** oleaut32.dll!VarDecFromUI1 */
  VarDecFromUI1(bIn: number, pdecOut: Win32Pointer): number;
  /** oleaut32.dll!VarDecFromUI2 */
  VarDecFromUI2(uiIn: number, pdecOut: Win32Pointer): number;
  /** oleaut32.dll!VarDecFromUI4 */
  VarDecFromUI4(ulIn: number, pdecOut: Win32Pointer): number;
  /** oleaut32.dll!VarDecFromUI8 */
  VarDecFromUI8(ui64In: number | bigint, pdecOut: Win32Pointer): number;
  /** oleaut32.dll!VarDecInt */
  VarDecInt(pdecIn: Win32Pointer, pdecResult: Win32Pointer): number;
  /** oleaut32.dll!VarDecMul */
  VarDecMul(pdecLeft: Win32Pointer, pdecRight: Win32Pointer, pdecResult: Win32Pointer): number;
  /** oleaut32.dll!VarDecNeg */
  VarDecNeg(pdecIn: Win32Pointer, pdecResult: Win32Pointer): number;
  /** oleaut32.dll!VarDecRound */
  VarDecRound(pdecIn: Win32Pointer, cDecimals: number, pdecResult: Win32Pointer): number;
  /** oleaut32.dll!VarDecSub */
  VarDecSub(pdecLeft: Win32Pointer, pdecRight: Win32Pointer, pdecResult: Win32Pointer): number;
  /** oleaut32.dll!VarDiv */
  VarDiv(pvarLeft: Win32Pointer, pvarRight: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarEqv */
  VarEqv(pvarLeft: Win32Pointer, pvarRight: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarFix */
  VarFix(pvarIn: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarFormat */
  VarFormat(pvarIn: Win32Pointer, pstrFormat: string | Win32Pointer, iFirstDay: number, iFirstWeek: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarFormatCurrency */
  VarFormatCurrency(pvarIn: Win32Pointer, iNumDig: number, iIncLead: number, iUseParens: number, iGroup: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarFormatDateTime */
  VarFormatDateTime(pvarIn: Win32Pointer, iNamedFormat: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarFormatFromTokens */
  VarFormatFromTokens(pvarIn: Win32Pointer, pstrFormat: string | Win32Pointer, pbTokCur: Win32Pointer, dwFlags: number, pbstrOut: Win32Pointer, lcid: number): number;
  /** oleaut32.dll!VarFormatNumber */
  VarFormatNumber(pvarIn: Win32Pointer, iNumDig: number, iIncLead: number, iUseParens: number, iGroup: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarFormatPercent */
  VarFormatPercent(pvarIn: Win32Pointer, iNumDig: number, iIncLead: number, iUseParens: number, iGroup: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarI1FromBool */
  VarI1FromBool(boolIn: number, pcOut: string | Win32Pointer): number;
  /** oleaut32.dll!VarI1FromCy */
  VarI1FromCy(cyIn: Win32StructInit, pcOut: string | Win32Pointer): number;
  /** oleaut32.dll!VarI1FromDate */
  VarI1FromDate(dateIn: number, pcOut: string | Win32Pointer): number;
  /** oleaut32.dll!VarI1FromDec */
  VarI1FromDec(pdecIn: Win32Pointer, pcOut: string | Win32Pointer): number;
  /** oleaut32.dll!VarI1FromDisp */
  VarI1FromDisp(pdispIn: Win32Pointer, lcid: number, pcOut: string | Win32Pointer): number;
  /** oleaut32.dll!VarI1FromI2 */
  VarI1FromI2(uiIn: number, pcOut: string | Win32Pointer): number;
  /** oleaut32.dll!VarI1FromI4 */
  VarI1FromI4(lIn: number, pcOut: string | Win32Pointer): number;
  /** oleaut32.dll!VarI1FromI8 */
  VarI1FromI8(i64In: number | bigint, pcOut: string | Win32Pointer): number;
  /** oleaut32.dll!VarI1FromR4 */
  VarI1FromR4(fltIn: number, pcOut: string | Win32Pointer): number;
  /** oleaut32.dll!VarI1FromR8 */
  VarI1FromR8(dblIn: number, pcOut: string | Win32Pointer): number;
  /** oleaut32.dll!VarI1FromStr */
  VarI1FromStr(strIn: string | Win32Pointer, lcid: number, dwFlags: number, pcOut: string | Win32Pointer): number;
  /** oleaut32.dll!VarI1FromUI1 */
  VarI1FromUI1(bIn: number, pcOut: string | Win32Pointer): number;
  /** oleaut32.dll!VarI1FromUI2 */
  VarI1FromUI2(uiIn: number, pcOut: string | Win32Pointer): number;
  /** oleaut32.dll!VarI1FromUI4 */
  VarI1FromUI4(ulIn: number, pcOut: string | Win32Pointer): number;
  /** oleaut32.dll!VarI1FromUI8 */
  VarI1FromUI8(i64In: number | bigint, pcOut: string | Win32Pointer): number;
  /** oleaut32.dll!VarI2FromBool */
  VarI2FromBool(boolIn: number, psOut: Win32Pointer): number;
  /** oleaut32.dll!VarI2FromCy */
  VarI2FromCy(cyIn: Win32StructInit, psOut: Win32Pointer): number;
  /** oleaut32.dll!VarI2FromDate */
  VarI2FromDate(dateIn: number, psOut: Win32Pointer): number;
  /** oleaut32.dll!VarI2FromDec */
  VarI2FromDec(pdecIn: Win32Pointer, psOut: Win32Pointer): number;
  /** oleaut32.dll!VarI2FromDisp */
  VarI2FromDisp(pdispIn: Win32Pointer, lcid: number, psOut: Win32Pointer): number;
  /** oleaut32.dll!VarI2FromI1 */
  VarI2FromI1(cIn: number, psOut: Win32Pointer): number;
  /** oleaut32.dll!VarI2FromI4 */
  VarI2FromI4(lIn: number, psOut: Win32Pointer): number;
  /** oleaut32.dll!VarI2FromI8 */
  VarI2FromI8(i64In: number | bigint, psOut: Win32Pointer): number;
  /** oleaut32.dll!VarI2FromR4 */
  VarI2FromR4(fltIn: number, psOut: Win32Pointer): number;
  /** oleaut32.dll!VarI2FromR8 */
  VarI2FromR8(dblIn: number, psOut: Win32Pointer): number;
  /** oleaut32.dll!VarI2FromStr */
  VarI2FromStr(strIn: string | Win32Pointer, lcid: number, dwFlags: number, psOut: Win32Pointer): number;
  /** oleaut32.dll!VarI2FromUI1 */
  VarI2FromUI1(bIn: number, psOut: Win32Pointer): number;
  /** oleaut32.dll!VarI2FromUI2 */
  VarI2FromUI2(uiIn: number, psOut: Win32Pointer): number;
  /** oleaut32.dll!VarI2FromUI4 */
  VarI2FromUI4(ulIn: number, psOut: Win32Pointer): number;
  /** oleaut32.dll!VarI2FromUI8 */
  VarI2FromUI8(ui64In: number | bigint, psOut: Win32Pointer): number;
  /** oleaut32.dll!VarI4FromBool */
  VarI4FromBool(boolIn: number, plOut: Win32Pointer): number;
  /** oleaut32.dll!VarI4FromCy */
  VarI4FromCy(cyIn: Win32StructInit, plOut: Win32Pointer): number;
  /** oleaut32.dll!VarI4FromDate */
  VarI4FromDate(dateIn: number, plOut: Win32Pointer): number;
  /** oleaut32.dll!VarI4FromDec */
  VarI4FromDec(pdecIn: Win32Pointer, plOut: Win32Pointer): number;
  /** oleaut32.dll!VarI4FromDisp */
  VarI4FromDisp(pdispIn: Win32Pointer, lcid: number, plOut: Win32Pointer): number;
  /** oleaut32.dll!VarI4FromI1 */
  VarI4FromI1(cIn: number, plOut: Win32Pointer): number;
  /** oleaut32.dll!VarI4FromI2 */
  VarI4FromI2(sIn: number, plOut: Win32Pointer): number;
  /** oleaut32.dll!VarI4FromI8 */
  VarI4FromI8(i64In: number | bigint, plOut: Win32Pointer): number;
  /** oleaut32.dll!VarI4FromR4 */
  VarI4FromR4(fltIn: number, plOut: Win32Pointer): number;
  /** oleaut32.dll!VarI4FromR8 */
  VarI4FromR8(dblIn: number, plOut: Win32Pointer): number;
  /** oleaut32.dll!VarI4FromStr */
  VarI4FromStr(strIn: string | Win32Pointer, lcid: number, dwFlags: number, plOut: Win32Pointer): number;
  /** oleaut32.dll!VarI4FromUI1 */
  VarI4FromUI1(bIn: number, plOut: Win32Pointer): number;
  /** oleaut32.dll!VarI4FromUI2 */
  VarI4FromUI2(uiIn: number, plOut: Win32Pointer): number;
  /** oleaut32.dll!VarI4FromUI4 */
  VarI4FromUI4(ulIn: number, plOut: Win32Pointer): number;
  /** oleaut32.dll!VarI4FromUI8 */
  VarI4FromUI8(ui64In: number | bigint, plOut: Win32Pointer): number;
  /** oleaut32.dll!VarI8FromBool */
  VarI8FromBool(boolIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarI8FromCy */
  VarI8FromCy(cyIn: Win32StructInit, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarI8FromDate */
  VarI8FromDate(dateIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarI8FromDec */
  VarI8FromDec(pdecIn: Win32Pointer, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarI8FromDisp */
  VarI8FromDisp(pdispIn: Win32Pointer, lcid: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarI8FromI1 */
  VarI8FromI1(cIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarI8FromI2 */
  VarI8FromI2(sIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarI8FromR4 */
  VarI8FromR4(fltIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarI8FromR8 */
  VarI8FromR8(dblIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarI8FromStr */
  VarI8FromStr(strIn: string | Win32Pointer, lcid: number, dwFlags: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarI8FromUI1 */
  VarI8FromUI1(bIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarI8FromUI2 */
  VarI8FromUI2(uiIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarI8FromUI4 */
  VarI8FromUI4(ulIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarI8FromUI8 */
  VarI8FromUI8(ui64In: number | bigint, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarIdiv */
  VarIdiv(pvarLeft: Win32Pointer, pvarRight: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarImp */
  VarImp(pvarLeft: Win32Pointer, pvarRight: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarInt */
  VarInt(pvarIn: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarMod */
  VarMod(pvarLeft: Win32Pointer, pvarRight: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarMonthName */
  VarMonthName(iMonth: number, fAbbrev: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarMul */
  VarMul(pvarLeft: Win32Pointer, pvarRight: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarNeg */
  VarNeg(pvarIn: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarNot */
  VarNot(pvarIn: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarNumFromParseNum */
  VarNumFromParseNum(pnumprs: Win32Pointer, rgbDig: Win32Pointer, dwVtBits: number, pvar: Win32Pointer): number;
  /** oleaut32.dll!VarOr */
  VarOr(pvarLeft: Win32Pointer, pvarRight: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarParseNumFromStr */
  VarParseNumFromStr(strIn: string | Win32Pointer, lcid: number, dwFlags: number, pnumprs: Win32Pointer, rgbDig: Win32Pointer): number;
  /** oleaut32.dll!VarPow */
  VarPow(pvarLeft: Win32Pointer, pvarRight: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarR4CmpR8 */
  VarR4CmpR8(fltLeft: number, dblRight: number): number;
  /** oleaut32.dll!VarR4FromBool */
  VarR4FromBool(boolIn: number, pfltOut: Win32Pointer): number;
  /** oleaut32.dll!VarR4FromCy */
  VarR4FromCy(cyIn: Win32StructInit, pfltOut: Win32Pointer): number;
  /** oleaut32.dll!VarR4FromDate */
  VarR4FromDate(dateIn: number, pfltOut: Win32Pointer): number;
  /** oleaut32.dll!VarR4FromDec */
  VarR4FromDec(pdecIn: Win32Pointer, pfltOut: Win32Pointer): number;
  /** oleaut32.dll!VarR4FromDisp */
  VarR4FromDisp(pdispIn: Win32Pointer, lcid: number, pfltOut: Win32Pointer): number;
  /** oleaut32.dll!VarR4FromI1 */
  VarR4FromI1(cIn: number, pfltOut: Win32Pointer): number;
  /** oleaut32.dll!VarR4FromI2 */
  VarR4FromI2(sIn: number, pfltOut: Win32Pointer): number;
  /** oleaut32.dll!VarR4FromI4 */
  VarR4FromI4(lIn: number, pfltOut: Win32Pointer): number;
  /** oleaut32.dll!VarR4FromI8 */
  VarR4FromI8(i64In: number | bigint, pfltOut: Win32Pointer): number;
  /** oleaut32.dll!VarR4FromR8 */
  VarR4FromR8(dblIn: number, pfltOut: Win32Pointer): number;
  /** oleaut32.dll!VarR4FromStr */
  VarR4FromStr(strIn: string | Win32Pointer, lcid: number, dwFlags: number, pfltOut: Win32Pointer): number;
  /** oleaut32.dll!VarR4FromUI1 */
  VarR4FromUI1(bIn: number, pfltOut: Win32Pointer): number;
  /** oleaut32.dll!VarR4FromUI2 */
  VarR4FromUI2(uiIn: number, pfltOut: Win32Pointer): number;
  /** oleaut32.dll!VarR4FromUI4 */
  VarR4FromUI4(ulIn: number, pfltOut: Win32Pointer): number;
  /** oleaut32.dll!VarR4FromUI8 */
  VarR4FromUI8(ui64In: number | bigint, pfltOut: Win32Pointer): number;
  /** oleaut32.dll!VarR8FromBool */
  VarR8FromBool(boolIn: number, pdblOut: Win32Pointer): number;
  /** oleaut32.dll!VarR8FromCy */
  VarR8FromCy(cyIn: Win32StructInit, pdblOut: Win32Pointer): number;
  /** oleaut32.dll!VarR8FromDate */
  VarR8FromDate(dateIn: number, pdblOut: Win32Pointer): number;
  /** oleaut32.dll!VarR8FromDec */
  VarR8FromDec(pdecIn: Win32Pointer, pdblOut: Win32Pointer): number;
  /** oleaut32.dll!VarR8FromDisp */
  VarR8FromDisp(pdispIn: Win32Pointer, lcid: number, pdblOut: Win32Pointer): number;
  /** oleaut32.dll!VarR8FromI1 */
  VarR8FromI1(cIn: number, pdblOut: Win32Pointer): number;
  /** oleaut32.dll!VarR8FromI2 */
  VarR8FromI2(sIn: number, pdblOut: Win32Pointer): number;
  /** oleaut32.dll!VarR8FromI4 */
  VarR8FromI4(lIn: number, pdblOut: Win32Pointer): number;
  /** oleaut32.dll!VarR8FromI8 */
  VarR8FromI8(i64In: number | bigint, pdblOut: Win32Pointer): number;
  /** oleaut32.dll!VarR8FromR4 */
  VarR8FromR4(fltIn: number, pdblOut: Win32Pointer): number;
  /** oleaut32.dll!VarR8FromStr */
  VarR8FromStr(strIn: string | Win32Pointer, lcid: number, dwFlags: number, pdblOut: Win32Pointer): number;
  /** oleaut32.dll!VarR8FromUI1 */
  VarR8FromUI1(bIn: number, pdblOut: Win32Pointer): number;
  /** oleaut32.dll!VarR8FromUI2 */
  VarR8FromUI2(uiIn: number, pdblOut: Win32Pointer): number;
  /** oleaut32.dll!VarR8FromUI4 */
  VarR8FromUI4(ulIn: number, pdblOut: Win32Pointer): number;
  /** oleaut32.dll!VarR8FromUI8 */
  VarR8FromUI8(ui64In: number | bigint, pdblOut: Win32Pointer): number;
  /** oleaut32.dll!VarR8Pow */
  VarR8Pow(dblLeft: number, dblRight: number, pdblResult: Win32Pointer): number;
  /** oleaut32.dll!VarR8Round */
  VarR8Round(dblIn: number, cDecimals: number, pdblResult: Win32Pointer): number;
  /** oleaut32.dll!VarRound */
  VarRound(pvarIn: Win32Pointer, cDecimals: number, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarSub */
  VarSub(pvarLeft: Win32Pointer, pvarRight: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VarTokenizeFormatString */
  VarTokenizeFormatString(pstrFormat: string | Win32Pointer, rgbTok: Win32Pointer, cbTok: number, iFirstDay: number, iFirstWeek: number, lcid: number, pcbActual: Win32Pointer): number;
  /** oleaut32.dll!VarUI1FromBool */
  VarUI1FromBool(boolIn: number, pbOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI1FromCy */
  VarUI1FromCy(cyIn: Win32StructInit, pbOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI1FromDate */
  VarUI1FromDate(dateIn: number, pbOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI1FromDec */
  VarUI1FromDec(pdecIn: Win32Pointer, pbOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI1FromDisp */
  VarUI1FromDisp(pdispIn: Win32Pointer, lcid: number, pbOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI1FromI1 */
  VarUI1FromI1(cIn: number, pbOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI1FromI2 */
  VarUI1FromI2(sIn: number, pbOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI1FromI4 */
  VarUI1FromI4(lIn: number, pbOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI1FromI8 */
  VarUI1FromI8(i64In: number | bigint, pbOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI1FromR4 */
  VarUI1FromR4(fltIn: number, pbOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI1FromR8 */
  VarUI1FromR8(dblIn: number, pbOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI1FromStr */
  VarUI1FromStr(strIn: string | Win32Pointer, lcid: number, dwFlags: number, pbOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI1FromUI2 */
  VarUI1FromUI2(uiIn: number, pbOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI1FromUI4 */
  VarUI1FromUI4(ulIn: number, pbOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI1FromUI8 */
  VarUI1FromUI8(ui64In: number | bigint, pbOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI2FromBool */
  VarUI2FromBool(boolIn: number, puiOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI2FromCy */
  VarUI2FromCy(cyIn: Win32StructInit, puiOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI2FromDate */
  VarUI2FromDate(dateIn: number, puiOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI2FromDec */
  VarUI2FromDec(pdecIn: Win32Pointer, puiOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI2FromDisp */
  VarUI2FromDisp(pdispIn: Win32Pointer, lcid: number, puiOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI2FromI1 */
  VarUI2FromI1(cIn: number, puiOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI2FromI2 */
  VarUI2FromI2(uiIn: number, puiOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI2FromI4 */
  VarUI2FromI4(lIn: number, puiOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI2FromI8 */
  VarUI2FromI8(i64In: number | bigint, puiOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI2FromR4 */
  VarUI2FromR4(fltIn: number, puiOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI2FromR8 */
  VarUI2FromR8(dblIn: number, puiOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI2FromStr */
  VarUI2FromStr(strIn: string | Win32Pointer, lcid: number, dwFlags: number, puiOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI2FromUI1 */
  VarUI2FromUI1(bIn: number, puiOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI2FromUI4 */
  VarUI2FromUI4(ulIn: number, puiOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI2FromUI8 */
  VarUI2FromUI8(i64In: number | bigint, puiOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI4FromBool */
  VarUI4FromBool(boolIn: number, pulOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI4FromCy */
  VarUI4FromCy(cyIn: Win32StructInit, pulOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI4FromDate */
  VarUI4FromDate(dateIn: number, pulOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI4FromDec */
  VarUI4FromDec(pdecIn: Win32Pointer, pulOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI4FromDisp */
  VarUI4FromDisp(pdispIn: Win32Pointer, lcid: number, pulOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI4FromI1 */
  VarUI4FromI1(cIn: number, pulOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI4FromI2 */
  VarUI4FromI2(uiIn: number, pulOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI4FromI4 */
  VarUI4FromI4(lIn: number, pulOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI4FromI8 */
  VarUI4FromI8(i64In: number | bigint, plOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI4FromR4 */
  VarUI4FromR4(fltIn: number, pulOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI4FromR8 */
  VarUI4FromR8(dblIn: number, pulOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI4FromStr */
  VarUI4FromStr(strIn: string | Win32Pointer, lcid: number, dwFlags: number, pulOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI4FromUI1 */
  VarUI4FromUI1(bIn: number, pulOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI4FromUI2 */
  VarUI4FromUI2(uiIn: number, pulOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI4FromUI8 */
  VarUI4FromUI8(ui64In: number | bigint, plOut: Win32Pointer): number;
  /** oleaut32.dll!VarUI8FromBool */
  VarUI8FromBool(boolIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarUI8FromCy */
  VarUI8FromCy(cyIn: Win32StructInit, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarUI8FromDate */
  VarUI8FromDate(dateIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarUI8FromDec */
  VarUI8FromDec(pdecIn: Win32Pointer, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarUI8FromDisp */
  VarUI8FromDisp(pdispIn: Win32Pointer, lcid: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarUI8FromI1 */
  VarUI8FromI1(cIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarUI8FromI2 */
  VarUI8FromI2(sIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarUI8FromI8 */
  VarUI8FromI8(ui64In: number | bigint, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarUI8FromR4 */
  VarUI8FromR4(fltIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarUI8FromR8 */
  VarUI8FromR8(dblIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarUI8FromStr */
  VarUI8FromStr(strIn: string | Win32Pointer, lcid: number, dwFlags: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarUI8FromUI1 */
  VarUI8FromUI1(bIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarUI8FromUI2 */
  VarUI8FromUI2(uiIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarUI8FromUI4 */
  VarUI8FromUI4(ulIn: number, pi64Out: Win32Pointer): number;
  /** oleaut32.dll!VarUdateFromDate */
  VarUdateFromDate(dateIn: number, dwFlags: number, pudateOut: Win32Pointer): number;
  /** oleaut32.dll!VarWeekdayName */
  VarWeekdayName(iWeekday: number, fAbbrev: number, iFirstDay: number, dwFlags: number, pbstrOut: Win32Pointer): number;
  /** oleaut32.dll!VarXor */
  VarXor(pvarLeft: Win32Pointer, pvarRight: Win32Pointer, pvarResult: Win32Pointer): number;
  /** oleaut32.dll!VariantChangeType */
  VariantChangeType(pvargDest: Win32Pointer, pvarSrc: Win32Pointer, wFlags: number, vt: number): number;
  /** oleaut32.dll!VariantChangeTypeEx */
  VariantChangeTypeEx(pvargDest: Win32Pointer, pvarSrc: Win32Pointer, lcid: number, wFlags: number, vt: number): number;
  /** oleaut32.dll!VariantClear */
  VariantClear(pvarg: Win32Pointer): number;
  /** oleaut32.dll!VariantCopy */
  VariantCopy(pvargDest: Win32Pointer, pvargSrc: Win32Pointer): number;
  /** oleaut32.dll!VariantCopyInd */
  VariantCopyInd(pvarDest: Win32Pointer, pvargSrc: Win32Pointer): number;
  /** oleaut32.dll!VariantInit */
  VariantInit(pvarg: Win32Pointer): void;
  /** oleaut32.dll!VariantTimeToDosDateTime */
  VariantTimeToDosDateTime(vtime: number, pwDosDate: Win32Pointer, pwDosTime: Win32Pointer): number;
  /** oleaut32.dll!VariantTimeToSystemTime */
  VariantTimeToSystemTime(vtime: number, lpSystemTime: Win32Pointer): number;
  /** oleaut32.dll!VectorFromBstr */
  VectorFromBstr(bstr: string | Win32Pointer, ppsa: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
