// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** wintrust.dll!CryptCATAdminAcquireContext */
  CryptCATAdminAcquireContext(phCatAdmin: Win32Pointer, pgSubsystem: Win32Pointer, dwFlags: number): number;
  /** wintrust.dll!CryptCATAdminAcquireContext2 */
  CryptCATAdminAcquireContext2(phCatAdmin: Win32Pointer, pgSubsystem: Win32Pointer, pwszHashAlgorithm: string | Win32Pointer, pStrongHashPolicy: Win32Pointer, dwFlags: number): number;
  /** wintrust.dll!CryptCATAdminAddCatalog */
  CryptCATAdminAddCatalog(hCatAdmin: number | bigint, pwszCatalogFile: string | Win32Pointer, pwszSelectBaseName: string | Win32Pointer, dwFlags: number): number | bigint;
  /** wintrust.dll!CryptCATAdminCalcHashFromFileHandle */
  CryptCATAdminCalcHashFromFileHandle(hFile: Win32Pointer, pcbHash: Win32Pointer, pbHash: Win32Pointer, dwFlags: number): number;
  /** wintrust.dll!CryptCATAdminCalcHashFromFileHandle2 */
  CryptCATAdminCalcHashFromFileHandle2(hCatAdmin: number | bigint, hFile: Win32Pointer, pcbHash: Win32Pointer, pbHash: Win32Pointer, dwFlags: number): number;
  /** wintrust.dll!CryptCATAdminEnumCatalogFromHash */
  CryptCATAdminEnumCatalogFromHash(hCatAdmin: number | bigint, pbHash: Win32Pointer, cbHash: number, dwFlags: number, phPrevCatInfo: Win32Pointer): number | bigint;
  /** wintrust.dll!CryptCATAdminPauseServiceForBackup */
  CryptCATAdminPauseServiceForBackup(dwFlags: number, fResume: number): number;
  /** wintrust.dll!CryptCATAdminReleaseCatalogContext */
  CryptCATAdminReleaseCatalogContext(hCatAdmin: number | bigint, hCatInfo: number | bigint, dwFlags: number): number;
  /** wintrust.dll!CryptCATAdminReleaseContext */
  CryptCATAdminReleaseContext(hCatAdmin: number | bigint, dwFlags: number): number;
  /** wintrust.dll!CryptCATAdminRemoveCatalog */
  CryptCATAdminRemoveCatalog(hCatAdmin: number | bigint, pwszCatalogFile: string | Win32Pointer, dwFlags: number): number;
  /** wintrust.dll!CryptCATAdminResolveCatalogPath */
  CryptCATAdminResolveCatalogPath(hCatAdmin: number | bigint, pwszCatalogFile: string | Win32Pointer, psCatInfo: Win32Pointer, dwFlags: number): number;
  /** wintrust.dll!CryptCATAllocSortedMemberInfo */
  CryptCATAllocSortedMemberInfo(hCatalog: Win32Pointer, pwszReferenceTag: string | Win32Pointer): number | null;
  /** wintrust.dll!CryptCATCDFClose */
  CryptCATCDFClose(pCDF: Win32Pointer): number;
  /** wintrust.dll!CryptCATCDFEnumAttributes */
  CryptCATCDFEnumAttributes(pCDF: Win32Pointer, pMember: Win32Pointer, pPrevAttr: Win32Pointer, pfnParseError: Win32Callback): number | null;
  /** wintrust.dll!CryptCATCDFEnumAttributesWithCDFTag */
  CryptCATCDFEnumAttributesWithCDFTag(pCDF: Win32Pointer, pwszMemberTag: string | Win32Pointer, pMember: Win32Pointer, pPrevAttr: Win32Pointer, pfnParseError: Win32Callback): number | null;
  /** wintrust.dll!CryptCATCDFEnumCatAttributes */
  CryptCATCDFEnumCatAttributes(pCDF: Win32Pointer, pPrevAttr: Win32Pointer, pfnParseError: Win32Callback): number | null;
  /** wintrust.dll!CryptCATCDFEnumMembers */
  CryptCATCDFEnumMembers(pCDF: Win32Pointer, pPrevMember: Win32Pointer, pfnParseError: Win32Callback): number | null;
  /** wintrust.dll!CryptCATCDFEnumMembersByCDFTagEx */
  CryptCATCDFEnumMembersByCDFTagEx(pCDF: Win32Pointer, pwszPrevCDFTag: string | Win32Pointer, pfnParseError: Win32Callback, ppMember: Win32Pointer, fContinueOnError: number, pvReserved: Win32Pointer): number | null;
  /** wintrust.dll!CryptCATCDFOpen */
  CryptCATCDFOpen(pwszFilePath: string | Win32Pointer, pfnParseError: Win32Callback): number | null;
  /** wintrust.dll!CryptCATCatalogInfoFromContext */
  CryptCATCatalogInfoFromContext(hCatInfo: number | bigint, psCatInfo: Win32Pointer, dwFlags: number): number;
  /** wintrust.dll!CryptCATClose */
  CryptCATClose(hCatalog: Win32Pointer): number;
  /** wintrust.dll!CryptCATEnumerateAttr */
  CryptCATEnumerateAttr(hCatalog: Win32Pointer, pCatMember: Win32Pointer, pPrevAttr: Win32Pointer): number | null;
  /** wintrust.dll!CryptCATEnumerateCatAttr */
  CryptCATEnumerateCatAttr(hCatalog: Win32Pointer, pPrevAttr: Win32Pointer): number | null;
  /** wintrust.dll!CryptCATEnumerateMember */
  CryptCATEnumerateMember(hCatalog: Win32Pointer, pPrevMember: Win32Pointer): number | null;
  /** wintrust.dll!CryptCATFreeSortedMemberInfo */
  CryptCATFreeSortedMemberInfo(hCatalog: Win32Pointer, pCatMember: Win32Pointer): void;
  /** wintrust.dll!CryptCATGetAttrInfo */
  CryptCATGetAttrInfo(hCatalog: Win32Pointer, pCatMember: Win32Pointer, pwszReferenceTag: string | Win32Pointer): number | null;
  /** wintrust.dll!CryptCATGetCatAttrInfo */
  CryptCATGetCatAttrInfo(hCatalog: Win32Pointer, pwszReferenceTag: string | Win32Pointer): number | null;
  /** wintrust.dll!CryptCATGetMemberInfo */
  CryptCATGetMemberInfo(hCatalog: Win32Pointer, pwszReferenceTag: string | Win32Pointer): number | null;
  /** wintrust.dll!CryptCATHandleFromStore */
  CryptCATHandleFromStore(pCatStore: Win32Pointer): number | null;
  /** wintrust.dll!CryptCATOpen */
  CryptCATOpen(pwszFileName: string | Win32Pointer, fdwOpenFlags: number, hProv: number | bigint, dwPublicVersion: number, dwEncodingType: number): number | null;
  /** wintrust.dll!CryptCATPersistStore */
  CryptCATPersistStore(hCatalog: Win32Pointer): number;
  /** wintrust.dll!CryptCATPutAttrInfo */
  CryptCATPutAttrInfo(hCatalog: Win32Pointer, pCatMember: Win32Pointer, pwszReferenceTag: string | Win32Pointer, dwAttrTypeAndAction: number, cbData: number, pbData: Win32Pointer): number | null;
  /** wintrust.dll!CryptCATPutCatAttrInfo */
  CryptCATPutCatAttrInfo(hCatalog: Win32Pointer, pwszReferenceTag: string | Win32Pointer, dwAttrTypeAndAction: number, cbData: number, pbData: Win32Pointer): number | null;
  /** wintrust.dll!CryptCATPutMemberInfo */
  CryptCATPutMemberInfo(hCatalog: Win32Pointer, pwszFileName: string | Win32Pointer, pwszReferenceTag: string | Win32Pointer, pgSubjectType: Win32Pointer, dwCertVersion: number, cbSIPIndirectData: number, pbSIPIndirectData: Win32Pointer): number | null;
  /** wintrust.dll!CryptCATStoreFromHandle */
  CryptCATStoreFromHandle(hCatalog: Win32Pointer): number | null;
  /** wintrust.dll!CryptSIPCreateIndirectData */
  CryptSIPCreateIndirectData(pSubjectInfo: Win32Pointer, pcbIndirectData: Win32Pointer, pIndirectData: Win32Pointer): number;
  /** wintrust.dll!CryptSIPGetCaps */
  CryptSIPGetCaps(pSubjInfo: Win32Pointer, pCaps: Win32Pointer): number;
  /** wintrust.dll!CryptSIPGetSealedDigest */
  CryptSIPGetSealedDigest(pSubjectInfo: Win32Pointer, pSig: Win32Pointer, dwSig: number, pbDigest: Win32Pointer, pcbDigest: Win32Pointer): number;
  /** wintrust.dll!CryptSIPGetSignedDataMsg */
  CryptSIPGetSignedDataMsg(pSubjectInfo: Win32Pointer, pdwEncodingType: Win32Pointer, dwIndex: number, pcbSignedDataMsg: Win32Pointer, pbSignedDataMsg: Win32Pointer): number;
  /** wintrust.dll!CryptSIPPutSignedDataMsg */
  CryptSIPPutSignedDataMsg(pSubjectInfo: Win32Pointer, dwEncodingType: number, pdwIndex: Win32Pointer, cbSignedDataMsg: number, pbSignedDataMsg: Win32Pointer): number;
  /** wintrust.dll!CryptSIPRemoveSignedDataMsg */
  CryptSIPRemoveSignedDataMsg(pSubjectInfo: Win32Pointer, dwIndex: number): number;
  /** wintrust.dll!CryptSIPVerifyIndirectData */
  CryptSIPVerifyIndirectData(pSubjectInfo: Win32Pointer, pIndirectData: Win32Pointer): number;
  /** wintrust.dll!FindCertsByIssuer */
  FindCertsByIssuer(pCertChains: Win32Pointer, pcbCertChains: Win32Pointer, pcCertChains: Win32Pointer, pbEncodedIssuerName: Win32Pointer, cbEncodedIssuerName: number, pwszPurpose: string | Win32Pointer, dwKeySpec: number): number;
  /** wintrust.dll!IsCatalogFile */
  IsCatalogFile(hFile: Win32Pointer, pwszFileName: string | Win32Pointer): number;
  /** wintrust.dll!OpenPersonalTrustDBDialog */
  OpenPersonalTrustDBDialog(hwndParent: Win32Pointer): number;
  /** wintrust.dll!OpenPersonalTrustDBDialogEx */
  OpenPersonalTrustDBDialogEx(hwndParent: Win32Pointer, dwFlags: number, pvReserved: Win32Pointer): number;
  /** wintrust.dll!WTHelperCertCheckValidSignature */
  WTHelperCertCheckValidSignature(pProvData: Win32Pointer): number;
  /** wintrust.dll!WTHelperCertIsSelfSigned */
  WTHelperCertIsSelfSigned(dwEncoding: number, pCert: Win32Pointer): number;
  /** wintrust.dll!WTHelperGetProvCertFromChain */
  WTHelperGetProvCertFromChain(pSgnr: Win32Pointer, idxCert: number): number | null;
  /** wintrust.dll!WTHelperGetProvPrivateDataFromChain */
  WTHelperGetProvPrivateDataFromChain(pProvData: Win32Pointer, pgProviderID: Win32Pointer): number | null;
  /** wintrust.dll!WTHelperGetProvSignerFromChain */
  WTHelperGetProvSignerFromChain(pProvData: Win32Pointer, idxSigner: number, fCounterSigner: number, idxCounterSigner: number): number | null;
  /** wintrust.dll!WTHelperProvDataFromStateData */
  WTHelperProvDataFromStateData(hStateData: Win32Pointer): number | null;
  /** wintrust.dll!WinVerifyTrust */
  WinVerifyTrust(hwnd: Win32Pointer, pgActionID: Win32Pointer, pWVTData: Win32Pointer): number;
  /** wintrust.dll!WinVerifyTrustEx */
  WinVerifyTrustEx(hwnd: Win32Pointer, pgActionID: Win32Pointer, pWinTrustData: Win32Pointer): number;
  /** wintrust.dll!WintrustAddActionID */
  WintrustAddActionID(pgActionID: Win32Pointer, fdwFlags: number, psProvInfo: Win32Pointer): number;
  /** wintrust.dll!WintrustAddDefaultForUsage */
  WintrustAddDefaultForUsage(pszUsageOID: string | Win32Pointer, psDefUsage: Win32Pointer): number;
  /** wintrust.dll!WintrustGetDefaultForUsage */
  WintrustGetDefaultForUsage(dwAction: number, pszUsageOID: string | Win32Pointer, psUsage: Win32Pointer): number;
  /** wintrust.dll!WintrustGetRegPolicyFlags */
  WintrustGetRegPolicyFlags(pdwPolicyFlags: Win32Pointer): void;
  /** wintrust.dll!WintrustLoadFunctionPointers */
  WintrustLoadFunctionPointers(pgActionID: Win32Pointer, pPfns: Win32Pointer): number;
  /** wintrust.dll!WintrustRemoveActionID */
  WintrustRemoveActionID(pgActionID: Win32Pointer): number;
  /** wintrust.dll!WintrustSetDefaultIncludePEPageHashes */
  WintrustSetDefaultIncludePEPageHashes(fIncludePEPageHashes: number): void;
  /** wintrust.dll!WintrustSetRegPolicyFlags */
  WintrustSetRegPolicyFlags(dwPolicyFlags: number): number;
}

declare const family: Win32Family & Functions;
export = family;
