// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** esent.dll!JetAddColumnA */
  JetAddColumnA(sesid: number | bigint, tableid: number | bigint, szColumnName: Win32Pointer, pcolumndef: Win32Pointer, pvDefault: Win32Pointer, cbDefault: number, pcolumnid: Win32Pointer): number;
  /** esent.dll!JetAddColumnW */
  JetAddColumnW(sesid: number | bigint, tableid: number | bigint, szColumnName: Win32Pointer, pcolumndef: Win32Pointer, pvDefault: Win32Pointer, cbDefault: number, pcolumnid: Win32Pointer): number;
  /** esent.dll!JetAddColumnW */
  JetAddColumn(sesid: number | bigint, tableid: number | bigint, szColumnName: Win32Pointer, pcolumndef: Win32Pointer, pvDefault: Win32Pointer, cbDefault: number, pcolumnid: Win32Pointer): number;
  /** esent.dll!JetAttachDatabase2A */
  JetAttachDatabase2A(sesid: number | bigint, szFilename: Win32Pointer, cpgDatabaseSizeMax: number, grbit: number): number;
  /** esent.dll!JetAttachDatabase2W */
  JetAttachDatabase2W(sesid: number | bigint, szFilename: Win32Pointer, cpgDatabaseSizeMax: number, grbit: number): number;
  /** esent.dll!JetAttachDatabase2W */
  JetAttachDatabase2(sesid: number | bigint, szFilename: Win32Pointer, cpgDatabaseSizeMax: number, grbit: number): number;
  /** esent.dll!JetAttachDatabaseA */
  JetAttachDatabaseA(sesid: number | bigint, szFilename: Win32Pointer, grbit: number): number;
  /** esent.dll!JetAttachDatabaseW */
  JetAttachDatabaseW(sesid: number | bigint, szFilename: Win32Pointer, grbit: number): number;
  /** esent.dll!JetAttachDatabaseW */
  JetAttachDatabase(sesid: number | bigint, szFilename: Win32Pointer, grbit: number): number;
  /** esent.dll!JetBackupA */
  JetBackupA(szBackupPath: Win32Pointer, grbit: number, pfnStatus: Win32Callback): number;
  /** esent.dll!JetBackupInstanceA */
  JetBackupInstanceA(instance: number | bigint, szBackupPath: Win32Pointer, grbit: number, pfnStatus: Win32Callback): number;
  /** esent.dll!JetBackupInstanceW */
  JetBackupInstanceW(instance: number | bigint, szBackupPath: Win32Pointer, grbit: number, pfnStatus: Win32Callback): number;
  /** esent.dll!JetBackupInstanceW */
  JetBackupInstance(instance: number | bigint, szBackupPath: Win32Pointer, grbit: number, pfnStatus: Win32Callback): number;
  /** esent.dll!JetBackupW */
  JetBackupW(szBackupPath: Win32Pointer, grbit: number, pfnStatus: Win32Callback): number;
  /** esent.dll!JetBackupW */
  JetBackup(szBackupPath: Win32Pointer, grbit: number, pfnStatus: Win32Callback): number;
  /** esent.dll!JetBeginExternalBackup */
  JetBeginExternalBackup(grbit: number): number;
  /** esent.dll!JetBeginExternalBackupInstance */
  JetBeginExternalBackupInstance(instance: number | bigint, grbit: number): number;
  /** esent.dll!JetBeginSessionA */
  JetBeginSessionA(instance: number | bigint, psesid: Win32Pointer, szUserName: Win32Pointer, szPassword: Win32Pointer): number;
  /** esent.dll!JetBeginSessionW */
  JetBeginSessionW(instance: number | bigint, psesid: Win32Pointer, szUserName: Win32Pointer, szPassword: Win32Pointer): number;
  /** esent.dll!JetBeginSessionW */
  JetBeginSession(instance: number | bigint, psesid: Win32Pointer, szUserName: Win32Pointer, szPassword: Win32Pointer): number;
  /** esent.dll!JetBeginTransaction */
  JetBeginTransaction(sesid: number | bigint): number;
  /** esent.dll!JetBeginTransaction2 */
  JetBeginTransaction2(sesid: number | bigint, grbit: number): number;
  /** esent.dll!JetBeginTransaction3 */
  JetBeginTransaction3(sesid: number | bigint, trxid: number | bigint, grbit: number): number;
  /** esent.dll!JetCloseDatabase */
  JetCloseDatabase(sesid: number | bigint, dbid: number, grbit: number): number;
  /** esent.dll!JetCloseFile */
  JetCloseFile(hfFile: number | bigint): number;
  /** esent.dll!JetCloseFileInstance */
  JetCloseFileInstance(instance: number | bigint, hfFile: number | bigint): number;
  /** esent.dll!JetCloseTable */
  JetCloseTable(sesid: number | bigint, tableid: number | bigint): number;
  /** esent.dll!JetCommitTransaction */
  JetCommitTransaction(sesid: number | bigint, grbit: number): number;
  /** esent.dll!JetCommitTransaction2 */
  JetCommitTransaction2(sesid: number | bigint, grbit: number, cmsecDurableCommit: number, pCommitId: Win32Pointer): number;
  /** esent.dll!JetCompactA */
  JetCompactA(sesid: number | bigint, szDatabaseSrc: Win32Pointer, szDatabaseDest: Win32Pointer, pfnStatus: Win32Callback, pconvert: Win32Pointer, grbit: number): number;
  /** esent.dll!JetCompactW */
  JetCompactW(sesid: number | bigint, szDatabaseSrc: Win32Pointer, szDatabaseDest: Win32Pointer, pfnStatus: Win32Callback, pconvert: Win32Pointer, grbit: number): number;
  /** esent.dll!JetCompactW */
  JetCompact(sesid: number | bigint, szDatabaseSrc: Win32Pointer, szDatabaseDest: Win32Pointer, pfnStatus: Win32Callback, pconvert: Win32Pointer, grbit: number): number;
  /** esent.dll!JetComputeStats */
  JetComputeStats(sesid: number | bigint, tableid: number | bigint): number;
  /** esent.dll!JetConfigureProcessForCrashDump */
  JetConfigureProcessForCrashDump(grbit: number): number;
  /** esent.dll!JetCreateDatabase2A */
  JetCreateDatabase2A(sesid: number | bigint, szFilename: Win32Pointer, cpgDatabaseSizeMax: number, pdbid: Win32Pointer, grbit: number): number;
  /** esent.dll!JetCreateDatabase2W */
  JetCreateDatabase2W(sesid: number | bigint, szFilename: Win32Pointer, cpgDatabaseSizeMax: number, pdbid: Win32Pointer, grbit: number): number;
  /** esent.dll!JetCreateDatabase2W */
  JetCreateDatabase2(sesid: number | bigint, szFilename: Win32Pointer, cpgDatabaseSizeMax: number, pdbid: Win32Pointer, grbit: number): number;
  /** esent.dll!JetCreateDatabaseA */
  JetCreateDatabaseA(sesid: number | bigint, szFilename: Win32Pointer, szConnect: Win32Pointer, pdbid: Win32Pointer, grbit: number): number;
  /** esent.dll!JetCreateDatabaseW */
  JetCreateDatabaseW(sesid: number | bigint, szFilename: Win32Pointer, szConnect: Win32Pointer, pdbid: Win32Pointer, grbit: number): number;
  /** esent.dll!JetCreateDatabaseW */
  JetCreateDatabase(sesid: number | bigint, szFilename: Win32Pointer, szConnect: Win32Pointer, pdbid: Win32Pointer, grbit: number): number;
  /** esent.dll!JetCreateIndex2A */
  JetCreateIndex2A(sesid: number | bigint, tableid: number | bigint, pindexcreate: Win32Pointer, cIndexCreate: number): number;
  /** esent.dll!JetCreateIndex2W */
  JetCreateIndex2W(sesid: number | bigint, tableid: number | bigint, pindexcreate: Win32Pointer, cIndexCreate: number): number;
  /** esent.dll!JetCreateIndex2W */
  JetCreateIndex2(sesid: number | bigint, tableid: number | bigint, pindexcreate: Win32Pointer, cIndexCreate: number): number;
  /** esent.dll!JetCreateIndex3A */
  JetCreateIndex3A(sesid: number | bigint, tableid: number | bigint, pindexcreate: Win32Pointer, cIndexCreate: number): number;
  /** esent.dll!JetCreateIndex3W */
  JetCreateIndex3W(sesid: number | bigint, tableid: number | bigint, pindexcreate: Win32Pointer, cIndexCreate: number): number;
  /** esent.dll!JetCreateIndex3W */
  JetCreateIndex3(sesid: number | bigint, tableid: number | bigint, pindexcreate: Win32Pointer, cIndexCreate: number): number;
  /** esent.dll!JetCreateIndex4A */
  JetCreateIndex4A(sesid: number | bigint, tableid: number | bigint, pindexcreate: Win32Pointer, cIndexCreate: number): number;
  /** esent.dll!JetCreateIndex4W */
  JetCreateIndex4W(sesid: number | bigint, tableid: number | bigint, pindexcreate: Win32Pointer, cIndexCreate: number): number;
  /** esent.dll!JetCreateIndex4W */
  JetCreateIndex4(sesid: number | bigint, tableid: number | bigint, pindexcreate: Win32Pointer, cIndexCreate: number): number;
  /** esent.dll!JetCreateIndexA */
  JetCreateIndexA(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, grbit: number, szKey: Win32Pointer, cbKey: number, lDensity: number): number;
  /** esent.dll!JetCreateIndexW */
  JetCreateIndexW(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, grbit: number, szKey: Win32Pointer, cbKey: number, lDensity: number): number;
  /** esent.dll!JetCreateIndexW */
  JetCreateIndex(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, grbit: number, szKey: Win32Pointer, cbKey: number, lDensity: number): number;
  /** esent.dll!JetCreateInstance2A */
  JetCreateInstance2A(pinstance: Win32Pointer, szInstanceName: Win32Pointer, szDisplayName: Win32Pointer, grbit: number): number;
  /** esent.dll!JetCreateInstance2W */
  JetCreateInstance2W(pinstance: Win32Pointer, szInstanceName: Win32Pointer, szDisplayName: Win32Pointer, grbit: number): number;
  /** esent.dll!JetCreateInstance2W */
  JetCreateInstance2(pinstance: Win32Pointer, szInstanceName: Win32Pointer, szDisplayName: Win32Pointer, grbit: number): number;
  /** esent.dll!JetCreateInstanceA */
  JetCreateInstanceA(pinstance: Win32Pointer, szInstanceName: Win32Pointer): number;
  /** esent.dll!JetCreateInstanceW */
  JetCreateInstanceW(pinstance: Win32Pointer, szInstanceName: Win32Pointer): number;
  /** esent.dll!JetCreateInstanceW */
  JetCreateInstance(pinstance: Win32Pointer, szInstanceName: Win32Pointer): number;
  /** esent.dll!JetCreateTableA */
  JetCreateTableA(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, lPages: number, lDensity: number, ptableid: Win32Pointer): number;
  /** esent.dll!JetCreateTableColumnIndex2A */
  JetCreateTableColumnIndex2A(sesid: number | bigint, dbid: number, ptablecreate: Win32Pointer): number;
  /** esent.dll!JetCreateTableColumnIndex2W */
  JetCreateTableColumnIndex2W(sesid: number | bigint, dbid: number, ptablecreate: Win32Pointer): number;
  /** esent.dll!JetCreateTableColumnIndex2W */
  JetCreateTableColumnIndex2(sesid: number | bigint, dbid: number, ptablecreate: Win32Pointer): number;
  /** esent.dll!JetCreateTableColumnIndex3A */
  JetCreateTableColumnIndex3A(sesid: number | bigint, dbid: number, ptablecreate: Win32Pointer): number;
  /** esent.dll!JetCreateTableColumnIndex3W */
  JetCreateTableColumnIndex3W(sesid: number | bigint, dbid: number, ptablecreate: Win32Pointer): number;
  /** esent.dll!JetCreateTableColumnIndex3W */
  JetCreateTableColumnIndex3(sesid: number | bigint, dbid: number, ptablecreate: Win32Pointer): number;
  /** esent.dll!JetCreateTableColumnIndex4A */
  JetCreateTableColumnIndex4A(sesid: number | bigint, dbid: number, ptablecreate: Win32Pointer): number;
  /** esent.dll!JetCreateTableColumnIndex4W */
  JetCreateTableColumnIndex4W(sesid: number | bigint, dbid: number, ptablecreate: Win32Pointer): number;
  /** esent.dll!JetCreateTableColumnIndex4W */
  JetCreateTableColumnIndex4(sesid: number | bigint, dbid: number, ptablecreate: Win32Pointer): number;
  /** esent.dll!JetCreateTableColumnIndexA */
  JetCreateTableColumnIndexA(sesid: number | bigint, dbid: number, ptablecreate: Win32Pointer): number;
  /** esent.dll!JetCreateTableColumnIndexW */
  JetCreateTableColumnIndexW(sesid: number | bigint, dbid: number, ptablecreate: Win32Pointer): number;
  /** esent.dll!JetCreateTableColumnIndexW */
  JetCreateTableColumnIndex(sesid: number | bigint, dbid: number, ptablecreate: Win32Pointer): number;
  /** esent.dll!JetCreateTableW */
  JetCreateTableW(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, lPages: number, lDensity: number, ptableid: Win32Pointer): number;
  /** esent.dll!JetCreateTableW */
  JetCreateTable(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, lPages: number, lDensity: number, ptableid: Win32Pointer): number;
  /** esent.dll!JetDefragment2A */
  JetDefragment2A(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, pcPasses: Win32Pointer, pcSeconds: Win32Pointer, callback: Win32Callback, grbit: number): number;
  /** esent.dll!JetDefragment2W */
  JetDefragment2W(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, pcPasses: Win32Pointer, pcSeconds: Win32Pointer, callback: Win32Callback, grbit: number): number;
  /** esent.dll!JetDefragment2W */
  JetDefragment2(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, pcPasses: Win32Pointer, pcSeconds: Win32Pointer, callback: Win32Callback, grbit: number): number;
  /** esent.dll!JetDefragment3A */
  JetDefragment3A(sesid: number | bigint, szDatabaseName: Win32Pointer, szTableName: Win32Pointer, pcPasses: Win32Pointer, pcSeconds: Win32Pointer, callback: Win32Callback, pvContext: Win32Pointer, grbit: number): number;
  /** esent.dll!JetDefragment3W */
  JetDefragment3W(sesid: number | bigint, szDatabaseName: Win32Pointer, szTableName: Win32Pointer, pcPasses: Win32Pointer, pcSeconds: Win32Pointer, callback: Win32Callback, pvContext: Win32Pointer, grbit: number): number;
  /** esent.dll!JetDefragment3W */
  JetDefragment3(sesid: number | bigint, szDatabaseName: Win32Pointer, szTableName: Win32Pointer, pcPasses: Win32Pointer, pcSeconds: Win32Pointer, callback: Win32Callback, pvContext: Win32Pointer, grbit: number): number;
  /** esent.dll!JetDefragmentA */
  JetDefragmentA(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, pcPasses: Win32Pointer, pcSeconds: Win32Pointer, grbit: number): number;
  /** esent.dll!JetDefragmentW */
  JetDefragmentW(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, pcPasses: Win32Pointer, pcSeconds: Win32Pointer, grbit: number): number;
  /** esent.dll!JetDefragmentW */
  JetDefragment(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, pcPasses: Win32Pointer, pcSeconds: Win32Pointer, grbit: number): number;
  /** esent.dll!JetDelete */
  JetDelete(sesid: number | bigint, tableid: number | bigint): number;
  /** esent.dll!JetDeleteColumn2A */
  JetDeleteColumn2A(sesid: number | bigint, tableid: number | bigint, szColumnName: Win32Pointer, grbit: number): number;
  /** esent.dll!JetDeleteColumn2W */
  JetDeleteColumn2W(sesid: number | bigint, tableid: number | bigint, szColumnName: Win32Pointer, grbit: number): number;
  /** esent.dll!JetDeleteColumn2W */
  JetDeleteColumn2(sesid: number | bigint, tableid: number | bigint, szColumnName: Win32Pointer, grbit: number): number;
  /** esent.dll!JetDeleteColumnA */
  JetDeleteColumnA(sesid: number | bigint, tableid: number | bigint, szColumnName: Win32Pointer): number;
  /** esent.dll!JetDeleteColumnW */
  JetDeleteColumnW(sesid: number | bigint, tableid: number | bigint, szColumnName: Win32Pointer): number;
  /** esent.dll!JetDeleteColumnW */
  JetDeleteColumn(sesid: number | bigint, tableid: number | bigint, szColumnName: Win32Pointer): number;
  /** esent.dll!JetDeleteIndexA */
  JetDeleteIndexA(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer): number;
  /** esent.dll!JetDeleteIndexW */
  JetDeleteIndexW(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer): number;
  /** esent.dll!JetDeleteIndexW */
  JetDeleteIndex(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer): number;
  /** esent.dll!JetDeleteTableA */
  JetDeleteTableA(sesid: number | bigint, dbid: number, szTableName: Win32Pointer): number;
  /** esent.dll!JetDeleteTableW */
  JetDeleteTableW(sesid: number | bigint, dbid: number, szTableName: Win32Pointer): number;
  /** esent.dll!JetDeleteTableW */
  JetDeleteTable(sesid: number | bigint, dbid: number, szTableName: Win32Pointer): number;
  /** esent.dll!JetDetachDatabase2A */
  JetDetachDatabase2A(sesid: number | bigint, szFilename: Win32Pointer, grbit: number): number;
  /** esent.dll!JetDetachDatabase2W */
  JetDetachDatabase2W(sesid: number | bigint, szFilename: Win32Pointer, grbit: number): number;
  /** esent.dll!JetDetachDatabase2W */
  JetDetachDatabase2(sesid: number | bigint, szFilename: Win32Pointer, grbit: number): number;
  /** esent.dll!JetDetachDatabaseA */
  JetDetachDatabaseA(sesid: number | bigint, szFilename: Win32Pointer): number;
  /** esent.dll!JetDetachDatabaseW */
  JetDetachDatabaseW(sesid: number | bigint, szFilename: Win32Pointer): number;
  /** esent.dll!JetDetachDatabaseW */
  JetDetachDatabase(sesid: number | bigint, szFilename: Win32Pointer): number;
  /** esent.dll!JetDupCursor */
  JetDupCursor(sesid: number | bigint, tableid: number | bigint, ptableid: Win32Pointer, grbit: number): number;
  /** esent.dll!JetDupSession */
  JetDupSession(sesid: number | bigint, psesid: Win32Pointer): number;
  /** esent.dll!JetEnableMultiInstanceA */
  JetEnableMultiInstanceA(psetsysparam: Win32Pointer, csetsysparam: number, pcsetsucceed: Win32Pointer): number;
  /** esent.dll!JetEnableMultiInstanceW */
  JetEnableMultiInstanceW(psetsysparam: Win32Pointer, csetsysparam: number, pcsetsucceed: Win32Pointer): number;
  /** esent.dll!JetEnableMultiInstanceW */
  JetEnableMultiInstance(psetsysparam: Win32Pointer, csetsysparam: number, pcsetsucceed: Win32Pointer): number;
  /** esent.dll!JetEndExternalBackup */
  JetEndExternalBackup(): number;
  /** esent.dll!JetEndExternalBackupInstance */
  JetEndExternalBackupInstance(instance: number | bigint): number;
  /** esent.dll!JetEndExternalBackupInstance2 */
  JetEndExternalBackupInstance2(instance: number | bigint, grbit: number): number;
  /** esent.dll!JetEndSession */
  JetEndSession(sesid: number | bigint, grbit: number): number;
  /** esent.dll!JetEnumerateColumns */
  JetEnumerateColumns(sesid: number | bigint, tableid: number | bigint, cEnumColumnId: number, rgEnumColumnId: Win32Pointer, pcEnumColumn: Win32Pointer, prgEnumColumn: Win32Pointer, pfnRealloc: Win32Callback, pvReallocContext: Win32Pointer, cbDataMost: number, grbit: number): number;
  /** esent.dll!JetEscrowUpdate */
  JetEscrowUpdate(sesid: number | bigint, tableid: number | bigint, columnid: number, pv: Win32Pointer, cbMax: number, pvOld: Win32Pointer, cbOldMax: number, pcbOldActual: Win32Pointer, grbit: number): number;
  /** esent.dll!JetExternalRestore2A */
  JetExternalRestore2A(szCheckpointFilePath: Win32Pointer, szLogPath: Win32Pointer, rgrstmap: Win32Pointer, crstfilemap: number, szBackupLogPath: Win32Pointer, pLogInfo: Win32Pointer, szTargetInstanceName: Win32Pointer, szTargetInstanceLogPath: Win32Pointer, szTargetInstanceCheckpointPath: Win32Pointer, pfn: Win32Callback): number;
  /** esent.dll!JetExternalRestore2W */
  JetExternalRestore2W(szCheckpointFilePath: Win32Pointer, szLogPath: Win32Pointer, rgrstmap: Win32Pointer, crstfilemap: number, szBackupLogPath: Win32Pointer, pLogInfo: Win32Pointer, szTargetInstanceName: Win32Pointer, szTargetInstanceLogPath: Win32Pointer, szTargetInstanceCheckpointPath: Win32Pointer, pfn: Win32Callback): number;
  /** esent.dll!JetExternalRestore2W */
  JetExternalRestore2(szCheckpointFilePath: Win32Pointer, szLogPath: Win32Pointer, rgrstmap: Win32Pointer, crstfilemap: number, szBackupLogPath: Win32Pointer, pLogInfo: Win32Pointer, szTargetInstanceName: Win32Pointer, szTargetInstanceLogPath: Win32Pointer, szTargetInstanceCheckpointPath: Win32Pointer, pfn: Win32Callback): number;
  /** esent.dll!JetExternalRestoreA */
  JetExternalRestoreA(szCheckpointFilePath: Win32Pointer, szLogPath: Win32Pointer, rgrstmap: Win32Pointer, crstfilemap: number, szBackupLogPath: Win32Pointer, genLow: number, genHigh: number, pfn: Win32Callback): number;
  /** esent.dll!JetExternalRestoreW */
  JetExternalRestoreW(szCheckpointFilePath: Win32Pointer, szLogPath: Win32Pointer, rgrstmap: Win32Pointer, crstfilemap: number, szBackupLogPath: Win32Pointer, genLow: number, genHigh: number, pfn: Win32Callback): number;
  /** esent.dll!JetExternalRestoreW */
  JetExternalRestore(szCheckpointFilePath: Win32Pointer, szLogPath: Win32Pointer, rgrstmap: Win32Pointer, crstfilemap: number, szBackupLogPath: Win32Pointer, genLow: number, genHigh: number, pfn: Win32Callback): number;
  /** esent.dll!JetFreeBuffer */
  JetFreeBuffer(pbBuf: Win32Pointer): number;
  /** esent.dll!JetGetAttachInfoA */
  JetGetAttachInfoA(szzDatabases: Win32Pointer, cbMax: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetGetAttachInfoInstanceA */
  JetGetAttachInfoInstanceA(instance: number | bigint, szzDatabases: Win32Pointer, cbMax: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetGetAttachInfoInstanceW */
  JetGetAttachInfoInstanceW(instance: number | bigint, szzDatabases: Win32Pointer, cbMax: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetGetAttachInfoInstanceW */
  JetGetAttachInfoInstance(instance: number | bigint, szzDatabases: Win32Pointer, cbMax: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetGetAttachInfoW */
  JetGetAttachInfoW(wszzDatabases: Win32Pointer, cbMax: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetGetAttachInfoW */
  JetGetAttachInfo(wszzDatabases: Win32Pointer, cbMax: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetGetBookmark */
  JetGetBookmark(sesid: number | bigint, tableid: number | bigint, pvBookmark: Win32Pointer, cbMax: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetGetColumnInfoA */
  JetGetColumnInfoA(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, pColumnNameOrId: Win32Pointer, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetColumnInfoW */
  JetGetColumnInfoW(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, pwColumnNameOrId: Win32Pointer, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetColumnInfoW */
  JetGetColumnInfo(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, pwColumnNameOrId: Win32Pointer, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetCurrentIndexA */
  JetGetCurrentIndexA(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, cbIndexName: number): number;
  /** esent.dll!JetGetCurrentIndexW */
  JetGetCurrentIndexW(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, cbIndexName: number): number;
  /** esent.dll!JetGetCurrentIndexW */
  JetGetCurrentIndex(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, cbIndexName: number): number;
  /** esent.dll!JetGetCursorInfo */
  JetGetCursorInfo(sesid: number | bigint, tableid: number | bigint, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetDatabaseFileInfoA */
  JetGetDatabaseFileInfoA(szDatabaseName: Win32Pointer, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetDatabaseFileInfoW */
  JetGetDatabaseFileInfoW(szDatabaseName: Win32Pointer, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetDatabaseFileInfoW */
  JetGetDatabaseFileInfo(szDatabaseName: Win32Pointer, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetDatabaseInfoA */
  JetGetDatabaseInfoA(sesid: number | bigint, dbid: number, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetDatabaseInfoW */
  JetGetDatabaseInfoW(sesid: number | bigint, dbid: number, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetDatabaseInfoW */
  JetGetDatabaseInfo(sesid: number | bigint, dbid: number, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetErrorInfoW */
  JetGetErrorInfoW(pvContext: Win32Pointer, pvResult: Win32Pointer, cbMax: number, InfoLevel: number, grbit: number): number;
  /** esent.dll!JetGetIndexInfoA */
  JetGetIndexInfoA(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, szIndexName: Win32Pointer, pvResult: Win32Pointer, cbResult: number, InfoLevel: number): number;
  /** esent.dll!JetGetIndexInfoW */
  JetGetIndexInfoW(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, szIndexName: Win32Pointer, pvResult: Win32Pointer, cbResult: number, InfoLevel: number): number;
  /** esent.dll!JetGetIndexInfoW */
  JetGetIndexInfo(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, szIndexName: Win32Pointer, pvResult: Win32Pointer, cbResult: number, InfoLevel: number): number;
  /** esent.dll!JetGetInstanceInfoA */
  JetGetInstanceInfoA(pcInstanceInfo: Win32Pointer, paInstanceInfo: Win32Pointer): number;
  /** esent.dll!JetGetInstanceInfoW */
  JetGetInstanceInfoW(pcInstanceInfo: Win32Pointer, paInstanceInfo: Win32Pointer): number;
  /** esent.dll!JetGetInstanceInfoW */
  JetGetInstanceInfo(pcInstanceInfo: Win32Pointer, paInstanceInfo: Win32Pointer): number;
  /** esent.dll!JetGetInstanceMiscInfo */
  JetGetInstanceMiscInfo(instance: number | bigint, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetLS */
  JetGetLS(sesid: number | bigint, tableid: number | bigint, pls: Win32Pointer, grbit: number): number;
  /** esent.dll!JetGetLock */
  JetGetLock(sesid: number | bigint, tableid: number | bigint, grbit: number): number;
  /** esent.dll!JetGetLogInfoA */
  JetGetLogInfoA(szzLogs: Win32Pointer, cbMax: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetGetLogInfoInstance2A */
  JetGetLogInfoInstance2A(instance: number | bigint, szzLogs: Win32Pointer, cbMax: number, pcbActual: Win32Pointer, pLogInfo: Win32Pointer): number;
  /** esent.dll!JetGetLogInfoInstance2W */
  JetGetLogInfoInstance2W(instance: number | bigint, wszzLogs: Win32Pointer, cbMax: number, pcbActual: Win32Pointer, pLogInfo: Win32Pointer): number;
  /** esent.dll!JetGetLogInfoInstance2W */
  JetGetLogInfoInstance2(instance: number | bigint, wszzLogs: Win32Pointer, cbMax: number, pcbActual: Win32Pointer, pLogInfo: Win32Pointer): number;
  /** esent.dll!JetGetLogInfoInstanceA */
  JetGetLogInfoInstanceA(instance: number | bigint, szzLogs: Win32Pointer, cbMax: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetGetLogInfoInstanceW */
  JetGetLogInfoInstanceW(instance: number | bigint, wszzLogs: Win32Pointer, cbMax: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetGetLogInfoInstanceW */
  JetGetLogInfoInstance(instance: number | bigint, wszzLogs: Win32Pointer, cbMax: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetGetLogInfoW */
  JetGetLogInfoW(szzLogs: Win32Pointer, cbMax: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetGetLogInfoW */
  JetGetLogInfo(szzLogs: Win32Pointer, cbMax: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetGetObjectInfoA */
  JetGetObjectInfoA(sesid: number | bigint, dbid: number, objtyp: number, szContainerName: Win32Pointer, szObjectName: Win32Pointer, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetObjectInfoW */
  JetGetObjectInfoW(sesid: number | bigint, dbid: number, objtyp: number, szContainerName: Win32Pointer, szObjectName: Win32Pointer, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetObjectInfoW */
  JetGetObjectInfo(sesid: number | bigint, dbid: number, objtyp: number, szContainerName: Win32Pointer, szObjectName: Win32Pointer, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetRecordPosition */
  JetGetRecordPosition(sesid: number | bigint, tableid: number | bigint, precpos: Win32Pointer, cbRecpos: number): number;
  /** esent.dll!JetGetRecordSize */
  JetGetRecordSize(sesid: number | bigint, tableid: number | bigint, precsize: Win32Pointer, grbit: number): number;
  /** esent.dll!JetGetRecordSize2 */
  JetGetRecordSize2(sesid: number | bigint, tableid: number | bigint, precsize: Win32Pointer, grbit: number): number;
  /** esent.dll!JetGetSecondaryIndexBookmark */
  JetGetSecondaryIndexBookmark(sesid: number | bigint, tableid: number | bigint, pvSecondaryKey: Win32Pointer, cbSecondaryKeyMax: number, pcbSecondaryKeyActual: Win32Pointer, pvPrimaryBookmark: Win32Pointer, cbPrimaryBookmarkMax: number, pcbPrimaryBookmarkActual: Win32Pointer, grbit: number): number;
  /** esent.dll!JetGetSessionParameter */
  JetGetSessionParameter(sesid: number | bigint, sesparamid: number, pvParam: Win32Pointer, cbParamMax: number, pcbParamActual: Win32Pointer): number;
  /** esent.dll!JetGetSystemParameterA */
  JetGetSystemParameterA(instance: number | bigint, sesid: number | bigint, paramid: number, plParam: Win32Pointer, szParam: Win32Pointer, cbMax: number): number;
  /** esent.dll!JetGetSystemParameterW */
  JetGetSystemParameterW(instance: number | bigint, sesid: number | bigint, paramid: number, plParam: Win32Pointer, szParam: Win32Pointer, cbMax: number): number;
  /** esent.dll!JetGetSystemParameterW */
  JetGetSystemParameter(instance: number | bigint, sesid: number | bigint, paramid: number, plParam: Win32Pointer, szParam: Win32Pointer, cbMax: number): number;
  /** esent.dll!JetGetTableColumnInfoA */
  JetGetTableColumnInfoA(sesid: number | bigint, tableid: number | bigint, szColumnName: Win32Pointer, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetTableColumnInfoW */
  JetGetTableColumnInfoW(sesid: number | bigint, tableid: number | bigint, szColumnName: Win32Pointer, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetTableColumnInfoW */
  JetGetTableColumnInfo(sesid: number | bigint, tableid: number | bigint, szColumnName: Win32Pointer, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetTableIndexInfoA */
  JetGetTableIndexInfoA(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, pvResult: Win32Pointer, cbResult: number, InfoLevel: number): number;
  /** esent.dll!JetGetTableIndexInfoW */
  JetGetTableIndexInfoW(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, pvResult: Win32Pointer, cbResult: number, InfoLevel: number): number;
  /** esent.dll!JetGetTableIndexInfoW */
  JetGetTableIndexInfo(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, pvResult: Win32Pointer, cbResult: number, InfoLevel: number): number;
  /** esent.dll!JetGetTableInfoA */
  JetGetTableInfoA(sesid: number | bigint, tableid: number | bigint, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetTableInfoW */
  JetGetTableInfoW(sesid: number | bigint, tableid: number | bigint, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetTableInfoW */
  JetGetTableInfo(sesid: number | bigint, tableid: number | bigint, pvResult: Win32Pointer, cbMax: number, InfoLevel: number): number;
  /** esent.dll!JetGetThreadStats */
  JetGetThreadStats(pvResult: Win32Pointer, cbMax: number): number;
  /** esent.dll!JetGetTruncateLogInfoInstanceA */
  JetGetTruncateLogInfoInstanceA(instance: number | bigint, szzLogs: Win32Pointer, cbMax: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetGetTruncateLogInfoInstanceW */
  JetGetTruncateLogInfoInstanceW(instance: number | bigint, wszzLogs: Win32Pointer, cbMax: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetGetTruncateLogInfoInstanceW */
  JetGetTruncateLogInfoInstance(instance: number | bigint, wszzLogs: Win32Pointer, cbMax: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetGetVersion */
  JetGetVersion(sesid: number | bigint, pwVersion: Win32Pointer): number;
  /** esent.dll!JetGotoBookmark */
  JetGotoBookmark(sesid: number | bigint, tableid: number | bigint, pvBookmark: Win32Pointer, cbBookmark: number): number;
  /** esent.dll!JetGotoPosition */
  JetGotoPosition(sesid: number | bigint, tableid: number | bigint, precpos: Win32Pointer): number;
  /** esent.dll!JetGotoSecondaryIndexBookmark */
  JetGotoSecondaryIndexBookmark(sesid: number | bigint, tableid: number | bigint, pvSecondaryKey: Win32Pointer, cbSecondaryKey: number, pvPrimaryBookmark: Win32Pointer, cbPrimaryBookmark: number, grbit: number): number;
  /** esent.dll!JetGrowDatabase */
  JetGrowDatabase(sesid: number | bigint, dbid: number, cpg: number, pcpgReal: Win32Pointer): number;
  /** esent.dll!JetIdle */
  JetIdle(sesid: number | bigint, grbit: number): number;
  /** esent.dll!JetIndexRecordCount */
  JetIndexRecordCount(sesid: number | bigint, tableid: number | bigint, pcrec: Win32Pointer, crecMax: number): number;
  /** esent.dll!JetInit */
  JetInit(pinstance: Win32Pointer): number;
  /** esent.dll!JetInit2 */
  JetInit2(pinstance: Win32Pointer, grbit: number): number;
  /** esent.dll!JetInit3A */
  JetInit3A(pinstance: Win32Pointer, prstInfo: Win32Pointer, grbit: number): number;
  /** esent.dll!JetInit3W */
  JetInit3W(pinstance: Win32Pointer, prstInfo: Win32Pointer, grbit: number): number;
  /** esent.dll!JetInit3W */
  JetInit3(pinstance: Win32Pointer, prstInfo: Win32Pointer, grbit: number): number;
  /** esent.dll!JetIntersectIndexes */
  JetIntersectIndexes(sesid: number | bigint, rgindexrange: Win32Pointer, cindexrange: number, precordlist: Win32Pointer, grbit: number): number;
  /** esent.dll!JetMakeKey */
  JetMakeKey(sesid: number | bigint, tableid: number | bigint, pvData: Win32Pointer, cbData: number, grbit: number): number;
  /** esent.dll!JetMove */
  JetMove(sesid: number | bigint, tableid: number | bigint, cRow: number, grbit: number): number;
  /** esent.dll!JetOSSnapshotAbort */
  JetOSSnapshotAbort(snapId: number | bigint, grbit: number): number;
  /** esent.dll!JetOSSnapshotEnd */
  JetOSSnapshotEnd(snapId: number | bigint, grbit: number): number;
  /** esent.dll!JetOSSnapshotFreezeA */
  JetOSSnapshotFreezeA(snapId: number | bigint, pcInstanceInfo: Win32Pointer, paInstanceInfo: Win32Pointer, grbit: number): number;
  /** esent.dll!JetOSSnapshotFreezeW */
  JetOSSnapshotFreezeW(snapId: number | bigint, pcInstanceInfo: Win32Pointer, paInstanceInfo: Win32Pointer, grbit: number): number;
  /** esent.dll!JetOSSnapshotFreezeW */
  JetOSSnapshotFreeze(snapId: number | bigint, pcInstanceInfo: Win32Pointer, paInstanceInfo: Win32Pointer, grbit: number): number;
  /** esent.dll!JetOSSnapshotGetFreezeInfoA */
  JetOSSnapshotGetFreezeInfoA(snapId: number | bigint, pcInstanceInfo: Win32Pointer, paInstanceInfo: Win32Pointer, grbit: number): number;
  /** esent.dll!JetOSSnapshotGetFreezeInfoW */
  JetOSSnapshotGetFreezeInfoW(snapId: number | bigint, pcInstanceInfo: Win32Pointer, paInstanceInfo: Win32Pointer, grbit: number): number;
  /** esent.dll!JetOSSnapshotGetFreezeInfoW */
  JetOSSnapshotGetFreezeInfo(snapId: number | bigint, pcInstanceInfo: Win32Pointer, paInstanceInfo: Win32Pointer, grbit: number): number;
  /** esent.dll!JetOSSnapshotPrepare */
  JetOSSnapshotPrepare(psnapId: Win32Pointer, grbit: number): number;
  /** esent.dll!JetOSSnapshotPrepareInstance */
  JetOSSnapshotPrepareInstance(snapId: number | bigint, instance: number | bigint, grbit: number): number;
  /** esent.dll!JetOSSnapshotThaw */
  JetOSSnapshotThaw(snapId: number | bigint, grbit: number): number;
  /** esent.dll!JetOSSnapshotTruncateLog */
  JetOSSnapshotTruncateLog(snapId: number | bigint, grbit: number): number;
  /** esent.dll!JetOSSnapshotTruncateLogInstance */
  JetOSSnapshotTruncateLogInstance(snapId: number | bigint, instance: number | bigint, grbit: number): number;
  /** esent.dll!JetOpenDatabaseA */
  JetOpenDatabaseA(sesid: number | bigint, szFilename: Win32Pointer, szConnect: Win32Pointer, pdbid: Win32Pointer, grbit: number): number;
  /** esent.dll!JetOpenDatabaseW */
  JetOpenDatabaseW(sesid: number | bigint, szFilename: Win32Pointer, szConnect: Win32Pointer, pdbid: Win32Pointer, grbit: number): number;
  /** esent.dll!JetOpenDatabaseW */
  JetOpenDatabase(sesid: number | bigint, szFilename: Win32Pointer, szConnect: Win32Pointer, pdbid: Win32Pointer, grbit: number): number;
  /** esent.dll!JetOpenFileA */
  JetOpenFileA(szFileName: Win32Pointer, phfFile: Win32Pointer, pulFileSizeLow: Win32Pointer, pulFileSizeHigh: Win32Pointer): number;
  /** esent.dll!JetOpenFileInstanceA */
  JetOpenFileInstanceA(instance: number | bigint, szFileName: Win32Pointer, phfFile: Win32Pointer, pulFileSizeLow: Win32Pointer, pulFileSizeHigh: Win32Pointer): number;
  /** esent.dll!JetOpenFileInstanceW */
  JetOpenFileInstanceW(instance: number | bigint, szFileName: Win32Pointer, phfFile: Win32Pointer, pulFileSizeLow: Win32Pointer, pulFileSizeHigh: Win32Pointer): number;
  /** esent.dll!JetOpenFileInstanceW */
  JetOpenFileInstance(instance: number | bigint, szFileName: Win32Pointer, phfFile: Win32Pointer, pulFileSizeLow: Win32Pointer, pulFileSizeHigh: Win32Pointer): number;
  /** esent.dll!JetOpenFileW */
  JetOpenFileW(szFileName: Win32Pointer, phfFile: Win32Pointer, pulFileSizeLow: Win32Pointer, pulFileSizeHigh: Win32Pointer): number;
  /** esent.dll!JetOpenFileW */
  JetOpenFile(szFileName: Win32Pointer, phfFile: Win32Pointer, pulFileSizeLow: Win32Pointer, pulFileSizeHigh: Win32Pointer): number;
  /** esent.dll!JetOpenTableA */
  JetOpenTableA(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, pvParameters: Win32Pointer, cbParameters: number, grbit: number, ptableid: Win32Pointer): number;
  /** esent.dll!JetOpenTableW */
  JetOpenTableW(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, pvParameters: Win32Pointer, cbParameters: number, grbit: number, ptableid: Win32Pointer): number;
  /** esent.dll!JetOpenTableW */
  JetOpenTable(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, pvParameters: Win32Pointer, cbParameters: number, grbit: number, ptableid: Win32Pointer): number;
  /** esent.dll!JetOpenTempTable */
  JetOpenTempTable(sesid: number | bigint, prgcolumndef: Win32Pointer, ccolumn: number, grbit: number, ptableid: Win32Pointer, prgcolumnid: Win32Pointer): number;
  /** esent.dll!JetOpenTempTable2 */
  JetOpenTempTable2(sesid: number | bigint, prgcolumndef: Win32Pointer, ccolumn: number, lcid: number, grbit: number, ptableid: Win32Pointer, prgcolumnid: Win32Pointer): number;
  /** esent.dll!JetOpenTempTable3 */
  JetOpenTempTable3(sesid: number | bigint, prgcolumndef: Win32Pointer, ccolumn: number, pidxunicode: Win32Pointer, grbit: number, ptableid: Win32Pointer, prgcolumnid: Win32Pointer): number;
  /** esent.dll!JetOpenTemporaryTable */
  JetOpenTemporaryTable(sesid: number | bigint, popentemporarytable: Win32Pointer): number;
  /** esent.dll!JetOpenTemporaryTable2 */
  JetOpenTemporaryTable2(sesid: number | bigint, popentemporarytable: Win32Pointer): number;
  /** esent.dll!JetPrepareUpdate */
  JetPrepareUpdate(sesid: number | bigint, tableid: number | bigint, prep: number): number;
  /** esent.dll!JetPrereadIndexRanges */
  JetPrereadIndexRanges(sesid: number | bigint, tableid: number | bigint, rgIndexRanges: Win32Pointer, cIndexRanges: number, pcRangesPreread: Win32Pointer, rgcolumnidPreread: Win32Pointer, ccolumnidPreread: number, grbit: number): number;
  /** esent.dll!JetPrereadKeys */
  JetPrereadKeys(sesid: number | bigint, tableid: number | bigint, rgpvKeys: Win32Pointer, rgcbKeys: Win32Pointer, ckeys: number, pckeysPreread: Win32Pointer, grbit: number): number;
  /** esent.dll!JetReadFile */
  JetReadFile(hfFile: number | bigint, pv: Win32Pointer, cb: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetReadFileInstance */
  JetReadFileInstance(instance: number | bigint, hfFile: number | bigint, pv: Win32Pointer, cb: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetRegisterCallback */
  JetRegisterCallback(sesid: number | bigint, tableid: number | bigint, cbtyp: number, pCallback: Win32Callback, pvContext: Win32Pointer, phCallbackId: Win32Pointer): number;
  /** esent.dll!JetRenameColumnA */
  JetRenameColumnA(sesid: number | bigint, tableid: number | bigint, szName: Win32Pointer, szNameNew: Win32Pointer, grbit: number): number;
  /** esent.dll!JetRenameColumnW */
  JetRenameColumnW(sesid: number | bigint, tableid: number | bigint, szName: Win32Pointer, szNameNew: Win32Pointer, grbit: number): number;
  /** esent.dll!JetRenameColumnW */
  JetRenameColumn(sesid: number | bigint, tableid: number | bigint, szName: Win32Pointer, szNameNew: Win32Pointer, grbit: number): number;
  /** esent.dll!JetRenameTableA */
  JetRenameTableA(sesid: number | bigint, dbid: number, szName: Win32Pointer, szNameNew: Win32Pointer): number;
  /** esent.dll!JetRenameTableW */
  JetRenameTableW(sesid: number | bigint, dbid: number, szName: Win32Pointer, szNameNew: Win32Pointer): number;
  /** esent.dll!JetRenameTableW */
  JetRenameTable(sesid: number | bigint, dbid: number, szName: Win32Pointer, szNameNew: Win32Pointer): number;
  /** esent.dll!JetResetSessionContext */
  JetResetSessionContext(sesid: number | bigint): number;
  /** esent.dll!JetResetTableSequential */
  JetResetTableSequential(sesid: number | bigint, tableid: number | bigint, grbit: number): number;
  /** esent.dll!JetResizeDatabase */
  JetResizeDatabase(sesid: number | bigint, dbid: number, cpgTarget: number, pcpgActual: Win32Pointer, grbit: number): number;
  /** esent.dll!JetRestore2A */
  JetRestore2A(sz: Win32Pointer, szDest: Win32Pointer, pfn: Win32Callback): number;
  /** esent.dll!JetRestore2W */
  JetRestore2W(sz: Win32Pointer, szDest: Win32Pointer, pfn: Win32Callback): number;
  /** esent.dll!JetRestore2W */
  JetRestore2(sz: Win32Pointer, szDest: Win32Pointer, pfn: Win32Callback): number;
  /** esent.dll!JetRestoreA */
  JetRestoreA(szSource: Win32Pointer, pfn: Win32Callback): number;
  /** esent.dll!JetRestoreInstanceA */
  JetRestoreInstanceA(instance: number | bigint, sz: Win32Pointer, szDest: Win32Pointer, pfn: Win32Callback): number;
  /** esent.dll!JetRestoreInstanceW */
  JetRestoreInstanceW(instance: number | bigint, sz: Win32Pointer, szDest: Win32Pointer, pfn: Win32Callback): number;
  /** esent.dll!JetRestoreInstanceW */
  JetRestoreInstance(instance: number | bigint, sz: Win32Pointer, szDest: Win32Pointer, pfn: Win32Callback): number;
  /** esent.dll!JetRestoreW */
  JetRestoreW(szSource: Win32Pointer, pfn: Win32Callback): number;
  /** esent.dll!JetRestoreW */
  JetRestore(szSource: Win32Pointer, pfn: Win32Callback): number;
  /** esent.dll!JetRetrieveColumn */
  JetRetrieveColumn(sesid: number | bigint, tableid: number | bigint, columnid: number, pvData: Win32Pointer, cbData: number, pcbActual: Win32Pointer, grbit: number, pretinfo: Win32Pointer): number;
  /** esent.dll!JetRetrieveColumns */
  JetRetrieveColumns(sesid: number | bigint, tableid: number | bigint, pretrievecolumn: Win32Pointer, cretrievecolumn: number): number;
  /** esent.dll!JetRetrieveKey */
  JetRetrieveKey(sesid: number | bigint, tableid: number | bigint, pvKey: Win32Pointer, cbMax: number, pcbActual: Win32Pointer, grbit: number): number;
  /** esent.dll!JetRollback */
  JetRollback(sesid: number | bigint, grbit: number): number;
  /** esent.dll!JetSeek */
  JetSeek(sesid: number | bigint, tableid: number | bigint, grbit: number): number;
  /** esent.dll!JetSetColumn */
  JetSetColumn(sesid: number | bigint, tableid: number | bigint, columnid: number, pvData: Win32Pointer, cbData: number, grbit: number, psetinfo: Win32Pointer): number;
  /** esent.dll!JetSetColumnDefaultValueA */
  JetSetColumnDefaultValueA(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, szColumnName: Win32Pointer, pvData: Win32Pointer, cbData: number, grbit: number): number;
  /** esent.dll!JetSetColumnDefaultValueW */
  JetSetColumnDefaultValueW(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, szColumnName: Win32Pointer, pvData: Win32Pointer, cbData: number, grbit: number): number;
  /** esent.dll!JetSetColumnDefaultValueW */
  JetSetColumnDefaultValue(sesid: number | bigint, dbid: number, szTableName: Win32Pointer, szColumnName: Win32Pointer, pvData: Win32Pointer, cbData: number, grbit: number): number;
  /** esent.dll!JetSetColumns */
  JetSetColumns(sesid: number | bigint, tableid: number | bigint, psetcolumn: Win32Pointer, csetcolumn: number): number;
  /** esent.dll!JetSetCurrentIndex2A */
  JetSetCurrentIndex2A(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, grbit: number): number;
  /** esent.dll!JetSetCurrentIndex2W */
  JetSetCurrentIndex2W(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, grbit: number): number;
  /** esent.dll!JetSetCurrentIndex2W */
  JetSetCurrentIndex2(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, grbit: number): number;
  /** esent.dll!JetSetCurrentIndex3A */
  JetSetCurrentIndex3A(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, grbit: number, itagSequence: number): number;
  /** esent.dll!JetSetCurrentIndex3W */
  JetSetCurrentIndex3W(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, grbit: number, itagSequence: number): number;
  /** esent.dll!JetSetCurrentIndex3W */
  JetSetCurrentIndex3(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, grbit: number, itagSequence: number): number;
  /** esent.dll!JetSetCurrentIndex4A */
  JetSetCurrentIndex4A(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, pindexid: Win32Pointer, grbit: number, itagSequence: number): number;
  /** esent.dll!JetSetCurrentIndex4W */
  JetSetCurrentIndex4W(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, pindexid: Win32Pointer, grbit: number, itagSequence: number): number;
  /** esent.dll!JetSetCurrentIndex4W */
  JetSetCurrentIndex4(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer, pindexid: Win32Pointer, grbit: number, itagSequence: number): number;
  /** esent.dll!JetSetCurrentIndexA */
  JetSetCurrentIndexA(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer): number;
  /** esent.dll!JetSetCurrentIndexW */
  JetSetCurrentIndexW(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer): number;
  /** esent.dll!JetSetCurrentIndexW */
  JetSetCurrentIndex(sesid: number | bigint, tableid: number | bigint, szIndexName: Win32Pointer): number;
  /** esent.dll!JetSetCursorFilter */
  JetSetCursorFilter(sesid: number | bigint, tableid: number | bigint, rgColumnFilters: Win32Pointer, cColumnFilters: number, grbit: number): number;
  /** esent.dll!JetSetDatabaseSizeA */
  JetSetDatabaseSizeA(sesid: number | bigint, szDatabaseName: Win32Pointer, cpg: number, pcpgReal: Win32Pointer): number;
  /** esent.dll!JetSetDatabaseSizeW */
  JetSetDatabaseSizeW(sesid: number | bigint, szDatabaseName: Win32Pointer, cpg: number, pcpgReal: Win32Pointer): number;
  /** esent.dll!JetSetDatabaseSizeW */
  JetSetDatabaseSize(sesid: number | bigint, szDatabaseName: Win32Pointer, cpg: number, pcpgReal: Win32Pointer): number;
  /** esent.dll!JetSetIndexRange */
  JetSetIndexRange(sesid: number | bigint, tableidSrc: number | bigint, grbit: number): number;
  /** esent.dll!JetSetLS */
  JetSetLS(sesid: number | bigint, tableid: number | bigint, ls: number | bigint, grbit: number): number;
  /** esent.dll!JetSetSessionContext */
  JetSetSessionContext(sesid: number | bigint, ulContext: number | bigint): number;
  /** esent.dll!JetSetSessionParameter */
  JetSetSessionParameter(sesid: number | bigint, sesparamid: number, pvParam: Win32Pointer, cbParam: number): number;
  /** esent.dll!JetSetSystemParameterA */
  JetSetSystemParameterA(pinstance: Win32Pointer, sesid: number | bigint, paramid: number, lParam: number | bigint, szParam: Win32Pointer): number;
  /** esent.dll!JetSetSystemParameterW */
  JetSetSystemParameterW(pinstance: Win32Pointer, sesid: number | bigint, paramid: number, lParam: number | bigint, szParam: Win32Pointer): number;
  /** esent.dll!JetSetSystemParameterW */
  JetSetSystemParameter(pinstance: Win32Pointer, sesid: number | bigint, paramid: number, lParam: number | bigint, szParam: Win32Pointer): number;
  /** esent.dll!JetSetTableSequential */
  JetSetTableSequential(sesid: number | bigint, tableid: number | bigint, grbit: number): number;
  /** esent.dll!JetStopBackup */
  JetStopBackup(): number;
  /** esent.dll!JetStopBackupInstance */
  JetStopBackupInstance(instance: number | bigint): number;
  /** esent.dll!JetStopService */
  JetStopService(): number;
  /** esent.dll!JetStopServiceInstance */
  JetStopServiceInstance(instance: number | bigint): number;
  /** esent.dll!JetStopServiceInstance2 */
  JetStopServiceInstance2(instance: number | bigint, grbit: number): number;
  /** esent.dll!JetTerm */
  JetTerm(instance: number | bigint): number;
  /** esent.dll!JetTerm2 */
  JetTerm2(instance: number | bigint, grbit: number): number;
  /** esent.dll!JetTruncateLog */
  JetTruncateLog(): number;
  /** esent.dll!JetTruncateLogInstance */
  JetTruncateLogInstance(instance: number | bigint): number;
  /** esent.dll!JetUnregisterCallback */
  JetUnregisterCallback(sesid: number | bigint, tableid: number | bigint, cbtyp: number, hCallbackId: number | bigint): number;
  /** esent.dll!JetUpdate */
  JetUpdate(sesid: number | bigint, tableid: number | bigint, pvBookmark: Win32Pointer, cbBookmark: number, pcbActual: Win32Pointer): number;
  /** esent.dll!JetUpdate2 */
  JetUpdate2(sesid: number | bigint, tableid: number | bigint, pvBookmark: Win32Pointer, cbBookmark: number, pcbActual: Win32Pointer, grbit: number): number;
}

declare const family: Win32Family & Functions;
export = family;
