// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** computestorage.dll!HcsAttachLayerStorageFilter */
  HcsAttachLayerStorageFilter(layerPath: string | Win32Pointer, layerData: string | Win32Pointer): number;
  /** computestorage.dll!HcsAttachOverlayFilter */
  HcsAttachOverlayFilter(VolumeMountPoint: string | Win32Pointer, LayerData: string | Win32Pointer): number;
  /** computestorage.dll!HcsDestroyLayer */
  HcsDestroyLayer(layerPath: string | Win32Pointer): number;
  /** computestorage.dll!HcsDetachLayerStorageFilter */
  HcsDetachLayerStorageFilter(layerPath: string | Win32Pointer): number;
  /** computestorage.dll!HcsDetachOverlayFilter */
  HcsDetachOverlayFilter(VolumeMountPoint: string | Win32Pointer, LayerData: string | Win32Pointer): number;
  /** computestorage.dll!HcsExportLayer */
  HcsExportLayer(layerPath: string | Win32Pointer, exportFolderPath: string | Win32Pointer, layerData: string | Win32Pointer, options: string | Win32Pointer): number;
  /** computestorage.dll!HcsExportLegacyWritableLayer */
  HcsExportLegacyWritableLayer(writableLayerMountPath: string | Win32Pointer, writableLayerFolderPath: string | Win32Pointer, exportFolderPath: string | Win32Pointer, layerData: string | Win32Pointer): number;
  /** computestorage.dll!HcsFormatWritableLayerVhd */
  HcsFormatWritableLayerVhd(vhdHandle: Win32Pointer): number;
  /** computestorage.dll!HcsGetLayerVhdMountPath */
  HcsGetLayerVhdMountPath(vhdHandle: Win32Pointer, mountPath: Win32Pointer): number;
  /** computestorage.dll!HcsImportLayer */
  HcsImportLayer(layerPath: string | Win32Pointer, sourceFolderPath: string | Win32Pointer, layerData: string | Win32Pointer): number;
  /** computestorage.dll!HcsInitializeLegacyWritableLayer */
  HcsInitializeLegacyWritableLayer(writableLayerMountPath: string | Win32Pointer, writableLayerFolderPath: string | Win32Pointer, layerData: string | Win32Pointer, options: string | Win32Pointer): number;
  /** computestorage.dll!HcsInitializeWritableLayer */
  HcsInitializeWritableLayer(writableLayerPath: string | Win32Pointer, layerData: string | Win32Pointer, options: string | Win32Pointer): number;
  /** computestorage.dll!HcsSetupBaseOSLayer */
  HcsSetupBaseOSLayer(layerPath: string | Win32Pointer, vhdHandle: Win32Pointer, options: string | Win32Pointer): number;
  /** computestorage.dll!HcsSetupBaseOSVolume */
  HcsSetupBaseOSVolume(layerPath: string | Win32Pointer, volumePath: string | Win32Pointer, options: string | Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
