// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** api-ms-win-core-libraryloader-l2-1-0.dll!QueryOptionalDelayLoadedAPI */
  QueryOptionalDelayLoadedAPI(hParentModule: Win32Pointer, lpDllName: string | Win32Pointer, lpProcName: string | Win32Pointer, Reserved: number): number;
}

declare const family: Win32Family & Functions;
export = family;
