// Generates, from src/agent_tools/tools.json and src/agent_tools/skills.json:
//
// - src/agent_tools/generated/tools.rs: the `tools/list` descriptors of `bun mcp`'s agent tools;
// - docs/project/agent-tools.mdx: their reference, and the list of generated skills;
// - .claude/skills/<name>/SKILL.md: one skill per entry of skills.json, every section extracted from the
//   repository (docs, CLAUDE.md, module docs, package.json scripts, the `bun lsp` sources).
//
// The outputs are checked in, so `cargo check`, `bun mcp` (which embeds .claude/skills and docs/) and the
// agent plugin (packages/bun-agent-plugin, which reads .claude/skills) need no build step. Same inputs, same
// bytes. Runs under Bun and Node (the build's codegen may run under either).
//
//   bun src/codegen/generate-agent-tools.ts            write the outputs
//   bun src/codegen/generate-agent-tools.ts --check    exit 1 when an output is stale
//   bun src/codegen/generate-agent-tools.ts --inputs   print the input files, one per line
//   --tools <file> --skills <file> --out <dir>         other sources or output root (tests)

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const SELF = "src/codegen/generate-agent-tools.ts";
const TOOLS_JSON = "src/agent_tools/tools.json";
const SKILLS_JSON = "src/agent_tools/skills.json";
const TOOLS_RS = "src/agent_tools/generated/tools.rs";
const DOCS_PAGE = "docs/project/agent-tools.mdx";
const SKILLS_DIR = ".claude/skills";
const MARKER = `<!-- Generated by ${SELF} from ${SKILLS_JSON}. Edit the sources it names, not this file. -->`;

type Schema = {
  type?: string;
  description?: string;
  default?: unknown;
  enum?: unknown[];
  minimum?: number;
  maximum?: number;
  items?: Schema;
  properties?: Record<string, Schema>;
  required?: string[];
};
type ToolSpec = { name: string; title: string; description: string; inputSchema: Schema };
type ToolsFile = { title: string; description: string; tools: ToolSpec[] };

type Section =
  | { kind: "markdown"; file: string; heading?: string; within?: string; bold?: string; title?: string }
  | { kind: "pages"; files: string[]; title?: string }
  | { kind: "rustdoc"; globs: string[]; title?: string }
  | { kind: "tsdoc"; file: string; title?: string }
  | { kind: "files"; glob: string; title?: string; limit?: number }
  | { kind: "skills"; names: string[]; title?: string }
  | { kind: "lsp"; languages: string[]; title?: string }
  | { kind: "scripts"; names: string[]; title?: string }
  | { kind: "tools"; names?: string[]; title?: string };
type SkillSpec = { name: string; description: string; sections: Section[] };
type SkillsFile = { skills: SkillSpec[] };

// ─── Reading ───────────────────────────────────────────────────────────────

function read(rel: string): string {
  return readFileSync(join(ROOT, rel), "utf8").replace(/\r\n/g, "\n");
}

function maybe(rel: string): string | undefined {
  return existsSync(join(ROOT, rel)) ? read(rel) : undefined;
}

/** Inputs actually read, for `--inputs` and for ninja. */
const inputs = new Set<string>();

function source(rel: string): string {
  inputs.add(rel);
  return read(rel);
}

function globRegex(glob: string): RegExp {
  let re = "";
  for (let i = 0; i < glob.length; i++) {
    const c = glob[i]!;
    if (c === "*" && glob[i + 1] === "*") {
      re += glob[i + 2] === "/" ? "(?:.*/)?" : ".*";
      i += glob[i + 2] === "/" ? 2 : 1;
    } else if (c === "*") re += "[^/]*";
    else if (c === "?") re += "[^/]";
    else re += c.replace(/[.+^${}()|[\]\\]/g, "\\$&");
  }
  return new RegExp(`^${re}$`);
}

/** Files of the repository matching `glob` (`*`, `**`, `?`), sorted. */
function glob(pattern: string): string[] {
  const base = pattern.slice(0, pattern.search(/[*?]/)).replace(/[^/]*$/, "");
  const re = globRegex(pattern);
  const out: string[] = [];
  const visit = (dir: string) => {
    const abs = join(ROOT, dir);
    if (!existsSync(abs)) return;
    for (const name of readdirSync(abs).sort()) {
      if (name === "node_modules" || name === ".git") continue;
      const rel = dir ? `${dir}/${name}` : name;
      if (statSync(join(ROOT, rel)).isDirectory()) visit(rel);
      else if (re.test(rel)) out.push(rel);
    }
  };
  visit(base.replace(/\/$/, ""));
  return out.sort();
}

// ─── Shipping safety ───────────────────────────────────────────────────────

const SEP = String.raw`(?:\\\\|\\|/)+`;
/** Lines naming a host, an address, an account or a credential are dropped. */
const DROP = [
  /\b(?:\d{1,3}\.){3}\d{1,3}\b/,
  /\b[\w.+-]+@[\w-]+\.[\w.-]+\b/,
  /\bdbfr\b/i,
  /\bvps\b/i,
  /\byohan/i,
  /npmrc/i,
  /\b(?:npm|crates\.io|gh|github|api|auth|buildkite|discord|bot)[ _-]?tokens?\b/i,
  /\btoken (?:in|from|=)/i,
  /\bpassword\s*[:=]\s*["'\w]/i,
  /\bssh\s+(?:-\S+\s+)*[\w.-]+@/i,
  /\bghp_|\bgithub_pat_|\bnpm_[A-Za-z0-9]{20}/,
];
/** Never in an output; generation fails instead. */
const FORBIDDEN = [
  /[A-Za-z]:(?:\\\\|\\|\/)+Users(?:\\\\|\\|\/)/i,
  /\/home\/[a-z_][\w-]*\//,
  /\/Users\/[a-z_][\w-]*\//,
  /\baphro\b/i,
  ...DROP,
];

/** Personal paths become placeholders (`~`, `<dir>` for a drive-root directory). */
export function sanitize(text: string): string {
  const out: string[] = [];
  for (let line of text.split("\n")) {
    line = line
      .replace(new RegExp(String.raw`(?<![A-Za-z])[A-Za-z]:${SEP}Users${SEP}[^\\/\s"'\`)\]]+`, "g"), "~")
      .replace(/\/(?:home|Users)\/[a-z_][\w-]*(?=\/|\b)/g, "~")
      .replace(new RegExp(String.raw`(?<![A-Za-z])[A-Za-z]:${SEP}([\w.-]+)`, "g"), "<$1>");
    if (DROP.some(r => r.test(line))) continue;
    out.push(line);
  }
  return out.join("\n");
}

function assertShippable(path: string, text: string) {
  for (const r of FORBIDDEN) {
    const m = r.exec(text);
    if (m) {
      const start = text.lastIndexOf("\n", m.index) + 1;
      const end = text.indexOf("\n", m.index);
      throw new Error(`${path}: forbidden content (${r}): ${text.slice(start, end === -1 ? undefined : end)}`);
    }
  }
}

// ─── Markdown ──────────────────────────────────────────────────────────────

export function frontMatter(md: string): { fields: Record<string, string>; body: string } {
  const m = /^---\n([\s\S]*?)\n---\n?/.exec(md);
  if (!m) return { fields: {}, body: md };
  const fields: Record<string, string> = {};
  for (const line of m[1]!.split("\n")) {
    const kv = /^([\w-]+):\s*(.*)$/.exec(line);
    if (kv) fields[kv[1]!] = kv[2]!.replace(/^(["'])(.*)\1$/, "$2");
  }
  return { fields, body: md.slice(m[0].length) };
}

type Line = { text: string; code: boolean; heading?: { level: number; title: string } };

/** Lines tagged as inside a code fence or as a heading (`#` lines in code blocks are not headings). */
function lines(md: string): Line[] {
  const out: Line[] = [];
  let fence: string | undefined;
  for (const text of md.split("\n")) {
    const f = /^\s*(```+|~~~+)/.exec(text);
    if (f) {
      if (!fence) fence = f[1];
      else if (f[1]!.startsWith(fence[0]!) && f[1]!.length >= fence.length) fence = undefined;
      out.push({ text, code: true });
      continue;
    }
    if (fence) {
      out.push({ text, code: true });
      continue;
    }
    const h = /^(#{1,6})\s+(.*?)\s*#*\s*$/.exec(text);
    out.push(h ? { text, code: false, heading: { level: h[1]!.length, title: h[2]! } } : { text, code: false });
  }
  return out;
}

function findHeading(ls: Line[], title: string, from = 0, prefix = false): number {
  for (let i = from; i < ls.length; i++) {
    const h = ls[i]!.heading;
    if (h && (prefix ? h.title.startsWith(title) : h.title === title)) return i;
  }
  return -1;
}

/** End (exclusive) of the section opened by the heading at `at`. */
function sectionEnd(ls: Line[], at: number): number {
  const level = ls[at]!.heading!.level;
  for (let i = at + 1; i < ls.length; i++) {
    const h = ls[i]!.heading;
    if (h && h.level <= level) return i;
  }
  return ls.length;
}

/** MDX to plain markdown: component tags dropped, fence info reduced to the language. */
function plain(ls: Line[]): string {
  const out: string[] = [];
  for (const l of ls) {
    if (l.code) {
      out.push(l.text.replace(/^(\s*(?:```+|~~~+)[\w+-]*)\s.*$/, "$1"));
      continue;
    }
    if (/^\s*<\/?[A-Z][\w.]*(?:\s[^>]*)?\/?>\s*$/.test(l.text)) continue;
    out.push(l.text);
  }
  return out.join("\n");
}

/** Re-levels headings so that a section titled at `from` lands at `to`. */
function relevel(ls: Line[], from: number, to: number): Line[] {
  return ls.map(l =>
    l.heading
      ? {
          ...l,
          text: `${"#".repeat(Math.min(6, Math.max(to, l.heading.level - from + to)))} ${l.heading.title}`,
        }
      : l,
  );
}

function squeeze(text: string): string {
  return text.replace(/\n{3,}/g, "\n\n").trim();
}

function firstParagraph(body: string): string {
  const para: string[] = [];
  for (const l of lines(body)) {
    const t = l.text.trim();
    if (l.code || l.heading || /^[|<>!-]/.test(t) || /^\*\*/.test(t)) {
      if (para.length) break;
      continue;
    }
    if (!t) {
      if (para.length) break;
      continue;
    }
    para.push(t);
  }
  return clip(para.join(" "), 280);
}

function clip(text: string, max: number): string {
  if (text.length <= max) return text;
  const cut = text.slice(0, max);
  const stop = cut.lastIndexOf(". ");
  return stop > max / 2 ? cut.slice(0, stop + 1) : cut.replace(/\s+\S*$/, "") + "…";
}

// ─── Sections ──────────────────────────────────────────────────────────────

function markdownSection(s: Extract<Section, { kind: "markdown" }>): string {
  const md = source(s.file);
  const { fields, body } = frontMatter(md);
  const ls = lines(body);
  let start = 0;
  let end = ls.length;
  if (s.within) {
    start = findHeading(ls, s.within, 0, true);
    if (start < 0) throw new Error(`${s.file}: no heading starting with ${JSON.stringify(s.within)}`);
    end = sectionEnd(ls, start);
  }
  if (s.heading) {
    const at = findHeading(ls.slice(0, end), s.heading, start);
    if (at < 0) throw new Error(`${s.file}: no heading ${JSON.stringify(s.heading)}`);
    const h = ls[at]!.heading!;
    const content = relevel(ls.slice(at + 1, sectionEnd(ls, at)), h.level + 1, 3);
    return `## ${s.title ?? h.title}\n\n_From \`${s.file}\`._\n\n${squeeze(plain(content))}`;
  }
  if (s.bold) {
    const label = `**${s.bold}`;
    let at = -1;
    for (let i = start; i < end; i++) if (!ls[i]!.code && ls[i]!.text.startsWith(label)) at = at < 0 ? i : at;
    if (at < 0) throw new Error(`${s.file}: no paragraph starting with ${label}**`);
    let stop = at + 1;
    while (stop < end && !ls[stop]!.heading && !(!ls[stop]!.code && ls[stop]!.text.startsWith("**"))) stop++;
    const first = ls[at]!.text.replace(/^\*\*[^*]+\*\*\s*(?:[—:-]\s*)?/, "");
    const content = [{ text: first, code: false }, ...ls.slice(at + 1, stop)];
    return `## ${s.title ?? s.bold}\n\n_From \`${s.file}\`._\n\n${squeeze(plain(content))}`;
  }
  const title = s.title ?? fields.title ?? ls.find(l => l.heading?.level === 1)?.heading?.title ?? s.file;
  const content = relevel(
    ls.filter(l => l.heading?.level !== 1),
    2,
    3,
  );
  const intro = fields.description ? `${fields.description}\n\n` : "";
  return `## ${title}\n\n_From \`${s.file}\`._\n\n${intro}${squeeze(plain(content))}`;
}

function pagesSection(s: Extract<Section, { kind: "pages" }>): string {
  const items = s.files.map(file => {
    const { fields, body } = frontMatter(source(file));
    const ls = lines(body);
    const title = fields.title ?? ls.find(l => l.heading?.level === 1)?.heading?.title ?? file;
    const description = fields.description ?? firstParagraph(body);
    const sections = ls.filter(l => l.heading?.level === 2).map(l => l.heading!.title);
    return `- \`${file}\`: **${title}**. ${description}${sections.length ? `\n  Sections: ${sections.join("; ")}.` : ""}`;
  });
  return `## ${s.title ?? "Read next"}\n\n${items.join("\n")}`;
}

function moduleDoc(text: string): string {
  const doc: string[] = [];
  for (const line of text.split("\n")) {
    const m = /^\s*\/\/!\s?(.*)$/.exec(line);
    if (!m) {
      if (doc.length || !/^\s*(?:#!?\[|\/\/|$)/.test(line)) break;
      continue;
    }
    if (!m[1]!.trim()) {
      if (doc.length) break;
      continue;
    }
    doc.push(m[1]!.trim());
  }
  return clip(doc.join(" "), 300);
}

function rustdocSection(s: Extract<Section, { kind: "rustdoc" }>): string {
  const items: string[] = [];
  for (const file of s.globs.flatMap(glob)) {
    const doc = moduleDoc(source(file));
    if (doc) items.push(`- \`${file}\`: ${doc}`);
  }
  return `## ${s.title ?? "Source map"}\n\n${items.join("\n")}`;
}

function jsdoc(comment: string): string {
  return comment
    .replace(/^\/\*\*?/, "")
    .replace(/\*\/$/, "")
    .split("\n")
    .map(l => l.replace(/^\s*\* ?/, ""))
    .join("\n")
    .trim();
}

function tsdocSection(s: Extract<Section, { kind: "tsdoc" }>): string {
  const text = source(s.file).replace(/^#!.*\n/, "");
  // Free-standing block comments of 3+ lines are prose; a doc comment on an export documents it.
  const prose: string[] = [];
  const items: string[] = [];
  const decl =
    /^(export\s+)?(?:declare\s+)?(?:async\s+)?(?:const|let|var|function\*?|class|type|interface|enum)\s+([\w$]+)(.*)$/;
  for (const m of text.matchAll(/\/\*\*?((?:(?!\*\/)[\s\S])*)\*\/[ \t]*(?:\n(.*))?/g)) {
    const doc = jsdoc(m[0].slice(0, m[0].indexOf("*/") + 2));
    const d = decl.exec(m[2] ?? "");
    if (d) {
      if (!d[1]) continue;
      const value = /^\s*(?::[^=]+)?=\s*("[^"\n]{1,100}"|\d+)\s*;?\s*$/.exec(d[3]!)?.[1];
      items.push(`- \`${d[2]}\`${value ? ` = \`${value}\`` : ""}: ${doc.replace(/\s*\n\s*/g, " ")}`);
    } else if (doc.split("\n").length >= 3) {
      prose.push(squeeze(plain(relevel(lines(doc), 2, 3))));
    }
  }
  const parts = [...prose];
  if (items.length) parts.push(items.join("\n"));
  return `## ${s.title ?? `\`${s.file}\``}\n\n_From \`${s.file}\`._\n\n${parts.join("\n\n")}`;
}

function filesSection(s: Extract<Section, { kind: "files" }>): string {
  const files = glob(s.glob);
  const dirs = new Map<string, number>();
  for (const f of files) {
    const d = f.slice(0, f.lastIndexOf("/"));
    dirs.set(d, (dirs.get(d) ?? 0) + 1);
  }
  const limit = s.limit ?? 0;
  const lines = [
    `${files.length} files match \`${s.glob}\`, in ${[...dirs].map(([d, n]) => `\`${d}\` (${n})`).join(", ")}.`,
  ];
  if (limit > 0) lines.push(...files.slice(0, limit).map(f => `- \`${f}\``));
  return `## ${s.title ?? `\`${s.glob}\``}\n\n${lines.join("\n")}`;
}

function skillsSection(s: Extract<Section, { kind: "skills" }>): string {
  const items = s.names.map(name => {
    const file = `${SKILLS_DIR}/${name}/SKILL.md`;
    const md = maybe(file);
    if (md === undefined) throw new Error(`skill ${name} not found at ${file}`);
    inputs.add(file);
    return `- \`${name}\`: ${frontMatter(md).fields.description ?? ""}`;
  });
  return `## ${s.title ?? "Related skills"}\n\n${items.join("\n")}`;
}

/** From the `bun lsp` sources (src/lsp); omitted while they are absent. */
function lspSection(s: Extract<Section, { kind: "lsp" }>): string | undefined {
  const cli = maybe("src/lsp/cli.rs");
  const lib = maybe("src/lsp/lib.rs");
  const language = maybe("src/lsp/language.rs");
  if (cli === undefined || lib === undefined || language === undefined) return undefined;
  for (const f of ["src/lsp/cli.rs", "src/lsp/lib.rs", "src/lsp/language.rs"]) inputs.add(f);
  const help = /const HELP: &str = "\\\n([\s\S]*?)";/.exec(cli)?.[1]?.replace(/\\"/g, '"');
  if (!help) throw new Error("src/lsp/cli.rs: no HELP text");
  const variant = (name: string) => {
    for (const m of language.matchAll(/^\s*((?:"[^"]+"\s*\|\s*)*"[^"]+")\s*=>\s*Language::(\w+),/gm))
      if (m[1]!.split("|").some(a => a.trim() === JSON.stringify(name))) return m[2]!;
    throw new Error(`src/lsp/language.rs: no language named ${name}`);
  };
  const bullets = [...lib.matchAll(/^\/\/! - (.*(?:\n\/\/! {3}.*)*)/gm)].map(m =>
    m[1]!.replace(/\n\/\/! {3}/g, " ").trim(),
  );
  const items = s.languages.map(name => {
    const v = variant(name);
    const markers = new RegExp(String.raw`Language::${v}\s*=>\s*&\[([^\]]*)\]`).exec(language)?.[1];
    const doc = new RegExp(String.raw`///\s*(.*)\n\s*${v},`).exec(language)?.[1];
    const servers = bullets.find(b => {
      const head = b.slice(0, b.indexOf(":")).toLowerCase();
      return head.includes(v === "Cpp" ? "c++" : v.toLowerCase());
    });
    return `- \`${name}\`${doc ? ` (${doc.replace(/\.$/, "")})` : ""}: ${servers ?? ""}${
      markers ? ` Project root: the nearest ${markers.replace(/\s+/g, " ").trim()}.` : ""
    }`;
  });
  return `## ${s.title ?? "Language server (`bun lsp`)"}\n\n_From \`src/lsp\`._\n\n${items.join("\n")}\n\n\`\`\`\n${help.trimEnd()}\n\`\`\``;
}

function scriptsSection(s: Extract<Section, { kind: "scripts" }>): string {
  const scripts: Record<string, string> = JSON.parse(source("package.json")).scripts ?? {};
  const rows = s.names.map(name => {
    if (!(name in scripts)) throw new Error(`package.json has no script ${name}`);
    return `| \`bun run ${name}\` | \`${scripts[name]!.replace(/\|/g, "\\|")}\` |`;
  });
  return `## ${s.title ?? "Gates"}\n\n_From \`package.json\`._\n\n| Script | Runs |\n| --- | --- |\n${rows.join("\n")}`;
}

function typeOf(p: Schema): string {
  if (p.type === "array") return `${p.items?.type ?? "any"}[]`;
  if (p.enum) return p.enum.map(v => JSON.stringify(v)).join(" \\| ");
  return p.type ?? "any";
}

function toolReference(tool: ToolSpec, level: number): string {
  const props = Object.entries(tool.inputSchema.properties ?? {});
  const required = new Set(tool.inputSchema.required ?? []);
  const rows = props.map(([name, p]) => {
    const bounds = [p.minimum !== undefined && `min ${p.minimum}`, p.maximum !== undefined && `max ${p.maximum}`]
      .filter(Boolean)
      .join(", ");
    return `| \`${name}\` | ${typeOf(p)}${required.has(name) ? " (required)" : ""}${bounds ? `, ${bounds}` : ""} | ${(
      p.description ?? ""
    ).replace(/\|/g, "\\|")} |`;
  });
  return [
    `${"#".repeat(level)} \`${tool.name}\`: ${tool.title}`,
    tool.description,
    rows.length ? `| Argument | Type | Description |\n| --- | --- | --- |\n${rows.join("\n")}` : "No arguments.",
  ].join("\n\n");
}

function toolsSection(tools: ToolsFile, s: Extract<Section, { kind: "tools" }>): string {
  inputs.add(TOOLS_JSON);
  const picked = s.names ? tools.tools.filter(t => s.names!.includes(t.name)) : tools.tools;
  return `## ${s.title ?? "Tools of `bun mcp`"}\n\n${tools.description}\n\n${picked.map(t => toolReference(t, 3)).join("\n\n")}`;
}

// ─── Outputs ───────────────────────────────────────────────────────────────

function rustString(s: string): string {
  let out = '"';
  for (const ch of s) {
    const c = ch.codePointAt(0)!;
    if (ch === '"') out += '\\"';
    else if (ch === "\\") out += "\\\\";
    else if (ch === "\n") out += "\\n";
    else if (ch === "\t") out += "\\t";
    else if (ch === "\r") out += "\\r";
    else if (c < 0x20 || c === 0x7f) out += `\\u{${c.toString(16)}}`;
    else out += ch;
  }
  return out + '"';
}

export function toolsRs(tools: ToolsFile): string {
  const ident = (name: string) => name.toUpperCase();
  const consts = tools.tools.map(
    t => `/// ${t.title}.
pub const ${ident(t.name)}: ToolSchema = ToolSchema {
    name: ${rustString(t.name)},
    title: ${rustString(t.title)},
    description: ${rustString(t.description)},
    input_schema: ${rustString(JSON.stringify(t.inputSchema))},
};`,
  );
  return `// Generated by ${SELF} from ${TOOLS_JSON}. Do not edit.

use crate::ToolSchema;

${consts.join("\n\n")}

/// Every tool of \`tools.json\`, in declaration order.
pub const SCHEMAS: &[ToolSchema] = &[
${tools.tools.map(t => `    ${ident(t.name)},\n`).join("")}];
`;
}

export function docsPage(tools: ToolsFile, skills: SkillsFile): string {
  const skillRows = skills.skills.map(
    s =>
      `| \`${s.name}\` | ${s.description.replace(/\|/g, "\\|")} | ${[
        ...new Set(
          s.sections.flatMap(x =>
            "file" in x
              ? [x.file]
              : "files" in x
                ? x.files
                : "globs" in x
                  ? x.globs
                  : "glob" in x
                    ? [x.glob]
                    : x.kind === "lsp"
                      ? ["src/lsp"]
                      : x.kind === "scripts"
                        ? ["package.json"]
                        : x.kind === "tools"
                          ? [TOOLS_JSON]
                          : [],
          ),
        ),
      ]
        .map(f => `\`${f}\``)
        .join(", ")} |`,
  );
  return `---
title: ${JSON.stringify(tools.title)}
description: ${JSON.stringify(tools.description)}
---

{/* Generated by ${SELF} from ${TOOLS_JSON} and ${SKILLS_JSON}. Do not edit. */}

${tools.description}

${tools.tools.map(t => toolReference(t, 2)).join("\n\n")}

## Skills

These skills are generated from the repository into \`${SKILLS_DIR}\`, shipped with \`bun mcp\` and the agent plugin:

| Skill | Use | Sources |
| --- | --- | --- |
${skillRows.join("\n")}
`;
}

export function skillDoc(tools: ToolsFile, skill: SkillSpec): string {
  const body = skill.sections
    .map(s => {
      switch (s.kind) {
        case "markdown":
          return markdownSection(s);
        case "pages":
          return pagesSection(s);
        case "rustdoc":
          return rustdocSection(s);
        case "tsdoc":
          return tsdocSection(s);
        case "files":
          return filesSection(s);
        case "skills":
          return skillsSection(s);
        case "lsp":
          return lspSection(s);
        case "scripts":
          return scriptsSection(s);
        case "tools":
          return toolsSection(tools, s);
      }
    })
    .filter((s): s is string => !!s);
  return sanitize(
    `---\nname: ${skill.name}\ndescription: ${JSON.stringify(skill.description)}\n---\n\n${MARKER}\n\n${body.join("\n\n")}\n`,
  ).replace(/\n{3,}/g, "\n\n");
}

export type Generated = Map<string, string>;

export function generate(toolsPath = TOOLS_JSON, skillsPath = SKILLS_JSON): Generated {
  inputs.clear();
  inputs.add(SELF);
  const tools: ToolsFile = JSON.parse(readFileSync(resolve(ROOT, toolsPath), "utf8"));
  const skills: SkillsFile = JSON.parse(readFileSync(resolve(ROOT, skillsPath), "utf8"));
  inputs.add(relative(ROOT, resolve(ROOT, toolsPath)).replace(/\\/g, "/"));
  inputs.add(relative(ROOT, resolve(ROOT, skillsPath)).replace(/\\/g, "/"));
  const names = new Set<string>();
  for (const t of tools.tools) {
    if (!/^[a-z][a-z0-9_]*$/.test(t.name) || names.has(t.name)) throw new Error(`bad or duplicate tool ${t.name}`);
    names.add(t.name);
  }
  const out: Generated = new Map();
  out.set(TOOLS_RS, toolsRs(tools));
  out.set(DOCS_PAGE, docsPage(tools, skills));
  for (const skill of skills.skills) {
    if (!/^[a-z][a-z0-9-]*$/.test(skill.name)) throw new Error(`bad skill name ${skill.name}`);
    out.set(`${SKILLS_DIR}/${skill.name}/SKILL.md`, skillDoc(tools, skill));
  }
  for (const [path, text] of out) assertShippable(path, text);
  return out;
}

/** Repository-relative inputs and outputs of one run, for the ninja edge in scripts/build/codegen.ts. */
export function plan(): { script: string; inputs: string[]; outputs: string[] } {
  const generated = generate();
  return { script: SELF, inputs: [...inputs].sort(), outputs: [...generated.keys()] };
}

/** Generated skill directories no longer in skills.json. */
function staleSkills(outRoot: string, generated: Generated): string[] {
  const dir = join(outRoot, SKILLS_DIR);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .sort()
    .filter(name => {
      const file = join(dir, name, "SKILL.md");
      return (
        !generated.has(`${SKILLS_DIR}/${name}/SKILL.md`) &&
        existsSync(file) &&
        readFileSync(file, "utf8").includes(`<!-- Generated by ${SELF}`)
      );
    })
    .map(name => `${SKILLS_DIR}/${name}`);
}

function option(args: string[], name: string): string | undefined {
  const i = args.indexOf(name);
  return i === -1 ? undefined : args[i + 1];
}

function main(args: string[]): number {
  const generated = generate(option(args, "--tools"), option(args, "--skills"));
  if (args.includes("--inputs")) {
    for (const f of [...inputs].sort()) console.log(f);
    return 0;
  }
  if (args.includes("--outputs")) {
    for (const f of generated.keys()) console.log(f);
    return 0;
  }
  const outRoot = resolve(option(args, "--out") ?? ROOT);
  const stale = staleSkills(outRoot, generated);
  const changed = [...generated].filter(([path, text]) => {
    const file = join(outRoot, path);
    return !existsSync(file) || readFileSync(file, "utf8") !== text;
  });
  if (args.includes("--check")) {
    for (const [path] of changed) console.error(`stale: ${path}`);
    for (const path of stale) console.error(`stale: ${path} (not in ${SKILLS_JSON})`);
    if (changed.length || stale.length) {
      console.error(`run: bun ${SELF}`);
      return 1;
    }
    return 0;
  }
  for (const [path, text] of changed) {
    mkdirSync(dirname(join(outRoot, path)), { recursive: true });
    writeFileSync(join(outRoot, path), text);
  }
  for (const path of stale) rmSync(join(outRoot, path), { recursive: true, force: true });
  return 0;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exitCode = main(process.argv.slice(2));
}
