// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** cryptnet.dll!CryptGetObjectUrl */
  CryptGetObjectUrl(pszUrlOid: string | Win32Pointer, pvPara: Win32Pointer, dwFlags: number, pUrlArray: Win32Pointer, pcbUrlArray: Win32Pointer, pUrlInfo: Win32Pointer, pcbUrlInfo: Win32Pointer, pvReserved: Win32Pointer): number;
  /** cryptnet.dll!CryptInstallCancelRetrieval */
  CryptInstallCancelRetrieval(pfnCancel: Win32Callback, pvArg: Win32Pointer, dwFlags: number, pvReserved: Win32Pointer): number;
  /** cryptnet.dll!CryptRetrieveObjectByUrlA */
  CryptRetrieveObjectByUrlA(pszUrl: string | Win32Pointer, pszObjectOid: string | Win32Pointer, dwRetrievalFlags: number, dwTimeout: number, ppvObject: Win32Pointer, hAsyncRetrieve: number | bigint, pCredentials: Win32Pointer, pvVerify: Win32Pointer, pAuxInfo: Win32Pointer): number;
  /** cryptnet.dll!CryptRetrieveObjectByUrlW */
  CryptRetrieveObjectByUrlW(pszUrl: string | Win32Pointer, pszObjectOid: string | Win32Pointer, dwRetrievalFlags: number, dwTimeout: number, ppvObject: Win32Pointer, hAsyncRetrieve: number | bigint, pCredentials: Win32Pointer, pvVerify: Win32Pointer, pAuxInfo: Win32Pointer): number;
  /** cryptnet.dll!CryptRetrieveObjectByUrlW */
  CryptRetrieveObjectByUrl(pszUrl: string | Win32Pointer, pszObjectOid: string | Win32Pointer, dwRetrievalFlags: number, dwTimeout: number, ppvObject: Win32Pointer, hAsyncRetrieve: number | bigint, pCredentials: Win32Pointer, pvVerify: Win32Pointer, pAuxInfo: Win32Pointer): number;
  /** cryptnet.dll!CryptUninstallCancelRetrieval */
  CryptUninstallCancelRetrieval(dwFlags: number, pvReserved: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
