// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** bluetoothapis.dll!BluetoothEnableDiscovery */
  BluetoothEnableDiscovery(hRadio: Win32Pointer, fEnabled: number): number;
  /** bluetoothapis.dll!BluetoothEnableIncomingConnections */
  BluetoothEnableIncomingConnections(hRadio: Win32Pointer, fEnabled: number): number;
  /** bluetoothapis.dll!BluetoothEnumerateInstalledServices */
  BluetoothEnumerateInstalledServices(hRadio: Win32Pointer, pbtdi: Win32Pointer, pcServiceInout: Win32Pointer, pGuidServices: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothFindDeviceClose */
  BluetoothFindDeviceClose(hFind: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothFindFirstDevice */
  BluetoothFindFirstDevice(pbtsp: Win32Pointer, pbtdi: Win32Pointer): number | null;
  /** bluetoothapis.dll!BluetoothFindFirstRadio */
  BluetoothFindFirstRadio(pbtfrp: Win32Pointer, phRadio: Win32Pointer): number | null;
  /** bluetoothapis.dll!BluetoothFindNextDevice */
  BluetoothFindNextDevice(hFind: Win32Pointer, pbtdi: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothFindNextRadio */
  BluetoothFindNextRadio(hFind: Win32Pointer, phRadio: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothFindRadioClose */
  BluetoothFindRadioClose(hFind: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothGATTAbortReliableWrite */
  BluetoothGATTAbortReliableWrite(hDevice: Win32Pointer, ReliableWriteContext: number | bigint, Flags: number): number;
  /** bluetoothapis.dll!BluetoothGATTBeginReliableWrite */
  BluetoothGATTBeginReliableWrite(hDevice: Win32Pointer, ReliableWriteContext: Win32Pointer, Flags: number): number;
  /** bluetoothapis.dll!BluetoothGATTEndReliableWrite */
  BluetoothGATTEndReliableWrite(hDevice: Win32Pointer, ReliableWriteContext: number | bigint, Flags: number): number;
  /** bluetoothapis.dll!BluetoothGATTGetCharacteristicValue */
  BluetoothGATTGetCharacteristicValue(hDevice: Win32Pointer, Characteristic: Win32Pointer, CharacteristicValueDataSize: number, CharacteristicValue: Win32Pointer, CharacteristicValueSizeRequired: Win32Pointer, Flags: number): number;
  /** bluetoothapis.dll!BluetoothGATTGetCharacteristics */
  BluetoothGATTGetCharacteristics(hDevice: Win32Pointer, Service: Win32Pointer, CharacteristicsBufferCount: number, CharacteristicsBuffer: Win32Pointer, CharacteristicsBufferActual: Win32Pointer, Flags: number): number;
  /** bluetoothapis.dll!BluetoothGATTGetDescriptorValue */
  BluetoothGATTGetDescriptorValue(hDevice: Win32Pointer, Descriptor: Win32Pointer, DescriptorValueDataSize: number, DescriptorValue: Win32Pointer, DescriptorValueSizeRequired: Win32Pointer, Flags: number): number;
  /** bluetoothapis.dll!BluetoothGATTGetDescriptors */
  BluetoothGATTGetDescriptors(hDevice: Win32Pointer, Characteristic: Win32Pointer, DescriptorsBufferCount: number, DescriptorsBuffer: Win32Pointer, DescriptorsBufferActual: Win32Pointer, Flags: number): number;
  /** bluetoothapis.dll!BluetoothGATTGetIncludedServices */
  BluetoothGATTGetIncludedServices(hDevice: Win32Pointer, ParentService: Win32Pointer, IncludedServicesBufferCount: number, IncludedServicesBuffer: Win32Pointer, IncludedServicesBufferActual: Win32Pointer, Flags: number): number;
  /** bluetoothapis.dll!BluetoothGATTGetServices */
  BluetoothGATTGetServices(hDevice: Win32Pointer, ServicesBufferCount: number, ServicesBuffer: Win32Pointer, ServicesBufferActual: Win32Pointer, Flags: number): number;
  /** bluetoothapis.dll!BluetoothGATTRegisterEvent */
  BluetoothGATTRegisterEvent(hService: Win32Pointer, EventType: number, EventParameterIn: Win32Pointer, Callback: Win32Callback, CallbackContext: Win32Pointer, pEventHandle: Win32Pointer, Flags: number): number;
  /** bluetoothapis.dll!BluetoothGATTSetCharacteristicValue */
  BluetoothGATTSetCharacteristicValue(hDevice: Win32Pointer, Characteristic: Win32Pointer, CharacteristicValue: Win32Pointer, ReliableWriteContext: number | bigint, Flags: number): number;
  /** bluetoothapis.dll!BluetoothGATTSetDescriptorValue */
  BluetoothGATTSetDescriptorValue(hDevice: Win32Pointer, Descriptor: Win32Pointer, DescriptorValue: Win32Pointer, Flags: number): number;
  /** bluetoothapis.dll!BluetoothGATTUnregisterEvent */
  BluetoothGATTUnregisterEvent(EventHandle: number | bigint, Flags: number): number;
  /** bluetoothapis.dll!BluetoothGetDeviceInfo */
  BluetoothGetDeviceInfo(hRadio: Win32Pointer, pbtdi: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothGetRadioInfo */
  BluetoothGetRadioInfo(hRadio: Win32Pointer, pRadioInfo: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothIsConnectable */
  BluetoothIsConnectable(hRadio: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothIsDiscoverable */
  BluetoothIsDiscoverable(hRadio: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothIsVersionAvailable */
  BluetoothIsVersionAvailable(MajorVersion: number, MinorVersion: number): number;
  /** bluetoothapis.dll!BluetoothRegisterForAuthentication */
  BluetoothRegisterForAuthentication(pbtdi: Win32Pointer, phRegHandle: Win32Pointer, pfnCallback: Win32Callback, pvParam: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothRegisterForAuthenticationEx */
  BluetoothRegisterForAuthenticationEx(pbtdiIn: Win32Pointer, phRegHandleOut: Win32Pointer, pfnCallbackIn: Win32Callback, pvParam: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothRemoveDevice */
  BluetoothRemoveDevice(pAddress: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothSdpEnumAttributes */
  BluetoothSdpEnumAttributes(pSDPStream: Win32Pointer, cbStreamSize: number, pfnCallback: Win32Callback, pvParam: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothSdpGetAttributeValue */
  BluetoothSdpGetAttributeValue(pRecordStream: Win32Pointer, cbRecordLength: number, usAttributeId: number, pAttributeData: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothSdpGetContainerElementData */
  BluetoothSdpGetContainerElementData(pContainerStream: Win32Pointer, cbContainerLength: number, pElement: Win32Pointer, pData: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothSdpGetElementData */
  BluetoothSdpGetElementData(pSdpStream: Win32Pointer, cbSdpStreamLength: number, pData: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothSdpGetString */
  BluetoothSdpGetString(pRecordStream: Win32Pointer, cbRecordLength: number, pStringData: Win32Pointer, usStringOffset: number, pszString: string | Win32Pointer, pcchStringLength: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothSendAuthenticationResponse */
  BluetoothSendAuthenticationResponse(hRadio: Win32Pointer, pbtdi: Win32Pointer, pszPasskey: string | Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothSendAuthenticationResponseEx */
  BluetoothSendAuthenticationResponseEx(hRadioIn: Win32Pointer, pauthResponse: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothSetLocalServiceInfo */
  BluetoothSetLocalServiceInfo(hRadioIn: Win32Pointer, pClassGuid: Win32Pointer, ulInstance: number, pServiceInfoIn: Win32Pointer): number;
  /** bluetoothapis.dll!BluetoothSetServiceState */
  BluetoothSetServiceState(hRadio: Win32Pointer, pbtdi: Win32Pointer, pGuidService: Win32Pointer, dwServiceFlags: number): number;
  /** bluetoothapis.dll!BluetoothUnregisterAuthentication */
  BluetoothUnregisterAuthentication(hRegHandle: number | bigint): number;
  /** bluetoothapis.dll!BluetoothUpdateDeviceRecord */
  BluetoothUpdateDeviceRecord(pbtdi: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
