// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** ualapi.dll!UalInstrument */
  UalInstrument(Data: Win32Pointer): number;
  /** ualapi.dll!UalRegisterProduct */
  UalRegisterProduct(wszProductName: string | Win32Pointer, wszRoleName: string | Win32Pointer, wszGuid: string | Win32Pointer): number;
  /** ualapi.dll!UalStart */
  UalStart(Data: Win32Pointer): number;
  /** ualapi.dll!UalStop */
  UalStop(Data: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
