// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** wscapi.dll!WscGetAntiMalwareUri */
  WscGetAntiMalwareUri(ppszUri: Win32Pointer): number;
  /** wscapi.dll!WscGetSecurityProviderHealth */
  WscGetSecurityProviderHealth(Providers: number, pHealth: Win32Pointer): number;
  /** wscapi.dll!WscQueryAntiMalwareUri */
  WscQueryAntiMalwareUri(): number;
  /** wscapi.dll!WscRegisterForChanges */
  WscRegisterForChanges(Reserved: Win32Pointer, phCallbackRegistration: Win32Pointer, lpCallbackAddress: Win32Callback, pContext: Win32Pointer): number;
  /** wscapi.dll!WscRegisterForUserNotifications */
  WscRegisterForUserNotifications(): number;
  /** wscapi.dll!WscUnRegisterChanges */
  WscUnRegisterChanges(hRegistrationHandle: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
