// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** wmvcore.dll!WMCreateBackupRestorer */
  WMCreateBackupRestorer(pCallback: Win32Pointer, ppBackup: Win32Pointer): number;
  /** wmvcore.dll!WMCreateEditor */
  WMCreateEditor(ppEditor: Win32Pointer): number;
  /** wmvcore.dll!WMCreateIndexer */
  WMCreateIndexer(ppIndexer: Win32Pointer): number;
  /** wmvcore.dll!WMCreateProfileManager */
  WMCreateProfileManager(ppProfileManager: Win32Pointer): number;
  /** wmvcore.dll!WMCreateReader */
  WMCreateReader(pUnkCert: Win32Pointer, dwRights: number, ppReader: Win32Pointer): number;
  /** wmvcore.dll!WMCreateSyncReader */
  WMCreateSyncReader(pUnkCert: Win32Pointer, dwRights: number, ppSyncReader: Win32Pointer): number;
  /** wmvcore.dll!WMCreateWriter */
  WMCreateWriter(pUnkCert: Win32Pointer, ppWriter: Win32Pointer): number;
  /** wmvcore.dll!WMCreateWriterFileSink */
  WMCreateWriterFileSink(ppSink: Win32Pointer): number;
  /** wmvcore.dll!WMCreateWriterNetworkSink */
  WMCreateWriterNetworkSink(ppSink: Win32Pointer): number;
  /** wmvcore.dll!WMCreateWriterPushSink */
  WMCreateWriterPushSink(ppSink: Win32Pointer): number;
  /** wmvcore.dll!WMIsContentProtected */
  WMIsContentProtected(pwszFileName: string | Win32Pointer, pfIsProtected: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
