// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** wlanui.dll!WlanUIEditProfile */
  WlanUIEditProfile(dwClientVersion: number, wstrProfileName: string | Win32Pointer, pInterfaceGuid: Win32Pointer, hWnd: Win32Pointer, wlStartPage: number, pReserved: Win32Pointer, pWlanReasonCode: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
