// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** ndfapi.dll!NdfCancelIncident */
  NdfCancelIncident(Handle: Win32Pointer): number;
  /** ndfapi.dll!NdfCloseIncident */
  NdfCloseIncident(handle: Win32Pointer): number;
  /** ndfapi.dll!NdfCreateConnectivityIncident */
  NdfCreateConnectivityIncident(handle: Win32Pointer): number;
  /** ndfapi.dll!NdfCreateDNSIncident */
  NdfCreateDNSIncident(hostname: string | Win32Pointer, queryType: number, handle: Win32Pointer): number;
  /** ndfapi.dll!NdfCreateGroupingIncident */
  NdfCreateGroupingIncident(CloudName: string | Win32Pointer, GroupName: string | Win32Pointer, Identity: string | Win32Pointer, Invitation: string | Win32Pointer, Addresses: Win32Pointer, appId: string | Win32Pointer, handle: Win32Pointer): number;
  /** ndfapi.dll!NdfCreateIncident */
  NdfCreateIncident(helperClassName: string | Win32Pointer, celt: number, attributes: Win32Pointer, handle: Win32Pointer): number;
  /** ndfapi.dll!NdfCreateNetConnectionIncident */
  NdfCreateNetConnectionIncident(handle: Win32Pointer, id: Win32StructInit): number;
  /** ndfapi.dll!NdfCreatePnrpIncident */
  NdfCreatePnrpIncident(cloudname: string | Win32Pointer, peername: string | Win32Pointer, diagnosePublish: number, appId: string | Win32Pointer, handle: Win32Pointer): number;
  /** ndfapi.dll!NdfCreateSharingIncident */
  NdfCreateSharingIncident(UNCPath: string | Win32Pointer, handle: Win32Pointer): number;
  /** ndfapi.dll!NdfCreateWebIncident */
  NdfCreateWebIncident(url: string | Win32Pointer, handle: Win32Pointer): number;
  /** ndfapi.dll!NdfCreateWebIncidentEx */
  NdfCreateWebIncidentEx(url: string | Win32Pointer, useWinHTTP: number, moduleName: string | Win32Pointer, handle: Win32Pointer): number;
  /** ndfapi.dll!NdfCreateWinSockIncident */
  NdfCreateWinSockIncident(sock: number | bigint, host: string | Win32Pointer, port: number, appId: string | Win32Pointer, userId: Win32Pointer, handle: Win32Pointer): number;
  /** ndfapi.dll!NdfDiagnoseIncident */
  NdfDiagnoseIncident(Handle: Win32Pointer, RootCauseCount: Win32Pointer, RootCauses: Win32Pointer, dwWait: number, dwFlags: number): number;
  /** ndfapi.dll!NdfExecuteDiagnosis */
  NdfExecuteDiagnosis(handle: Win32Pointer, hwnd: Win32Pointer): number;
  /** ndfapi.dll!NdfGetTraceFile */
  NdfGetTraceFile(Handle: Win32Pointer, TraceFileLocation: Win32Pointer): number;
  /** ndfapi.dll!NdfRepairIncident */
  NdfRepairIncident(Handle: Win32Pointer, RepairEx: Win32Pointer, dwWait: number): number;
}

declare const family: Win32Family & Functions;
export = family;
