// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** schannel.dll!SslCrackCertificate */
  SslCrackCertificate(pbCertificate: Win32Pointer, cbCertificate: number, dwFlags: number, ppCertificate: Win32Pointer): number;
  /** schannel.dll!SslDeserializeCertificateStore */
  SslDeserializeCertificateStore(SerializedCertificateStore: Win32StructInit, ppCertContext: Win32Pointer): number;
  /** schannel.dll!SslEmptyCacheA */
  SslEmptyCacheA(pszTargetName: string | Win32Pointer, dwFlags: number): number;
  /** schannel.dll!SslEmptyCacheW */
  SslEmptyCacheW(pszTargetName: string | Win32Pointer, dwFlags: number): number;
  /** schannel.dll!SslEmptyCacheW */
  SslEmptyCache(pszTargetName: string | Win32Pointer, dwFlags: number): number;
  /** schannel.dll!SslFreeCertificate */
  SslFreeCertificate(pCertificate: Win32Pointer): void;
  /** schannel.dll!SslGenerateRandomBits */
  SslGenerateRandomBits(pRandomData: Win32Pointer, cRandomData: number): void;
  /** schannel.dll!SslGetExtensions */
  SslGetExtensions(clientHello: Win32Pointer, clientHelloByteSize: number, genericExtensions: Win32Pointer, genericExtensionsCount: number, bytesToRead: Win32Pointer, flags: number): number;
  /** schannel.dll!SslGetMaximumKeySize */
  SslGetMaximumKeySize(Reserved: number): number;
  /** schannel.dll!SslGetServerIdentity */
  SslGetServerIdentity(ClientHello: Win32Pointer, ClientHelloSize: number, ServerIdentity: Win32Pointer, ServerIdentitySize: Win32Pointer, Flags: number): number;
}

declare const family: Win32Family & Functions;
export = family;
