// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** windows.media.mediacontrol.dll!CreateCaptureAudioStateMonitor */
  CreateCaptureAudioStateMonitor(audioStateMonitor: Win32Pointer): number;
  /** windows.media.mediacontrol.dll!CreateCaptureAudioStateMonitorForCategory */
  CreateCaptureAudioStateMonitorForCategory(category: number, audioStateMonitor: Win32Pointer): number;
  /** windows.media.mediacontrol.dll!CreateCaptureAudioStateMonitorForCategoryAndDeviceId */
  CreateCaptureAudioStateMonitorForCategoryAndDeviceId(category: number, deviceId: string | Win32Pointer, audioStateMonitor: Win32Pointer): number;
  /** windows.media.mediacontrol.dll!CreateCaptureAudioStateMonitorForCategoryAndDeviceRole */
  CreateCaptureAudioStateMonitorForCategoryAndDeviceRole(category: number, role: number, audioStateMonitor: Win32Pointer): number;
  /** windows.media.mediacontrol.dll!CreateRenderAudioStateMonitor */
  CreateRenderAudioStateMonitor(audioStateMonitor: Win32Pointer): number;
  /** windows.media.mediacontrol.dll!CreateRenderAudioStateMonitorForCategory */
  CreateRenderAudioStateMonitorForCategory(category: number, audioStateMonitor: Win32Pointer): number;
  /** windows.media.mediacontrol.dll!CreateRenderAudioStateMonitorForCategoryAndDeviceId */
  CreateRenderAudioStateMonitorForCategoryAndDeviceId(category: number, deviceId: string | Win32Pointer, audioStateMonitor: Win32Pointer): number;
  /** windows.media.mediacontrol.dll!CreateRenderAudioStateMonitorForCategoryAndDeviceRole */
  CreateRenderAudioStateMonitorForCategoryAndDeviceRole(category: number, role: number, audioStateMonitor: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
