// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** icuin.dll!u_formatMessage */
  u_formatMessage(locale: string | Win32Pointer, pattern: Win32Pointer, patternLength: number, result: Win32Pointer, resultLength: number, status: Win32Pointer): number;
  /** icuin.dll!u_formatMessageWithError */
  u_formatMessageWithError(locale: string | Win32Pointer, pattern: Win32Pointer, patternLength: number, result: Win32Pointer, resultLength: number, parseError: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!u_parseMessage */
  u_parseMessage(locale: string | Win32Pointer, pattern: Win32Pointer, patternLength: number, source: Win32Pointer, sourceLength: number, status: Win32Pointer): void;
  /** icuin.dll!u_parseMessageWithError */
  u_parseMessageWithError(locale: string | Win32Pointer, pattern: Win32Pointer, patternLength: number, source: Win32Pointer, sourceLength: number, parseError: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!u_vformatMessage */
  u_vformatMessage(locale: string | Win32Pointer, pattern: Win32Pointer, patternLength: number, result: Win32Pointer, resultLength: number, ap: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!u_vformatMessageWithError */
  u_vformatMessageWithError(locale: string | Win32Pointer, pattern: Win32Pointer, patternLength: number, result: Win32Pointer, resultLength: number, parseError: Win32Pointer, ap: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!u_vparseMessage */
  u_vparseMessage(locale: string | Win32Pointer, pattern: Win32Pointer, patternLength: number, source: Win32Pointer, sourceLength: number, ap: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!u_vparseMessageWithError */
  u_vparseMessageWithError(locale: string | Win32Pointer, pattern: Win32Pointer, patternLength: number, source: Win32Pointer, sourceLength: number, ap: Win32Pointer, parseError: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!ucal_add */
  ucal_add(cal: Win32Pointer, field: number, amount: number, status: Win32Pointer): void;
  /** icuin.dll!ucal_clear */
  ucal_clear(calendar: Win32Pointer): void;
  /** icuin.dll!ucal_clearField */
  ucal_clearField(cal: Win32Pointer, field: number): void;
  /** icuin.dll!ucal_clone */
  ucal_clone(cal: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ucal_close */
  ucal_close(cal: Win32Pointer): void;
  /** icuin.dll!ucal_countAvailable */
  ucal_countAvailable(): number;
  /** icuin.dll!ucal_equivalentTo */
  ucal_equivalentTo(cal1: Win32Pointer, cal2: Win32Pointer): number;
  /** icuin.dll!ucal_get */
  ucal_get(cal: Win32Pointer, field: number, status: Win32Pointer): number;
  /** icuin.dll!ucal_getAttribute */
  ucal_getAttribute(cal: Win32Pointer, attr: number): number;
  /** icuin.dll!ucal_getAvailable */
  ucal_getAvailable(localeIndex: number): number | null;
  /** icuin.dll!ucal_getCanonicalTimeZoneID */
  ucal_getCanonicalTimeZoneID(id: Win32Pointer, len: number, result: Win32Pointer, resultCapacity: number, isSystemID: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!ucal_getDSTSavings */
  ucal_getDSTSavings(zoneID: Win32Pointer, ec: Win32Pointer): number;
  /** icuin.dll!ucal_getDayOfWeekType */
  ucal_getDayOfWeekType(cal: Win32Pointer, dayOfWeek: number, status: Win32Pointer): number;
  /** icuin.dll!ucal_getDefaultTimeZone */
  ucal_getDefaultTimeZone(result: Win32Pointer, resultCapacity: number, ec: Win32Pointer): number;
  /** icuin.dll!ucal_getFieldDifference */
  ucal_getFieldDifference(cal: Win32Pointer, target: number, field: number, status: Win32Pointer): number;
  /** icuin.dll!ucal_getGregorianChange */
  ucal_getGregorianChange(cal: Win32Pointer, pErrorCode: Win32Pointer): number;
  /** icuin.dll!ucal_getKeywordValuesForLocale */
  ucal_getKeywordValuesForLocale(key: string | Win32Pointer, locale: string | Win32Pointer, commonlyUsed: number, status: Win32Pointer): number | null;
  /** icuin.dll!ucal_getLimit */
  ucal_getLimit(cal: Win32Pointer, field: number, type: number, status: Win32Pointer): number;
  /** icuin.dll!ucal_getLocaleByType */
  ucal_getLocaleByType(cal: Win32Pointer, type: number, status: Win32Pointer): number | null;
  /** icuin.dll!ucal_getMillis */
  ucal_getMillis(cal: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!ucal_getNow */
  ucal_getNow(): number;
  /** icuin.dll!ucal_getTZDataVersion */
  ucal_getTZDataVersion(status: Win32Pointer): number | null;
  /** icuin.dll!ucal_getTimeZoneDisplayName */
  ucal_getTimeZoneDisplayName(cal: Win32Pointer, type: number, locale: string | Win32Pointer, result: Win32Pointer, resultLength: number, status: Win32Pointer): number;
  /** icuin.dll!ucal_getTimeZoneID */
  ucal_getTimeZoneID(cal: Win32Pointer, result: Win32Pointer, resultLength: number, status: Win32Pointer): number;
  /** icuin.dll!ucal_getTimeZoneIDForWindowsID */
  ucal_getTimeZoneIDForWindowsID(winid: Win32Pointer, len: number, region: string | Win32Pointer, id: Win32Pointer, idCapacity: number, status: Win32Pointer): number;
  /** icuin.dll!ucal_getTimeZoneTransitionDate */
  ucal_getTimeZoneTransitionDate(cal: Win32Pointer, type: number, transition: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!ucal_getType */
  ucal_getType(cal: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ucal_getWeekendTransition */
  ucal_getWeekendTransition(cal: Win32Pointer, dayOfWeek: number, status: Win32Pointer): number;
  /** icuin.dll!ucal_getWindowsTimeZoneID */
  ucal_getWindowsTimeZoneID(id: Win32Pointer, len: number, winid: Win32Pointer, winidCapacity: number, status: Win32Pointer): number;
  /** icuin.dll!ucal_inDaylightTime */
  ucal_inDaylightTime(cal: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!ucal_isSet */
  ucal_isSet(cal: Win32Pointer, field: number): number;
  /** icuin.dll!ucal_isWeekend */
  ucal_isWeekend(cal: Win32Pointer, date: number, status: Win32Pointer): number;
  /** icuin.dll!ucal_open */
  ucal_open(zoneID: Win32Pointer, len: number, locale: string | Win32Pointer, type: number, status: Win32Pointer): number | null;
  /** icuin.dll!ucal_openCountryTimeZones */
  ucal_openCountryTimeZones(country: string | Win32Pointer, ec: Win32Pointer): number | null;
  /** icuin.dll!ucal_openTimeZoneIDEnumeration */
  ucal_openTimeZoneIDEnumeration(zoneType: number, region: string | Win32Pointer, rawOffset: Win32Pointer, ec: Win32Pointer): number | null;
  /** icuin.dll!ucal_openTimeZones */
  ucal_openTimeZones(ec: Win32Pointer): number | null;
  /** icuin.dll!ucal_roll */
  ucal_roll(cal: Win32Pointer, field: number, amount: number, status: Win32Pointer): void;
  /** icuin.dll!ucal_set */
  ucal_set(cal: Win32Pointer, field: number, value: number): void;
  /** icuin.dll!ucal_setAttribute */
  ucal_setAttribute(cal: Win32Pointer, attr: number, newValue: number): void;
  /** icuin.dll!ucal_setDate */
  ucal_setDate(cal: Win32Pointer, year: number, month: number, date: number, status: Win32Pointer): void;
  /** icuin.dll!ucal_setDateTime */
  ucal_setDateTime(cal: Win32Pointer, year: number, month: number, date: number, hour: number, minute: number, second: number, status: Win32Pointer): void;
  /** icuin.dll!ucal_setDefaultTimeZone */
  ucal_setDefaultTimeZone(zoneID: Win32Pointer, ec: Win32Pointer): void;
  /** icuin.dll!ucal_setGregorianChange */
  ucal_setGregorianChange(cal: Win32Pointer, date: number, pErrorCode: Win32Pointer): void;
  /** icuin.dll!ucal_setMillis */
  ucal_setMillis(cal: Win32Pointer, dateTime: number, status: Win32Pointer): void;
  /** icuin.dll!ucal_setTimeZone */
  ucal_setTimeZone(cal: Win32Pointer, zoneID: Win32Pointer, len: number, status: Win32Pointer): void;
  /** icuin.dll!ucol_cloneBinary */
  ucol_cloneBinary(coll: Win32Pointer, buffer: Win32Pointer, capacity: number, status: Win32Pointer): number;
  /** icuin.dll!ucol_close */
  ucol_close(coll: Win32Pointer): void;
  /** icuin.dll!ucol_closeElements */
  ucol_closeElements(elems: Win32Pointer): void;
  /** icuin.dll!ucol_countAvailable */
  ucol_countAvailable(): number;
  /** icuin.dll!ucol_equal */
  ucol_equal(coll: Win32Pointer, source: Win32Pointer, sourceLength: number, target: Win32Pointer, targetLength: number): number;
  /** icuin.dll!ucol_getAttribute */
  ucol_getAttribute(coll: Win32Pointer, attr: number, status: Win32Pointer): number;
  /** icuin.dll!ucol_getAvailable */
  ucol_getAvailable(localeIndex: number): number | null;
  /** icuin.dll!ucol_getBound */
  ucol_getBound(source: Win32Pointer, sourceLength: number, boundType: number, noOfLevels: number, result: Win32Pointer, resultLength: number, status: Win32Pointer): number;
  /** icuin.dll!ucol_getContractionsAndExpansions */
  ucol_getContractionsAndExpansions(coll: Win32Pointer, contractions: Win32Pointer, expansions: Win32Pointer, addPrefixes: number, status: Win32Pointer): void;
  /** icuin.dll!ucol_getDisplayName */
  ucol_getDisplayName(objLoc: string | Win32Pointer, dispLoc: string | Win32Pointer, result: Win32Pointer, resultLength: number, status: Win32Pointer): number;
  /** icuin.dll!ucol_getEquivalentReorderCodes */
  ucol_getEquivalentReorderCodes(reorderCode: number, dest: Win32Pointer, destCapacity: number, pErrorCode: Win32Pointer): number;
  /** icuin.dll!ucol_getFunctionalEquivalent */
  ucol_getFunctionalEquivalent(result: string | Win32Pointer, resultCapacity: number, keyword: string | Win32Pointer, locale: string | Win32Pointer, isAvailable: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!ucol_getKeywordValues */
  ucol_getKeywordValues(keyword: string | Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ucol_getKeywordValuesForLocale */
  ucol_getKeywordValuesForLocale(key: string | Win32Pointer, locale: string | Win32Pointer, commonlyUsed: number, status: Win32Pointer): number | null;
  /** icuin.dll!ucol_getKeywords */
  ucol_getKeywords(status: Win32Pointer): number | null;
  /** icuin.dll!ucol_getLocaleByType */
  ucol_getLocaleByType(coll: Win32Pointer, type: number, status: Win32Pointer): number | null;
  /** icuin.dll!ucol_getMaxExpansion */
  ucol_getMaxExpansion(elems: Win32Pointer, order: number): number;
  /** icuin.dll!ucol_getMaxVariable */
  ucol_getMaxVariable(coll: Win32Pointer): number;
  /** icuin.dll!ucol_getOffset */
  ucol_getOffset(elems: Win32Pointer): number;
  /** icuin.dll!ucol_getReorderCodes */
  ucol_getReorderCodes(coll: Win32Pointer, dest: Win32Pointer, destCapacity: number, pErrorCode: Win32Pointer): number;
  /** icuin.dll!ucol_getRules */
  ucol_getRules(coll: Win32Pointer, length: Win32Pointer): number | null;
  /** icuin.dll!ucol_getRulesEx */
  ucol_getRulesEx(coll: Win32Pointer, delta: number, buffer: Win32Pointer, bufferLen: number): number;
  /** icuin.dll!ucol_getSortKey */
  ucol_getSortKey(coll: Win32Pointer, source: Win32Pointer, sourceLength: number, result: Win32Pointer, resultLength: number): number;
  /** icuin.dll!ucol_getStrength */
  ucol_getStrength(coll: Win32Pointer): number;
  /** icuin.dll!ucol_getTailoredSet */
  ucol_getTailoredSet(coll: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ucol_getUCAVersion */
  ucol_getUCAVersion(coll: Win32Pointer, info: Win32Pointer): void;
  /** icuin.dll!ucol_getVariableTop */
  ucol_getVariableTop(coll: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!ucol_getVersion */
  ucol_getVersion(coll: Win32Pointer, info: Win32Pointer): void;
  /** icuin.dll!ucol_greater */
  ucol_greater(coll: Win32Pointer, source: Win32Pointer, sourceLength: number, target: Win32Pointer, targetLength: number): number;
  /** icuin.dll!ucol_greaterOrEqual */
  ucol_greaterOrEqual(coll: Win32Pointer, source: Win32Pointer, sourceLength: number, target: Win32Pointer, targetLength: number): number;
  /** icuin.dll!ucol_keyHashCode */
  ucol_keyHashCode(key: Win32Pointer, length: number): number;
  /** icuin.dll!ucol_mergeSortkeys */
  ucol_mergeSortkeys(src1: Win32Pointer, src1Length: number, src2: Win32Pointer, src2Length: number, dest: Win32Pointer, destCapacity: number): number;
  /** icuin.dll!ucol_next */
  ucol_next(elems: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!ucol_nextSortKeyPart */
  ucol_nextSortKeyPart(coll: Win32Pointer, iter: Win32Pointer, state: Win32Pointer, dest: Win32Pointer, count: number, status: Win32Pointer): number;
  /** icuin.dll!ucol_open */
  ucol_open(loc: string | Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ucol_openAvailableLocales */
  ucol_openAvailableLocales(status: Win32Pointer): number | null;
  /** icuin.dll!ucol_openBinary */
  ucol_openBinary(bin: Win32Pointer, length: number, base: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ucol_openElements */
  ucol_openElements(coll: Win32Pointer, text: Win32Pointer, textLength: number, status: Win32Pointer): number | null;
  /** icuin.dll!ucol_openRules */
  ucol_openRules(rules: Win32Pointer, rulesLength: number, normalizationMode: number, strength: number, parseError: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ucol_previous */
  ucol_previous(elems: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!ucol_primaryOrder */
  ucol_primaryOrder(order: number): number;
  /** icuin.dll!ucol_reset */
  ucol_reset(elems: Win32Pointer): void;
  /** icuin.dll!ucol_safeClone */
  ucol_safeClone(coll: Win32Pointer, stackBuffer: Win32Pointer, pBufferSize: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ucol_secondaryOrder */
  ucol_secondaryOrder(order: number): number;
  /** icuin.dll!ucol_setAttribute */
  ucol_setAttribute(coll: Win32Pointer, attr: number, value: number, status: Win32Pointer): void;
  /** icuin.dll!ucol_setMaxVariable */
  ucol_setMaxVariable(coll: Win32Pointer, group: number, pErrorCode: Win32Pointer): void;
  /** icuin.dll!ucol_setOffset */
  ucol_setOffset(elems: Win32Pointer, offset: number, status: Win32Pointer): void;
  /** icuin.dll!ucol_setReorderCodes */
  ucol_setReorderCodes(coll: Win32Pointer, reorderCodes: Win32Pointer, reorderCodesLength: number, pErrorCode: Win32Pointer): void;
  /** icuin.dll!ucol_setStrength */
  ucol_setStrength(coll: Win32Pointer, strength: number): void;
  /** icuin.dll!ucol_setText */
  ucol_setText(elems: Win32Pointer, text: Win32Pointer, textLength: number, status: Win32Pointer): void;
  /** icuin.dll!ucol_strcoll */
  ucol_strcoll(coll: Win32Pointer, source: Win32Pointer, sourceLength: number, target: Win32Pointer, targetLength: number): number;
  /** icuin.dll!ucol_strcollIter */
  ucol_strcollIter(coll: Win32Pointer, sIter: Win32Pointer, tIter: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!ucol_strcollUTF8 */
  ucol_strcollUTF8(coll: Win32Pointer, source: string | Win32Pointer, sourceLength: number, target: string | Win32Pointer, targetLength: number, status: Win32Pointer): number;
  /** icuin.dll!ucol_tertiaryOrder */
  ucol_tertiaryOrder(order: number): number;
  /** icuin.dll!ucsdet_close */
  ucsdet_close(ucsd: Win32Pointer): void;
  /** icuin.dll!ucsdet_detect */
  ucsdet_detect(ucsd: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ucsdet_detectAll */
  ucsdet_detectAll(ucsd: Win32Pointer, matchesFound: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ucsdet_enableInputFilter */
  ucsdet_enableInputFilter(ucsd: Win32Pointer, filter: number): number;
  /** icuin.dll!ucsdet_getAllDetectableCharsets */
  ucsdet_getAllDetectableCharsets(ucsd: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ucsdet_getConfidence */
  ucsdet_getConfidence(ucsm: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!ucsdet_getLanguage */
  ucsdet_getLanguage(ucsm: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ucsdet_getName */
  ucsdet_getName(ucsm: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ucsdet_getUChars */
  ucsdet_getUChars(ucsm: Win32Pointer, buf: Win32Pointer, cap: number, status: Win32Pointer): number;
  /** icuin.dll!ucsdet_isInputFilterEnabled */
  ucsdet_isInputFilterEnabled(ucsd: Win32Pointer): number;
  /** icuin.dll!ucsdet_open */
  ucsdet_open(status: Win32Pointer): number | null;
  /** icuin.dll!ucsdet_setDeclaredEncoding */
  ucsdet_setDeclaredEncoding(ucsd: Win32Pointer, encoding: string | Win32Pointer, length: number, status: Win32Pointer): void;
  /** icuin.dll!ucsdet_setText */
  ucsdet_setText(ucsd: Win32Pointer, textIn: string | Win32Pointer, len: number, status: Win32Pointer): void;
  /** icuin.dll!udat_adoptNumberFormat */
  udat_adoptNumberFormat(fmt: Win32Pointer, numberFormatToAdopt: Win32Pointer): void;
  /** icuin.dll!udat_adoptNumberFormatForFields */
  udat_adoptNumberFormatForFields(fmt: Win32Pointer, fields: Win32Pointer, numberFormatToSet: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!udat_applyPattern */
  udat_applyPattern(format: Win32Pointer, localized: number, pattern: Win32Pointer, patternLength: number): void;
  /** icuin.dll!udat_clone */
  udat_clone(fmt: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!udat_close */
  udat_close(format: Win32Pointer): void;
  /** icuin.dll!udat_countAvailable */
  udat_countAvailable(): number;
  /** icuin.dll!udat_countSymbols */
  udat_countSymbols(fmt: Win32Pointer, type: number): number;
  /** icuin.dll!udat_format */
  udat_format(format: Win32Pointer, dateToFormat: number, result: Win32Pointer, resultLength: number, position: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!udat_formatCalendar */
  udat_formatCalendar(format: Win32Pointer, calendar: Win32Pointer, result: Win32Pointer, capacity: number, position: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!udat_formatCalendarForFields */
  udat_formatCalendarForFields(format: Win32Pointer, calendar: Win32Pointer, result: Win32Pointer, capacity: number, fpositer: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!udat_formatForFields */
  udat_formatForFields(format: Win32Pointer, dateToFormat: number, result: Win32Pointer, resultLength: number, fpositer: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!udat_get2DigitYearStart */
  udat_get2DigitYearStart(fmt: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!udat_getAvailable */
  udat_getAvailable(localeIndex: number): number | null;
  /** icuin.dll!udat_getBooleanAttribute */
  udat_getBooleanAttribute(fmt: Win32Pointer, attr: number, status: Win32Pointer): number;
  /** icuin.dll!udat_getCalendar */
  udat_getCalendar(fmt: Win32Pointer): number | null;
  /** icuin.dll!udat_getContext */
  udat_getContext(fmt: Win32Pointer, type: number, status: Win32Pointer): number;
  /** icuin.dll!udat_getLocaleByType */
  udat_getLocaleByType(fmt: Win32Pointer, type: number, status: Win32Pointer): number | null;
  /** icuin.dll!udat_getNumberFormat */
  udat_getNumberFormat(fmt: Win32Pointer): number | null;
  /** icuin.dll!udat_getNumberFormatForField */
  udat_getNumberFormatForField(fmt: Win32Pointer, field: number): number | null;
  /** icuin.dll!udat_getSymbols */
  udat_getSymbols(fmt: Win32Pointer, type: number, symbolIndex: number, result: Win32Pointer, resultLength: number, status: Win32Pointer): number;
  /** icuin.dll!udat_isLenient */
  udat_isLenient(fmt: Win32Pointer): number;
  /** icuin.dll!udat_open */
  udat_open(timeStyle: number, dateStyle: number, locale: string | Win32Pointer, tzID: Win32Pointer, tzIDLength: number, pattern: Win32Pointer, patternLength: number, status: Win32Pointer): number | null;
  /** icuin.dll!udat_parse */
  udat_parse(format: Win32Pointer, text: Win32Pointer, textLength: number, parsePos: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!udat_parseCalendar */
  udat_parseCalendar(format: Win32Pointer, calendar: Win32Pointer, text: Win32Pointer, textLength: number, parsePos: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!udat_set2DigitYearStart */
  udat_set2DigitYearStart(fmt: Win32Pointer, d: number, status: Win32Pointer): void;
  /** icuin.dll!udat_setBooleanAttribute */
  udat_setBooleanAttribute(fmt: Win32Pointer, attr: number, newValue: number, status: Win32Pointer): void;
  /** icuin.dll!udat_setCalendar */
  udat_setCalendar(fmt: Win32Pointer, calendarToSet: Win32Pointer): void;
  /** icuin.dll!udat_setContext */
  udat_setContext(fmt: Win32Pointer, value: number, status: Win32Pointer): void;
  /** icuin.dll!udat_setLenient */
  udat_setLenient(fmt: Win32Pointer, isLenient: number): void;
  /** icuin.dll!udat_setNumberFormat */
  udat_setNumberFormat(fmt: Win32Pointer, numberFormatToSet: Win32Pointer): void;
  /** icuin.dll!udat_setSymbols */
  udat_setSymbols(format: Win32Pointer, type: number, symbolIndex: number, value: Win32Pointer, valueLength: number, status: Win32Pointer): void;
  /** icuin.dll!udat_toCalendarDateField */
  udat_toCalendarDateField(field: number): number;
  /** icuin.dll!udat_toPattern */
  udat_toPattern(fmt: Win32Pointer, localized: number, result: Win32Pointer, resultLength: number, status: Win32Pointer): number;
  /** icuin.dll!udatpg_addPattern */
  udatpg_addPattern(dtpg: Win32Pointer, pattern: Win32Pointer, patternLength: number, override: number, conflictingPattern: Win32Pointer, capacity: number, pLength: Win32Pointer, pErrorCode: Win32Pointer): number;
  /** icuin.dll!udatpg_clone */
  udatpg_clone(dtpg: Win32Pointer, pErrorCode: Win32Pointer): number | null;
  /** icuin.dll!udatpg_close */
  udatpg_close(dtpg: Win32Pointer): void;
  /** icuin.dll!udatpg_getAppendItemFormat */
  udatpg_getAppendItemFormat(dtpg: Win32Pointer, field: number, pLength: Win32Pointer): number | null;
  /** icuin.dll!udatpg_getAppendItemName */
  udatpg_getAppendItemName(dtpg: Win32Pointer, field: number, pLength: Win32Pointer): number | null;
  /** icuin.dll!udatpg_getBaseSkeleton */
  udatpg_getBaseSkeleton(unusedDtpg: Win32Pointer, pattern: Win32Pointer, length: number, baseSkeleton: Win32Pointer, capacity: number, pErrorCode: Win32Pointer): number;
  /** icuin.dll!udatpg_getBestPattern */
  udatpg_getBestPattern(dtpg: Win32Pointer, skeleton: Win32Pointer, length: number, bestPattern: Win32Pointer, capacity: number, pErrorCode: Win32Pointer): number;
  /** icuin.dll!udatpg_getBestPatternWithOptions */
  udatpg_getBestPatternWithOptions(dtpg: Win32Pointer, skeleton: Win32Pointer, length: number, options: number, bestPattern: Win32Pointer, capacity: number, pErrorCode: Win32Pointer): number;
  /** icuin.dll!udatpg_getDateTimeFormat */
  udatpg_getDateTimeFormat(dtpg: Win32Pointer, pLength: Win32Pointer): number | null;
  /** icuin.dll!udatpg_getDecimal */
  udatpg_getDecimal(dtpg: Win32Pointer, pLength: Win32Pointer): number | null;
  /** icuin.dll!udatpg_getPatternForSkeleton */
  udatpg_getPatternForSkeleton(dtpg: Win32Pointer, skeleton: Win32Pointer, skeletonLength: number, pLength: Win32Pointer): number | null;
  /** icuin.dll!udatpg_getSkeleton */
  udatpg_getSkeleton(unusedDtpg: Win32Pointer, pattern: Win32Pointer, length: number, skeleton: Win32Pointer, capacity: number, pErrorCode: Win32Pointer): number;
  /** icuin.dll!udatpg_open */
  udatpg_open(locale: string | Win32Pointer, pErrorCode: Win32Pointer): number | null;
  /** icuin.dll!udatpg_openBaseSkeletons */
  udatpg_openBaseSkeletons(dtpg: Win32Pointer, pErrorCode: Win32Pointer): number | null;
  /** icuin.dll!udatpg_openEmpty */
  udatpg_openEmpty(pErrorCode: Win32Pointer): number | null;
  /** icuin.dll!udatpg_openSkeletons */
  udatpg_openSkeletons(dtpg: Win32Pointer, pErrorCode: Win32Pointer): number | null;
  /** icuin.dll!udatpg_replaceFieldTypes */
  udatpg_replaceFieldTypes(dtpg: Win32Pointer, pattern: Win32Pointer, patternLength: number, skeleton: Win32Pointer, skeletonLength: number, dest: Win32Pointer, destCapacity: number, pErrorCode: Win32Pointer): number;
  /** icuin.dll!udatpg_replaceFieldTypesWithOptions */
  udatpg_replaceFieldTypesWithOptions(dtpg: Win32Pointer, pattern: Win32Pointer, patternLength: number, skeleton: Win32Pointer, skeletonLength: number, options: number, dest: Win32Pointer, destCapacity: number, pErrorCode: Win32Pointer): number;
  /** icuin.dll!udatpg_setAppendItemFormat */
  udatpg_setAppendItemFormat(dtpg: Win32Pointer, field: number, value: Win32Pointer, length: number): void;
  /** icuin.dll!udatpg_setAppendItemName */
  udatpg_setAppendItemName(dtpg: Win32Pointer, field: number, value: Win32Pointer, length: number): void;
  /** icuin.dll!udatpg_setDateTimeFormat */
  udatpg_setDateTimeFormat(dtpg: Win32Pointer, dtFormat: Win32Pointer, length: number): void;
  /** icuin.dll!udatpg_setDecimal */
  udatpg_setDecimal(dtpg: Win32Pointer, decimal: Win32Pointer, length: number): void;
  /** icuin.dll!udtitvfmt_close */
  udtitvfmt_close(formatter: Win32Pointer): void;
  /** icuin.dll!udtitvfmt_format */
  udtitvfmt_format(formatter: Win32Pointer, fromDate: number, toDate: number, result: Win32Pointer, resultCapacity: number, position: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!udtitvfmt_open */
  udtitvfmt_open(locale: string | Win32Pointer, skeleton: Win32Pointer, skeletonLength: number, tzID: Win32Pointer, tzIDLength: number, status: Win32Pointer): number | null;
  /** icuin.dll!ufieldpositer_close */
  ufieldpositer_close(fpositer: Win32Pointer): void;
  /** icuin.dll!ufieldpositer_next */
  ufieldpositer_next(fpositer: Win32Pointer, beginIndex: Win32Pointer, endIndex: Win32Pointer): number;
  /** icuin.dll!ufieldpositer_open */
  ufieldpositer_open(status: Win32Pointer): number | null;
  /** icuin.dll!ufmt_close */
  ufmt_close(fmt: Win32Pointer): void;
  /** icuin.dll!ufmt_getArrayItemByIndex */
  ufmt_getArrayItemByIndex(fmt: Win32Pointer, n: number, status: Win32Pointer): number | null;
  /** icuin.dll!ufmt_getArrayLength */
  ufmt_getArrayLength(fmt: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!ufmt_getDate */
  ufmt_getDate(fmt: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!ufmt_getDecNumChars */
  ufmt_getDecNumChars(fmt: Win32Pointer, len: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ufmt_getDouble */
  ufmt_getDouble(fmt: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!ufmt_getInt64 */
  ufmt_getInt64(fmt: Win32Pointer, status: Win32Pointer): bigint;
  /** icuin.dll!ufmt_getLong */
  ufmt_getLong(fmt: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!ufmt_getObject */
  ufmt_getObject(fmt: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ufmt_getType */
  ufmt_getType(fmt: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!ufmt_getUChars */
  ufmt_getUChars(fmt: Win32Pointer, len: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ufmt_isNumeric */
  ufmt_isNumeric(fmt: Win32Pointer): number;
  /** icuin.dll!ufmt_open */
  ufmt_open(status: Win32Pointer): number | null;
  /** icuin.dll!ugender_getInstance */
  ugender_getInstance(locale: string | Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ugender_getListGender */
  ugender_getListGender(genderInfo: Win32Pointer, genders: Win32Pointer, size: number, status: Win32Pointer): number;
  /** icuin.dll!ulocdata_close */
  ulocdata_close(uld: Win32Pointer): void;
  /** icuin.dll!ulocdata_getCLDRVersion */
  ulocdata_getCLDRVersion(versionArray: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!ulocdata_getDelimiter */
  ulocdata_getDelimiter(uld: Win32Pointer, type: number, result: Win32Pointer, resultLength: number, status: Win32Pointer): number;
  /** icuin.dll!ulocdata_getExemplarSet */
  ulocdata_getExemplarSet(uld: Win32Pointer, fillIn: Win32Pointer, options: number, extype: number, status: Win32Pointer): number | null;
  /** icuin.dll!ulocdata_getLocaleDisplayPattern */
  ulocdata_getLocaleDisplayPattern(uld: Win32Pointer, pattern: Win32Pointer, patternCapacity: number, status: Win32Pointer): number;
  /** icuin.dll!ulocdata_getLocaleSeparator */
  ulocdata_getLocaleSeparator(uld: Win32Pointer, separator: Win32Pointer, separatorCapacity: number, status: Win32Pointer): number;
  /** icuin.dll!ulocdata_getMeasurementSystem */
  ulocdata_getMeasurementSystem(localeID: string | Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!ulocdata_getNoSubstitute */
  ulocdata_getNoSubstitute(uld: Win32Pointer): number;
  /** icuin.dll!ulocdata_getPaperSize */
  ulocdata_getPaperSize(localeID: string | Win32Pointer, height: Win32Pointer, width: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!ulocdata_open */
  ulocdata_open(localeID: string | Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!ulocdata_setNoSubstitute */
  ulocdata_setNoSubstitute(uld: Win32Pointer, setting: number): void;
  /** icuin.dll!umsg_applyPattern */
  umsg_applyPattern(fmt: Win32Pointer, pattern: Win32Pointer, patternLength: number, parseError: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!umsg_autoQuoteApostrophe */
  umsg_autoQuoteApostrophe(pattern: Win32Pointer, patternLength: number, dest: Win32Pointer, destCapacity: number, ec: Win32Pointer): number;
  /** icuin.dll!umsg_clone */
  umsg_clone(fmt: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!umsg_close */
  umsg_close(format: Win32Pointer): void;
  /** icuin.dll!umsg_format */
  umsg_format(fmt: Win32Pointer, result: Win32Pointer, resultLength: number, status: Win32Pointer): number;
  /** icuin.dll!umsg_getLocale */
  umsg_getLocale(fmt: Win32Pointer): number | null;
  /** icuin.dll!umsg_open */
  umsg_open(pattern: Win32Pointer, patternLength: number, locale: string | Win32Pointer, parseError: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!umsg_parse */
  umsg_parse(fmt: Win32Pointer, source: Win32Pointer, sourceLength: number, count: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!umsg_setLocale */
  umsg_setLocale(fmt: Win32Pointer, locale: string | Win32Pointer): void;
  /** icuin.dll!umsg_toPattern */
  umsg_toPattern(fmt: Win32Pointer, result: Win32Pointer, resultLength: number, status: Win32Pointer): number;
  /** icuin.dll!umsg_vformat */
  umsg_vformat(fmt: Win32Pointer, result: Win32Pointer, resultLength: number, ap: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!umsg_vparse */
  umsg_vparse(fmt: Win32Pointer, source: Win32Pointer, sourceLength: number, count: Win32Pointer, ap: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!unum_applyPattern */
  unum_applyPattern(format: Win32Pointer, localized: number, pattern: Win32Pointer, patternLength: number, parseError: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!unum_clone */
  unum_clone(fmt: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!unum_close */
  unum_close(fmt: Win32Pointer): void;
  /** icuin.dll!unum_countAvailable */
  unum_countAvailable(): number;
  /** icuin.dll!unum_format */
  unum_format(fmt: Win32Pointer, number: number, result: Win32Pointer, resultLength: number, pos: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!unum_formatDecimal */
  unum_formatDecimal(fmt: Win32Pointer, number: string | Win32Pointer, length: number, result: Win32Pointer, resultLength: number, pos: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!unum_formatDouble */
  unum_formatDouble(fmt: Win32Pointer, number: number, result: Win32Pointer, resultLength: number, pos: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!unum_formatDoubleCurrency */
  unum_formatDoubleCurrency(fmt: Win32Pointer, number: number, currency: Win32Pointer, result: Win32Pointer, resultLength: number, pos: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!unum_formatDoubleForFields */
  unum_formatDoubleForFields(format: Win32Pointer, number: number, result: Win32Pointer, resultLength: number, fpositer: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!unum_formatInt64 */
  unum_formatInt64(fmt: Win32Pointer, number: number | bigint, result: Win32Pointer, resultLength: number, pos: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!unum_formatUFormattable */
  unum_formatUFormattable(fmt: Win32Pointer, number: Win32Pointer, result: Win32Pointer, resultLength: number, pos: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!unum_getAttribute */
  unum_getAttribute(fmt: Win32Pointer, attr: number): number;
  /** icuin.dll!unum_getAvailable */
  unum_getAvailable(localeIndex: number): number | null;
  /** icuin.dll!unum_getContext */
  unum_getContext(fmt: Win32Pointer, type: number, status: Win32Pointer): number;
  /** icuin.dll!unum_getDoubleAttribute */
  unum_getDoubleAttribute(fmt: Win32Pointer, attr: number): number;
  /** icuin.dll!unum_getLocaleByType */
  unum_getLocaleByType(fmt: Win32Pointer, type: number, status: Win32Pointer): number | null;
  /** icuin.dll!unum_getSymbol */
  unum_getSymbol(fmt: Win32Pointer, symbol: number, buffer: Win32Pointer, size: number, status: Win32Pointer): number;
  /** icuin.dll!unum_getTextAttribute */
  unum_getTextAttribute(fmt: Win32Pointer, tag: number, result: Win32Pointer, resultLength: number, status: Win32Pointer): number;
  /** icuin.dll!unum_open */
  unum_open(style: number, pattern: Win32Pointer, patternLength: number, locale: string | Win32Pointer, parseErr: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!unum_parse */
  unum_parse(fmt: Win32Pointer, text: Win32Pointer, textLength: number, parsePos: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!unum_parseDecimal */
  unum_parseDecimal(fmt: Win32Pointer, text: Win32Pointer, textLength: number, parsePos: Win32Pointer, outBuf: string | Win32Pointer, outBufLength: number, status: Win32Pointer): number;
  /** icuin.dll!unum_parseDouble */
  unum_parseDouble(fmt: Win32Pointer, text: Win32Pointer, textLength: number, parsePos: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!unum_parseDoubleCurrency */
  unum_parseDoubleCurrency(fmt: Win32Pointer, text: Win32Pointer, textLength: number, parsePos: Win32Pointer, currency: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!unum_parseInt64 */
  unum_parseInt64(fmt: Win32Pointer, text: Win32Pointer, textLength: number, parsePos: Win32Pointer, status: Win32Pointer): bigint;
  /** icuin.dll!unum_parseToUFormattable */
  unum_parseToUFormattable(fmt: Win32Pointer, result: Win32Pointer, text: Win32Pointer, textLength: number, parsePos: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!unum_setAttribute */
  unum_setAttribute(fmt: Win32Pointer, attr: number, newValue: number): void;
  /** icuin.dll!unum_setContext */
  unum_setContext(fmt: Win32Pointer, value: number, status: Win32Pointer): void;
  /** icuin.dll!unum_setDoubleAttribute */
  unum_setDoubleAttribute(fmt: Win32Pointer, attr: number, newValue: number): void;
  /** icuin.dll!unum_setSymbol */
  unum_setSymbol(fmt: Win32Pointer, symbol: number, value: Win32Pointer, length: number, status: Win32Pointer): void;
  /** icuin.dll!unum_setTextAttribute */
  unum_setTextAttribute(fmt: Win32Pointer, tag: number, newValue: Win32Pointer, newValueLength: number, status: Win32Pointer): void;
  /** icuin.dll!unum_toPattern */
  unum_toPattern(fmt: Win32Pointer, isPatternLocalized: number, result: Win32Pointer, resultLength: number, status: Win32Pointer): number;
  /** icuin.dll!unumsys_close */
  unumsys_close(unumsys: Win32Pointer): void;
  /** icuin.dll!unumsys_getDescription */
  unumsys_getDescription(unumsys: Win32Pointer, result: Win32Pointer, resultLength: number, status: Win32Pointer): number;
  /** icuin.dll!unumsys_getName */
  unumsys_getName(unumsys: Win32Pointer): number | null;
  /** icuin.dll!unumsys_getRadix */
  unumsys_getRadix(unumsys: Win32Pointer): number;
  /** icuin.dll!unumsys_isAlgorithmic */
  unumsys_isAlgorithmic(unumsys: Win32Pointer): number;
  /** icuin.dll!unumsys_open */
  unumsys_open(locale: string | Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!unumsys_openAvailableNames */
  unumsys_openAvailableNames(status: Win32Pointer): number | null;
  /** icuin.dll!unumsys_openByName */
  unumsys_openByName(name: string | Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uplrules_close */
  uplrules_close(uplrules: Win32Pointer): void;
  /** icuin.dll!uplrules_getKeywords */
  uplrules_getKeywords(uplrules: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uplrules_open */
  uplrules_open(locale: string | Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uplrules_openForType */
  uplrules_openForType(locale: string | Win32Pointer, type: number, status: Win32Pointer): number | null;
  /** icuin.dll!uplrules_select */
  uplrules_select(uplrules: Win32Pointer, number: number, keyword: Win32Pointer, capacity: number, status: Win32Pointer): number;
  /** icuin.dll!uregex_appendReplacement */
  uregex_appendReplacement(regexp: Win32Pointer, replacementText: Win32Pointer, replacementLength: number, destBuf: Win32Pointer, destCapacity: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uregex_appendReplacementUText */
  uregex_appendReplacementUText(regexp: Win32Pointer, replacementText: Win32Pointer, dest: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!uregex_appendTail */
  uregex_appendTail(regexp: Win32Pointer, destBuf: Win32Pointer, destCapacity: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uregex_appendTailUText */
  uregex_appendTailUText(regexp: Win32Pointer, dest: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uregex_clone */
  uregex_clone(regexp: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uregex_close */
  uregex_close(regexp: Win32Pointer): void;
  /** icuin.dll!uregex_end */
  uregex_end(regexp: Win32Pointer, groupNum: number, status: Win32Pointer): number;
  /** icuin.dll!uregex_end64 */
  uregex_end64(regexp: Win32Pointer, groupNum: number, status: Win32Pointer): bigint;
  /** icuin.dll!uregex_find */
  uregex_find(regexp: Win32Pointer, startIndex: number, status: Win32Pointer): number;
  /** icuin.dll!uregex_find64 */
  uregex_find64(regexp: Win32Pointer, startIndex: number | bigint, status: Win32Pointer): number;
  /** icuin.dll!uregex_findNext */
  uregex_findNext(regexp: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uregex_flags */
  uregex_flags(regexp: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uregex_getFindProgressCallback */
  uregex_getFindProgressCallback(regexp: Win32Pointer, callback: Win32Pointer, context: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!uregex_getMatchCallback */
  uregex_getMatchCallback(regexp: Win32Pointer, callback: Win32Pointer, context: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!uregex_getStackLimit */
  uregex_getStackLimit(regexp: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uregex_getText */
  uregex_getText(regexp: Win32Pointer, textLength: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uregex_getTimeLimit */
  uregex_getTimeLimit(regexp: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uregex_getUText */
  uregex_getUText(regexp: Win32Pointer, dest: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uregex_group */
  uregex_group(regexp: Win32Pointer, groupNum: number, dest: Win32Pointer, destCapacity: number, status: Win32Pointer): number;
  /** icuin.dll!uregex_groupCount */
  uregex_groupCount(regexp: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uregex_groupNumberFromCName */
  uregex_groupNumberFromCName(regexp: Win32Pointer, groupName: string | Win32Pointer, nameLength: number, status: Win32Pointer): number;
  /** icuin.dll!uregex_groupNumberFromName */
  uregex_groupNumberFromName(regexp: Win32Pointer, groupName: Win32Pointer, nameLength: number, status: Win32Pointer): number;
  /** icuin.dll!uregex_groupUText */
  uregex_groupUText(regexp: Win32Pointer, groupNum: number, dest: Win32Pointer, groupLength: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uregex_hasAnchoringBounds */
  uregex_hasAnchoringBounds(regexp: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uregex_hasTransparentBounds */
  uregex_hasTransparentBounds(regexp: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uregex_hitEnd */
  uregex_hitEnd(regexp: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uregex_lookingAt */
  uregex_lookingAt(regexp: Win32Pointer, startIndex: number, status: Win32Pointer): number;
  /** icuin.dll!uregex_lookingAt64 */
  uregex_lookingAt64(regexp: Win32Pointer, startIndex: number | bigint, status: Win32Pointer): number;
  /** icuin.dll!uregex_matches */
  uregex_matches(regexp: Win32Pointer, startIndex: number, status: Win32Pointer): number;
  /** icuin.dll!uregex_matches64 */
  uregex_matches64(regexp: Win32Pointer, startIndex: number | bigint, status: Win32Pointer): number;
  /** icuin.dll!uregex_open */
  uregex_open(pattern: Win32Pointer, patternLength: number, flags: number, pe: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uregex_openC */
  uregex_openC(pattern: string | Win32Pointer, flags: number, pe: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uregex_openUText */
  uregex_openUText(pattern: Win32Pointer, flags: number, pe: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uregex_pattern */
  uregex_pattern(regexp: Win32Pointer, patLength: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uregex_patternUText */
  uregex_patternUText(regexp: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uregex_refreshUText */
  uregex_refreshUText(regexp: Win32Pointer, text: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!uregex_regionEnd */
  uregex_regionEnd(regexp: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uregex_regionEnd64 */
  uregex_regionEnd64(regexp: Win32Pointer, status: Win32Pointer): bigint;
  /** icuin.dll!uregex_regionStart */
  uregex_regionStart(regexp: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uregex_regionStart64 */
  uregex_regionStart64(regexp: Win32Pointer, status: Win32Pointer): bigint;
  /** icuin.dll!uregex_replaceAll */
  uregex_replaceAll(regexp: Win32Pointer, replacementText: Win32Pointer, replacementLength: number, destBuf: Win32Pointer, destCapacity: number, status: Win32Pointer): number;
  /** icuin.dll!uregex_replaceAllUText */
  uregex_replaceAllUText(regexp: Win32Pointer, replacement: Win32Pointer, dest: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uregex_replaceFirst */
  uregex_replaceFirst(regexp: Win32Pointer, replacementText: Win32Pointer, replacementLength: number, destBuf: Win32Pointer, destCapacity: number, status: Win32Pointer): number;
  /** icuin.dll!uregex_replaceFirstUText */
  uregex_replaceFirstUText(regexp: Win32Pointer, replacement: Win32Pointer, dest: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uregex_requireEnd */
  uregex_requireEnd(regexp: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uregex_reset */
  uregex_reset(regexp: Win32Pointer, index: number, status: Win32Pointer): void;
  /** icuin.dll!uregex_reset64 */
  uregex_reset64(regexp: Win32Pointer, index: number | bigint, status: Win32Pointer): void;
  /** icuin.dll!uregex_setFindProgressCallback */
  uregex_setFindProgressCallback(regexp: Win32Pointer, callback: Win32Callback, context: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!uregex_setMatchCallback */
  uregex_setMatchCallback(regexp: Win32Pointer, callback: Win32Callback, context: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!uregex_setRegion */
  uregex_setRegion(regexp: Win32Pointer, regionStart: number, regionLimit: number, status: Win32Pointer): void;
  /** icuin.dll!uregex_setRegion64 */
  uregex_setRegion64(regexp: Win32Pointer, regionStart: number | bigint, regionLimit: number | bigint, status: Win32Pointer): void;
  /** icuin.dll!uregex_setRegionAndStart */
  uregex_setRegionAndStart(regexp: Win32Pointer, regionStart: number | bigint, regionLimit: number | bigint, startIndex: number | bigint, status: Win32Pointer): void;
  /** icuin.dll!uregex_setStackLimit */
  uregex_setStackLimit(regexp: Win32Pointer, limit: number, status: Win32Pointer): void;
  /** icuin.dll!uregex_setText */
  uregex_setText(regexp: Win32Pointer, text: Win32Pointer, textLength: number, status: Win32Pointer): void;
  /** icuin.dll!uregex_setTimeLimit */
  uregex_setTimeLimit(regexp: Win32Pointer, limit: number, status: Win32Pointer): void;
  /** icuin.dll!uregex_setUText */
  uregex_setUText(regexp: Win32Pointer, text: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!uregex_split */
  uregex_split(regexp: Win32Pointer, destBuf: Win32Pointer, destCapacity: number, requiredCapacity: Win32Pointer, destFields: Win32Pointer, destFieldsCapacity: number, status: Win32Pointer): number;
  /** icuin.dll!uregex_splitUText */
  uregex_splitUText(regexp: Win32Pointer, destFields: Win32Pointer, destFieldsCapacity: number, status: Win32Pointer): number;
  /** icuin.dll!uregex_start */
  uregex_start(regexp: Win32Pointer, groupNum: number, status: Win32Pointer): number;
  /** icuin.dll!uregex_start64 */
  uregex_start64(regexp: Win32Pointer, groupNum: number, status: Win32Pointer): bigint;
  /** icuin.dll!uregex_useAnchoringBounds */
  uregex_useAnchoringBounds(regexp: Win32Pointer, b: number, status: Win32Pointer): void;
  /** icuin.dll!uregex_useTransparentBounds */
  uregex_useTransparentBounds(regexp: Win32Pointer, b: number, status: Win32Pointer): void;
  /** icuin.dll!uregion_areEqual */
  uregion_areEqual(uregion: Win32Pointer, otherRegion: Win32Pointer): number;
  /** icuin.dll!uregion_contains */
  uregion_contains(uregion: Win32Pointer, otherRegion: Win32Pointer): number;
  /** icuin.dll!uregion_getAvailable */
  uregion_getAvailable(type: number, status: Win32Pointer): number | null;
  /** icuin.dll!uregion_getContainedRegions */
  uregion_getContainedRegions(uregion: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uregion_getContainedRegionsOfType */
  uregion_getContainedRegionsOfType(uregion: Win32Pointer, type: number, status: Win32Pointer): number | null;
  /** icuin.dll!uregion_getContainingRegion */
  uregion_getContainingRegion(uregion: Win32Pointer): number | null;
  /** icuin.dll!uregion_getContainingRegionOfType */
  uregion_getContainingRegionOfType(uregion: Win32Pointer, type: number): number | null;
  /** icuin.dll!uregion_getNumericCode */
  uregion_getNumericCode(uregion: Win32Pointer): number;
  /** icuin.dll!uregion_getPreferredValues */
  uregion_getPreferredValues(uregion: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uregion_getRegionCode */
  uregion_getRegionCode(uregion: Win32Pointer): number | null;
  /** icuin.dll!uregion_getRegionFromCode */
  uregion_getRegionFromCode(regionCode: string | Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uregion_getRegionFromNumericCode */
  uregion_getRegionFromNumericCode(code: number, status: Win32Pointer): number | null;
  /** icuin.dll!uregion_getType */
  uregion_getType(uregion: Win32Pointer): number;
  /** icuin.dll!ureldatefmt_close */
  ureldatefmt_close(reldatefmt: Win32Pointer): void;
  /** icuin.dll!ureldatefmt_combineDateAndTime */
  ureldatefmt_combineDateAndTime(reldatefmt: Win32Pointer, relativeDateString: Win32Pointer, relativeDateStringLen: number, timeString: Win32Pointer, timeStringLen: number, result: Win32Pointer, resultCapacity: number, status: Win32Pointer): number;
  /** icuin.dll!ureldatefmt_format */
  ureldatefmt_format(reldatefmt: Win32Pointer, offset: number, unit: number, result: Win32Pointer, resultCapacity: number, status: Win32Pointer): number;
  /** icuin.dll!ureldatefmt_formatNumeric */
  ureldatefmt_formatNumeric(reldatefmt: Win32Pointer, offset: number, unit: number, result: Win32Pointer, resultCapacity: number, status: Win32Pointer): number;
  /** icuin.dll!ureldatefmt_open */
  ureldatefmt_open(locale: string | Win32Pointer, nfToAdopt: Win32Pointer, width: number, capitalizationContext: number, status: Win32Pointer): number | null;
  /** icuin.dll!usearch_close */
  usearch_close(searchiter: Win32Pointer): void;
  /** icuin.dll!usearch_first */
  usearch_first(strsrch: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!usearch_following */
  usearch_following(strsrch: Win32Pointer, position: number, status: Win32Pointer): number;
  /** icuin.dll!usearch_getAttribute */
  usearch_getAttribute(strsrch: Win32Pointer, attribute: number): number;
  /** icuin.dll!usearch_getBreakIterator */
  usearch_getBreakIterator(strsrch: Win32Pointer): number | null;
  /** icuin.dll!usearch_getCollator */
  usearch_getCollator(strsrch: Win32Pointer): number | null;
  /** icuin.dll!usearch_getMatchedLength */
  usearch_getMatchedLength(strsrch: Win32Pointer): number;
  /** icuin.dll!usearch_getMatchedStart */
  usearch_getMatchedStart(strsrch: Win32Pointer): number;
  /** icuin.dll!usearch_getMatchedText */
  usearch_getMatchedText(strsrch: Win32Pointer, result: Win32Pointer, resultCapacity: number, status: Win32Pointer): number;
  /** icuin.dll!usearch_getOffset */
  usearch_getOffset(strsrch: Win32Pointer): number;
  /** icuin.dll!usearch_getPattern */
  usearch_getPattern(strsrch: Win32Pointer, length: Win32Pointer): number | null;
  /** icuin.dll!usearch_getText */
  usearch_getText(strsrch: Win32Pointer, length: Win32Pointer): number | null;
  /** icuin.dll!usearch_last */
  usearch_last(strsrch: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!usearch_next */
  usearch_next(strsrch: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!usearch_open */
  usearch_open(pattern: Win32Pointer, patternlength: number, text: Win32Pointer, textlength: number, locale: string | Win32Pointer, breakiter: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!usearch_openFromCollator */
  usearch_openFromCollator(pattern: Win32Pointer, patternlength: number, text: Win32Pointer, textlength: number, collator: Win32Pointer, breakiter: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!usearch_preceding */
  usearch_preceding(strsrch: Win32Pointer, position: number, status: Win32Pointer): number;
  /** icuin.dll!usearch_previous */
  usearch_previous(strsrch: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!usearch_reset */
  usearch_reset(strsrch: Win32Pointer): void;
  /** icuin.dll!usearch_setAttribute */
  usearch_setAttribute(strsrch: Win32Pointer, attribute: number, value: number, status: Win32Pointer): void;
  /** icuin.dll!usearch_setBreakIterator */
  usearch_setBreakIterator(strsrch: Win32Pointer, breakiter: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!usearch_setCollator */
  usearch_setCollator(strsrch: Win32Pointer, collator: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!usearch_setOffset */
  usearch_setOffset(strsrch: Win32Pointer, position: number, status: Win32Pointer): void;
  /** icuin.dll!usearch_setPattern */
  usearch_setPattern(strsrch: Win32Pointer, pattern: Win32Pointer, patternlength: number, status: Win32Pointer): void;
  /** icuin.dll!usearch_setText */
  usearch_setText(strsrch: Win32Pointer, text: Win32Pointer, textlength: number, status: Win32Pointer): void;
  /** icuin.dll!uspoof_areConfusable */
  uspoof_areConfusable(sc: Win32Pointer, id1: Win32Pointer, length1: number, id2: Win32Pointer, length2: number, status: Win32Pointer): number;
  /** icuin.dll!uspoof_areConfusableUTF8 */
  uspoof_areConfusableUTF8(sc: Win32Pointer, id1: string | Win32Pointer, length1: number, id2: string | Win32Pointer, length2: number, status: Win32Pointer): number;
  /** icuin.dll!uspoof_check */
  uspoof_check(sc: Win32Pointer, id: Win32Pointer, length: number, position: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uspoof_check2 */
  uspoof_check2(sc: Win32Pointer, id: Win32Pointer, length: number, checkResult: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uspoof_check2UTF8 */
  uspoof_check2UTF8(sc: Win32Pointer, id: string | Win32Pointer, length: number, checkResult: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uspoof_checkUTF8 */
  uspoof_checkUTF8(sc: Win32Pointer, id: string | Win32Pointer, length: number, position: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uspoof_clone */
  uspoof_clone(sc: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uspoof_close */
  uspoof_close(sc: Win32Pointer): void;
  /** icuin.dll!uspoof_closeCheckResult */
  uspoof_closeCheckResult(checkResult: Win32Pointer): void;
  /** icuin.dll!uspoof_getAllowedChars */
  uspoof_getAllowedChars(sc: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uspoof_getAllowedLocales */
  uspoof_getAllowedLocales(sc: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uspoof_getCheckResultChecks */
  uspoof_getCheckResultChecks(checkResult: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uspoof_getCheckResultNumerics */
  uspoof_getCheckResultNumerics(checkResult: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uspoof_getCheckResultRestrictionLevel */
  uspoof_getCheckResultRestrictionLevel(checkResult: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uspoof_getChecks */
  uspoof_getChecks(sc: Win32Pointer, status: Win32Pointer): number;
  /** icuin.dll!uspoof_getInclusionSet */
  uspoof_getInclusionSet(status: Win32Pointer): number | null;
  /** icuin.dll!uspoof_getRecommendedSet */
  uspoof_getRecommendedSet(status: Win32Pointer): number | null;
  /** icuin.dll!uspoof_getRestrictionLevel */
  uspoof_getRestrictionLevel(sc: Win32Pointer): number;
  /** icuin.dll!uspoof_getSkeleton */
  uspoof_getSkeleton(sc: Win32Pointer, type: number, id: Win32Pointer, length: number, dest: Win32Pointer, destCapacity: number, status: Win32Pointer): number;
  /** icuin.dll!uspoof_getSkeletonUTF8 */
  uspoof_getSkeletonUTF8(sc: Win32Pointer, type: number, id: string | Win32Pointer, length: number, dest: string | Win32Pointer, destCapacity: number, status: Win32Pointer): number;
  /** icuin.dll!uspoof_open */
  uspoof_open(status: Win32Pointer): number | null;
  /** icuin.dll!uspoof_openCheckResult */
  uspoof_openCheckResult(status: Win32Pointer): number | null;
  /** icuin.dll!uspoof_openFromSerialized */
  uspoof_openFromSerialized(data: Win32Pointer, length: number, pActualLength: Win32Pointer, pErrorCode: Win32Pointer): number | null;
  /** icuin.dll!uspoof_openFromSource */
  uspoof_openFromSource(confusables: string | Win32Pointer, confusablesLen: number, confusablesWholeScript: string | Win32Pointer, confusablesWholeScriptLen: number, errType: Win32Pointer, pe: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!uspoof_serialize */
  uspoof_serialize(sc: Win32Pointer, data: Win32Pointer, capacity: number, status: Win32Pointer): number;
  /** icuin.dll!uspoof_setAllowedChars */
  uspoof_setAllowedChars(sc: Win32Pointer, chars: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!uspoof_setAllowedLocales */
  uspoof_setAllowedLocales(sc: Win32Pointer, localesList: string | Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!uspoof_setChecks */
  uspoof_setChecks(sc: Win32Pointer, checks: number, status: Win32Pointer): void;
  /** icuin.dll!uspoof_setRestrictionLevel */
  uspoof_setRestrictionLevel(sc: Win32Pointer, restrictionLevel: number): void;
  /** icuin.dll!utmscale_fromInt64 */
  utmscale_fromInt64(otherTime: number | bigint, timeScale: number, status: Win32Pointer): bigint;
  /** icuin.dll!utmscale_getTimeScaleValue */
  utmscale_getTimeScaleValue(timeScale: number, value: number, status: Win32Pointer): bigint;
  /** icuin.dll!utmscale_toInt64 */
  utmscale_toInt64(universalTime: number | bigint, timeScale: number, status: Win32Pointer): bigint;
  /** icuin.dll!utrans_clone */
  utrans_clone(trans: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!utrans_close */
  utrans_close(trans: Win32Pointer): void;
  /** icuin.dll!utrans_countAvailableIDs */
  utrans_countAvailableIDs(): number;
  /** icuin.dll!utrans_getSourceSet */
  utrans_getSourceSet(trans: Win32Pointer, ignoreFilter: number, fillIn: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!utrans_getUnicodeID */
  utrans_getUnicodeID(trans: Win32Pointer, resultLength: Win32Pointer): number | null;
  /** icuin.dll!utrans_openIDs */
  utrans_openIDs(pErrorCode: Win32Pointer): number | null;
  /** icuin.dll!utrans_openInverse */
  utrans_openInverse(trans: Win32Pointer, status: Win32Pointer): number | null;
  /** icuin.dll!utrans_openU */
  utrans_openU(id: Win32Pointer, idLength: number, dir: number, rules: Win32Pointer, rulesLength: number, parseError: Win32Pointer, pErrorCode: Win32Pointer): number | null;
  /** icuin.dll!utrans_register */
  utrans_register(adoptedTrans: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!utrans_setFilter */
  utrans_setFilter(trans: Win32Pointer, filterPattern: Win32Pointer, filterPatternLen: number, status: Win32Pointer): void;
  /** icuin.dll!utrans_toRules */
  utrans_toRules(trans: Win32Pointer, escapeUnprintable: number, result: Win32Pointer, resultLength: number, status: Win32Pointer): number;
  /** icuin.dll!utrans_trans */
  utrans_trans(trans: Win32Pointer, rep: Win32Pointer, repFunc: Win32Pointer, start: number, limit: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!utrans_transIncremental */
  utrans_transIncremental(trans: Win32Pointer, rep: Win32Pointer, repFunc: Win32Pointer, pos: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!utrans_transIncrementalUChars */
  utrans_transIncrementalUChars(trans: Win32Pointer, text: Win32Pointer, textLength: Win32Pointer, textCapacity: number, pos: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!utrans_transUChars */
  utrans_transUChars(trans: Win32Pointer, text: Win32Pointer, textLength: Win32Pointer, textCapacity: number, start: number, limit: Win32Pointer, status: Win32Pointer): void;
  /** icuin.dll!utrans_unregisterID */
  utrans_unregisterID(id: Win32Pointer, idLength: number): void;
}

declare const family: Win32Family & Functions;
export = family;
