// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** scarddlg.dll!GetOpenCardNameA */
  GetOpenCardNameA(param0: Win32Pointer): number;
  /** scarddlg.dll!GetOpenCardNameW */
  GetOpenCardNameW(param0: Win32Pointer): number;
  /** scarddlg.dll!GetOpenCardNameW */
  GetOpenCardName(param0: Win32Pointer): number;
  /** scarddlg.dll!SCardDlgExtendedError */
  SCardDlgExtendedError(): number;
  /** scarddlg.dll!SCardUIDlgSelectCardA */
  SCardUIDlgSelectCardA(param0: Win32Pointer): number;
  /** scarddlg.dll!SCardUIDlgSelectCardW */
  SCardUIDlgSelectCardW(param0: Win32Pointer): number;
  /** scarddlg.dll!SCardUIDlgSelectCardW */
  SCardUIDlgSelectCard(param0: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
