# SPDX-License-Identifier: Apache-2.0
# Formatting policy the n2b crates were written with (stable Rust 2024, from the Aphrody monorepo).
edition                    = "2024"
style_edition              = "2024"
max_width                  = 100
use_small_heuristics       = "Max"
newline_style              = "Unix"
hard_tabs                  = false
tab_spaces                 = 4
reorder_imports            = true
reorder_modules            = true
match_block_trailing_comma = true
use_field_init_shorthand   = true
use_try_shorthand          = true
force_explicit_abi         = true
