// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** api-ms-win-core-winrt-error-l1-1-1.dll!IsErrorPropagationEnabled */
  IsErrorPropagationEnabled(): number;
  /** api-ms-win-core-winrt-error-l1-1-1.dll!RoClearError */
  RoClearError(): void;
  /** api-ms-win-core-winrt-error-l1-1-1.dll!RoGetMatchingRestrictedErrorInfo */
  RoGetMatchingRestrictedErrorInfo(hrIn: number, ppRestrictedErrorInfo: Win32Pointer): number;
  /** api-ms-win-core-winrt-error-l1-1-1.dll!RoInspectCapturedStackBackTrace */
  RoInspectCapturedStackBackTrace(targetErrorInfoAddress: number | bigint, machine: number, readMemoryCallback: Win32Callback, context: Win32Pointer, frameCount: Win32Pointer, targetBackTraceAddress: Win32Pointer): number;
  /** api-ms-win-core-winrt-error-l1-1-1.dll!RoInspectThreadErrorInfo */
  RoInspectThreadErrorInfo(targetTebAddress: number | bigint, machine: number, readMemoryCallback: Win32Callback, context: Win32Pointer, targetErrorInfoAddress: Win32Pointer): number;
  /** api-ms-win-core-winrt-error-l1-1-1.dll!RoOriginateLanguageException */
  RoOriginateLanguageException(error: number, message: Win32Pointer, languageException: Win32Pointer): number;
  /** api-ms-win-core-winrt-error-l1-1-1.dll!RoReportFailedDelegate */
  RoReportFailedDelegate(punkDelegate: Win32Pointer, pRestrictedErrorInfo: Win32Pointer): number;
  /** api-ms-win-core-winrt-error-l1-1-1.dll!RoReportUnhandledError */
  RoReportUnhandledError(pRestrictedErrorInfo: Win32Pointer): number;
}

declare const family: Win32Family & Functions;
export = family;
