// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** api-ms-win-core-sysinfo-l1-2-4.dll!GetSystemTimeAdjustmentPrecise */
  GetSystemTimeAdjustmentPrecise(lpTimeAdjustment: Win32Pointer, lpTimeIncrement: Win32Pointer, lpTimeAdjustmentDisabled: Win32Pointer): number;
  /** api-ms-win-core-sysinfo-l1-2-4.dll!SetSystemTimeAdjustmentPrecise */
  SetSystemTimeAdjustmentPrecise(dwTimeAdjustment: number | bigint, bTimeAdjustmentDisabled: number): number;
}

declare const family: Win32Family & Functions;
export = family;
