// Generated by scripts/aphrody/win32/gen.ts from Microsoft.Windows.SDK.Win32Metadata 71.0.30-preview. Do not edit.
import type { Win32Callback, Win32Family, Win32Pointer, Win32Struct, Win32StructInit } from "bun:windows";

interface Functions {
  /** dcomp.dll!CreatePresentationFactory */
  CreatePresentationFactory(d3dDevice: Win32Pointer, riid: Win32Pointer, presentationFactory: Win32Pointer): number;
  /** dcomp.dll!DCompositionAttachMouseDragToHwnd */
  DCompositionAttachMouseDragToHwnd(visual: Win32Pointer, hwnd: Win32Pointer, enable: number): number;
  /** dcomp.dll!DCompositionAttachMouseWheelToHwnd */
  DCompositionAttachMouseWheelToHwnd(visual: Win32Pointer, hwnd: Win32Pointer, enable: number): number;
  /** dcomp.dll!DCompositionBoostCompositorClock */
  DCompositionBoostCompositorClock(enable: number): number;
  /** dcomp.dll!DCompositionCreateDevice */
  DCompositionCreateDevice(dxgiDevice: Win32Pointer, iid: Win32Pointer, dcompositionDevice: Win32Pointer): number;
  /** dcomp.dll!DCompositionCreateDevice2 */
  DCompositionCreateDevice2(renderingDevice: Win32Pointer, iid: Win32Pointer, dcompositionDevice: Win32Pointer): number;
  /** dcomp.dll!DCompositionCreateDevice3 */
  DCompositionCreateDevice3(renderingDevice: Win32Pointer, iid: Win32Pointer, dcompositionDevice: Win32Pointer): number;
  /** dcomp.dll!DCompositionCreateSurfaceHandle */
  DCompositionCreateSurfaceHandle(desiredAccess: number, securityAttributes: Win32Pointer, surfaceHandle: Win32Pointer): number;
  /** dcomp.dll!DCompositionGetFrameId */
  DCompositionGetFrameId(frameIdType: number, frameId: Win32Pointer): number;
  /** dcomp.dll!DCompositionGetStatistics */
  DCompositionGetStatistics(frameId: number | bigint, frameStats: Win32Pointer, targetIdCount: number, targetIds: Win32Pointer, actualTargetIdCount: Win32Pointer): number;
  /** dcomp.dll!DCompositionGetTargetStatistics */
  DCompositionGetTargetStatistics(frameId: number | bigint, targetId: Win32Pointer, targetStats: Win32Pointer): number;
  /** dcomp.dll!DCompositionWaitForCompositorClock */
  DCompositionWaitForCompositorClock(count: number, handles: Win32Pointer, timeoutInMs: number): number;
}

declare const family: Win32Family & Functions;
export = family;
